/- Generated by scripts/generate_refutation.py from our own SAT trace.
Every statement below is proved with ordinary kernel-checked proof terms. -/
import Jsp746.Certificate.Steps03

namespace Jsp746.Certificate
variable (e : ℕ → ℕ → Prop)
variable (tri : TriangleCondition e) (schur : SchurCondition e)
include tri schur

theorem c1338 : (e 2 11) → (e 2 7) → (e 2 6) → (e 1 4) → (¬ e 1 6) → (¬ e 4 11) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 6 7) := fun hu => c178 e tri schur hu h1 h2
  have v1 : (¬ e 6 11) := fun hu => c182 e tri schur hu h0 h2
  have v2 : (¬ e 7 11) := fun hu => c193 e tri schur hu h0 h1
  have v3 : (e 1 7) := Classical.byContradiction (fun hu => c820 e tri schur h4 hu v0)
  have v4 : (e 4 7) := Classical.byContradiction (fun hu => c860 e tri schur hu h5 v2)
  have v5 : (¬ e 2 5) := fun hu => c916 e tri schur h0 h2 hu
  have v6 : (¬ e 2 4) := fun hu => c1185 e tri schur h0 h1 hu
  have v7 : (¬ e 2 17) := fun hu => c1333 e tri schur hu h0 h2
  have v8 : (¬ e 1 2) := fun hu => c4 e tri schur h1 v3 hu
  exact c33 e tri schur v4 v3 h3

theorem c1339 : (e 6 9) → (e 4 6) → (e 2 11) → (e 2 6) → (e 1 4) → (¬ e 4 11) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 1 6) := fun hu => c32 e tri schur h1 hu h4
  have v1 : (¬ e 2 4) := fun hu => c152 e tri schur h1 h3 hu
  have v2 : (¬ e 2 9) := fun hu => c180 e tri schur h0 hu h3
  have v3 : (¬ e 6 11) := fun hu => c182 e tri schur hu h2 h3
  have v4 : (¬ e 4 9) := fun hu => c376 e tri schur h0 hu h1
  have v5 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v4 h6 hu)
  have v6 : (¬ e 2 5) := fun hu => c916 e tri schur h2 h3 hu
  have v7 : (¬ e 2 17) := fun hu => c1333 e tri schur hu h2 h3
  have v8 : (¬ e 2 7) := fun hu => c1338 e tri schur h2 hu h3 h4 v0 h5
  have v9 : (¬ e 6 13) := fun hu => c554 e tri schur v5 hu h0
  have v10 : (e 5 7) := Classical.byContradiction (fun hu => c834 e tri schur v6 v8 hu)
  have v11 : (e 7 9) := Classical.byContradiction (fun hu => c836 e tri schur v8 v2 hu)
  have v12 : (¬ e 4 7) := fun hu => c925 e tri schur hu v6 v8 v2
  have v13 : (¬ e 5 9) := fun hu => c465 e tri schur v11 hu v10
  have v14 : (¬ e 6 7) := fun hu => c531 e tri schur v11 h0 hu
  have v15 : (¬ e 7 13) := fun hu => c609 e tri schur v5 hu v11
  have v16 : (e 1 7) := Classical.byContradiction (fun hu => c820 e tri schur v0 hu v14)
  have v17 : (e 4 5) := Classical.byContradiction (fun hu => c858 e tri schur hu v4 v13)
  have v18 : (e 7 11) := Classical.byContradiction (fun hu => c860 e tri schur v12 h5 hu)
  exact c876 e tri schur v14 v9 v15

theorem c1340 : (e 11 14) → (e 11 12) → (e 2 11) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 12) := fun hu => c228 e tri schur h1 hu h2
  have v1 : (¬ e 2 14) := fun hu => c230 e tri schur h0 hu h2
  have v2 : (¬ e 12 14) := fun hu => c761 e tri schur hu h0 h1
  exact c841 e tri schur v0 v1 v2

theorem c1341 : (e 12 14) → (e 4 12) → (e 3 14) → (e 1 10) → (¬ e 1 15) → (¬ e 4 10) → (¬ e 12 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 3 12) := fun hu => c341 e tri schur h0 h2 hu
  have v1 : (¬ e 4 14) := fun hu => c432 e tri schur h0 hu h1
  have v2 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur v0 hu h6)
  have v3 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur h5 v1 hu)
  have v4 : (¬ e 1 14) := fun hu => c103 e tri schur v3 hu h3
  have v5 : (¬ e 3 10) := fun hu => c328 e tri schur v3 h2 hu
  have v6 : (¬ e 14 15) := fun hu => c351 e tri schur hu v2 h2
  have v7 : (¬ e 10 12) := fun hu => c740 e tri schur h0 v3 hu
  exact c828 e tri schur v4 h4 v6

theorem c1342 : (e 4 12) → (e 3 14) → (e 2 15) → (e 1 10) → (¬ e 1 15) → (¬ e 2 12) → (¬ e 4 10) → (¬ e 12 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 12 14) := fun hu => c1341 e tri schur hu h0 h1 h3 h4 h6 h7
  have v1 : (e 2 14) := Classical.byContradiction (fun hu => c841 e tri schur h5 hu v0)
  have v2 : (¬ e 2 3) := fun hu => c146 e tri schur h1 v1 hu
  have v3 : (¬ e 14 15) := fun hu => c246 e tri schur hu h2 v1
  have v4 : (e 1 14) := Classical.byContradiction (fun hu => c828 e tri schur hu h4 v3)
  have v5 : (¬ e 1 2) := fun hu => c11 e tri schur v1 v4 hu
  have v6 : (¬ e 1 3) := fun hu => c26 e tri schur h1 v4 hu
  have v7 : (¬ e 10 14) := fun hu => c103 e tri schur hu v4 h3
  exact c816 e tri schur v5 v6 v2

theorem c1343 : (e 1 14) → (e 1 10) → (e 1 4) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 10) := fun hu => c36 e tri schur hu h1 h2
  have v1 : (¬ e 4 14) := fun hu => c40 e tri schur hu h0 h2
  have v2 : (¬ e 10 14) := fun hu => c103 e tri schur hu h0 h1
  exact c863 e tri schur v0 v1 v2

theorem c1344 : (e 11 12) → (e 4 12) → (e 2 15) → (e 2 11) → (e 2 6) → (e 1 10) → (e 1 4) → (¬ e 1 15) → (¬ e 3 4) → (¬ e 4 11) → (¬ e 12 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10
  have v0 : (¬ e 4 10) := fun hu => c36 e tri schur hu h5 h6
  have v1 : (¬ e 1 12) := fun hu => c38 e tri schur h1 hu h6
  have v2 : (¬ e 6 11) := fun hu => c182 e tri schur hu h3 h4
  have v3 : (¬ e 6 15) := fun hu => c186 e tri schur hu h2 h4
  have v4 : (¬ e 2 12) := fun hu => c228 e tri schur h0 hu h3
  have v5 : (¬ e 11 15) := fun hu => c231 e tri schur hu h2 h3
  have v6 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur h9 hu v5)
  have v7 : (¬ e 2 5) := fun hu => c916 e tri schur h3 h4 hu
  have v8 : (¬ e 2 4) := fun hu => c1177 e tri schur h2 h3 hu
  have v9 : (¬ e 4 13) := fun hu => c1260 e tri schur hu h1 h6
  have v10 : (¬ e 2 17) := fun hu => c1333 e tri schur hu h3 h4
  have v11 : (¬ e 10 11) := fun hu => c1336 e tri schur h0 hu h3
  have v12 : (¬ e 11 14) := fun hu => c1340 e tri schur hu h0 h3
  have v13 : (¬ e 3 14) := fun hu => c1342 e tri schur h1 hu h2 h5 h7 v4 v0 h10
  have v14 : (¬ e 1 14) := fun hu => c1343 e tri schur hu h5 h6
  have v15 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v14 h7 hu)
  have v16 : (e 3 11) := Classical.byContradiction (fun hu => c853 e tri schur hu v13 v12)
  have v17 : (¬ e 2 3) := fun hu => c143 e tri schur v16 h3 hu
  have v18 : (¬ e 2 14) := fun hu => c246 e tri schur v15 h2 hu
  have v19 : (¬ e 3 12) := fun hu => c333 e tri schur h0 hu v16
  have v20 : (¬ e 4 14) := fun hu => c442 e tri schur v15 v6 hu
  have v21 : (e 3 5) := Classical.byContradiction (fun hu => c832 e tri schur v17 v7 hu)
  have v22 : (e 12 14) := Classical.byContradiction (fun hu => c841 e tri schur v4 v18 hu)
  have v23 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur v19 hu h10)
  have v24 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v0 v20 hu)
  have v25 : (¬ e 7 15) := fun hu => c1023 e tri schur hu v6 v23
  have v26 : (¬ e 3 6) := fun hu => c1310 e tri schur v16 hu v21
  have v27 : (¬ e 5 11) := fun hu => c275 e tri schur hu v16 v21
  have v28 : (¬ e 5 15) := fun hu => c279 e tri schur hu v23 v21
  have v29 : (¬ e 10 12) := fun hu => c740 e tri schur v22 v24 hu
  have v30 : (¬ e 10 15) := fun hu => c750 e tri schur v15 hu v24
  have v31 : (e 2 10) := Classical.byContradiction (fun hu => c839 e tri schur hu v4 v29)
  have v32 : (e 5 6) := Classical.byContradiction (fun hu => c868 e tri schur hu v27 v2)
  have v33 : (e 5 10) := Classical.byContradiction (fun hu => c872 e tri schur hu v28 v30)
  have v34 : (¬ e 2 16) := fun hu => c994 e tri schur hu v31 h4
  have v35 : (e 6 9) := Classical.byContradiction (fun hu => c1042 e tri schur v23 v26 hu v3)
  have v36 : (¬ e 5 16) := fun hu => c1178 e tri schur hu v33 v32
  have v37 : (¬ e 4 6) := fun hu => c1339 e tri schur v35 hu h3 h4 h6 h9 v9
  have v38 : (¬ e 1 2) := fun hu => c7 e tri schur v31 h5 hu
  have v39 : (¬ e 1 5) := fun hu => c49 e tri schur v33 h5 hu
  have v40 : (¬ e 2 9) := fun hu => c180 e tri schur v35 hu h4
  have v41 : (¬ e 6 10) := fun hu => c181 e tri schur hu v31 h4
  have v42 : (¬ e 3 10) := fun hu => c274 e tri schur v33 hu v21
  have v43 : (¬ e 5 9) := fun hu => c454 e tri schur v35 hu v32
  have v44 : (¬ e 5 14) := fun hu => c497 e tri schur v24 hu v33
  have v45 : (e 1 3) := Classical.byContradiction (fun hu => c816 e tri schur v38 hu v17)
  have v46 : (e 14 16) := Classical.byContradiction (fun hu => c843 e tri schur v18 v34 hu)
  exact c859 e tri schur v37 v0 v41

theorem c1345 : (e 15 17) → (e 14 15) → (e 3 15) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 14) := fun hu => c351 e tri schur h1 h2 hu
  have v1 : (¬ e 3 17) := fun hu => c356 e tri schur h0 hu h2
  have v2 : (¬ e 14 17) := fun hu => c807 e tri schur h0 hu h1
  exact c856 e tri schur v0 v1 v2

theorem c1346 : (e 11 12) → (e 4 15) → (e 4 12) → (e 2 11) → (e 2 6) → (e 1 10) → (e 1 4) → (¬ e 4 11) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 4 10) := fun hu => c36 e tri schur hu h5 h6
  have v1 : (¬ e 1 12) := fun hu => c38 e tri schur h2 hu h6
  have v2 : (¬ e 1 15) := fun hu => c41 e tri schur h1 hu h6
  have v3 : (¬ e 6 11) := fun hu => c182 e tri schur hu h3 h4
  have v4 : (¬ e 2 12) := fun hu => c228 e tri schur h0 hu h3
  have v5 : (¬ e 12 15) := fun hu => c433 e tri schur hu h1 h2
  have v6 : (¬ e 2 5) := fun hu => c916 e tri schur h3 h4 hu
  have v7 : (¬ e 3 4) := fun hu => c1188 e tri schur h1 h2 hu
  have v8 : (¬ e 4 13) := fun hu => c1260 e tri schur hu h2 h6
  have v9 : (¬ e 2 17) := fun hu => c1333 e tri schur hu h3 h4
  have v10 : (¬ e 10 11) := fun hu => c1336 e tri schur h0 hu h3
  have v11 : (¬ e 11 14) := fun hu => c1340 e tri schur hu h0 h3
  have v12 : (¬ e 1 14) := fun hu => c1343 e tri schur hu h5 h6
  have v13 : (¬ e 2 15) := fun hu => c1344 e tri schur h0 h2 hu h3 h4 h5 h6 v2 v7 h7 v5
  have v14 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v12 v2 hu)
  have v15 : (e 15 17) := Classical.byContradiction (fun hu => c844 e tri schur v13 v9 hu)
  have v16 : (¬ e 3 15) := fun hu => c1345 e tri schur v15 v14 hu
  have v17 : (¬ e 4 14) := fun hu => c442 e tri schur v14 h1 hu
  have v18 : (¬ e 4 17) := fun hu => c447 e tri schur v15 hu h1
  have v19 : (¬ e 14 17) := fun hu => c807 e tri schur v15 hu v14
  have v20 : (e 3 12) := Classical.byContradiction (fun hu => c854 e tri schur hu v16 v5)
  have v21 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v0 v17 hu)
  have v22 : (e 13 17) := Classical.byContradiction (fun hu => c866 e tri schur v8 v18 hu)
  have v23 : (¬ e 3 11) := fun hu => c333 e tri schur h0 v20 hu
  have v24 : (¬ e 10 15) := fun hu => c750 e tri schur v14 hu v21
  have v25 : (¬ e 13 15) := fun hu => c801 e tri schur v15 v22 hu
  have v26 : (e 2 13) := Classical.byContradiction (fun hu => c842 e tri schur hu v13 v25)
  have v27 : (e 3 14) := Classical.byContradiction (fun hu => c853 e tri schur v23 hu v11)
  have v28 : (¬ e 2 3) := fun hu => c1323 e tri schur v27 v20 hu
  have v29 : (¬ e 12 14) := fun hu => c1341 e tri schur hu h2 v27 h5 v2 v0 v5
  have v30 : (¬ e 6 13) := fun hu => c184 e tri schur hu v26 h4
  have v31 : (¬ e 11 13) := fun hu => c229 e tri schur hu v26 h3
  have v32 : (¬ e 3 10) := fun hu => c328 e tri schur v21 v27 hu
  have v33 : (e 3 5) := Classical.byContradiction (fun hu => c832 e tri schur v28 v6 hu)
  have v34 : (e 2 14) := Classical.byContradiction (fun hu => c841 e tri schur v4 hu v29)
  have v35 : (¬ e 3 9) := fun hu => c992 e tri schur v27 hu v33
  have v36 : (¬ e 2 8) := fun hu => c1215 e tri schur v34 hu h4
  have v37 : (¬ e 6 14) := fun hu => c185 e tri schur hu v34 h4
  have v38 : (¬ e 2 10) := fun hu => c223 e tri schur v21 v34 hu
  have v39 : (¬ e 13 14) := fun hu => c241 e tri schur hu v34 v26
  have v40 : (¬ e 5 12) := fun hu => c276 e tri schur hu v20 v33
  have v41 : (¬ e 5 14) := fun hu => c278 e tri schur hu v27 v33
  have v42 : (e 1 13) := Classical.byContradiction (fun hu => c827 e tri schur hu v12 v39)
  have v43 : (e 8 10) := Classical.byContradiction (fun hu => c837 e tri schur v36 v38 hu)
  have v44 : (e 10 12) := Classical.byContradiction (fun hu => c839 e tri schur v38 v4 hu)
  have v45 : (¬ e 1 2) := fun hu => c10 e tri schur v26 v42 hu
  have v46 : (¬ e 1 8) := fun hu => c82 e tri schur v43 h5 hu
  have v47 : (¬ e 10 13) := fun hu => c102 e tri schur hu v42 h5
  have v48 : (¬ e 1 17) := fun hu => c124 e tri schur v22 hu v42
  have v49 : (¬ e 8 12) := fun hu => c661 e tri schur v44 hu v43
  have v50 : (¬ e 8 14) := fun hu => c663 e tri schur v21 hu v43
  have v51 : (e 1 3) := Classical.byContradiction (fun hu => c816 e tri schur v45 hu v28)
  have v52 : (e 3 13) := Classical.byContradiction (fun hu => c852 e tri schur v32 hu v47)
  have v53 : (e 6 8) := Classical.byContradiction (fun hu => c877 e tri schur hu v37 v50)
  have v54 : (¬ e 1 5) := fun hu => c17 e tri schur v33 hu v51
  exact c25 e tri schur v52 v42 v51

theorem c1347 : (e 2 14) → (e 2 13) → (e 1 10) → (¬ e 1 14) → (¬ e 2 3) → (¬ e 3 10) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 13 14) := fun hu => c241 e tri schur hu h0 h1
  have v1 : (e 1 13) := Classical.byContradiction (fun hu => c827 e tri schur hu h3 v0)
  have v2 : (¬ e 1 2) := fun hu => c10 e tri schur h1 v1 hu
  have v3 : (¬ e 10 13) := fun hu => c102 e tri schur hu v1 h2
  have v4 : (e 1 3) := Classical.byContradiction (fun hu => c816 e tri schur v2 hu h4)
  have v5 : (e 3 13) := Classical.byContradiction (fun hu => c852 e tri schur h5 hu v3)
  exact c25 e tri schur v5 v1 v4

theorem c1348 : (e 15 17) → (e 13 15) → (e 4 15) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 4 17) := fun hu => c447 e tri schur h0 hu h2
  have v1 : (¬ e 13 17) := fun hu => c801 e tri schur h0 hu h1
  exact c866 e tri schur h3 v0 v1

theorem c1349 : (e 1 10) → (e 1 8) → (e 1 2) → (¬ e 2 10) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 2 8) := fun hu => c5 e tri schur hu h1 h2
  have v1 : (¬ e 8 10) := fun hu => c82 e tri schur hu h0 h1
  exact c837 e tri schur v0 h3 v1

theorem c1350 : (e 4 15) → (e 4 12) → (e 3 14) → (e 1 10) → (e 1 4) → (¬ e 2 6) → (¬ e 2 12) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 4 10) := fun hu => c36 e tri schur hu h3 h4
  have v1 : (¬ e 1 12) := fun hu => c38 e tri schur h1 hu h4
  have v2 : (¬ e 1 15) := fun hu => c41 e tri schur h0 hu h4
  have v3 : (¬ e 12 15) := fun hu => c433 e tri schur hu h0 h1
  have v4 : (¬ e 3 4) := fun hu => c1188 e tri schur h0 h1 hu
  have v5 : (¬ e 4 13) := fun hu => c1260 e tri schur hu h1 h4
  have v6 : (¬ e 4 11) := fun hu => c1335 e tri schur h1 hu h4 v1
  have v7 : (¬ e 12 14) := fun hu => c1341 e tri schur hu h1 h2 h3 v2 v0 v3
  have v8 : (¬ e 2 15) := fun hu => c1342 e tri schur h1 h2 hu h3 v2 h6 v0 v3
  have v9 : (¬ e 1 14) := fun hu => c1343 e tri schur hu h3 h4
  have v10 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v9 v2 hu)
  have v11 : (e 2 14) := Classical.byContradiction (fun hu => c841 e tri schur h6 hu v7)
  have v12 : (¬ e 2 3) := fun hu => c146 e tri schur h2 v11 hu
  have v13 : (¬ e 3 15) := fun hu => c351 e tri schur v10 hu h2
  have v14 : (¬ e 4 14) := fun hu => c442 e tri schur v10 h0 hu
  have v15 : (e 3 12) := Classical.byContradiction (fun hu => c854 e tri schur hu v13 v3)
  have v16 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v0 v14 hu)
  have v17 : (¬ e 2 10) := fun hu => c223 e tri schur v16 v11 hu
  have v18 : (¬ e 3 10) := fun hu => c328 e tri schur v16 h2 hu
  have v19 : (¬ e 10 15) := fun hu => c750 e tri schur v10 hu v16
  have v20 : (e 10 12) := Classical.byContradiction (fun hu => c839 e tri schur v17 h6 hu)
  have v21 : (¬ e 2 13) := fun hu => c1347 e tri schur v11 hu h3 v9 v12 v18
  have v22 : (e 13 15) := Classical.byContradiction (fun hu => c842 e tri schur v21 v8 hu)
  have v23 : (¬ e 15 17) := fun hu => c1348 e tri schur hu v22 h0 v5
  have v24 : (¬ e 13 14) := fun hu => c796 e tri schur v10 v22 hu
  have v25 : (e 1 13) := Classical.byContradiction (fun hu => c827 e tri schur hu v9 v24)
  have v26 : (e 2 17) := Classical.byContradiction (fun hu => c844 e tri schur v8 hu v23)
  have v27 : (¬ e 10 13) := fun hu => c102 e tri schur hu v25 h3
  have v28 : (¬ e 14 17) := fun hu => c248 e tri schur hu v26 v11
  have v29 : (e 3 13) := Classical.byContradiction (fun hu => c852 e tri schur v18 hu v27)
  have v30 : (¬ e 13 18) := fun hu => c1136 e tri schur hu v22 v29 v13
  have v31 : (¬ e 1 3) := fun hu => c25 e tri schur v29 v25 hu
  have v32 : (¬ e 12 13) := fun hu => c340 e tri schur hu v29 v15
  have v33 : (e 1 2) := Classical.byContradiction (fun hu => c816 e tri schur hu v31 v12)
  have v34 : (¬ e 1 8) := fun hu => c1349 e tri schur h3 hu v33 v17
  have v35 : (¬ e 2 4) := fun hu => c1 e tri schur hu h4 v33
  have v36 : (¬ e 1 17) := fun hu => c14 e tri schur v26 hu v33
  have v37 : (e 4 6) := Classical.byContradiction (fun hu => c833 e tri schur v35 h5 hu)
  have v38 : (¬ e 4 9) := fun hu => c1194 e tri schur h0 hu v37
  have v39 : (¬ e 1 6) := fun hu => c32 e tri schur v37 hu h4
  have v40 : (¬ e 6 12) := fun hu => c379 e tri schur hu h1 v37
  have v41 : (¬ e 6 15) := fun hu => c382 e tri schur hu h0 v37
  have v42 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v38 v5 hu)
  have v43 : (¬ e 6 13) := fun hu => c940 e tri schur v42 hu v29
  have v44 : (¬ e 7 9) := fun hu => c1221 e tri schur v22 v42 hu v41
  have v45 : (¬ e 1 9) := fun hu => c94 e tri schur v42 v25 hu
  have v46 : (¬ e 3 9) := fun hu => c319 e tri schur v42 v29 hu
  have v47 : (¬ e 9 15) := fun hu => c718 e tri schur v22 hu v42
  have v48 : (e 8 9) := Classical.byContradiction (fun hu => c822 e tri schur v34 v45 hu)
  have v49 : (e 6 9) := Classical.byContradiction (fun hu => c878 e tri schur hu v41 v47)
  have v50 : (¬ e 2 9) := fun hu => c903 e tri schur v48 v49 hu
  have v51 : (¬ e 6 8) := fun hu => c541 e tri schur v48 v49 hu
  have v52 : (¬ e 8 13) := fun hu => c654 e tri schur v42 hu v48
  have v53 : (e 2 8) := Classical.byContradiction (fun hu => c835 e tri schur h5 hu v51)
  have v54 : (e 2 7) := Classical.byContradiction (fun hu => c836 e tri schur hu v50 v44)
  have v55 : (¬ e 1 7) := fun hu => c4 e tri schur v54 hu v33
  have v56 : (¬ e 7 8) := fun hu => c190 e tri schur hu v53 v54
  have v57 : (¬ e 7 14) := fun hu => c196 e tri schur hu v11 v54
  have v58 : (¬ e 7 17) := fun hu => c199 e tri schur hu v26 v54
  have v59 : (¬ e 8 14) := fun hu => c206 e tri schur hu v11 v53
  have v60 : (¬ e 8 17) := fun hu => c209 e tri schur hu v26 v53
  have v61 : (e 6 7) := Classical.byContradiction (fun hu => c820 e tri schur v39 v55 hu)
  exact c821 e tri schur v55 v34 v56

theorem c1351 : (e 2 8) → (e 2 7) → (e 1 2) → (¬ e 1 8) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 1 7) := fun hu => c4 e tri schur h1 hu h2
  have v1 : (¬ e 7 8) := fun hu => c190 e tri schur hu h0 h1
  exact c821 e tri schur v0 h3 v1

theorem c1352 : (e 2 14) → (e 2 13) → (e 1 2) → (¬ e 1 14) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 1 13) := fun hu => c10 e tri schur h1 hu h2
  have v1 : (¬ e 13 14) := fun hu => c241 e tri schur hu h0 h1
  exact c827 e tri schur v0 h3 v1

theorem c1353 : (e 8 9) → (e 6 9) → (e 1 2) → (¬ e 1 8) → (¬ e 2 6) → (¬ e 7 9) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 6 8) := fun hu => c541 e tri schur h0 h1 hu
  have v1 : (e 2 8) := Classical.byContradiction (fun hu => c835 e tri schur h4 hu v0)
  have v2 : (¬ e 2 9) := fun hu => c903 e tri schur h0 h1 hu
  have v3 : (¬ e 2 7) := fun hu => c1351 e tri schur v1 hu h2 h3
  exact c836 e tri schur v3 v2 h5

theorem c1354 : (e 4 15) → (e 2 14) → (e 1 10) → (e 1 4) → (e 1 2) → (¬ e 2 6) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 2 4) := fun hu => c1 e tri schur hu h3 h4
  have v1 : (¬ e 2 10) := fun hu => c7 e tri schur hu h2 h4
  have v2 : (¬ e 1 14) := fun hu => c11 e tri schur h1 hu h4
  have v3 : (¬ e 4 10) := fun hu => c36 e tri schur hu h2 h3
  have v4 : (¬ e 1 15) := fun hu => c41 e tri schur h0 hu h3
  have v5 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v2 v4 hu)
  have v6 : (e 4 6) := Classical.byContradiction (fun hu => c833 e tri schur v0 h5 hu)
  have v7 : (¬ e 4 9) := fun hu => c1194 e tri schur h0 hu v6
  have v8 : (¬ e 1 8) := fun hu => c1349 e tri schur h2 hu h4 v1
  have v9 : (¬ e 2 13) := fun hu => c1352 e tri schur h1 hu h4 v2
  have v10 : (¬ e 1 6) := fun hu => c32 e tri schur v6 hu h3
  have v11 : (¬ e 2 15) := fun hu => c246 e tri schur v5 hu h1
  have v12 : (¬ e 6 15) := fun hu => c382 e tri schur hu h0 v6
  have v13 : (¬ e 4 14) := fun hu => c442 e tri schur v5 h0 hu
  have v14 : (e 13 15) := Classical.byContradiction (fun hu => c842 e tri schur v9 v11 hu)
  have v15 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v7 h6 hu)
  have v16 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v3 v13 hu)
  have v17 : (¬ e 7 9) := fun hu => c1221 e tri schur v14 v15 hu v12
  have v18 : (¬ e 15 17) := fun hu => c1348 e tri schur hu v14 h0 h6
  have v19 : (¬ e 9 15) := fun hu => c718 e tri schur v14 hu v15
  have v20 : (¬ e 10 15) := fun hu => c750 e tri schur v5 hu v16
  have v21 : (¬ e 13 14) := fun hu => c796 e tri schur v5 v14 hu
  have v22 : (e 1 13) := Classical.byContradiction (fun hu => c827 e tri schur hu v2 v21)
  have v23 : (e 2 17) := Classical.byContradiction (fun hu => c844 e tri schur v11 hu v18)
  have v24 : (e 6 9) := Classical.byContradiction (fun hu => c878 e tri schur hu v12 v19)
  have v25 : (¬ e 8 9) := fun hu => c1353 e tri schur hu v24 h4 v8 h5 v17
  have v26 : (¬ e 1 17) := fun hu => c14 e tri schur v23 hu h4
  have v27 : (¬ e 1 9) := fun hu => c94 e tri schur v15 v22 hu
  have v28 : (¬ e 10 13) := fun hu => c102 e tri schur hu v22 h2
  have v29 : (¬ e 14 17) := fun hu => c248 e tri schur hu v23 h1
  have v30 : (¬ e 6 13) := fun hu => c554 e tri schur v15 hu v24
  exact c822 e tri schur v8 v27 v25

theorem c1355 : (e 4 15) → (e 3 15) → (e 2 14) → (e 1 10) → (e 1 4) → (¬ e 2 3) → (¬ e 2 6) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 4 10) := fun hu => c36 e tri schur hu h3 h4
  have v1 : (¬ e 1 15) := fun hu => c41 e tri schur h0 hu h4
  have v2 : (¬ e 3 4) := fun hu => c266 e tri schur h0 h1 hu
  have v3 : (¬ e 7 15) := fun hu => c1023 e tri schur hu h0 h1
  have v4 : (¬ e 1 14) := fun hu => c1343 e tri schur hu h3 h4
  have v5 : (¬ e 1 2) := fun hu => c1354 e tri schur h0 h2 h3 h4 hu h6 h7
  have v6 : (e 1 3) := Classical.byContradiction (fun hu => c816 e tri schur v5 hu h5)
  have v7 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v4 v1 hu)
  have v8 : (¬ e 15 17) := fun hu => c1345 e tri schur hu v7 h1
  have v9 : (¬ e 3 10) := fun hu => c22 e tri schur hu h3 v6
  have v10 : (¬ e 2 15) := fun hu => c246 e tri schur v7 hu h2
  have v11 : (¬ e 3 14) := fun hu => c351 e tri schur v7 h1 hu
  have v12 : (¬ e 4 14) := fun hu => c442 e tri schur v7 h0 hu
  have v13 : (e 2 17) := Classical.byContradiction (fun hu => c844 e tri schur v10 hu v8)
  have v14 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v0 v12 hu)
  have v15 : (¬ e 2 13) := fun hu => c1347 e tri schur h2 hu h3 v4 h5 v9
  have v16 : (¬ e 2 10) := fun hu => c223 e tri schur v14 h2 hu
  have v17 : (¬ e 14 17) := fun hu => c248 e tri schur hu v13 h2
  have v18 : (¬ e 10 15) := fun hu => c750 e tri schur v7 hu v14
  have v19 : (e 13 15) := Classical.byContradiction (fun hu => c842 e tri schur v15 v10 hu)
  have v20 : (e 3 17) := Classical.byContradiction (fun hu => c856 e tri schur v11 hu v17)
  have v21 : (¬ e 1 17) := fun hu => c29 e tri schur v20 hu v6
  have v22 : (¬ e 3 13) := fun hu => c347 e tri schur v19 h1 hu
  have v23 : (¬ e 13 14) := fun hu => c796 e tri schur v7 v19 hu
  have v24 : (e 1 13) := Classical.byContradiction (fun hu => c827 e tri schur hu v4 v23)
  have v25 : (e 10 13) := Classical.byContradiction (fun hu => c852 e tri schur v9 v22 hu)
  exact c102 e tri schur v25 v24 h3

theorem c1356 : (e 14 15) → (e 13 15) → (e 3 15) → (e 1 10) → (¬ e 1 14) → (¬ e 3 10) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 3 13) := fun hu => c347 e tri schur h1 h2 hu
  have v1 : (¬ e 3 14) := fun hu => c351 e tri schur h0 h2 hu
  have v2 : (¬ e 13 14) := fun hu => c796 e tri schur h0 h1 hu
  have v3 : (e 1 13) := Classical.byContradiction (fun hu => c827 e tri schur hu h4 v2)
  have v4 : (e 10 13) := Classical.byContradiction (fun hu => c852 e tri schur h5 v0 hu)
  have v5 : (¬ e 10 15) := fun hu => c1232 e tri schur h1 hu h2
  have v6 : (¬ e 15 17) := fun hu => c1345 e tri schur hu h0 h2
  exact c102 e tri schur v4 v3 h3

theorem c1357 : (e 1 13) → (e 1 10) → (e 1 3) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 10) := fun hu => c22 e tri schur hu h1 h2
  have v1 : (¬ e 3 13) := fun hu => c25 e tri schur hu h0 h2
  have v2 : (¬ e 10 13) := fun hu => c102 e tri schur hu h0 h1
  exact c852 e tri schur v0 v1 v2

theorem c1358 : (e 4 15) → (e 4 12) → (e 2 11) → (e 1 4) → (¬ e 1 11) → (¬ e 1 12) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 1 15) := fun hu => c41 e tri schur h0 hu h3
  have v1 : (¬ e 12 15) := fun hu => c433 e tri schur hu h0 h1
  have v2 : (e 11 12) := Classical.byContradiction (fun hu => c825 e tri schur h4 h5 hu)
  have v3 : (¬ e 3 4) := fun hu => c1188 e tri schur h0 h1 hu
  have v4 : (¬ e 4 13) := fun hu => c1260 e tri schur hu h1 h3
  have v5 : (¬ e 4 11) := fun hu => c1335 e tri schur h1 hu h3 h5
  have v6 : (¬ e 10 11) := fun hu => c1336 e tri schur v2 hu h2
  have v7 : (¬ e 11 14) := fun hu => c1340 e tri schur hu v2 h2
  have v8 : (¬ e 2 12) := fun hu => c228 e tri schur v2 hu h2
  have v9 : (e 1 10) := Classical.byContradiction (fun hu => c824 e tri schur hu h4 v6)
  have v10 : (¬ e 1 14) := fun hu => c1343 e tri schur hu v9 h3
  have v11 : (¬ e 2 6) := fun hu => c1346 e tri schur v2 h0 h1 h2 hu v9 h3 v5
  have v12 : (¬ e 3 14) := fun hu => c1350 e tri schur h0 h1 hu v9 h3 v11 v8
  have v13 : (¬ e 4 10) := fun hu => c36 e tri schur hu v9 h3
  have v14 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v10 v0 hu)
  have v15 : (e 3 11) := Classical.byContradiction (fun hu => c853 e tri schur hu v12 v7)
  have v16 : (¬ e 2 3) := fun hu => c143 e tri schur v15 h2 hu
  have v17 : (¬ e 3 12) := fun hu => c333 e tri schur v2 hu v15
  have v18 : (¬ e 4 14) := fun hu => c442 e tri schur v14 h0 hu
  have v19 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur v17 hu v1)
  have v20 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v13 v18 hu)
  have v21 : (¬ e 7 15) := fun hu => c1023 e tri schur hu h0 v19
  have v22 : (¬ e 15 17) := fun hu => c1345 e tri schur hu v14 v19
  have v23 : (¬ e 2 14) := fun hu => c1355 e tri schur h0 v19 hu v9 h3 v16 v11 v4
  have v24 : (¬ e 11 15) := fun hu => c336 e tri schur hu v19 v15
  have v25 : (¬ e 10 15) := fun hu => c750 e tri schur v14 hu v20
  have v26 : (e 12 14) := Classical.byContradiction (fun hu => c841 e tri schur v8 v23 hu)
  have v27 : (¬ e 10 12) := fun hu => c740 e tri schur v26 v20 hu
  have v28 : (e 2 10) := Classical.byContradiction (fun hu => c839 e tri schur hu v8 v27)
  have v29 : (¬ e 1 2) := fun hu => c7 e tri schur v28 v9 hu
  have v30 : (e 1 3) := Classical.byContradiction (fun hu => c816 e tri schur v29 hu v16)
  have v31 : (¬ e 1 13) := fun hu => c1357 e tri schur hu v9 v30
  have v32 : (¬ e 3 10) := fun hu => c22 e tri schur hu v9 v30
  have v33 : (e 12 13) := Classical.byContradiction (fun hu => c826 e tri schur h5 v31 hu)
  have v34 : (e 13 14) := Classical.byContradiction (fun hu => c827 e tri schur v31 v10 hu)
  have v35 : (¬ e 13 15) := fun hu => c1356 e tri schur v14 hu v19 v9 v10 v32
  have v36 : (¬ e 10 13) := fun hu => c745 e tri schur v34 v20 hu
  have v37 : (¬ e 11 13) := fun hu => c760 e tri schur v33 hu v2
  exact c781 e tri schur v34 v26 v33

theorem c1359 : (e 11 12) → (¬ e 1 12) → (¬ e 1 13) → (¬ e 1 14) → (¬ e 2 11) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (e 12 13) := Classical.byContradiction (fun hu => c826 e tri schur h1 h2 hu)
  have v1 : (e 13 14) := Classical.byContradiction (fun hu => c827 e tri schur h2 h3 hu)
  have v2 : (¬ e 11 13) := fun hu => c760 e tri schur v0 hu h0
  have v3 : (¬ e 12 14) := fun hu => c781 e tri schur v1 hu v0
  have v4 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur h4 hu v2)
  have v5 : (¬ e 2 12) := fun hu => c235 e tri schur v0 v4 hu
  have v6 : (¬ e 2 14) := fun hu => c241 e tri schur v1 hu v4
  exact c841 e tri schur v5 v6 v3

theorem c1360 : (e 11 12) → (e 10 14) → (e 4 12) → (e 1 10) → (¬ e 1 3) → (¬ e 1 15) → (¬ e 2 12) → (¬ e 2 14) → (¬ e 4 10) → (¬ e 10 13) → (¬ e 12 15) → (¬ e 13 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11
  have v0 : (¬ e 1 14) := fun hu => c103 e tri schur h1 hu h3
  have v1 : (¬ e 4 11) := fun hu => c424 e tri schur h0 h2 hu
  have v2 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v0 h5 hu)
  have v3 : (e 12 14) := Classical.byContradiction (fun hu => c841 e tri schur h6 h7 hu)
  have v4 : (¬ e 3 14) := fun hu => c1341 e tri schur v3 h2 hu h3 h5 h8 h10
  have v5 : (¬ e 4 14) := fun hu => c432 e tri schur v3 hu h2
  have v6 : (¬ e 10 12) := fun hu => c740 e tri schur v3 h1 hu
  have v7 : (¬ e 10 15) := fun hu => c750 e tri schur v2 hu h1
  have v8 : (¬ e 11 14) := fun hu => c761 e tri schur v3 hu h0
  have v9 : (e 2 10) := Classical.byContradiction (fun hu => c839 e tri schur hu h6 v6)
  have v10 : (e 3 11) := Classical.byContradiction (fun hu => c853 e tri schur hu v4 v8)
  have v11 : (¬ e 1 2) := fun hu => c7 e tri schur v9 h3 hu
  have v12 : (¬ e 3 12) := fun hu => c333 e tri schur h0 hu v10
  have v13 : (e 2 3) := Classical.byContradiction (fun hu => c816 e tri schur v11 h4 hu)
  have v14 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur v12 hu h10)
  have v15 : (¬ e 15 17) := fun hu => c1345 e tri schur hu v2 v14
  have v16 : (¬ e 3 10) := fun hu => c142 e tri schur hu v9 v13
  have v17 : (¬ e 2 11) := fun hu => c143 e tri schur v10 hu v13
  have v18 : (¬ e 2 15) := fun hu => c147 e tri schur v14 hu v13
  have v19 : (¬ e 11 15) := fun hu => c336 e tri schur hu v14 v10
  have v20 : (e 2 13) := Classical.byContradiction (fun hu => c842 e tri schur hu v18 h11)
  have v21 : (e 2 17) := Classical.byContradiction (fun hu => c844 e tri schur v18 hu v15)
  have v22 : (e 3 13) := Classical.byContradiction (fun hu => c852 e tri schur v16 hu h9)
  have v23 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur v1 hu v19)
  have v24 : (¬ e 7 15) := fun hu => c1023 e tri schur hu v23 v14
  have v25 : (¬ e 3 4) := fun hu => c1188 e tri schur v23 h2 hu
  exact c145 e tri schur v22 v20 v13

theorem c1361 : (e 11 12) → (e 9 11) → (e 3 11) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 9) := fun hu => c317 e tri schur h1 h2 hu
  have v1 : (¬ e 3 12) := fun hu => c333 e tri schur h0 hu h2
  have v2 : (¬ e 9 12) := fun hu => c704 e tri schur h0 hu h1
  exact c851 e tri schur v0 v1 v2

theorem c1362 : (e 11 12) → (e 4 15) → (e 3 11) → (e 2 12) → (e 1 13) → (e 1 10) → (¬ e 2 4) → (¬ e 2 11) → (¬ e 12 15) → (¬ e 13 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9
  have v0 : (¬ e 10 13) := fun hu => c102 e tri schur hu h4 h5
  have v1 : (¬ e 3 12) := fun hu => c333 e tri schur h0 hu h2
  have v2 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur v1 hu h8)
  have v3 : (¬ e 7 15) := fun hu => c1023 e tri schur hu h1 v2
  have v4 : (¬ e 1 3) := fun hu => c1357 e tri schur h4 h5 hu
  have v5 : (¬ e 9 11) := fun hu => c1361 e tri schur h0 hu h2
  have v6 : (¬ e 3 4) := fun hu => c266 e tri schur h1 v2 hu
  have v7 : (¬ e 11 15) := fun hu => c336 e tri schur hu v2 h2
  have v8 : (e 1 4) := Classical.byContradiction (fun hu => c817 e tri schur v4 hu v6)
  have v9 : (e 2 9) := Classical.byContradiction (fun hu => c838 e tri schur hu h7 v5)
  have v10 : (¬ e 1 14) := fun hu => c1343 e tri schur hu h5 v8
  have v11 : (¬ e 4 10) := fun hu => c36 e tri schur hu h5 v8
  have v12 : (¬ e 4 13) := fun hu => c39 e tri schur hu h4 v8
  have v13 : (¬ e 1 15) := fun hu => c41 e tri schur h1 hu v8
  have v14 : (¬ e 9 12) := fun hu => c213 e tri schur hu h3 v9
  have v15 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v10 v13 hu)
  have v16 : (e 3 9) := Classical.byContradiction (fun hu => c851 e tri schur hu v1 v14)
  have v17 : (¬ e 15 17) := fun hu => c1345 e tri schur hu v15 v2
  have v18 : (¬ e 2 3) := fun hu => c141 e tri schur v16 v9 hu
  have v19 : (¬ e 9 15) := fun hu => c321 e tri schur hu v2 v16
  have v20 : (¬ e 3 14) := fun hu => c351 e tri schur v15 v2 hu
  have v21 : (¬ e 4 14) := fun hu => c442 e tri schur v15 h1 hu
  have v22 : (e 1 2) := Classical.byContradiction (fun hu => c816 e tri schur hu v4 v18)
  have v23 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v11 v21 hu)
  have v24 : (¬ e 1 9) := fun hu => c6 e tri schur v9 hu v22
  have v25 : (¬ e 2 10) := fun hu => c7 e tri schur hu h5 v22
  have v26 : (¬ e 1 12) := fun hu => c9 e tri schur h3 hu v22
  have v27 : (¬ e 2 13) := fun hu => c10 e tri schur hu h4 v22
  have v28 : (¬ e 10 15) := fun hu => c750 e tri schur v15 hu v23
  have v29 : (e 11 13) := Classical.byContradiction (fun hu => c840 e tri schur h7 v27 hu)
  have v30 : (e 2 15) := Classical.byContradiction (fun hu => c842 e tri schur v27 hu h9)
  have v31 : (¬ e 1 8) := fun hu => c1349 e tri schur h5 hu v22 v25
  have v32 : (¬ e 1 11) := fun hu => c109 e tri schur v29 h4 hu
  have v33 : (¬ e 2 14) := fun hu => c246 e tri schur v15 v30 hu
  have v34 : (¬ e 3 13) := fun hu => c334 e tri schur v29 hu h2
  have v35 : (¬ e 12 13) := fun hu => c760 e tri schur hu v29 h0
  have v36 : (e 8 9) := Classical.byContradiction (fun hu => c822 e tri schur v31 v24 hu)
  have v37 : (e 3 10) := Classical.byContradiction (fun hu => c852 e tri schur hu v34 v0)
  have v38 : (¬ e 6 9) := fun hu => c903 e tri schur v36 hu v9
  have v39 : (¬ e 2 8) := fun hu => c201 e tri schur v36 v9 hu
  have v40 : (¬ e 3 8) := fun hu => c306 e tri schur v36 v16 hu
  have v41 : (¬ e 9 10) := fun hu => c316 e tri schur hu v37 v16
  have v42 : (¬ e 10 11) := fun hu => c325 e tri schur hu h2 v37
  have v43 : (e 8 10) := Classical.byContradiction (fun hu => c837 e tri schur v39 v25 hu)
  have v44 : (e 6 15) := Classical.byContradiction (fun hu => c878 e tri schur v38 hu v19)
  have v45 : (¬ e 5 10) := fun hu => c942 e tri schur v43 hu v37
  have v46 : (¬ e 2 6) := fun hu => c186 e tri schur v44 v30 hu
  have v47 : (¬ e 3 6) := fun hu => c291 e tri schur v44 v2 hu
  have v48 : (¬ e 4 6) := fun hu => c382 e tri schur v44 h1 hu
  have v49 : (¬ e 6 14) := fun hu => c586 e tri schur v15 v44 hu
  have v50 : (¬ e 8 14) := fun hu => c663 e tri schur v23 hu v43
  exact c833 e tri schur h6 v46 v48

theorem c1363 : (e 2 12) → (e 2 9) → (e 2 3) → (¬ e 3 12) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 9) := fun hu => c141 e tri schur hu h1 h2
  have v1 : (¬ e 9 12) := fun hu => c213 e tri schur hu h0 h1
  exact c851 e tri schur v0 h3 v1

theorem c1364 : (e 9 11) → (e 4 17) → (e 4 15) → (e 4 6) → (¬ e 9 15) → (¬ e 11 17) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 6 15) := fun hu => c382 e tri schur hu h2 h3
  have v1 : (¬ e 6 17) := fun hu => c384 e tri schur hu h1 h3
  have v2 : (¬ e 15 17) := fun hu => c447 e tri schur hu h1 h2
  have v3 : (e 6 9) := Classical.byContradiction (fun hu => c878 e tri schur hu v0 h4)
  have v4 : (e 6 11) := Classical.byContradiction (fun hu => c880 e tri schur hu v1 h5)
  have v5 : (¬ e 4 9) := fun hu => c1194 e tri schur h2 hu h3
  have v6 : (¬ e 4 11) := fun hu => c378 e tri schur v4 hu h3
  exact c552 e tri schur h0 v4 v3

theorem c1365 : (e 14 15) → (e 13 14) → (e 11 12) → (e 4 15) → (e 2 12) → (e 1 13) → (¬ e 1 3) → (¬ e 2 4) → (¬ e 2 11) → (¬ e 3 11) → (¬ e 3 12) → (¬ e 4 10) → (¬ e 4 13) → (¬ e 10 13) → (¬ e 12 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14
  have v0 : (¬ e 1 14) := fun hu => c121 e tri schur h1 hu h5
  have v1 : (¬ e 4 14) := fun hu => c442 e tri schur h0 h3 hu
  have v2 : (¬ e 13 15) := fun hu => c796 e tri schur h0 hu h1
  have v3 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur h10 hu h14)
  have v4 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur h11 v1 hu)
  have v5 : (¬ e 7 15) := fun hu => c1023 e tri schur hu h3 v3
  have v6 : (¬ e 15 17) := fun hu => c1345 e tri schur hu h0 v3
  have v7 : (¬ e 3 4) := fun hu => c266 e tri schur h3 v3 hu
  have v8 : (¬ e 3 14) := fun hu => c351 e tri schur h0 v3 hu
  have v9 : (¬ e 10 15) := fun hu => c750 e tri schur h0 hu v4
  have v10 : (e 1 4) := Classical.byContradiction (fun hu => c817 e tri schur h6 hu v7)
  have v11 : (e 11 14) := Classical.byContradiction (fun hu => c853 e tri schur h9 v8 hu)
  have v12 : (¬ e 1 15) := fun hu => c41 e tri schur h3 hu v10
  have v13 : (¬ e 10 11) := fun hu => c734 e tri schur v11 v4 hu
  have v14 : (¬ e 12 14) := fun hu => c761 e tri schur hu v11 h2
  have v15 : (¬ e 11 13) := fun hu => c766 e tri schur h1 v11 hu
  have v16 : (¬ e 11 15) := fun hu => c771 e tri schur h0 hu v11
  have v17 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur h8 hu v15)
  have v18 : (¬ e 1 2) := fun hu => c10 e tri schur v17 h5 hu
  have v19 : (¬ e 12 13) := fun hu => c235 e tri schur hu v17 h4
  have v20 : (¬ e 2 14) := fun hu => c241 e tri schur h1 hu v17
  have v21 : (e 2 3) := Classical.byContradiction (fun hu => c816 e tri schur v18 h6 hu)
  have v22 : (¬ e 2 15) := fun hu => c913 e tri schur hu h4 v21 h14
  have v23 : (¬ e 2 9) := fun hu => c1363 e tri schur h4 hu v21 h10
  have v24 : (¬ e 3 13) := fun hu => c145 e tri schur hu v17 v21
  have v25 : (e 9 11) := Classical.byContradiction (fun hu => c838 e tri schur v23 h8 hu)
  have v26 : (e 2 17) := Classical.byContradiction (fun hu => c844 e tri schur v22 hu v6)
  have v27 : (e 3 10) := Classical.byContradiction (fun hu => c852 e tri schur hu v24 h13)
  have v28 : (¬ e 2 5) := fun hu => c1231 e tri schur v26 h4 hu
  have v29 : (¬ e 3 8) := fun hu => c1324 e tri schur v27 hu v21
  have v30 : (¬ e 2 10) := fun hu => c142 e tri schur v27 hu v21
  have v31 : (¬ e 3 17) := fun hu => c149 e tri schur hu v26 v21
  have v32 : (¬ e 12 17) := fun hu => c239 e tri schur hu v26 h4
  have v33 : (¬ e 13 17) := fun hu => c244 e tri schur hu v26 v17
  have v34 : (¬ e 9 12) := fun hu => c704 e tri schur h2 hu v25
  have v35 : (¬ e 9 14) := fun hu => c706 e tri schur v11 hu v25
  have v36 : (e 8 11) := Classical.byContradiction (fun hu => c850 e tri schur v29 h9 hu)
  have v37 : (e 3 9) := Classical.byContradiction (fun hu => c851 e tri schur hu h10 v34)
  have v38 : (e 14 17) := Classical.byContradiction (fun hu => c856 e tri schur v8 v31 hu)
  have v39 : (e 4 17) := Classical.byContradiction (fun hu => c866 e tri schur h12 hu v33)
  have v40 : (¬ e 1 17) := fun hu => c43 e tri schur v39 hu v10
  have v41 : (¬ e 9 10) := fun hu => c316 e tri schur hu v27 v37
  have v42 : (¬ e 9 15) := fun hu => c321 e tri schur hu v3 v37
  have v43 : (¬ e 8 9) := fun hu => c652 e tri schur v25 v36 hu
  have v44 : (¬ e 8 12) := fun hu => c668 e tri schur h2 hu v36
  have v45 : (¬ e 8 14) := fun hu => c670 e tri schur v11 hu v36
  have v46 : (¬ e 10 17) := fun hu => c752 e tri schur v38 hu v4
  have v47 : (¬ e 11 17) := fun hu => c773 e tri schur v38 hu v11
  have v48 : (¬ e 4 6) := fun hu => c1364 e tri schur v25 v39 h3 hu v42 v47
  have v49 : (e 2 6) := Classical.byContradiction (fun hu => c833 e tri schur h7 hu v48)
  have v50 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur v48 h11 hu)
  have v51 : (¬ e 3 6) := fun hu => c138 e tri schur hu v49 v21
  have v52 : (¬ e 6 12) := fun hu => c183 e tri schur hu h4 v49
  have v53 : (¬ e 6 13) := fun hu => c184 e tri schur hu v17 v49
  have v54 : (¬ e 6 17) := fun hu => c188 e tri schur hu v26 v49
  have v55 : (¬ e 6 14) := fun hu => c563 e tri schur v4 hu v50
  have v56 : (e 6 8) := Classical.byContradiction (fun hu => c877 e tri schur hu v55 v45)
  have v57 : (e 6 11) := Classical.byContradiction (fun hu => c880 e tri schur hu v54 v47)
  have v58 : (¬ e 2 7) := fun hu => c947 e tri schur v57 hu v49 v15
  have v59 : (¬ e 2 8) := fun hu => c179 e tri schur v56 hu v49
  have v60 : (¬ e 8 10) := fun hu => c542 e tri schur hu v50 v56
  exact c543 e tri schur v36 v57 v56

theorem c1366 : (e 13 14) → (e 10 14) → (e 3 14) → (¬ e 10 13) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 10) := fun hu => c328 e tri schur h1 h2 hu
  have v1 : (¬ e 3 13) := fun hu => c346 e tri schur h0 h2 hu
  exact c852 e tri schur v0 v1 h3

theorem c1367 : (e 11 12) → (e 4 15) → (e 4 12) → (e 3 11) → (e 1 13) → (e 1 10) → (e 1 4) → (e 1 2) → (¬ e 2 11) → (¬ e 13 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9
  have v0 : (¬ e 2 4) := fun hu => c1 e tri schur hu h6 h7
  have v1 : (¬ e 2 10) := fun hu => c7 e tri schur hu h5 h7
  have v2 : (¬ e 2 13) := fun hu => c10 e tri schur hu h4 h7
  have v3 : (¬ e 4 10) := fun hu => c36 e tri schur hu h5 h6
  have v4 : (¬ e 1 12) := fun hu => c38 e tri schur h2 hu h6
  have v5 : (¬ e 4 13) := fun hu => c39 e tri schur hu h4 h6
  have v6 : (¬ e 1 15) := fun hu => c41 e tri schur h1 hu h6
  have v7 : (¬ e 10 13) := fun hu => c102 e tri schur hu h4 h5
  have v8 : (¬ e 3 12) := fun hu => c333 e tri schur h0 hu h3
  have v9 : (¬ e 4 11) := fun hu => c424 e tri schur h0 h2 hu
  have v10 : (¬ e 12 15) := fun hu => c433 e tri schur hu h1 h2
  have v11 : (e 11 13) := Classical.byContradiction (fun hu => c840 e tri schur h8 v2 hu)
  have v12 : (e 2 15) := Classical.byContradiction (fun hu => c842 e tri schur v2 hu h9)
  have v13 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur v8 hu v10)
  have v14 : (¬ e 7 15) := fun hu => c1023 e tri schur hu h1 v13
  have v15 : (¬ e 3 4) := fun hu => c1188 e tri schur h1 h2 hu
  have v16 : (¬ e 1 14) := fun hu => c1343 e tri schur hu h5 h6
  have v17 : (¬ e 1 8) := fun hu => c1349 e tri schur h5 hu h7 v1
  have v18 : (¬ e 1 3) := fun hu => c1357 e tri schur h4 h5 hu
  have v19 : (¬ e 9 11) := fun hu => c1361 e tri schur h0 hu h3
  have v20 : (¬ e 2 12) := fun hu => c1362 e tri schur h0 h1 h3 hu h4 h5 v0 h8 v10 h9
  have v21 : (¬ e 1 11) := fun hu => c109 e tri schur v11 h4 hu
  have v22 : (¬ e 2 3) := fun hu => c147 e tri schur v13 v12 hu
  have v23 : (¬ e 3 13) := fun hu => c334 e tri schur v11 hu h3
  have v24 : (¬ e 11 15) := fun hu => c336 e tri schur hu v13 h3
  have v25 : (¬ e 12 13) := fun hu => c760 e tri schur hu v11 h0
  have v26 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v16 v6 hu)
  have v27 : (e 2 9) := Classical.byContradiction (fun hu => c838 e tri schur hu h8 v19)
  have v28 : (e 10 12) := Classical.byContradiction (fun hu => c839 e tri schur v1 v20 hu)
  have v29 : (e 3 10) := Classical.byContradiction (fun hu => c852 e tri schur hu v23 v7)
  have v30 : (¬ e 3 14) := fun hu => c1342 e tri schur h2 hu v12 h5 v6 v20 v3 v10
  have v31 : (¬ e 15 17) := fun hu => c1345 e tri schur hu v26 v13
  have v32 : (¬ e 1 9) := fun hu => c6 e tri schur v27 hu h7
  have v33 : (¬ e 9 15) := fun hu => c216 e tri schur hu v12 v27
  have v34 : (¬ e 2 14) := fun hu => c246 e tri schur v26 v12 hu
  have v35 : (¬ e 10 11) := fun hu => c325 e tri schur hu h3 v29
  have v36 : (¬ e 10 15) := fun hu => c329 e tri schur hu v13 v29
  have v37 : (¬ e 4 14) := fun hu => c442 e tri schur v26 h1 hu
  have v38 : (e 8 9) := Classical.byContradiction (fun hu => c822 e tri schur v17 v32 hu)
  have v39 : (e 12 14) := Classical.byContradiction (fun hu => c841 e tri schur v20 v34 hu)
  have v40 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v3 v37 hu)
  have v41 : (¬ e 6 9) := fun hu => c903 e tri schur v38 hu v27
  exact c1360 e tri schur h0 v40 h2 h5 v18 v6 v20 v34 v3 v7 v10 h9

theorem c1368 : (e 13 14) → (e 11 12) → (e 4 15) → (e 4 12) → (e 3 11) → (e 1 13) → (e 1 10) → (e 1 4) → (¬ e 2 11) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8
  have v0 : (¬ e 4 10) := fun hu => c36 e tri schur hu h6 h7
  have v1 : (¬ e 1 12) := fun hu => c38 e tri schur h3 hu h7
  have v2 : (¬ e 4 13) := fun hu => c39 e tri schur hu h5 h7
  have v3 : (¬ e 1 15) := fun hu => c41 e tri schur h2 hu h7
  have v4 : (¬ e 10 13) := fun hu => c102 e tri schur hu h5 h6
  have v5 : (¬ e 1 14) := fun hu => c121 e tri schur h0 hu h5
  have v6 : (¬ e 3 12) := fun hu => c333 e tri schur h1 hu h4
  have v7 : (¬ e 4 11) := fun hu => c424 e tri schur h1 h3 hu
  have v8 : (¬ e 12 15) := fun hu => c433 e tri schur hu h2 h3
  have v9 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v5 v3 hu)
  have v10 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur v6 hu v8)
  have v11 : (¬ e 7 15) := fun hu => c1023 e tri schur hu h2 v10
  have v12 : (¬ e 3 4) := fun hu => c1188 e tri schur h2 h3 hu
  have v13 : (¬ e 15 17) := fun hu => c1345 e tri schur hu v9 v10
  have v14 : (¬ e 1 3) := fun hu => c1357 e tri schur h5 h6 hu
  have v15 : (¬ e 9 11) := fun hu => c1361 e tri schur h1 hu h4
  have v16 : (¬ e 11 15) := fun hu => c336 e tri schur hu v10 h4
  have v17 : (¬ e 3 14) := fun hu => c351 e tri schur v9 v10 hu
  have v18 : (¬ e 4 14) := fun hu => c442 e tri schur v9 h2 hu
  have v19 : (¬ e 13 15) := fun hu => c796 e tri schur v9 hu h0
  have v20 : (e 2 9) := Classical.byContradiction (fun hu => c838 e tri schur hu h8 v15)
  have v21 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v0 v18 hu)
  have v22 : (¬ e 1 2) := fun hu => c1367 e tri schur h1 h2 h3 h4 h5 h6 h7 hu h8 v19
  have v23 : (¬ e 10 15) := fun hu => c750 e tri schur v9 hu v21
  have v24 : (e 2 3) := Classical.byContradiction (fun hu => c816 e tri schur v22 v14 hu)
  have v25 : (¬ e 2 6) := fun hu => c1010 e tri schur v20 hu v24
  have v26 : (¬ e 2 12) := fun hu => c1363 e tri schur hu v20 v24 v6
  have v27 : (¬ e 3 9) := fun hu => c141 e tri schur hu v20 v24
  have v28 : (¬ e 2 15) := fun hu => c147 e tri schur v10 hu v24
  have v29 : (e 2 13) := Classical.byContradiction (fun hu => c842 e tri schur hu v28 v19)
  have v30 : (e 2 17) := Classical.byContradiction (fun hu => c844 e tri schur v28 hu v13)
  have v31 : (e 9 12) := Classical.byContradiction (fun hu => c851 e tri schur v27 v6 hu)
  have v32 : (e 2 14) := Classical.byContradiction (fun hu => c1360 e tri schur h1 v21 h3 h6 v14 v3 v26 hu v0 v4 v8 v19)
  have v33 : (¬ e 3 13) := fun hu => c145 e tri schur hu v29 v24
  have v34 : (¬ e 3 17) := fun hu => c149 e tri schur hu v30 v24
  have v35 : (¬ e 9 13) := fun hu => c214 e tri schur hu v29 v20
  have v36 : (¬ e 9 14) := fun hu => c215 e tri schur hu v32 v20
  have v37 : (¬ e 9 17) := fun hu => c218 e tri schur hu v30 v20
  have v38 : (¬ e 2 10) := fun hu => c223 e tri schur v21 v32 hu
  exact c241 e tri schur h0 v32 v29

theorem c1369 : (e 13 14) → (e 11 12) → (e 4 15) → (e 4 12) → (e 1 13) → (e 1 10) → (e 1 4) → (¬ e 2 11) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 4 10) := fun hu => c36 e tri schur hu h5 h6
  have v1 : (¬ e 1 12) := fun hu => c38 e tri schur h3 hu h6
  have v2 : (¬ e 4 13) := fun hu => c39 e tri schur hu h4 h6
  have v3 : (¬ e 1 15) := fun hu => c41 e tri schur h2 hu h6
  have v4 : (¬ e 10 13) := fun hu => c102 e tri schur hu h4 h5
  have v5 : (¬ e 1 14) := fun hu => c121 e tri schur h0 hu h4
  have v6 : (¬ e 4 11) := fun hu => c424 e tri schur h1 h3 hu
  have v7 : (¬ e 12 15) := fun hu => c433 e tri schur hu h2 h3
  have v8 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v5 v3 hu)
  have v9 : (¬ e 3 4) := fun hu => c1188 e tri schur h2 h3 hu
  have v10 : (¬ e 1 3) := fun hu => c1357 e tri schur h4 h5 hu
  have v11 : (¬ e 3 11) := fun hu => c1368 e tri schur h0 h1 h2 h3 hu h4 h5 h6 h7
  have v12 : (¬ e 4 14) := fun hu => c442 e tri schur v8 h2 hu
  have v13 : (¬ e 13 15) := fun hu => c796 e tri schur v8 hu h0
  have v14 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v0 v12 hu)
  have v15 : (¬ e 3 14) := fun hu => c1366 e tri schur h0 v14 hu v4
  have v16 : (¬ e 10 15) := fun hu => c750 e tri schur v8 hu v14
  have v17 : (e 11 14) := Classical.byContradiction (fun hu => c853 e tri schur v11 v15 hu)
  have v18 : (¬ e 10 11) := fun hu => c734 e tri schur v17 v14 hu
  have v19 : (¬ e 12 14) := fun hu => c761 e tri schur hu v17 h1
  have v20 : (¬ e 11 13) := fun hu => c766 e tri schur h0 v17 hu
  have v21 : (¬ e 11 15) := fun hu => c771 e tri schur v8 hu v17
  have v22 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur h7 hu v20)
  have v23 : (¬ e 1 2) := fun hu => c10 e tri schur v22 h4 hu
  have v24 : (¬ e 2 14) := fun hu => c241 e tri schur h0 hu v22
  have v25 : (e 2 3) := Classical.byContradiction (fun hu => c816 e tri schur v23 v10 hu)
  have v26 : (e 2 12) := Classical.byContradiction (fun hu => c841 e tri schur hu v24 v19)
  have v27 : (¬ e 2 15) := fun hu => c913 e tri schur hu v26 v25 v7
  have v28 : (¬ e 3 12) := fun hu => c144 e tri schur hu v26 v25
  have v29 : (¬ e 3 13) := fun hu => c145 e tri schur hu v22 v25
  have v30 : (¬ e 2 4) := fun hu => c158 e tri schur h3 v26 hu
  have v31 : (¬ e 12 13) := fun hu => c235 e tri schur hu v22 v26
  have v32 : (e 3 10) := Classical.byContradiction (fun hu => c852 e tri schur hu v29 v4)
  have v33 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur v28 hu v7)
  have v34 : (¬ e 7 15) := fun hu => c1023 e tri schur hu h2 v33
  have v35 : (¬ e 3 8) := fun hu => c1324 e tri schur v32 hu v25
  have v36 : (¬ e 15 17) := fun hu => c1345 e tri schur hu v8 v33
  have v37 : (¬ e 2 9) := fun hu => c1363 e tri schur v26 hu v25 v28
  exact c1365 e tri schur v8 h0 h1 h2 v26 h4 v10 v30 h7 v11 v28 v0 v2 v4 v7

theorem c1370 : (e 11 14) → (e 10 14) → (e 9 11) → (e 4 15) → (e 2 17) → (e 2 13) → (e 2 3) → (¬ e 2 4) → (¬ e 3 11) → (¬ e 4 10) → (¬ e 4 13) → (¬ e 9 15) → (¬ e 10 13) → (¬ e 11 17) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13
  have v0 : (¬ e 3 13) := fun hu => c145 e tri schur hu h5 h6
  have v1 : (¬ e 3 17) := fun hu => c149 e tri schur hu h4 h6
  have v2 : (¬ e 13 17) := fun hu => c244 e tri schur hu h4 h5
  have v3 : (¬ e 9 14) := fun hu => c706 e tri schur h0 hu h2
  have v4 : (¬ e 10 11) := fun hu => c734 e tri schur h0 h1 hu
  have v5 : (e 3 10) := Classical.byContradiction (fun hu => c852 e tri schur hu v0 h12)
  have v6 : (e 4 17) := Classical.byContradiction (fun hu => c866 e tri schur h10 hu v2)
  have v7 : (¬ e 3 8) := fun hu => c1324 e tri schur v5 hu h6
  have v8 : (¬ e 4 6) := fun hu => c1364 e tri schur h2 v6 h3 hu h11 h13
  have v9 : (¬ e 2 10) := fun hu => c142 e tri schur v5 hu h6
  have v10 : (¬ e 3 14) := fun hu => c328 e tri schur h1 hu v5
  have v11 : (¬ e 15 17) := fun hu => c447 e tri schur hu v6 h3
  have v12 : (e 2 6) := Classical.byContradiction (fun hu => c833 e tri schur h7 hu v8)
  have v13 : (e 8 11) := Classical.byContradiction (fun hu => c850 e tri schur v7 h8 hu)
  have v14 : (e 14 17) := Classical.byContradiction (fun hu => c856 e tri schur v10 v1 hu)
  have v15 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur v8 h9 hu)
  have v16 : (¬ e 2 9) := fun hu => c1010 e tri schur hu v12 h6
  have v17 : (¬ e 2 11) := fun hu => c1333 e tri schur h4 hu v12
  have v18 : (¬ e 3 6) := fun hu => c138 e tri schur hu v12 h6
  have v19 : (¬ e 6 13) := fun hu => c184 e tri schur hu h5 v12
  have v20 : (¬ e 6 17) := fun hu => c188 e tri schur hu h4 v12
  have v21 : (¬ e 2 14) := fun hu => c248 e tri schur v14 h4 hu
  have v22 : (¬ e 4 14) := fun hu => c444 e tri schur v14 v6 hu
  have v23 : (¬ e 6 14) := fun hu => c563 e tri schur h1 hu v15
  have v24 : (¬ e 8 9) := fun hu => c652 e tri schur h2 v13 hu
  have v25 : (¬ e 8 14) := fun hu => c670 e tri schur h0 hu v13
  have v26 : (¬ e 10 17) := fun hu => c752 e tri schur v14 hu h1
  have v27 : (e 6 8) := Classical.byContradiction (fun hu => c877 e tri schur hu v23 v25)
  have v28 : (e 6 11) := Classical.byContradiction (fun hu => c880 e tri schur hu v20 h13)
  have v29 : (¬ e 2 8) := fun hu => c179 e tri schur v27 hu v12
  have v30 : (¬ e 8 10) := fun hu => c542 e tri schur hu v15 v27
  exact c543 e tri schur v13 v28 v27

theorem c1371 : (e 14 15) → (e 11 14) → (e 11 12) → (e 4 15) → (e 2 12) → (e 2 3) → (e 1 10) → (¬ e 1 14) → (¬ e 2 4) → (¬ e 2 11) → (¬ e 3 11) → (¬ e 3 14) → (¬ e 4 10) → (¬ e 4 13) → (¬ e 10 13) → (¬ e 12 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14 h15
  have v0 : (¬ e 3 12) := fun hu => c144 e tri schur hu h4 h5
  have v1 : (¬ e 4 14) := fun hu => c442 e tri schur h0 h3 hu
  have v2 : (¬ e 12 14) := fun hu => c761 e tri schur hu h1 h2
  have v3 : (¬ e 11 15) := fun hu => c771 e tri schur h0 hu h1
  have v4 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur v0 hu h15)
  have v5 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur h12 v1 hu)
  have v6 : (¬ e 2 15) := fun hu => c913 e tri schur hu h4 h5 h15
  have v7 : (¬ e 7 15) := fun hu => c1023 e tri schur hu h3 v4
  have v8 : (¬ e 15 17) := fun hu => c1345 e tri schur hu h0 v4
  have v9 : (¬ e 2 9) := fun hu => c1363 e tri schur h4 hu h5 v0
  have v10 : (¬ e 3 4) := fun hu => c266 e tri schur h3 v4 hu
  have v11 : (¬ e 10 11) := fun hu => c734 e tri schur h1 v5 hu
  have v12 : (¬ e 10 15) := fun hu => c750 e tri schur h0 hu v5
  have v13 : (e 9 11) := Classical.byContradiction (fun hu => c838 e tri schur v9 h9 hu)
  have v14 : (e 2 17) := Classical.byContradiction (fun hu => c844 e tri schur v6 hu v8)
  have v15 : (¬ e 2 5) := fun hu => c1231 e tri schur v14 h4 hu
  have v16 : (¬ e 3 17) := fun hu => c149 e tri schur hu v14 h5
  have v17 : (¬ e 12 17) := fun hu => c239 e tri schur hu v14 h4
  have v18 : (¬ e 9 12) := fun hu => c704 e tri schur h2 hu v13
  have v19 : (¬ e 9 14) := fun hu => c706 e tri schur h1 hu v13
  have v20 : (e 3 9) := Classical.byContradiction (fun hu => c851 e tri schur hu v0 v18)
  have v21 : (e 14 17) := Classical.byContradiction (fun hu => c856 e tri schur h11 v16 hu)
  have v22 : (¬ e 2 14) := fun hu => c248 e tri schur v21 v14 hu
  have v23 : (¬ e 9 15) := fun hu => c321 e tri schur hu v4 v20
  have v24 : (¬ e 10 17) := fun hu => c752 e tri schur v21 hu v5
  have v25 : (¬ e 11 17) := fun hu => c773 e tri schur v21 hu h1
  have v26 : (¬ e 2 13) := fun hu => c1370 e tri schur h1 v5 v13 h3 v14 hu h5 h8 h10 h12 h13 v23 h14 v25
  have v27 : (e 11 13) := Classical.byContradiction (fun hu => c840 e tri schur h9 v26 hu)
  have v28 : (e 13 15) := Classical.byContradiction (fun hu => c842 e tri schur v26 v6 hu)
  have v29 : (¬ e 4 11) := fun hu => c1028 e tri schur v27 v13 hu
  have v30 : (¬ e 4 6) := fun hu => c1111 e tri schur v28 v27 v13 hu
  have v31 : (e 3 10) := Classical.byContradiction (fun hu => c1356 e tri schur h0 v28 v4 h6 h7 hu)
  have v32 : (¬ e 1 3) := fun hu => c22 e tri schur v31 h6 hu
  have v33 : (¬ e 2 10) := fun hu => c142 e tri schur v31 hu h5
  have v34 : (¬ e 9 10) := fun hu => c316 e tri schur hu v31 v20
  have v35 : (¬ e 3 13) := fun hu => c347 e tri schur v28 v4 hu
  have v36 : (¬ e 9 13) := fun hu => c705 e tri schur v27 hu v13
  have v37 : (¬ e 12 13) := fun hu => c760 e tri schur hu v27 h2
  have v38 : (¬ e 13 14) := fun hu => c766 e tri schur hu h1 v27
  have v39 : (e 1 4) := Classical.byContradiction (fun hu => c817 e tri schur v32 hu v10)
  have v40 : (e 1 13) := Classical.byContradiction (fun hu => c827 e tri schur hu h7 v38)
  have v41 : (e 2 6) := Classical.byContradiction (fun hu => c833 e tri schur h8 hu v30)
  have v42 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur v30 h12 hu)
  have v43 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu h13 v36)
  have v44 : (¬ e 7 9) := fun hu => c894 e tri schur hu v43 v20
  have v45 : (¬ e 1 6) := fun hu => c1312 e tri schur h6 hu v39 v30
  have v46 : (¬ e 3 8) := fun hu => c1324 e tri schur v31 hu h5
  have v47 : (¬ e 1 9) := fun hu => c35 e tri schur v43 hu v39
  have v48 : (¬ e 1 15) := fun hu => c41 e tri schur h3 hu v39
  have v49 : (¬ e 1 11) := fun hu => c109 e tri schur v27 v40 hu
  have v50 : (¬ e 3 6) := fun hu => c138 e tri schur hu v41 h5
  have v51 : (¬ e 6 12) := fun hu => c183 e tri schur hu h4 v41
  have v52 : (¬ e 6 17) := fun hu => c188 e tri schur hu v14 v41
  have v53 : (¬ e 6 14) := fun hu => c563 e tri schur v5 hu v42
  have v54 : (e 2 7) := Classical.byContradiction (fun hu => c836 e tri schur hu v9 v44)
  have v55 : (e 8 11) := Classical.byContradiction (fun hu => c850 e tri schur v46 h10 hu)
  have v56 : (e 6 11) := Classical.byContradiction (fun hu => c880 e tri schur hu v52 v25)
  have v57 : (¬ e 6 13) := fun hu => c1018 e tri schur hu v56 v54 v41
  have v58 : (¬ e 7 11) := fun hu => c1154 e tri schur v27 hu v56
  have v59 : (¬ e 3 7) := fun hu => c139 e tri schur hu v54 h5
  have v60 : (¬ e 6 7) := fun hu => c178 e tri schur hu v54 v41
  have v61 : (¬ e 7 12) := fun hu => c194 e tri schur hu h4 v54
  have v62 : (¬ e 7 17) := fun hu => c199 e tri schur hu v14 v54
  have v63 : (¬ e 6 8) := fun hu => c543 e tri schur v55 v56 hu
  have v64 : (¬ e 6 9) := fun hu => c552 e tri schur v13 v56 hu
  have v65 : (¬ e 8 9) := fun hu => c652 e tri schur v13 v55 hu
  have v66 : (¬ e 8 12) := fun hu => c668 e tri schur h2 hu v55
  have v67 : (¬ e 8 13) := fun hu => c669 e tri schur v27 hu v55
  have v68 : (¬ e 8 14) := fun hu => c670 e tri schur h1 hu v55
  have v69 : (e 1 7) := Classical.byContradiction (fun hu => c820 e tri schur v45 hu v60)
  have v70 : (e 1 8) := Classical.byContradiction (fun hu => c822 e tri schur hu v47 v65)
  have v71 : (e 4 7) := Classical.byContradiction (fun hu => c846 e tri schur v10 v59 hu)
  have v72 : (e 7 13) := Classical.byContradiction (fun hu => c876 e tri schur v60 v57 hu)
  exact c877 e tri schur v63 v53 v68

theorem c1373 : (e 10 14) → (e 8 10) → (e 6 10) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 6 8) := fun hu => c542 e tri schur h1 h2 hu
  have v1 : (¬ e 6 14) := fun hu => c563 e tri schur h0 hu h2
  have v2 : (¬ e 8 14) := fun hu => c663 e tri schur h0 hu h1
  exact c877 e tri schur v0 v1 v2

theorem c1374 : (e 13 15) → (e 10 14) → (e 4 15) → (e 2 9) → (e 1 2) → (¬ e 1 8) → (¬ e 2 10) → (¬ e 4 10) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8
  have v0 : (¬ e 1 9) := fun hu => c6 e tri schur h3 hu h4
  have v1 : (e 8 9) := Classical.byContradiction (fun hu => c822 e tri schur h5 v0 hu)
  have v2 : (¬ e 6 9) := fun hu => c903 e tri schur v1 hu h3
  have v3 : (¬ e 15 17) := fun hu => c1348 e tri schur hu h0 h2 h8
  have v4 : (¬ e 2 8) := fun hu => c201 e tri schur v1 h3 hu
  have v5 : (e 8 10) := Classical.byContradiction (fun hu => c837 e tri schur v4 h6 hu)
  have v6 : (¬ e 6 10) := fun hu => c1373 e tri schur h1 v5 hu
  have v7 : (¬ e 9 10) := fun hu => c651 e tri schur hu v5 v1
  have v8 : (¬ e 8 14) := fun hu => c663 e tri schur h1 hu v5
  have v9 : (e 1 10) := Classical.byContradiction (fun hu => c823 e tri schur v0 hu v7)
  have v10 : (e 4 6) := Classical.byContradiction (fun hu => c859 e tri schur hu h7 v6)
  have v11 : (¬ e 4 9) := fun hu => c1194 e tri schur h2 hu v10
  have v12 : (¬ e 1 14) := fun hu => c103 e tri schur h1 hu v9
  have v13 : (¬ e 6 15) := fun hu => c382 e tri schur hu h2 v10
  have v14 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v11 h8 hu)
  have v15 : (e 9 15) := Classical.byContradiction (fun hu => c878 e tri schur v2 v13 hu)
  have v16 : (¬ e 7 9) := fun hu => c1221 e tri schur h0 v14 hu v13
  have v17 : (¬ e 2 13) := fun hu => c214 e tri schur v14 hu h3
  have v18 : (¬ e 2 15) := fun hu => c216 e tri schur v15 hu h3
  have v19 : (¬ e 8 13) := fun hu => c654 e tri schur v14 hu v1
  have v20 : (¬ e 8 15) := fun hu => c656 e tri schur v15 hu v1
  exact c718 e tri schur h0 v15 v14

theorem c1375 : (e 13 15) → (e 11 13) → (e 10 14) → (e 4 15) → (e 1 2) → (¬ e 1 8) → (¬ e 2 10) → (¬ e 2 11) → (¬ e 4 10) → (¬ e 4 11) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10
  have v0 : (¬ e 11 15) := fun hu => c767 e tri schur h0 hu h1
  have v1 : (¬ e 15 17) := fun hu => c1348 e tri schur hu h0 h3 h10
  have v2 : (¬ e 2 9) := fun hu => c1374 e tri schur h0 h2 h3 hu h4 h5 h6 h8 h10
  have v3 : (e 9 11) := Classical.byContradiction (fun hu => c838 e tri schur v2 h7 hu)
  have v4 : (¬ e 4 6) := fun hu => c1111 e tri schur h0 h1 v3 hu
  have v5 : (¬ e 9 13) := fun hu => c705 e tri schur h1 hu v3
  have v6 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur v4 h8 hu)
  have v7 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu h10 v5)
  have v8 : (¬ e 8 10) := fun hu => c1373 e tri schur h2 hu v6
  have v9 : (¬ e 9 15) := fun hu => c412 e tri schur hu h3 v7
  have v10 : (¬ e 6 14) := fun hu => c563 e tri schur h2 hu v6
  have v11 : (e 2 8) := Classical.byContradiction (fun hu => c837 e tri schur hu h6 v8)
  have v12 : (¬ e 2 7) := fun hu => c1351 e tri schur v11 hu h4 h5
  have v13 : (e 7 9) := Classical.byContradiction (fun hu => c836 e tri schur v12 v2 hu)
  have v14 : (¬ e 3 9) := fun hu => c894 e tri schur v13 v7 hu
  have v15 : (¬ e 4 7) := fun hu => c387 e tri schur v13 v7 hu
  have v16 : (¬ e 7 11) := fun hu => c607 e tri schur v3 hu v13
  exact c860 e tri schur v15 h9 v16

theorem c1376 : (e 11 13) → (¬ e 2 7) → (¬ e 2 9) → (¬ e 2 11) → (¬ e 4 11) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (e 7 9) := Classical.byContradiction (fun hu => c836 e tri schur h1 h2 hu)
  have v1 : (e 9 11) := Classical.byContradiction (fun hu => c838 e tri schur h2 h3 hu)
  have v2 : (¬ e 7 11) := fun hu => c607 e tri schur v1 hu v0
  have v3 : (¬ e 9 13) := fun hu => c705 e tri schur h0 hu v1
  have v4 : (e 4 7) := Classical.byContradiction (fun hu => c860 e tri schur hu h4 v2)
  have v5 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu h5 v3)
  have v6 : (¬ e 3 9) := fun hu => c894 e tri schur v0 v5 hu
  have v7 : (e 2 5) := Classical.byContradiction (fun hu => c925 e tri schur v4 hu h1 h2)
  exact c387 e tri schur v0 v5 v4

theorem c1377 : (e 11 13) → (e 2 8) → (e 1 2) → (¬ e 1 8) → (¬ e 2 11) → (¬ e 4 11) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 2 7) := fun hu => c1351 e tri schur h1 hu h2 h3
  have v1 : (e 2 9) := Classical.byContradiction (fun hu => c1376 e tri schur h0 v0 hu h4 h5 h6)
  have v2 : (¬ e 1 9) := fun hu => c6 e tri schur v1 hu h2
  have v3 : (¬ e 8 9) := fun hu => c201 e tri schur hu v1 h1
  exact c822 e tri schur h3 v2 v3

theorem c1378 : (e 10 14) → (e 4 15) → (e 1 13) → (e 1 10) → (e 1 2) → (¬ e 2 11) → (¬ e 4 10) → (¬ e 4 11) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8
  have v0 : (¬ e 2 10) := fun hu => c7 e tri schur hu h3 h4
  have v1 : (¬ e 2 13) := fun hu => c10 e tri schur hu h2 h4
  have v2 : (¬ e 10 13) := fun hu => c102 e tri schur hu h2 h3
  have v3 : (¬ e 1 14) := fun hu => c103 e tri schur h0 hu h3
  have v4 : (e 11 13) := Classical.byContradiction (fun hu => c840 e tri schur h5 v1 hu)
  have v5 : (¬ e 1 8) := fun hu => c1349 e tri schur h3 hu h4 v0
  have v6 : (¬ e 1 3) := fun hu => c1357 e tri schur h2 h3 hu
  have v7 : (¬ e 13 15) := fun hu => c1375 e tri schur hu v4 h0 h1 h4 v5 v0 h5 h6 h7 h8
  have v8 : (¬ e 2 8) := fun hu => c1377 e tri schur v4 hu h4 v5 h5 h7 h8
  have v9 : (¬ e 1 11) := fun hu => c109 e tri schur v4 h2 hu
  have v10 : (e 8 10) := Classical.byContradiction (fun hu => c837 e tri schur v8 v0 hu)
  have v11 : (e 2 15) := Classical.byContradiction (fun hu => c842 e tri schur v1 hu v7)
  have v12 : (¬ e 6 10) := fun hu => c1373 e tri schur h0 v10 hu
  have v13 : (¬ e 1 15) := fun hu => c12 e tri schur v11 hu h4
  have v14 : (¬ e 2 4) := fun hu => c161 e tri schur h1 v11 hu
  have v15 : (¬ e 8 14) := fun hu => c663 e tri schur h0 hu v10
  have v16 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v3 v13 hu)
  have v17 : (e 4 6) := Classical.byContradiction (fun hu => c859 e tri schur hu h6 v12)
  have v18 : (¬ e 4 9) := fun hu => c1194 e tri schur h1 hu v17
  have v19 : (¬ e 2 14) := fun hu => c246 e tri schur v16 v11 hu
  have v20 : (¬ e 6 15) := fun hu => c382 e tri schur hu h1 v17
  have v21 : (¬ e 4 14) := fun hu => c442 e tri schur v16 h1 hu
  have v22 : (¬ e 10 15) := fun hu => c750 e tri schur v16 hu h0
  have v23 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v18 h8 hu)
  have v24 : (¬ e 1 9) := fun hu => c94 e tri schur v23 h2 hu
  have v25 : (¬ e 9 11) := fun hu => c705 e tri schur v4 v23 hu
  have v26 : (e 8 9) := Classical.byContradiction (fun hu => c822 e tri schur v5 v24 hu)
  have v27 : (e 2 9) := Classical.byContradiction (fun hu => c838 e tri schur hu h5 v25)
  have v28 : (¬ e 6 9) := fun hu => c903 e tri schur v26 hu v27
  have v29 : (¬ e 9 15) := fun hu => c216 e tri schur hu v11 v27
  have v30 : (¬ e 9 10) := fun hu => c651 e tri schur hu v10 v26
  have v31 : (¬ e 8 13) := fun hu => c654 e tri schur v23 hu v26
  exact c878 e tri schur v28 v20 v29

theorem c1379 : (e 4 15) → (e 4 6) → (e 2 9) → (e 1 13) → (¬ e 1 8) → (¬ e 2 13) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 6 15) := fun hu => c382 e tri schur hu h0 h1
  have v1 : (¬ e 4 9) := fun hu => c1194 e tri schur h0 hu h1
  have v2 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v1 h6 hu)
  have v3 : (¬ e 1 9) := fun hu => c94 e tri schur v2 h3 hu
  have v4 : (e 8 9) := Classical.byContradiction (fun hu => c822 e tri schur h4 v3 hu)
  have v5 : (¬ e 6 9) := fun hu => c903 e tri schur v4 hu h2
  have v6 : (¬ e 2 8) := fun hu => c201 e tri schur v4 h2 hu
  have v7 : (¬ e 8 13) := fun hu => c654 e tri schur v2 hu v4
  have v8 : (e 9 15) := Classical.byContradiction (fun hu => c878 e tri schur v5 v0 hu)
  have v9 : (¬ e 2 15) := fun hu => c216 e tri schur v8 hu h2
  have v10 : (¬ e 8 15) := fun hu => c656 e tri schur v8 hu v4
  have v11 : (¬ e 13 15) := fun hu => c718 e tri schur hu v8 v2
  exact c842 e tri schur h5 v9 v11

theorem c1380 : (e 10 14) → (e 4 12) → (¬ e 2 6) → (¬ e 2 8) → (¬ e 4 6) → (¬ e 4 10) → (¬ e 12 14) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (e 2 4) := Classical.byContradiction (fun hu => c833 e tri schur hu h2 h4)
  have v1 : (e 6 8) := Classical.byContradiction (fun hu => c835 e tri schur h2 h3 hu)
  have v2 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur h4 h5 hu)
  have v3 : (¬ e 8 10) := fun hu => c1373 e tri schur h0 hu v2
  have v4 : (¬ e 2 12) := fun hu => c158 e tri schur h1 hu v0
  have v5 : (¬ e 6 14) := fun hu => c563 e tri schur h0 hu v2
  have v6 : (e 2 10) := Classical.byContradiction (fun hu => c837 e tri schur h3 hu v3)
  have v7 : (e 2 14) := Classical.byContradiction (fun hu => c841 e tri schur v4 hu h6)
  have v8 : (¬ e 2 18) := fun hu => c1289 e tri schur hu v7 v0
  have v9 : (¬ e 4 14) := fun hu => c160 e tri schur hu v7 v0
  exact c223 e tri schur h0 v7 v6

theorem c1381 : (e 10 14) → (e 4 15) → (e 4 12) → (e 2 9) → (e 2 3) → (e 1 13) → (e 1 10) → (¬ e 2 8) → (¬ e 4 10) → (¬ e 4 13) → (¬ e 12 14) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10
  have v0 : (¬ e 10 13) := fun hu => c102 e tri schur hu h5 h6
  have v1 : (¬ e 1 14) := fun hu => c103 e tri schur h0 hu h6
  have v2 : (¬ e 3 9) := fun hu => c141 e tri schur hu h3 h4
  have v3 : (¬ e 12 15) := fun hu => c433 e tri schur hu h1 h2
  have v4 : (¬ e 2 6) := fun hu => c1010 e tri schur h3 hu h4
  have v5 : (¬ e 3 4) := fun hu => c1188 e tri schur h1 h2 hu
  have v6 : (¬ e 1 3) := fun hu => c1357 e tri schur h5 h6 hu
  have v7 : (e 4 6) := Classical.byContradiction (fun hu => c1380 e tri schur h0 h2 v4 h7 hu h8 h10)
  have v8 : (¬ e 6 12) := fun hu => c379 e tri schur hu h2 v7
  have v9 : (¬ e 6 15) := fun hu => c382 e tri schur hu h1 v7
  have v10 : (e 1 4) := Classical.byContradiction (fun hu => c817 e tri schur v6 hu v5)
  have v11 : (e 6 8) := Classical.byContradiction (fun hu => c835 e tri schur v4 h7 hu)
  have v12 : (¬ e 4 9) := fun hu => c1194 e tri schur h1 hu v7
  have v13 : (¬ e 1 6) := fun hu => c32 e tri schur v7 hu v10
  have v14 : (¬ e 1 12) := fun hu => c38 e tri schur h2 hu v10
  have v15 : (¬ e 1 15) := fun hu => c41 e tri schur h1 hu v10
  have v16 : (¬ e 4 8) := fun hu => c375 e tri schur v11 hu v7
  have v17 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v1 v15 hu)
  have v18 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v12 h9 hu)
  have v19 : (¬ e 4 11) := fun hu => c1335 e tri schur h2 hu v10 v14
  have v20 : (¬ e 1 9) := fun hu => c94 e tri schur v18 h5 hu
  have v21 : (¬ e 2 13) := fun hu => c214 e tri schur v18 hu h3
  have v22 : (¬ e 4 14) := fun hu => c442 e tri schur v17 h1 hu
  have v23 : (¬ e 10 15) := fun hu => c750 e tri schur v17 hu h0
  have v24 : (e 1 8) := Classical.byContradiction (fun hu => c1379 e tri schur h1 v7 h3 h5 hu v21 h9)
  have v25 : (¬ e 8 10) := fun hu => c82 e tri schur hu h6 v24
  have v26 : (¬ e 8 13) := fun hu => c85 e tri schur hu h5 v24
  have v27 : (e 2 10) := Classical.byContradiction (fun hu => c837 e tri schur h7 hu v25)
  have v28 : (¬ e 1 2) := fun hu => c7 e tri schur v27 h6 hu
  have v29 : (¬ e 3 10) := fun hu => c142 e tri schur hu v27 h4
  have v30 : (¬ e 9 10) := fun hu => c211 e tri schur hu v27 h3
  have v31 : (¬ e 2 14) := fun hu => c223 e tri schur h0 hu v27
  have v32 : (e 2 12) := Classical.byContradiction (fun hu => c841 e tri schur hu v31 h10)
  have v33 : (e 3 13) := Classical.byContradiction (fun hu => c852 e tri schur v29 hu v0)
  have v34 : (¬ e 2 15) := fun hu => c913 e tri schur hu v32 h4 v3
  have v35 : (¬ e 6 13) := fun hu => c940 e tri schur v18 hu v33
  have v36 : (e 3 12) := Classical.byContradiction (fun hu => c1363 e tri schur v32 h3 h4 hu)
  exact c144 e tri schur v36 v32 h4

theorem c1382 : (e 14 15) → (e 11 14) → (e 11 12) → (e 4 15) → (e 4 12) → (e 2 12) → (e 2 3) → (e 1 10) → (¬ e 1 14) → (¬ e 2 11) → (¬ e 3 11) → (¬ e 3 14) → (¬ e 4 10) → (¬ e 4 13) → (¬ e 10 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14
  have v0 : (¬ e 3 12) := fun hu => c144 e tri schur hu h5 h6
  have v1 : (¬ e 2 4) := fun hu => c158 e tri schur h4 h5 hu
  have v2 : (¬ e 4 11) := fun hu => c424 e tri schur h2 h4 hu
  have v3 : (¬ e 12 15) := fun hu => c433 e tri schur hu h3 h4
  have v4 : (¬ e 4 14) := fun hu => c442 e tri schur h0 h3 hu
  have v5 : (¬ e 12 14) := fun hu => c761 e tri schur hu h1 h2
  have v6 : (¬ e 11 15) := fun hu => c771 e tri schur h0 hu h1
  have v7 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur v0 hu v3)
  have v8 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur h12 v4 hu)
  have v9 : (¬ e 2 15) := fun hu => c913 e tri schur hu h5 h6 v3
  have v10 : (¬ e 7 15) := fun hu => c1023 e tri schur hu h3 v7
  have v11 : (¬ e 3 4) := fun hu => c1188 e tri schur h3 h4 hu
  have v12 : (¬ e 15 17) := fun hu => c1345 e tri schur hu h0 v7
  have v13 : (¬ e 2 9) := fun hu => c1363 e tri schur h5 hu h6 v0
  exact c1371 e tri schur h0 h1 h2 h3 h5 h6 h7 h8 v1 h9 h10 h11 h12 h13 h14 v3

theorem c1383 : (e 10 14) → (e 4 15) → (e 4 12) → (e 2 3) → (e 1 13) → (e 1 10) → (¬ e 2 8) → (¬ e 2 10) → (¬ e 2 11) → (¬ e 3 11) → (¬ e 4 10) → (¬ e 4 13) → (¬ e 12 14) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12
  have v0 : (¬ e 10 13) := fun hu => c102 e tri schur hu h4 h5
  have v1 : (¬ e 1 14) := fun hu => c103 e tri schur h0 hu h5
  have v2 : (¬ e 12 15) := fun hu => c433 e tri schur hu h1 h2
  have v3 : (e 8 10) := Classical.byContradiction (fun hu => c837 e tri schur h6 h7 hu)
  have v4 : (¬ e 3 4) := fun hu => c1188 e tri schur h1 h2 hu
  have v5 : (¬ e 1 3) := fun hu => c1357 e tri schur h4 h5 hu
  have v6 : (¬ e 6 10) := fun hu => c1373 e tri schur h0 v3 hu
  have v7 : (¬ e 2 9) := fun hu => c1381 e tri schur h0 h1 h2 hu h3 h4 h5 h6 h10 h11 h12
  have v8 : (¬ e 1 8) := fun hu => c82 e tri schur v3 h5 hu
  have v9 : (¬ e 8 14) := fun hu => c663 e tri schur h0 hu v3
  have v10 : (e 1 4) := Classical.byContradiction (fun hu => c817 e tri schur v5 hu v4)
  have v11 : (e 9 11) := Classical.byContradiction (fun hu => c838 e tri schur v7 h8 hu)
  have v12 : (e 4 6) := Classical.byContradiction (fun hu => c859 e tri schur hu h10 v6)
  have v13 : (¬ e 4 9) := fun hu => c1194 e tri schur h1 hu v12
  have v14 : (¬ e 1 6) := fun hu => c32 e tri schur v12 hu v10
  have v15 : (¬ e 1 12) := fun hu => c38 e tri schur h2 hu v10
  have v16 : (¬ e 1 15) := fun hu => c41 e tri schur h1 hu v10
  have v17 : (¬ e 6 12) := fun hu => c379 e tri schur hu h2 v12
  have v18 : (¬ e 6 15) := fun hu => c382 e tri schur hu h1 v12
  have v19 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v1 v16 hu)
  have v20 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v13 h11 hu)
  have v21 : (¬ e 4 11) := fun hu => c1335 e tri schur h2 hu v10 v15
  have v22 : (¬ e 1 2) := fun hu => c1378 e tri schur h0 h1 h4 h5 hu h8 h10 v21 h11
  have v23 : (¬ e 1 9) := fun hu => c94 e tri schur v20 h4 hu
  have v24 : (¬ e 4 14) := fun hu => c442 e tri schur v19 h1 hu
  have v25 : (¬ e 11 13) := fun hu => c705 e tri schur hu v20 v11
  have v26 : (¬ e 10 15) := fun hu => c750 e tri schur v19 hu h0
  have v27 : (e 8 9) := Classical.byContradiction (fun hu => c822 e tri schur v8 v23 hu)
  have v28 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur h8 hu v25)
  have v29 : (¬ e 3 13) := fun hu => c145 e tri schur hu v28 h3
  have v30 : (¬ e 9 10) := fun hu => c651 e tri schur hu v3 v27
  have v31 : (¬ e 8 11) := fun hu => c652 e tri schur v11 hu v27
  have v32 : (¬ e 8 13) := fun hu => c654 e tri schur v20 hu v27
  have v33 : (e 3 8) := Classical.byContradiction (fun hu => c850 e tri schur hu h9 v31)
  have v34 : (e 3 10) := Classical.byContradiction (fun hu => c852 e tri schur hu v29 v0)
  have v35 : (¬ e 5 10) := fun hu => c942 e tri schur v3 hu v34
  have v36 : (¬ e 3 18) := fun hu => c963 e tri schur hu v34 v33
  exact c1324 e tri schur v34 v33 h3

theorem c1384 : (e 1 13) → (e 1 9) → (e 1 4) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 4 9) := fun hu => c35 e tri schur hu h1 h2
  have v1 : (¬ e 9 13) := fun hu => c94 e tri schur hu h0 h1
  exact c862 e tri schur v0 h3 v1

theorem c1385 : (e 2 17) → (e 2 14) → (e 2 3) → (¬ e 3 14) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 17) := fun hu => c149 e tri schur hu h0 h2
  have v1 : (¬ e 14 17) := fun hu => c248 e tri schur hu h0 h1
  exact c856 e tri schur h3 v0 v1

theorem c1386 : (e 14 15) → (e 11 14) → (e 11 12) → (e 4 15) → (e 4 12) → (e 2 3) → (e 1 10) → (¬ e 1 14) → (¬ e 2 11) → (¬ e 3 11) → (¬ e 3 14) → (¬ e 4 10) → (¬ e 4 13) → (¬ e 10 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13
  have v0 : (¬ e 4 11) := fun hu => c424 e tri schur h2 h4 hu
  have v1 : (¬ e 12 15) := fun hu => c433 e tri schur hu h3 h4
  have v2 : (¬ e 4 14) := fun hu => c442 e tri schur h0 h3 hu
  have v3 : (¬ e 12 14) := fun hu => c761 e tri schur hu h1 h2
  have v4 : (¬ e 11 15) := fun hu => c771 e tri schur h0 hu h1
  have v5 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur h11 v2 hu)
  have v6 : (¬ e 3 4) := fun hu => c1188 e tri schur h3 h4 hu
  have v7 : (¬ e 2 12) := fun hu => c1382 e tri schur h0 h1 h2 h3 h4 hu h5 h6 h7 h8 h9 h10 h11 h12 h13
  have v8 : (¬ e 10 11) := fun hu => c734 e tri schur h1 v5 hu
  have v9 : (¬ e 10 15) := fun hu => c750 e tri schur h0 hu v5
  have v10 : (e 2 14) := Classical.byContradiction (fun hu => c841 e tri schur v7 hu v3)
  have v11 : (¬ e 2 17) := fun hu => c1385 e tri schur hu v10 h5 h10
  have v12 : (¬ e 2 10) := fun hu => c223 e tri schur v5 v10 hu
  have v13 : (¬ e 2 15) := fun hu => c246 e tri schur h0 hu v10
  have v14 : (e 10 12) := Classical.byContradiction (fun hu => c839 e tri schur v12 v7 hu)
  have v15 : (e 15 17) := Classical.byContradiction (fun hu => c844 e tri schur v13 v11 hu)
  have v16 : (¬ e 3 15) := fun hu => c1345 e tri schur v15 h0 hu
  have v17 : (¬ e 13 15) := fun hu => c1348 e tri schur v15 hu h3 h12
  have v18 : (¬ e 1 12) := fun hu => c101 e tri schur v14 hu h6
  have v19 : (¬ e 4 17) := fun hu => c447 e tri schur v15 hu h3
  have v20 : (¬ e 14 17) := fun hu => c807 e tri schur v15 hu h0
  have v21 : (e 2 13) := Classical.byContradiction (fun hu => c842 e tri schur hu v13 v17)
  have v22 : (e 3 12) := Classical.byContradiction (fun hu => c854 e tri schur hu v16 v1)
  have v23 : (e 3 17) := Classical.byContradiction (fun hu => c856 e tri schur h10 hu v20)
  have v24 : (e 13 17) := Classical.byContradiction (fun hu => c866 e tri schur h12 v19 hu)
  have v25 : (¬ e 1 2) := fun hu => c1352 e tri schur v10 v21 hu h7
  have v26 : (e 1 13) := Classical.byContradiction (fun hu => c1359 e tri schur h2 v18 hu h7 h8)
  have v27 : (e 2 8) := Classical.byContradiction (fun hu => c1383 e tri schur v5 h3 h4 h5 v26 h6 hu v12 h8 h9 h11 h12 v3)
  have v28 : (¬ e 1 17) := fun hu => c124 e tri schur v24 hu v26
  have v29 : (¬ e 3 8) := fun hu => c140 e tri schur hu v27 h5
  have v30 : (¬ e 3 13) := fun hu => c145 e tri schur hu v21 h5
  have v31 : (¬ e 8 13) := fun hu => c205 e tri schur hu v21 v27
  have v32 : (¬ e 8 14) := fun hu => c206 e tri schur hu v10 v27
  have v33 : (¬ e 13 14) := fun hu => c241 e tri schur hu v10 v21
  have v34 : (¬ e 3 10) := fun hu => c326 e tri schur v14 v22 hu
  have v35 : (¬ e 12 17) := fun hu => c344 e tri schur hu v23 v22
  have v36 : (e 8 11) := Classical.byContradiction (fun hu => c850 e tri schur v29 h9 hu)
  exact c852 e tri schur v34 v30 h13

theorem c1387 : (e 14 15) → (e 3 14) → (e 2 3) → (¬ e 12 15) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 2 14) := fun hu => c146 e tri schur h1 hu h2
  have v1 : (¬ e 3 15) := fun hu => c351 e tri schur h0 hu h1
  have v2 : (e 3 12) := Classical.byContradiction (fun hu => c854 e tri schur hu v1 h3)
  exact c1323 e tri schur h1 v2 h2

theorem c1388 : (e 14 15) → (e 11 14) → (e 11 12) → (e 4 15) → (e 4 12) → (e 2 3) → (e 1 10) → (¬ e 1 14) → (¬ e 2 11) → (¬ e 4 10) → (¬ e 4 13) → (¬ e 10 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11
  have v0 : (¬ e 4 11) := fun hu => c424 e tri schur h2 h4 hu
  have v1 : (¬ e 12 15) := fun hu => c433 e tri schur hu h3 h4
  have v2 : (¬ e 4 14) := fun hu => c442 e tri schur h0 h3 hu
  have v3 : (¬ e 12 14) := fun hu => c761 e tri schur hu h1 h2
  have v4 : (¬ e 11 15) := fun hu => c771 e tri schur h0 hu h1
  have v5 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur h9 v2 hu)
  have v6 : (¬ e 3 4) := fun hu => c1188 e tri schur h3 h4 hu
  have v7 : (¬ e 3 14) := fun hu => c1387 e tri schur h0 hu h5 v1
  have v8 : (¬ e 10 11) := fun hu => c734 e tri schur h1 v5 hu
  have v9 : (¬ e 10 15) := fun hu => c750 e tri schur h0 hu v5
  have v10 : (e 3 11) := Classical.byContradiction (fun hu => c1386 e tri schur h0 h1 h2 h3 h4 h5 h6 h7 h8 hu v7 h9 h10 h11)
  have v11 : (¬ e 3 12) := fun hu => c333 e tri schur h2 hu v10
  have v12 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur v11 hu v1)
  have v13 : (¬ e 7 15) := fun hu => c1023 e tri schur hu h3 v12
  have v14 : (¬ e 15 17) := fun hu => c1345 e tri schur hu h0 v12
  have v15 : (¬ e 9 11) := fun hu => c1361 e tri schur h2 hu v10
  have v16 : (¬ e 2 15) := fun hu => c147 e tri schur v12 hu h5
  have v17 : (e 2 9) := Classical.byContradiction (fun hu => c838 e tri schur hu h8 v15)
  have v18 : (e 2 17) := Classical.byContradiction (fun hu => c844 e tri schur v16 hu v14)
  have v19 : (¬ e 2 6) := fun hu => c1010 e tri schur v17 hu h5
  have v20 : (¬ e 2 12) := fun hu => c1363 e tri schur hu v17 h5 v11
  have v21 : (¬ e 2 14) := fun hu => c1385 e tri schur v18 hu h5 v7
  have v22 : (¬ e 3 9) := fun hu => c141 e tri schur hu v17 h5
  have v23 : (¬ e 3 17) := fun hu => c149 e tri schur hu v18 h5
  have v24 : (¬ e 9 17) := fun hu => c218 e tri schur hu v18 v17
  exact c841 e tri schur v20 v21 v3

theorem c1389 : (e 4 15) → (e 4 12) → (e 1 10) → (e 1 4) → (¬ e 1 11) → (¬ e 1 12) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 4 10) := fun hu => c36 e tri schur hu h2 h3
  have v1 : (¬ e 1 15) := fun hu => c41 e tri schur h0 hu h3
  have v2 : (¬ e 12 15) := fun hu => c433 e tri schur hu h0 h1
  have v3 : (e 11 12) := Classical.byContradiction (fun hu => c825 e tri schur h4 h5 hu)
  have v4 : (¬ e 3 4) := fun hu => c1188 e tri schur h0 h1 hu
  have v5 : (¬ e 4 13) := fun hu => c1260 e tri schur hu h1 h3
  have v6 : (¬ e 4 11) := fun hu => c1335 e tri schur h1 hu h3 h5
  have v7 : (¬ e 1 14) := fun hu => c1343 e tri schur hu h2 h3
  have v8 : (¬ e 2 11) := fun hu => c1358 e tri schur h0 h1 hu h3 h4 h5
  have v9 : (e 1 13) := Classical.byContradiction (fun hu => c1359 e tri schur v3 h5 hu v7 v8)
  have v10 : (¬ e 13 14) := fun hu => c1369 e tri schur hu v3 h0 h1 v9 h2 h3 v8
  have v11 : (¬ e 1 9) := fun hu => c1384 e tri schur v9 hu h3 v5
  have v12 : (¬ e 10 13) := fun hu => c102 e tri schur hu v9 h2
  have v13 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v7 v1 hu)
  have v14 : (¬ e 1 3) := fun hu => c1357 e tri schur v9 h2 hu
  have v15 : (¬ e 4 14) := fun hu => c442 e tri schur v13 h0 hu
  have v16 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v0 v15 hu)
  have v17 : (¬ e 1 2) := fun hu => c1378 e tri schur v16 h0 v9 h2 hu v8 v0 v6 v5
  have v18 : (¬ e 10 15) := fun hu => c750 e tri schur v13 hu v16
  have v19 : (e 2 3) := Classical.byContradiction (fun hu => c816 e tri schur v17 v14 hu)
  have v20 : (¬ e 3 14) := fun hu => c1387 e tri schur v13 hu v19 v2
  have v21 : (¬ e 11 14) := fun hu => c1388 e tri schur v13 hu v3 h0 h1 v19 h2 v7 v8 v0 v5 v12
  have v22 : (e 3 11) := Classical.byContradiction (fun hu => c853 e tri schur hu v20 v21)
  have v23 : (¬ e 9 11) := fun hu => c1361 e tri schur v3 hu v22
  have v24 : (¬ e 3 12) := fun hu => c333 e tri schur v3 hu v22
  have v25 : (e 2 9) := Classical.byContradiction (fun hu => c838 e tri schur hu v8 v23)
  have v26 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur v24 hu v2)
  have v27 : (¬ e 2 6) := fun hu => c1010 e tri schur v25 hu v19
  have v28 : (¬ e 7 15) := fun hu => c1023 e tri schur hu h0 v26
  have v29 : (¬ e 15 17) := fun hu => c1345 e tri schur hu v13 v26
  have v30 : (¬ e 2 12) := fun hu => c1363 e tri schur hu v25 v19 v24
  have v31 : (¬ e 3 9) := fun hu => c141 e tri schur hu v25 v19
  have v32 : (¬ e 2 15) := fun hu => c147 e tri schur v26 hu v19
  have v33 : (¬ e 11 15) := fun hu => c336 e tri schur hu v26 v22
  have v34 : (e 2 17) := Classical.byContradiction (fun hu => c844 e tri schur v32 hu v29)
  have v35 : (e 9 12) := Classical.byContradiction (fun hu => c851 e tri schur v31 v24 hu)
  have v36 : (¬ e 2 14) := fun hu => c1385 e tri schur v34 hu v19 v20
  have v37 : (¬ e 3 17) := fun hu => c149 e tri schur hu v34 v19
  have v38 : (¬ e 9 17) := fun hu => c218 e tri schur hu v34 v25
  have v39 : (¬ e 4 9) := fun hu => c409 e tri schur v35 h1 hu
  have v40 : (e 12 14) := Classical.byContradiction (fun hu => c841 e tri schur v30 v36 hu)
  have v41 : (e 14 17) := Classical.byContradiction (fun hu => c856 e tri schur v20 v37 hu)
  have v42 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v39 v5 hu)
  have v43 : (e 13 15) := Classical.byContradiction (fun hu => c1360 e tri schur v3 v16 h1 h2 v14 v1 v30 v36 v0 v12 v2 hu)
  have v44 : (¬ e 2 13) := fun hu => c214 e tri schur v42 hu v25
  have v45 : (¬ e 3 13) := fun hu => c347 e tri schur v43 v26 hu
  have v46 : (¬ e 12 13) := fun hu => c711 e tri schur hu v42 v35
  have v47 : (¬ e 9 14) := fun hu => c712 e tri schur v40 hu v35
  have v48 : (¬ e 9 15) := fun hu => c718 e tri schur v43 hu v42
  have v49 : (¬ e 10 12) := fun hu => c740 e tri schur v40 v16 hu
  have v50 : (¬ e 10 17) := fun hu => c752 e tri schur v41 hu v16
  have v51 : (¬ e 12 17) := fun hu => c788 e tri schur v41 hu v40
  have v52 : (e 2 10) := Classical.byContradiction (fun hu => c839 e tri schur hu v30 v49)
  have v53 : (e 11 13) := Classical.byContradiction (fun hu => c840 e tri schur v8 v44 hu)
  have v54 : (e 3 10) := Classical.byContradiction (fun hu => c852 e tri schur hu v45 v12)
  have v55 : (¬ e 3 8) := fun hu => c1324 e tri schur v54 hu v19
  exact c142 e tri schur v54 v52 v19

theorem c1390 : (e 10 11) → (e 9 10) → (e 2 3) → (¬ e 2 11) → (¬ e 10 12) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 9 11) := fun hu => c696 e tri schur h0 hu h1
  have v1 : (e 2 9) := Classical.byContradiction (fun hu => c838 e tri schur hu h3 v0)
  have v2 : (¬ e 2 6) := fun hu => c1010 e tri schur v1 hu h2
  have v3 : (¬ e 3 9) := fun hu => c141 e tri schur hu v1 h2
  have v4 : (¬ e 2 10) := fun hu => c211 e tri schur h1 hu v1
  have v5 : (e 2 12) := Classical.byContradiction (fun hu => c839 e tri schur v4 hu h4)
  have v6 : (e 3 12) := Classical.byContradiction (fun hu => c1363 e tri schur v5 v1 h2 hu)
  exact c144 e tri schur v6 v5 h2

theorem c1391 : (e 11 12) → (e 10 11) → (e 2 3) → (e 1 4) → (¬ e 1 10) → (¬ e 1 12) → (¬ e 2 11) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 10 12) := fun hu => c732 e tri schur h0 hu h1
  have v1 : (¬ e 9 10) := fun hu => c1390 e tri schur h1 hu h2 h6 v0
  have v2 : (e 1 9) := Classical.byContradiction (fun hu => c823 e tri schur hu h4 v1)
  have v3 : (¬ e 1 13) := fun hu => c1384 e tri schur hu v2 h3 h7
  have v4 : (¬ e 4 9) := fun hu => c35 e tri schur hu v2 h3
  have v5 : (e 12 13) := Classical.byContradiction (fun hu => c826 e tri schur h5 v3 hu)
  have v6 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v4 h7 hu)
  have v7 : (e 1 14) := Classical.byContradiction (fun hu => c1359 e tri schur h0 h5 v3 hu h6)
  have v8 : (¬ e 4 14) := fun hu => c40 e tri schur hu v7 h3
  have v9 : (¬ e 9 14) := fun hu => c95 e tri schur hu v7 v2
  have v10 : (¬ e 9 12) := fun hu => c711 e tri schur v5 v6 hu
  have v11 : (¬ e 11 13) := fun hu => c760 e tri schur v5 hu h0
  have v12 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur h6 hu v11)
  have v13 : (¬ e 3 13) := fun hu => c145 e tri schur hu v12 h2
  have v14 : (¬ e 2 9) := fun hu => c214 e tri schur v6 v12 hu
  have v15 : (¬ e 2 12) := fun hu => c235 e tri schur v5 v12 hu
  have v16 : (e 9 11) := Classical.byContradiction (fun hu => c838 e tri schur v14 h6 hu)
  have v17 : (e 2 10) := Classical.byContradiction (fun hu => c839 e tri schur hu v15 v0)
  have v18 : (¬ e 3 11) := fun hu => c1361 e tri schur h0 v16 hu
  have v19 : (¬ e 1 11) := fun hu => c92 e tri schur v16 hu v2
  have v20 : (¬ e 3 10) := fun hu => c142 e tri schur hu v17 h2
  have v21 : (¬ e 10 13) := fun hu => c222 e tri schur hu v12 v17
  exact c852 e tri schur v20 v13 v21

theorem c1392 : (e 12 13) → (e 9 13) → (e 3 13) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 9) := fun hu => c319 e tri schur h1 h2 hu
  have v1 : (¬ e 3 12) := fun hu => c340 e tri schur h0 h2 hu
  have v2 : (¬ e 9 12) := fun hu => c711 e tri schur h0 h1 hu
  exact c851 e tri schur v0 v1 v2

theorem c1393 : (e 7 8) → (e 2 5) → (e 1 8) → (e 1 2) → (¬ e 5 13) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 1 5) := fun hu => c2 e tri schur h1 hu h3
  have v1 : (¬ e 2 8) := fun hu => c5 e tri schur hu h2 h3
  have v2 : (¬ e 1 7) := fun hu => c70 e tri schur h0 h2 hu
  have v3 : (¬ e 5 6) := fun hu => c1080 e tri schur h0 hu h1 v1 h4
  have v4 : (e 1 6) := Classical.byContradiction (fun hu => c819 e tri schur v0 hu v3)
  have v5 : (¬ e 2 6) := fun hu => c3 e tri schur hu v4 h3
  have v6 : (¬ e 6 8) := fun hu => c59 e tri schur hu h2 v4
  exact c835 e tri schur v5 v1 v6

theorem c1394 : (e 1 6) → (e 1 4) → (e 1 2) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 4) := fun hu => c1 e tri schur hu h1 h2
  have v1 : (¬ e 2 6) := fun hu => c3 e tri schur hu h0 h2
  have v2 : (¬ e 4 6) := fun hu => c32 e tri schur hu h0 h1
  exact c833 e tri schur v0 v1 v2

theorem c1395 : (e 11 12) → (e 4 15) → (e 3 10) → (e 2 10) → (e 1 14) → (e 1 9) → (e 1 4) → (¬ e 2 3) → (¬ e 2 12) → (¬ e 3 11) → (¬ e 3 12) → (¬ e 9 12) → (¬ e 12 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12
  have v0 : (¬ e 4 9) := fun hu => c35 e tri schur hu h5 h6
  have v1 : (¬ e 4 14) := fun hu => c40 e tri schur hu h4 h6
  have v2 : (¬ e 1 15) := fun hu => c41 e tri schur h1 hu h6
  have v3 : (¬ e 9 14) := fun hu => c95 e tri schur hu h4 h5
  have v4 : (e 3 9) := Classical.byContradiction (fun hu => c851 e tri schur hu h10 h11)
  have v5 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur h10 hu h12)
  have v6 : (¬ e 7 15) := fun hu => c1023 e tri schur hu h1 v5
  have v7 : (¬ e 1 10) := fun hu => c1343 e tri schur h4 hu h6
  have v8 : (¬ e 1 3) := fun hu => c21 e tri schur v4 h5 hu
  have v9 : (¬ e 3 4) := fun hu => c266 e tri schur h1 v5 hu
  have v10 : (¬ e 9 10) := fun hu => c316 e tri schur hu h2 v4
  have v11 : (¬ e 9 15) := fun hu => c321 e tri schur hu v5 v4
  have v12 : (¬ e 10 15) := fun hu => c329 e tri schur hu v5 h2
  have v13 : (e 1 2) := Classical.byContradiction (fun hu => c816 e tri schur hu v8 h7)
  have v14 : (¬ e 1 6) := fun hu => c1394 e tri schur hu h6 v13
  have v15 : (¬ e 2 4) := fun hu => c1 e tri schur hu h6 v13
  have v16 : (¬ e 2 9) := fun hu => c6 e tri schur hu h5 v13
  have v17 : (¬ e 2 14) := fun hu => c11 e tri schur hu h4 v13
  have v18 : (e 12 14) := Classical.byContradiction (fun hu => c841 e tri schur h8 v17 hu)
  have v19 : (¬ e 1 12) := fun hu => c116 e tri schur v18 h4 hu
  have v20 : (¬ e 11 14) := fun hu => c761 e tri schur v18 hu h0
  have v21 : (e 3 14) := Classical.byContradiction (fun hu => c853 e tri schur h9 hu v20)
  have v22 : (¬ e 3 5) := fun hu => c992 e tri schur v21 v4 hu
  have v23 : (¬ e 10 14) := fun hu => c328 e tri schur hu v21 h2
  have v24 : (¬ e 14 15) := fun hu => c351 e tri schur hu v5 v21
  have v25 : (e 2 5) := Classical.byContradiction (fun hu => c832 e tri schur h7 hu v22)
  have v26 : (e 4 10) := Classical.byContradiction (fun hu => c863 e tri schur hu v1 v23)
  have v27 : (¬ e 2 15) := fun hu => c1217 e tri schur hu h3 v25
  have v28 : (¬ e 1 5) := fun hu => c2 e tri schur v25 hu v13
  have v29 : (¬ e 5 10) := fun hu => c169 e tri schur hu h3 v25
  have v30 : (e 5 6) := Classical.byContradiction (fun hu => c819 e tri schur v28 v14 hu)
  have v31 : (e 5 15) := Classical.byContradiction (fun hu => c872 e tri schur v29 hu v12)
  have v32 : (¬ e 4 5) := fun hu => c986 e tri schur h1 v26 hu v29
  have v33 : (¬ e 8 15) := fun hu => c1013 e tri schur hu v31 v5
  have v34 : (¬ e 5 17) := fun hu => c1129 e tri schur hu v31 v25 v27
  have v35 : (¬ e 5 8) := fun hu => c1182 e tri schur hu v30 v25
  have v36 : (¬ e 2 6) := fun hu => c165 e tri schur v30 hu v25
  have v37 : (¬ e 6 15) := fun hu => c460 e tri schur hu v31 v30
  have v38 : (e 4 6) := Classical.byContradiction (fun hu => c833 e tri schur v15 v36 hu)
  have v39 : (e 3 8) := Classical.byContradiction (fun hu => c847 e tri schur v22 hu v35)
  have v40 : (e 5 9) := Classical.byContradiction (fun hu => c858 e tri schur v32 v0 hu)
  have v41 : (e 6 9) := Classical.byContradiction (fun hu => c878 e tri schur hu v37 v11)
  have v42 : (e 7 8) := Classical.byContradiction (fun hu => c882 e tri schur hu v6 v33)
  have v43 : (¬ e 8 9) := fun hu => c914 e tri schur hu v40 v4 v35
  have v44 : (¬ e 3 6) := fun hu => c950 e tri schur v21 v39 hu
  have v45 : (¬ e 3 18) := fun hu => c963 e tri schur hu h2 v39
  have v46 : (¬ e 5 11) := fun hu => c1322 e tri schur hu v40 v25
  have v47 : (¬ e 3 7) := fun hu => c295 e tri schur v42 v39 hu
  have v48 : (¬ e 8 10) := fun hu => c307 e tri schur hu h2 v39
  have v49 : (¬ e 8 14) := fun hu => c311 e tri schur hu v21 v39
  have v50 : (¬ e 6 10) := fun hu => c377 e tri schur hu v26 v38
  exact c454 e tri schur v41 v40 v30

theorem c1396 : (e 12 14) → (e 11 12) → (e 3 12) → (¬ e 3 11) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 14) := fun hu => c341 e tri schur h0 hu h2
  have v1 : (¬ e 11 14) := fun hu => c761 e tri schur h0 hu h1
  exact c853 e tri schur h3 v0 v1

theorem c1397 : (e 5 6) → (e 2 14) → (e 2 10) → (e 2 5) → (¬ e 9 14) → (¬ e 10 15) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 2 6) := fun hu => c165 e tri schur h0 hu h3
  have v1 : (¬ e 5 10) := fun hu => c169 e tri schur hu h2 h3
  have v2 : (¬ e 5 14) := fun hu => c173 e tri schur hu h1 h3
  have v3 : (¬ e 10 14) := fun hu => c223 e tri schur hu h1 h2
  have v4 : (e 5 9) := Classical.byContradiction (fun hu => c871 e tri schur hu v2 h4)
  have v5 : (e 5 15) := Classical.byContradiction (fun hu => c872 e tri schur v1 hu h5)
  have v6 : (¬ e 5 8) := fun hu => c1182 e tri schur hu h0 h3
  have v7 : (¬ e 2 15) := fun hu => c1217 e tri schur hu h2 h3
  have v8 : (¬ e 5 11) := fun hu => c1322 e tri schur hu v4 h3
  have v9 : (¬ e 2 9) := fun hu => c168 e tri schur v4 hu h3
  have v10 : (¬ e 6 9) := fun hu => c454 e tri schur hu v4 h0
  have v11 : (¬ e 6 15) := fun hu => c460 e tri schur hu v5 h0
  have v12 : (¬ e 9 15) := fun hu => c490 e tri schur hu v5 v4
  exact c878 e tri schur v10 v11 v12

theorem c1398 : (e 5 6) → (e 4 15) → (e 4 10) → (e 3 10) → (e 2 14) → (e 2 10) → (¬ e 2 3) → (¬ e 3 9) → (¬ e 4 9) → (¬ e 9 14) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9
  have v0 : (¬ e 2 4) := fun hu => c156 e tri schur h2 h5 hu
  have v1 : (¬ e 10 14) := fun hu => c223 e tri schur hu h4 h5
  have v2 : (¬ e 3 4) := fun hu => c261 e tri schur h2 h3 hu
  have v3 : (¬ e 10 15) := fun hu => c420 e tri schur hu h1 h2
  have v4 : (¬ e 2 5) := fun hu => c1397 e tri schur h0 h4 h5 hu h9 v3
  have v5 : (e 3 5) := Classical.byContradiction (fun hu => c832 e tri schur h6 v4 hu)
  have v6 : (¬ e 3 6) := fun hu => c270 e tri schur h0 hu v5
  have v7 : (¬ e 5 10) := fun hu => c274 e tri schur hu h3 v5
  have v8 : (e 6 9) := Classical.byContradiction (fun hu => c848 e tri schur v6 h7 hu)
  have v9 : (e 5 15) := Classical.byContradiction (fun hu => c872 e tri schur v7 hu v3)
  have v10 : (¬ e 4 5) := fun hu => c986 e tri schur h1 h2 hu v7
  have v11 : (¬ e 3 15) := fun hu => c279 e tri schur v9 hu v5
  have v12 : (¬ e 5 9) := fun hu => c454 e tri schur v8 hu h0
  have v13 : (¬ e 6 15) := fun hu => c460 e tri schur hu v9 h0
  exact c858 e tri schur v10 h8 v12

end Jsp746.Certificate
