/- Generated by scripts/generate_refutation.py from our own SAT trace.
Every statement below is proved with ordinary kernel-checked proof terms. -/
import Jsp746.Certificate.Steps01

namespace Jsp746.Certificate
variable (e : ℕ → ℕ → Prop)
variable (tri : TriangleCondition e) (schur : SchurCondition e)
include tri schur

theorem c1124 : (e 4 14) → (e 3 15) → (e 3 4) → (¬ e 11 15) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 14) := fun hu => c265 e tri schur h0 hu h2
  have v1 : (¬ e 4 15) := fun hu => c266 e tri schur hu h1 h2
  have v2 : (e 4 11) := Classical.byContradiction (fun hu => c864 e tri schur hu v1 h3)
  exact c1105 e tri schur h0 v2 h2

theorem c1125 : (e 4 10) → (¬ e 3 4) → (¬ e 3 7) → (¬ e 3 10) → False := by
  intro h0 h1 h2 h3
  have v0 : (e 4 7) := Classical.byContradiction (fun hu => c846 e tri schur h1 h2 hu)
  have v1 : (e 7 10) := Classical.byContradiction (fun hu => c849 e tri schur h2 h3 hu)
  have v2 : (¬ e 6 7) := fun hu => c1052 e tri schur v1 hu v0
  exact c388 e tri schur v1 h0 v0

theorem c1127 : (e 4 14) → (e 4 9) → (e 2 5) → (¬ e 2 12) → (¬ e 2 16) → (¬ e 5 9) → (¬ e 12 16) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 9 14) := fun hu => c411 e tri schur hu h0 h1
  have v1 : (e 5 14) := Classical.byContradiction (fun hu => c871 e tri schur h5 hu v0)
  have v2 : (¬ e 4 12) := fun hu => c1096 e tri schur h0 hu h1 h2 h3 h5
  have v3 : (¬ e 2 14) := fun hu => c173 e tri schur v1 hu h2
  have v4 : (¬ e 4 5) := fun hu => c369 e tri schur v1 h0 hu
  have v5 : (e 12 14) := Classical.byContradiction (fun hu => c841 e tri schur h3 v3 hu)
  have v6 : (e 14 16) := Classical.byContradiction (fun hu => c843 e tri schur v3 h4 hu)
  have v7 : (e 4 16) := Classical.byContradiction (fun hu => c865 e tri schur v2 hu h6)
  have v8 : (¬ e 9 16) := fun hu => c413 e tri schur hu v7 h1
  exact c443 e tri schur v6 v7 h0

theorem c1129 : (e 5 17) → (e 5 15) → (e 2 5) → (¬ e 2 15) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 2 17) := fun hu => c176 e tri schur h0 hu h2
  have v1 : (¬ e 15 17) := fun hu => c525 e tri schur hu h0 h1
  exact c844 e tri schur h3 v0 v1

theorem c1130 : (e 7 16) → (e 6 16) → (e 3 7) → (¬ e 3 13) → (¬ e 6 7) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 3 16) := fun hu => c303 e tri schur h0 hu h2
  have v1 : (e 13 16) := Classical.byContradiction (fun hu => c855 e tri schur h3 v0 hu)
  have v2 : (¬ e 6 13) := fun hu => c583 e tri schur v1 h1 hu
  have v3 : (¬ e 7 13) := fun hu => c638 e tri schur v1 h0 hu
  exact c876 e tri schur h4 v2 v3

theorem c1133 : (e 6 8) → (e 5 8) → (e 3 18) → (e 3 13) → (e 3 7) → (¬ e 3 8) → (¬ e 5 13) → (¬ e 7 11) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 7 13) := fun hu => c300 e tri schur hu h3 h4
  have v1 : (¬ e 7 18) := fun hu => c305 e tri schur hu h2 h4
  have v2 : (¬ e 13 18) := fun hu => c350 e tri schur hu h2 h3
  have v3 : (¬ e 5 6) := fun hu => c453 e tri schur h0 h1 hu
  have v4 : (e 5 18) := Classical.byContradiction (fun hu => c875 e tri schur h6 hu v2)
  have v5 : (e 11 18) := Classical.byContradiction (fun hu => c885 e tri schur h7 v1 hu)
  have v6 : (¬ e 16 18) := fun hu => c1035 e tri schur hu v5 v4
  have v7 : (¬ e 3 5) := fun hu => c282 e tri schur v4 h2 hu
  have v8 : (¬ e 3 11) := fun hu => c339 e tri schur v5 h2 hu
  have v9 : (¬ e 8 18) := fun hu => c484 e tri schur hu v4 h1
  have v10 : (¬ e 5 11) := fun hu => c508 e tri schur v5 v4 hu
  have v11 : (e 8 11) := Classical.byContradiction (fun hu => c850 e tri schur h5 v8 hu)
  have v12 : (e 6 11) := Classical.byContradiction (fun hu => c868 e tri schur v3 v10 hu)
  have v13 : (¬ e 3 6) := fun hu => c959 e tri schur v12 h0 hu
  exact c1027 e tri schur v11 h0 h1 v10

theorem c1136 : (e 13 18) → (e 13 15) → (e 3 13) → (¬ e 3 15) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 18) := fun hu => c350 e tri schur h0 hu h2
  have v1 : (¬ e 15 18) := fun hu => c802 e tri schur hu h0 h1
  exact c857 e tri schur h3 v0 v1

theorem c1137 : (e 8 11) → (e 6 13) → (e 5 13) → (e 3 13) → (¬ e 3 8) → (¬ e 6 11) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 3 5) := fun hu => c277 e tri schur h2 h3 hu
  have v1 : (¬ e 3 6) := fun hu => c289 e tri schur h1 h3 hu
  have v2 : (¬ e 5 6) := fun hu => c458 e tri schur h1 h2 hu
  have v3 : (e 5 8) := Classical.byContradiction (fun hu => c847 e tri schur v0 h4 hu)
  have v4 : (e 5 11) := Classical.byContradiction (fun hu => c868 e tri schur v2 hu h5)
  have v5 : (¬ e 9 13) := fun hu => c940 e tri schur hu h1 h3
  exact c477 e tri schur h0 v4 v3

theorem c1141 : (e 7 8) → (e 5 8) → (e 3 13) → (e 3 11) → (¬ e 2 13) → (¬ e 3 5) → (¬ e 6 8) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 11 13) := fun hu => c334 e tri schur hu h2 h3
  have v1 : (¬ e 5 7) := fun hu => c464 e tri schur h0 h1 hu
  have v2 : (e 2 11) := Classical.byContradiction (fun hu => c840 e tri schur hu h4 v0)
  have v3 : (e 2 7) := Classical.byContradiction (fun hu => c1055 e tri schur h0 h1 v2 hu h6)
  have v4 : (¬ e 2 3) := fun hu => c143 e tri schur h3 v2 hu
  have v5 : (¬ e 2 8) := fun hu => c190 e tri schur h0 hu v3
  have v6 : (¬ e 7 11) := fun hu => c193 e tri schur hu v2 v3
  have v7 : (e 2 5) := Classical.byContradiction (fun hu => c832 e tri schur v4 hu h5)
  have v8 : (e 2 6) := Classical.byContradiction (fun hu => c835 e tri schur hu v5 h6)
  exact c916 e tri schur v2 v8 v7

theorem c1144 : (e 13 18) → (e 13 15) → (e 10 18) → (¬ e 3 10) → (¬ e 3 15) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 10 13) := fun hu => c749 e tri schur h0 h2 hu
  have v1 : (¬ e 15 18) := fun hu => c802 e tri schur hu h0 h1
  have v2 : (e 3 13) := Classical.byContradiction (fun hu => c852 e tri schur h3 hu v0)
  have v3 : (e 3 18) := Classical.byContradiction (fun hu => c857 e tri schur h4 hu v1)
  exact c1136 e tri schur h0 h1 v2 h4

theorem c1145 : (e 13 15) → (e 10 18) → (e 10 13) → (¬ e 5 15) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 10 15) := fun hu => c746 e tri schur h0 hu h2
  have v1 : (¬ e 13 18) := fun hu => c749 e tri schur hu h1 h2
  have v2 : (e 5 10) := Classical.byContradiction (fun hu => c872 e tri schur hu h3 v0)
  exact c1000 e tri schur h1 h2 v2

theorem c1147 : (e 7 8) → (e 5 8) → (e 2 8) → (¬ e 3 5) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 2 5) := fun hu => c167 e tri schur h1 h2 hu
  have v1 : (¬ e 2 7) := fun hu => c190 e tri schur h0 h2 hu
  have v2 : (¬ e 5 7) := fun hu => c464 e tri schur h0 h1 hu
  have v3 : (e 2 3) := Classical.byContradiction (fun hu => c832 e tri schur hu v0 h3)
  exact c834 e tri schur v0 v1 v2

theorem c1148 : (e 14 18) → (e 11 18) → (e 3 18) → (¬ e 3 11) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 14) := fun hu => c354 e tri schur h0 h2 hu
  have v1 : (¬ e 11 14) := fun hu => c774 e tri schur h0 h1 hu
  exact c853 e tri schur h3 v0 v1

theorem c1154 : (e 11 13) → (e 7 11) → (e 6 11) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 6 7) := fun hu => c533 e tri schur h1 h2 hu
  have v1 : (¬ e 6 13) := fun hu => c569 e tri schur h0 hu h2
  have v2 : (¬ e 7 13) := fun hu => c624 e tri schur h0 hu h1
  exact c876 e tri schur v0 v1 v2

theorem c1158 : (e 6 13) → (e 4 6) → (e 3 13) → (e 3 4) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 6) := fun hu => c257 e tri schur h1 hu h3
  have v1 : (¬ e 4 13) := fun hu => c264 e tri schur hu h2 h3
  have v2 : (¬ e 9 13) := fun hu => c940 e tri schur hu h0 h2
  have v3 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu v1 v2)
  have v4 : (¬ e 6 9) := fun hu => c904 e tri schur h0 hu h1 v2
  have v5 : (¬ e 3 9) := fun hu => c260 e tri schur v3 hu h3
  exact c848 e tri schur v0 v5 v4

theorem c1159 : (e 4 9) → (e 4 6) → (e 3 4) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 6) := fun hu => c257 e tri schur h1 hu h2
  have v1 : (¬ e 3 9) := fun hu => c260 e tri schur h0 hu h2
  have v2 : (¬ e 6 9) := fun hu => c376 e tri schur hu h0 h1
  exact c848 e tri schur v0 v1 v2

theorem c1160 : (e 16 18) → (e 14 18) → (e 3 18) → (e 2 11) → (¬ e 2 16) → (¬ e 3 11) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 3 14) := fun hu => c354 e tri schur h1 h2 hu
  have v1 : (¬ e 3 16) := fun hu => c359 e tri schur h0 h2 hu
  have v2 : (¬ e 14 16) := fun hu => c810 e tri schur h0 h1 hu
  have v3 : (e 2 14) := Classical.byContradiction (fun hu => c843 e tri schur hu h4 v2)
  have v4 : (e 11 14) := Classical.byContradiction (fun hu => c853 e tri schur h5 v0 hu)
  have v5 : (¬ e 11 18) := fun hu => c1148 e tri schur h1 hu h2 h5
  exact c230 e tri schur v4 v3 h3

theorem c1168 : (e 3 18) → (e 3 13) → (¬ e 5 8) → (¬ e 5 13) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 13 18) := fun hu => c350 e tri schur hu h0 h1
  have v1 : (e 8 13) := Classical.byContradiction (fun hu => c870 e tri schur h2 h3 hu)
  have v2 : (e 5 18) := Classical.byContradiction (fun hu => c875 e tri schur h3 hu v0)
  have v3 : (¬ e 3 5) := fun hu => c282 e tri schur v2 h0 hu
  have v4 : (¬ e 3 8) := fun hu => c310 e tri schur v1 h1 hu
  exact c847 e tri schur v3 v4 h2

theorem c1170 : (e 5 13) → (e 5 7) → (e 5 6) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 6 7) := fun hu => c452 e tri schur hu h1 h2
  have v1 : (¬ e 6 13) := fun hu => c458 e tri schur hu h0 h2
  have v2 : (¬ e 7 13) := fun hu => c469 e tri schur hu h0 h1
  exact c876 e tri schur v0 v1 v2

theorem c1173 : (e 5 13) → (e 5 6) → (e 4 6) → (e 3 4) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 3 6) := fun hu => c257 e tri schur h2 hu h3
  have v1 : (¬ e 4 5) := fun hu => c361 e tri schur h1 h2 hu
  have v2 : (¬ e 6 13) := fun hu => c458 e tri schur hu h0 h1
  have v3 : (¬ e 4 9) := fun hu => c1159 e tri schur hu h2 h3
  have v4 : (¬ e 5 7) := fun hu => c1170 e tri schur h0 hu h1
  have v5 : (e 5 9) := Classical.byContradiction (fun hu => c858 e tri schur v1 v3 hu)
  have v6 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v3 h4 hu)
  have v7 : (¬ e 6 9) := fun hu => c454 e tri schur hu v5 h1
  exact c488 e tri schur v6 h0 v5

theorem c1175 : (e 5 13) → (¬ e 4 5) → (¬ e 4 9) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3
  have v0 : (e 5 9) := Classical.byContradiction (fun hu => c858 e tri schur h1 h2 hu)
  have v1 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur h2 h3 hu)
  exact c488 e tri schur v1 h0 v0

theorem c1176 : (e 13 15) → (e 11 13) → (e 5 13) → (e 4 10) → (¬ e 4 11) → (¬ e 5 10) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 5 11) := fun hu => c503 e tri schur h1 h2 hu
  have v1 : (¬ e 5 15) := fun hu => c516 e tri schur h0 hu h2
  have v2 : (¬ e 11 15) := fun hu => c767 e tri schur h0 hu h1
  have v3 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur h4 hu v2)
  have v4 : (e 10 15) := Classical.byContradiction (fun hu => c872 e tri schur h5 v1 hu)
  have v5 : (¬ e 4 5) := fun hu => c986 e tri schur v3 h3 hu h5
  exact c420 e tri schur v4 v3 h3

theorem c1177 : (e 2 15) → (e 2 11) → (e 2 4) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 11) := fun hu => c157 e tri schur hu h1 h2
  have v1 : (¬ e 4 15) := fun hu => c161 e tri schur hu h0 h2
  have v2 : (¬ e 11 15) := fun hu => c231 e tri schur hu h0 h1
  exact c864 e tri schur v0 v1 v2

theorem c1178 : (e 5 16) → (e 5 10) → (e 5 6) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 6 10) := fun hu => c455 e tri schur hu h1 h2
  have v1 : (¬ e 6 16) := fun hu => c461 e tri schur hu h0 h2
  have v2 : (¬ e 10 16) := fun hu => c499 e tri schur hu h0 h1
  exact c879 e tri schur v0 v1 v2

theorem c1179 : (e 11 16) → (e 11 14) → (e 2 11) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 14) := fun hu => c230 e tri schur h1 hu h2
  have v1 : (¬ e 2 16) := fun hu => c232 e tri schur h0 hu h2
  have v2 : (¬ e 14 16) := fun hu => c772 e tri schur hu h0 h1
  exact c843 e tri schur v0 v1 v2

theorem c1180 : (e 3 18) → (e 3 14) → (e 3 4) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 14) := fun hu => c265 e tri schur hu h1 h2
  have v1 : (¬ e 4 18) := fun hu => c269 e tri schur hu h0 h2
  have v2 : (¬ e 14 18) := fun hu => c354 e tri schur hu h0 h1
  exact c867 e tri schur v0 v1 v2

theorem c1181 : (e 2 11) → (¬ e 2 6) → (¬ e 3 5) → (¬ e 3 8) → (¬ e 3 11) → (¬ e 5 11) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (e 5 8) := Classical.byContradiction (fun hu => c847 e tri schur h2 h3 hu)
  have v1 : (e 8 11) := Classical.byContradiction (fun hu => c850 e tri schur h3 h4 hu)
  have v2 : (¬ e 6 8) := fun hu => c1027 e tri schur v1 hu v0 h5
  have v3 : (¬ e 2 8) := fun hu => c203 e tri schur v1 h0 hu
  exact c835 e tri schur h1 v3 v2

theorem c1182 : (e 5 8) → (e 5 6) → (e 2 5) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 6) := fun hu => c165 e tri schur h1 hu h2
  have v1 : (¬ e 2 8) := fun hu => c167 e tri schur h0 hu h2
  have v2 : (¬ e 6 8) := fun hu => c453 e tri schur hu h0 h1
  exact c835 e tri schur v0 v1 v2

theorem c1183 : (e 11 13) → (e 7 11) → (e 6 9) → (e 2 11) → (¬ e 2 9) → (¬ e 6 13) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 2 7) := fun hu => c193 e tri schur h1 h3 hu
  have v1 : (¬ e 2 13) := fun hu => c229 e tri schur h0 hu h3
  have v2 : (¬ e 7 13) := fun hu => c624 e tri schur h0 hu h1
  have v3 : (e 7 9) := Classical.byContradiction (fun hu => c836 e tri schur v0 h4 hu)
  have v4 : (e 6 7) := Classical.byContradiction (fun hu => c876 e tri schur hu h5 v2)
  have v5 : (¬ e 7 15) := fun hu => c1037 e tri schur hu v3 v4
  have v6 : (¬ e 6 11) := fun hu => c1154 e tri schur h0 h1 hu
  exact c531 e tri schur v3 h2 v4

theorem c1184 : (e 11 13) → (e 5 13) → (e 5 6) → (e 3 13) → (e 3 4) → (e 2 11) → (e 2 5) → (¬ e 3 6) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 2 6) := fun hu => c165 e tri schur h2 hu h6
  have v1 : (¬ e 5 11) := fun hu => c170 e tri schur hu h5 h6
  have v2 : (¬ e 2 13) := fun hu => c172 e tri schur h1 hu h6
  have v3 : (¬ e 4 13) := fun hu => c264 e tri schur hu h3 h4
  have v4 : (¬ e 3 5) := fun hu => c277 e tri schur h1 h3 hu
  have v5 : (¬ e 3 11) := fun hu => c334 e tri schur h0 h3 hu
  have v6 : (¬ e 6 13) := fun hu => c458 e tri schur hu h1 h2
  have v7 : (¬ e 2 16) := fun hu => c1065 e tri schur hu h5 h6 v1
  have v8 : (¬ e 5 7) := fun hu => c1170 e tri schur h1 hu h2
  have v9 : (¬ e 4 6) := fun hu => c1173 e tri schur h1 h2 hu h4 v3
  have v10 : (e 3 8) := Classical.byContradiction (fun hu => c1181 e tri schur h5 v0 v4 hu v5 v1)
  have v11 : (¬ e 5 8) := fun hu => c1182 e tri schur hu h2 h6
  have v12 : (¬ e 4 8) := fun hu => c259 e tri schur hu v10 h4
  have v13 : (¬ e 8 13) := fun hu => c310 e tri schur hu h3 v10
  have v14 : (e 2 4) := Classical.byContradiction (fun hu => c833 e tri schur hu v0 v9)
  have v15 : (¬ e 2 9) := fun hu => c1118 e tri schur hu h6 v14
  have v16 : (¬ e 2 15) := fun hu => c1177 e tri schur hu h5 v14
  have v17 : (¬ e 2 3) := fun hu => c136 e tri schur h4 v14 hu
  have v18 : (¬ e 4 5) := fun hu => c151 e tri schur hu h6 v14
  have v19 : (¬ e 4 11) := fun hu => c157 e tri schur hu h5 v14
  have v20 : (e 13 15) := Classical.byContradiction (fun hu => c842 e tri schur v2 v16 hu)
  have v21 : (e 4 9) := Classical.byContradiction (fun hu => c1175 e tri schur h1 v18 hu v3)
  have v22 : (¬ e 3 9) := fun hu => c260 e tri schur v21 hu h4
  have v23 : (¬ e 3 15) := fun hu => c347 e tri schur v20 hu h3
  have v24 : (¬ e 5 15) := fun hu => c516 e tri schur v20 hu h1
  have v25 : (¬ e 11 15) := fun hu => c767 e tri schur v20 hu h0
  have v26 : (e 6 9) := Classical.byContradiction (fun hu => c848 e tri schur h7 v22 hu)
  have v27 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur v19 hu v25)
  have v28 : (¬ e 13 18) := fun hu => c1136 e tri schur hu v20 h3 v23
  have v29 : (¬ e 7 11) := fun hu => c1183 e tri schur h0 hu v26 h5 v15 v6
  have v30 : (¬ e 9 15) := fun hu => c412 e tri schur hu v27 v21
  have v31 : (¬ e 5 9) := fun hu => c454 e tri schur v26 hu h2
  have v32 : (e 4 7) := Classical.byContradiction (fun hu => c860 e tri schur hu v19 v29)
  have v33 : (¬ e 7 15) := fun hu => c900 e tri schur hu v19 v29 v25
  have v34 : (¬ e 2 7) := fun hu => c153 e tri schur v32 hu v14
  have v35 : (¬ e 3 7) := fun hu => c258 e tri schur v32 hu h4
  have v36 : (¬ e 7 9) := fun hu => c387 e tri schur hu v21 v32
  exact c836 e tri schur v34 v15 v36

theorem c1185 : (e 2 11) → (e 2 7) → (e 2 4) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 7) := fun hu => c153 e tri schur hu h1 h2
  have v1 : (¬ e 4 11) := fun hu => c157 e tri schur hu h0 h2
  have v2 : (¬ e 7 11) := fun hu => c193 e tri schur hu h0 h1
  exact c860 e tri schur v0 v1 v2

theorem c1187 : (e 13 15) → (e 11 13) → (e 4 13) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 11) := fun hu => c425 e tri schur h1 h2 hu
  have v1 : (¬ e 4 15) := fun hu => c438 e tri schur h0 hu h2
  have v2 : (¬ e 11 15) := fun hu => c767 e tri schur h0 hu h1
  exact c864 e tri schur v0 v1 v2

theorem c1188 : (e 4 15) → (e 4 12) → (e 3 4) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 12) := fun hu => c263 e tri schur h1 hu h2
  have v1 : (¬ e 3 15) := fun hu => c266 e tri schur h0 hu h2
  have v2 : (¬ e 12 15) := fun hu => c433 e tri schur hu h0 h1
  exact c854 e tri schur v0 v1 v2

theorem c1189 : (e 4 15) → (e 3 14) → (e 3 8) → (e 3 4) → (¬ e 6 8) → (¬ e 6 12) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 4 8) := fun hu => c259 e tri schur hu h2 h3
  have v1 : (¬ e 4 14) := fun hu => c265 e tri schur hu h1 h3
  have v2 : (¬ e 3 15) := fun hu => c266 e tri schur h0 hu h3
  have v3 : (¬ e 8 14) := fun hu => c311 e tri schur hu h1 h2
  have v4 : (e 6 14) := Classical.byContradiction (fun hu => c877 e tri schur h4 hu v3)
  have v5 : (¬ e 3 6) := fun hu => c950 e tri schur h1 h2 hu
  have v6 : (¬ e 3 18) := fun hu => c1180 e tri schur hu h1 h3
  have v7 : (¬ e 4 12) := fun hu => c1188 e tri schur h0 hu h3
  have v8 : (e 15 18) := Classical.byContradiction (fun hu => c857 e tri schur v2 v6 hu)
  have v9 : (e 8 12) := Classical.byContradiction (fun hu => c861 e tri schur v0 v7 hu)
  have v10 : (¬ e 8 15) := fun hu => c987 e tri schur hu v9 h2
  have v11 : (¬ e 3 12) := fun hu => c309 e tri schur v9 hu h2
  have v12 : (¬ e 4 18) := fun hu => c448 e tri schur v8 hu h0
  have v13 : (e 12 15) := Classical.byContradiction (fun hu => c854 e tri schur v11 v2 hu)
  have v14 : (e 14 18) := Classical.byContradiction (fun hu => c867 e tri schur v1 v12 hu)
  have v15 : (¬ e 6 18) := fun hu => c589 e tri schur v14 hu v4
  have v16 : (¬ e 12 18) := fun hu => c792 e tri schur v8 hu v13
  have v17 : (¬ e 14 15) := fun hu => c808 e tri schur v8 v14 hu
  exact c881 e tri schur h5 v15 v16

theorem c1190 : (e 15 18) → (e 12 15) → (e 6 14) → (e 4 15) → (¬ e 4 14) → (¬ e 6 12) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 4 12) := fun hu => c433 e tri schur h1 h3 hu
  have v1 : (¬ e 4 18) := fun hu => c448 e tri schur h0 hu h3
  have v2 : (¬ e 12 18) := fun hu => c792 e tri schur h0 hu h1
  have v3 : (e 14 18) := Classical.byContradiction (fun hu => c867 e tri schur h4 v1 hu)
  have v4 : (e 6 18) := Classical.byContradiction (fun hu => c881 e tri schur h5 hu v2)
  have v5 : (¬ e 9 18) := fun hu => c890 e tri schur h0 hu v4
  exact c589 e tri schur v3 v4 h2

theorem c1194 : (e 4 15) → (e 4 9) → (e 4 6) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 6 9) := fun hu => c376 e tri schur hu h1 h2
  have v1 : (¬ e 6 15) := fun hu => c382 e tri schur hu h0 h2
  have v2 : (¬ e 9 15) := fun hu => c412 e tri schur hu h0 h1
  exact c878 e tri schur v0 v1 v2

theorem c1195 : (e 4 11) → (e 4 6) → (e 3 18) → (e 3 7) → (¬ e 6 8) → (¬ e 7 11) → (¬ e 8 11) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 7 18) := fun hu => c305 e tri schur hu h2 h3
  have v1 : (¬ e 6 11) := fun hu => c378 e tri schur hu h0 h1
  have v2 : (e 11 18) := Classical.byContradiction (fun hu => c885 e tri schur h5 v0 hu)
  have v3 : (¬ e 4 5) := fun hu => c984 e tri schur h0 h1 hu
  have v4 : (¬ e 3 11) := fun hu => c339 e tri schur v2 h2 hu
  have v5 : (¬ e 4 18) := fun hu => c430 e tri schur v2 hu h0
  have v6 : (e 3 8) := Classical.byContradiction (fun hu => c850 e tri schur hu v4 h6)
  have v7 : (¬ e 3 10) := fun hu => c963 e tri schur h2 hu v6
  have v8 : (¬ e 14 18) := fun hu => c1148 e tri schur hu v2 h2 v4
  have v9 : (¬ e 7 8) := fun hu => c295 e tri schur hu v6 h3
  have v10 : (¬ e 8 18) := fun hu => c315 e tri schur hu h2 v6
  have v11 : (e 4 14) := Classical.byContradiction (fun hu => c867 e tri schur hu v5 v8)
  have v12 : (¬ e 3 4) := fun hu => c1105 e tri schur v11 h0 hu
  have v13 : (¬ e 6 14) := fun hu => c381 e tri schur hu v11 h1
  have v14 : (¬ e 11 14) := fun hu => c426 e tri schur hu v11 h0
  have v15 : (e 3 14) := Classical.byContradiction (fun hu => c853 e tri schur v4 hu v14)
  have v16 : (e 8 14) := Classical.byContradiction (fun hu => c877 e tri schur h4 v13 hu)
  have v17 : (¬ e 3 6) := fun hu => c950 e tri schur v15 v6 hu
  have v18 : (¬ e 7 14) := fun hu => c301 e tri schur hu v15 h3
  exact c311 e tri schur v16 v15 v6

theorem c1196 : (e 2 12) → (e 2 7) → (e 2 5) → (¬ e 5 7) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 5 12) := fun hu => c171 e tri schur hu h0 h2
  have v1 : (¬ e 7 12) := fun hu => c194 e tri schur hu h0 h1
  exact c869 e tri schur h3 v0 v1

theorem c1197 : (e 10 12) → (¬ e 2 12) → (¬ e 2 14) → (¬ e 2 16) → (¬ e 4 16) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (e 12 14) := Classical.byContradiction (fun hu => c841 e tri schur h1 h2 hu)
  have v1 : (e 14 16) := Classical.byContradiction (fun hu => c843 e tri schur h2 h3 hu)
  have v2 : (¬ e 10 14) := fun hu => c740 e tri schur v0 hu h0
  have v3 : (¬ e 12 16) := fun hu => c787 e tri schur v1 hu v0
  have v4 : (e 4 12) := Classical.byContradiction (fun hu => c865 e tri schur hu h4 v3)
  have v5 : (¬ e 4 10) := fun hu => c417 e tri schur h0 v4 hu
  have v6 : (¬ e 4 14) := fun hu => c432 e tri schur v0 hu v4
  exact c863 e tri schur v5 v6 v2

theorem c1199 : (e 15 18) → (e 8 15) → (e 5 13) → (e 2 8) → (¬ e 2 13) → (¬ e 5 10) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 2 15) := fun hu => c207 e tri schur h1 hu h3
  have v1 : (¬ e 8 18) := fun hu => c692 e tri schur h0 hu h1
  have v2 : (e 13 15) := Classical.byContradiction (fun hu => c842 e tri schur h4 v0 hu)
  have v3 : (¬ e 10 15) := fun hu => c944 e tri schur h0 hu h1
  have v4 : (¬ e 10 18) := fun hu => c998 e tri schur h0 v2 hu h5
  have v5 : (¬ e 5 15) := fun hu => c516 e tri schur v2 hu h2
  have v6 : (¬ e 8 13) := fun hu => c682 e tri schur v2 h1 hu
  have v7 : (¬ e 13 18) := fun hu => c802 e tri schur h0 hu v2
  exact c872 e tri schur h5 v5 v3

theorem c1200 : (e 6 18) → (e 6 14) → (e 4 6) → (¬ e 4 18) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 4 14) := fun hu => c381 e tri schur h1 hu h2
  have v1 : (¬ e 14 18) := fun hu => c589 e tri schur hu h0 h1
  exact c867 e tri schur v0 h3 v1

theorem c1204 : (e 12 16) → (e 10 12) → (e 6 12) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 6 10) := fun hu => c561 e tri schur h1 h2 hu
  have v1 : (¬ e 6 16) := fun hu => c578 e tri schur h0 hu h2
  have v2 : (¬ e 10 16) := fun hu => c742 e tri schur h0 hu h1
  exact c879 e tri schur v0 v1 v2

theorem c1208 : (e 2 18) → (e 2 10) → (e 2 8) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 8 10) := fun hu => c202 e tri schur hu h1 h2
  have v1 : (¬ e 8 18) := fun hu => c210 e tri schur hu h0 h2
  have v2 : (¬ e 10 18) := fun hu => c227 e tri schur hu h0 h1
  exact c887 e tri schur v0 v1 v2

theorem c1210 : (e 16 18) → (e 10 18) → (e 6 12) → (e 4 6) → (e 2 8) → (¬ e 2 16) → (¬ e 12 16) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 4 12) := fun hu => c379 e tri schur h2 hu h3
  have v1 : (¬ e 10 16) := fun hu => c758 e tri schur h0 h1 hu
  have v2 : (e 4 16) := Classical.byContradiction (fun hu => c865 e tri schur v0 hu h6)
  have v3 : (¬ e 6 8) := fun hu => c1091 e tri schur h2 hu h3
  have v4 : (¬ e 6 16) := fun hu => c383 e tri schur hu v2 h3
  have v5 : (¬ e 4 18) := fun hu => c450 e tri schur h0 hu v2
  have v6 : (e 6 10) := Classical.byContradiction (fun hu => c879 e tri schur hu v4 v1)
  have v7 : (¬ e 4 10) := fun hu => c377 e tri schur v6 hu h3
  have v8 : (¬ e 10 12) := fun hu => c561 e tri schur hu h2 v6
  have v9 : (¬ e 6 18) := fun hu => c567 e tri schur h1 hu v6
  have v10 : (e 4 14) := Classical.byContradiction (fun hu => c1095 e tri schur h1 v7 hu v5)
  have v11 : (¬ e 6 14) := fun hu => c381 e tri schur hu v10 h3
  have v12 : (¬ e 14 16) := fun hu => c443 e tri schur hu v2 v10
  have v13 : (e 2 14) := Classical.byContradiction (fun hu => c843 e tri schur hu h5 v12)
  have v14 : (e 8 14) := Classical.byContradiction (fun hu => c877 e tri schur v3 v11 hu)
  have v15 : (¬ e 8 12) := fun hu => c951 e tri schur v14 hu h4
  have v16 : (¬ e 8 10) := fun hu => c971 e tri schur v14 hu h4 v0
  have v17 : (¬ e 2 4) := fun hu => c160 e tri schur v10 v13 hu
  exact c206 e tri schur v14 v13 h4

theorem c1211 : (e 10 18) → (e 4 16) → (e 2 10) → (e 2 4) → (¬ e 2 16) → (¬ e 4 18) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 4 10) := fun hu => c156 e tri schur hu h2 h3
  have v1 : (¬ e 2 18) := fun hu => c227 e tri schur h0 hu h2
  have v2 : (e 16 18) := Classical.byContradiction (fun hu => c845 e tri schur h4 v1 hu)
  have v3 : (¬ e 10 16) := fun hu => c1081 e tri schur h0 hu h2 v1
  have v4 : (e 4 14) := Classical.byContradiction (fun hu => c1095 e tri schur h0 v0 hu h5)
  have v5 : (¬ e 2 14) := fun hu => c160 e tri schur v4 hu h3
  have v6 : (¬ e 14 16) := fun hu => c443 e tri schur hu h1 v4
  exact c843 e tri schur v5 h4 v6

theorem c1212 : (e 2 14) → (e 2 8) → (e 2 6) → (¬ e 6 8) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 6 14) := fun hu => c185 e tri schur hu h0 h2
  have v1 : (¬ e 8 14) := fun hu => c206 e tri schur hu h0 h1
  exact c877 e tri schur h3 v0 v1

theorem c1213 : (e 16 18) → (e 14 16) → (e 4 16) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 14) := fun hu => c443 e tri schur h1 h2 hu
  have v1 : (¬ e 4 18) := fun hu => c450 e tri schur h0 hu h2
  have v2 : (¬ e 14 18) := fun hu => c810 e tri schur h0 hu h1
  exact c867 e tri schur v0 v1 v2

theorem c1214 : (e 10 18) → (e 4 16) → (e 2 10) → (e 2 8) → (¬ e 2 16) → (¬ e 4 6) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 8 10) := fun hu => c202 e tri schur hu h2 h3
  have v1 : (¬ e 2 18) := fun hu => c227 e tri schur h0 hu h2
  have v2 : (e 16 18) := Classical.byContradiction (fun hu => c845 e tri schur h4 v1 hu)
  have v3 : (¬ e 10 16) := fun hu => c1081 e tri schur h0 hu h2 v1
  have v4 : (¬ e 14 16) := fun hu => c1213 e tri schur v2 hu h1
  have v5 : (¬ e 4 18) := fun hu => c450 e tri schur v2 hu h1
  have v6 : (e 2 14) := Classical.byContradiction (fun hu => c843 e tri schur hu h4 v4)
  have v7 : (¬ e 2 4) := fun hu => c1211 e tri schur h0 h1 h2 hu h4 v5
  have v8 : (¬ e 8 14) := fun hu => c206 e tri schur hu v6 h3
  have v9 : (¬ e 10 14) := fun hu => c223 e tri schur hu v6 h2
  have v10 : (e 2 6) := Classical.byContradiction (fun hu => c833 e tri schur v7 hu h5)
  have v11 : (e 6 8) := Classical.byContradiction (fun hu => c1212 e tri schur v6 h3 v10 hu)
  exact c179 e tri schur v11 h3 v10

theorem c1215 : (e 2 14) → (e 2 8) → (e 2 6) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 6 8) := fun hu => c179 e tri schur hu h1 h2
  have v1 : (¬ e 6 14) := fun hu => c185 e tri schur hu h0 h2
  have v2 : (¬ e 8 14) := fun hu => c206 e tri schur hu h0 h1
  exact c877 e tri schur v0 v1 v2

theorem c1216 : (e 2 14) → (e 2 10) → (e 2 8) → (¬ e 4 6) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 8 10) := fun hu => c202 e tri schur hu h1 h2
  have v1 : (¬ e 8 14) := fun hu => c206 e tri schur hu h0 h2
  have v2 : (¬ e 10 14) := fun hu => c223 e tri schur hu h0 h1
  have v3 : (¬ e 2 18) := fun hu => c1208 e tri schur hu h1 h2
  have v4 : (¬ e 2 6) := fun hu => c1215 e tri schur h0 h2 hu
  have v5 : (e 2 4) := Classical.byContradiction (fun hu => c833 e tri schur hu v4 h3)
  have v6 : (¬ e 4 8) := fun hu => c154 e tri schur hu h2 v5
  have v7 : (¬ e 4 10) := fun hu => c156 e tri schur hu h1 v5
  have v8 : (¬ e 4 14) := fun hu => c160 e tri schur hu h0 v5
  have v9 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur h3 v7 hu)
  exact c863 e tri schur v7 v8 v2

theorem c1217 : (e 2 15) → (e 2 10) → (e 2 5) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 5 10) := fun hu => c169 e tri schur hu h1 h2
  have v1 : (¬ e 5 15) := fun hu => c174 e tri schur hu h0 h2
  have v2 : (¬ e 10 15) := fun hu => c224 e tri schur hu h0 h1
  exact c872 e tri schur v0 v1 v2

theorem c1218 : (e 4 11) → (e 2 4) → (¬ e 2 9) → (¬ e 2 13) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 2 11) := fun hu => c157 e tri schur h0 hu h1
  have v1 : (e 9 11) := Classical.byContradiction (fun hu => c838 e tri schur h2 v0 hu)
  have v2 : (e 11 13) := Classical.byContradiction (fun hu => c840 e tri schur v0 h3 hu)
  exact c1028 e tri schur v2 v1 h0

theorem c1219 : (e 13 15) → (e 12 14) → (e 10 15) → (e 4 12) → (¬ e 2 9) → (¬ e 2 11) → (¬ e 2 13) → (¬ e 4 11) → (¬ e 4 13) → (¬ e 5 6) → (¬ e 5 8) → (¬ e 5 14) → (¬ e 6 15) → (¬ e 10 13) → (¬ e 15 18) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14
  have v0 : (¬ e 4 14) := fun hu => c432 e tri schur h1 hu h3
  have v1 : (e 9 11) := Classical.byContradiction (fun hu => c838 e tri schur h4 h5 hu)
  have v2 : (e 11 13) := Classical.byContradiction (fun hu => c840 e tri schur h5 h6 hu)
  have v3 : (¬ e 4 6) := fun hu => c1111 e tri schur h0 v2 v1 hu
  have v4 : (¬ e 9 13) := fun hu => c705 e tri schur v2 hu v1
  have v5 : (¬ e 11 15) := fun hu => c767 e tri schur h0 hu v2
  have v6 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu h8 v4)
  have v7 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur h7 hu v5)
  have v8 : (¬ e 3 4) := fun hu => c1188 e tri schur v7 h3 hu
  have v9 : (¬ e 9 12) := fun hu => c409 e tri schur hu h3 v6
  have v10 : (¬ e 9 15) := fun hu => c412 e tri schur hu v7 v6
  have v11 : (¬ e 4 10) := fun hu => c420 e tri schur h2 v7 hu
  have v12 : (¬ e 12 15) := fun hu => c433 e tri schur hu v7 h3
  have v13 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur v3 v11 hu)
  have v14 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v11 v0 hu)
  have v15 : (e 6 9) := Classical.byContradiction (fun hu => c878 e tri schur hu h12 v10)
  have v16 : (¬ e 9 10) := fun hu => c551 e tri schur hu v13 v15
  have v17 : (¬ e 6 11) := fun hu => c552 e tri schur v1 hu v15
  have v18 : (¬ e 6 14) := fun hu => c563 e tri schur v14 hu v13
  have v19 : (¬ e 10 12) := fun hu => c740 e tri schur h1 v14 hu
  have v20 : (¬ e 14 15) := fun hu => c750 e tri schur hu h2 v14
  have v21 : (e 5 11) := Classical.byContradiction (fun hu => c868 e tri schur h9 hu v17)
  have v22 : (¬ e 5 9) := fun hu => c486 e tri schur v1 v21 hu
  have v23 : (¬ e 5 13) := fun hu => c503 e tri schur v2 hu v21
  have v24 : (e 8 13) := Classical.byContradiction (fun hu => c870 e tri schur h10 v23 hu)
  have v25 : (e 9 14) := Classical.byContradiction (fun hu => c871 e tri schur v22 h11 hu)
  have v26 : (¬ e 3 9) := fun hu => c948 e tri schur v25 v1 hu
  have v27 : (¬ e 8 11) := fun hu => c669 e tri schur v2 v24 hu
  have v28 : (¬ e 8 15) := fun hu => c682 e tri schur h0 hu v24
  have v29 : (¬ e 11 14) := fun hu => c706 e tri schur hu v25 v1
  have v30 : (e 3 12) := Classical.byContradiction (fun hu => c851 e tri schur v26 hu v9)
  have v31 : (¬ e 3 14) := fun hu => c341 e tri schur h1 hu v30
  have v32 : (e 3 11) := Classical.byContradiction (fun hu => c853 e tri schur hu v31 v29)
  have v33 : (¬ e 3 5) := fun hu => c275 e tri schur v21 v32 hu
  have v34 : (¬ e 11 12) := fun hu => c333 e tri schur hu v30 v32
  have v35 : (¬ e 3 13) := fun hu => c334 e tri schur v2 hu v32
  have v36 : (e 3 8) := Classical.byContradiction (fun hu => c847 e tri schur v33 hu h10)
  have v37 : (e 3 10) := Classical.byContradiction (fun hu => c852 e tri schur hu v35 h13)
  have v38 : (¬ e 3 18) := fun hu => c963 e tri schur hu v37 v36
  have v39 : (¬ e 3 6) := fun hu => c286 e tri schur v13 v37 hu
  have v40 : (¬ e 8 10) := fun hu => c307 e tri schur hu v37 v36
  have v41 : (¬ e 8 12) := fun hu => c309 e tri schur hu v30 v36
  have v42 : (¬ e 10 11) := fun hu => c325 e tri schur hu v32 v37
  have v43 : (¬ e 3 15) := fun hu => c329 e tri schur h2 hu v37
  exact c857 e tri schur v43 v38 h14

theorem c1221 : (e 13 15) → (e 9 13) → (e 7 9) → (¬ e 6 15) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 7 13) := fun hu => c609 e tri schur h1 hu h2
  have v1 : (¬ e 9 15) := fun hu => c718 e tri schur h0 hu h1
  have v2 : (e 6 9) := Classical.byContradiction (fun hu => c878 e tri schur hu h3 v1)
  have v3 : (¬ e 6 7) := fun hu => c531 e tri schur h2 v2 hu
  have v4 : (¬ e 6 13) := fun hu => c554 e tri schur h1 hu v2
  exact c876 e tri schur v3 v4 v0

theorem c1222 : (e 13 18) → (e 13 15) → (e 12 14) → (e 10 18) → (e 10 15) → (e 6 10) → (e 4 12) → (e 2 8) → (e 2 4) → (¬ e 2 9) → (¬ e 2 13) → (¬ e 4 13) → (¬ e 5 6) → (¬ e 5 8) → (¬ e 5 14) → (¬ e 8 15) → (¬ e 15 18) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14 h15 h16
  have v0 : (¬ e 4 8) := fun hu => c154 e tri schur hu h7 h8
  have v1 : (¬ e 2 12) := fun hu => c158 e tri schur h6 hu h8
  have v2 : (¬ e 4 14) := fun hu => c432 e tri schur h2 hu h6
  have v3 : (¬ e 6 15) := fun hu => c564 e tri schur h4 hu h5
  have v4 : (¬ e 6 18) := fun hu => c567 e tri schur h3 hu h5
  have v5 : (¬ e 10 13) := fun hu => c746 e tri schur h1 h4 hu
  have v6 : (¬ e 4 11) := fun hu => c1218 e tri schur hu h8 h9 h10
  have v7 : (e 2 11) := Classical.byContradiction (fun hu => c1219 e tri schur h1 h2 h4 h6 h9 hu h10 v6 h11 h12 h13 h14 v3 v5 h16)
  have v8 : (¬ e 8 11) := fun hu => c203 e tri schur hu v7 h7
  have v9 : (¬ e 2 15) := fun hu => c1177 e tri schur hu v7 h8
  have v10 : (¬ e 2 7) := fun hu => c1185 e tri schur v7 hu h8
  have v11 : (e 7 9) := Classical.byContradiction (fun hu => c836 e tri schur v10 h9 hu)
  have v12 : (¬ e 9 13) := fun hu => c1221 e tri schur h1 hu v11 v3
  have v13 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu h11 v12)
  have v14 : (¬ e 3 9) := fun hu => c894 e tri schur v11 v13 hu
  have v15 : (¬ e 4 7) := fun hu => c387 e tri schur v11 v13 hu
  have v16 : (¬ e 9 12) := fun hu => c409 e tri schur hu h6 v13
  have v17 : (e 3 12) := Classical.byContradiction (fun hu => c851 e tri schur v14 hu v16)
  have v18 : (e 7 11) := Classical.byContradiction (fun hu => c860 e tri schur v15 v6 hu)
  have v19 : (¬ e 3 4) := fun hu => c263 e tri schur h6 v17 hu
  have v20 : (¬ e 3 14) := fun hu => c341 e tri schur h2 hu v17
  have v21 : (¬ e 9 11) := fun hu => c607 e tri schur hu v18 v11
  have v22 : (e 3 7) := Classical.byContradiction (fun hu => c846 e tri schur v19 hu v15)
  have v23 : (¬ e 7 12) := fun hu => c1094 e tri schur hu v11 v22 v14
  have v24 : (¬ e 7 8) := fun hu => c1121 e tri schur v18 hu v22
  have v25 : (¬ e 3 11) := fun hu => c298 e tri schur v18 hu v22
  have v26 : (e 3 8) := Classical.byContradiction (fun hu => c850 e tri schur hu v25 v8)
  have v27 : (e 11 14) := Classical.byContradiction (fun hu => c853 e tri schur v25 v20 hu)
  have v28 : (e 7 15) := Classical.byContradiction (fun hu => c882 e tri schur v24 hu h15)
  have v29 : (¬ e 6 7) := fun hu => c1037 e tri schur v28 v11 hu
  have v30 : (¬ e 11 16) := fun hu => c1179 e tri schur hu v27 v7
  have v31 : (¬ e 2 3) := fun hu => c140 e tri schur v26 h7 hu
  have v32 : (¬ e 2 14) := fun hu => c230 e tri schur v27 hu v7
  have v33 : (¬ e 3 15) := fun hu => c302 e tri schur v28 hu v22
  have v34 : (¬ e 8 12) := fun hu => c309 e tri schur hu v17 v26
  have v35 : (¬ e 9 15) := fun hu => c611 e tri schur hu v28 v11
  have v36 : (¬ e 7 10) := fun hu => c619 e tri schur h4 v28 hu
  have v37 : (¬ e 7 14) := fun hu => c625 e tri schur v27 hu v18
  have v38 : (¬ e 11 15) := fun hu => c626 e tri schur hu v28 v18
  have v39 : (¬ e 7 13) := fun hu => c637 e tri schur h1 v28 hu
  have v40 : (¬ e 11 12) := fun hu => c761 e tri schur h2 v27 hu
  have v41 : (e 3 18) := Classical.byContradiction (fun hu => c857 e tri schur v33 hu h16)
  have v42 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur v6 hu v38)
  have v43 : (e 6 13) := Classical.byContradiction (fun hu => c876 e tri schur v29 hu v39)
  have v44 : (e 6 9) := Classical.byContradiction (fun hu => c878 e tri schur hu v3 v35)
  have v45 : (¬ e 4 6) := fun hu => c904 e tri schur v43 v44 hu v12
  have v46 : (e 2 5) := Classical.byContradiction (fun hu => c905 e tri schur v22 v31 hu v10)
  have v47 : (¬ e 2 6) := fun hu => c916 e tri schur v7 hu v46
  have v48 : (¬ e 3 10) := fun hu => c963 e tri schur v41 hu v26
  have v49 : (¬ e 3 13) := fun hu => c1136 e tri schur h0 h1 hu v33
  exact c1144 e tri schur h0 h1 h3 v48 v33

theorem c1223 : (e 13 18) → (e 13 15) → (e 10 18) → (e 7 9) → (e 4 12) → (e 4 9) → (e 2 8) → (¬ e 2 9) → (¬ e 4 11) → (¬ e 8 15) → (¬ e 15 18) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10
  have v0 : (¬ e 4 7) := fun hu => c387 e tri schur h3 h5 hu
  have v1 : (¬ e 9 12) := fun hu => c409 e tri schur hu h4 h5
  have v2 : (¬ e 10 13) := fun hu => c749 e tri schur h0 h2 hu
  have v3 : (e 7 11) := Classical.byContradiction (fun hu => c860 e tri schur v0 h8 hu)
  have v4 : (¬ e 3 9) := fun hu => c894 e tri schur h3 h5 hu
  have v5 : (¬ e 2 7) := fun hu => c977 e tri schur v3 h3 hu
  have v6 : (¬ e 9 11) := fun hu => c607 e tri schur hu v3 h3
  have v7 : (e 2 11) := Classical.byContradiction (fun hu => c838 e tri schur h7 hu v6)
  have v8 : (e 3 12) := Classical.byContradiction (fun hu => c851 e tri schur v4 hu v1)
  have v9 : (¬ e 8 11) := fun hu => c203 e tri schur hu v7 h6
  have v10 : (¬ e 3 4) := fun hu => c263 e tri schur h4 v8 hu
  have v11 : (e 3 7) := Classical.byContradiction (fun hu => c846 e tri schur v10 hu v0)
  have v12 : (¬ e 7 12) := fun hu => c1094 e tri schur hu h3 v11 v4
  have v13 : (¬ e 7 8) := fun hu => c1121 e tri schur v3 hu v11
  have v14 : (¬ e 3 11) := fun hu => c298 e tri schur v3 hu v11
  have v15 : (e 3 8) := Classical.byContradiction (fun hu => c850 e tri schur hu v14 v9)
  have v16 : (e 7 15) := Classical.byContradiction (fun hu => c882 e tri schur v13 hu h9)
  have v17 : (¬ e 6 7) := fun hu => c1037 e tri schur v16 h3 hu
  have v18 : (¬ e 2 3) := fun hu => c140 e tri schur v15 h6 hu
  have v19 : (¬ e 3 15) := fun hu => c302 e tri schur v16 hu v11
  have v20 : (¬ e 8 12) := fun hu => c309 e tri schur hu v8 v15
  have v21 : (¬ e 9 15) := fun hu => c611 e tri schur hu v16 h3
  have v22 : (¬ e 11 15) := fun hu => c626 e tri schur hu v16 v3
  have v23 : (¬ e 7 13) := fun hu => c637 e tri schur h1 v16 hu
  have v24 : (e 3 18) := Classical.byContradiction (fun hu => c857 e tri schur v19 hu h10)
  have v25 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur h8 hu v22)
  have v26 : (e 6 13) := Classical.byContradiction (fun hu => c876 e tri schur v17 hu v23)
  have v27 : (e 2 5) := Classical.byContradiction (fun hu => c905 e tri schur v11 v18 hu v5)
  have v28 : (¬ e 2 6) := fun hu => c916 e tri schur v7 hu v27
  have v29 : (¬ e 3 10) := fun hu => c963 e tri schur v24 hu v15
  have v30 : (¬ e 3 13) := fun hu => c1136 e tri schur h0 h1 hu v19
  exact c1144 e tri schur h0 h1 h2 v29 v19

theorem c1224 : (e 13 18) → (e 13 15) → (e 10 18) → (¬ e 3 15) → (¬ e 15 18) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 10 13) := fun hu => c749 e tri schur h0 h2 hu
  have v1 : (e 3 18) := Classical.byContradiction (fun hu => c857 e tri schur h3 hu h4)
  have v2 : (¬ e 3 13) := fun hu => c1136 e tri schur h0 h1 hu h3
  have v3 : (e 3 10) := Classical.byContradiction (fun hu => c1144 e tri schur h0 h1 h2 hu h3)
  exact c332 e tri schur h2 v1 v3

theorem c1225 : (e 13 15) → (e 7 15) → (e 5 15) → (e 3 15) → (e 2 4) → (¬ e 2 9) → (¬ e 2 13) → (¬ e 4 13) → (¬ e 5 6) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8
  have v0 : (¬ e 3 5) := fun hu => c279 e tri schur h2 h3 hu
  have v1 : (¬ e 3 7) := fun hu => c302 e tri schur h1 h3 hu
  have v2 : (¬ e 3 13) := fun hu => c347 e tri schur h0 h3 hu
  have v3 : (¬ e 5 7) := fun hu => c471 e tri schur h1 h2 hu
  have v4 : (¬ e 5 13) := fun hu => c516 e tri schur h0 h2 hu
  have v5 : (¬ e 7 13) := fun hu => c637 e tri schur h0 h1 hu
  have v6 : (¬ e 8 15) := fun hu => c1013 e tri schur hu h2 h3
  have v7 : (¬ e 4 15) := fun hu => c1023 e tri schur h1 hu h3
  have v8 : (¬ e 4 11) := fun hu => c1218 e tri schur hu h4 h5 h6
  have v9 : (e 11 15) := Classical.byContradiction (fun hu => c864 e tri schur v8 v7 hu)
  have v10 : (¬ e 3 11) := fun hu => c336 e tri schur v9 h3 hu
  have v11 : (¬ e 5 11) := fun hu => c505 e tri schur v9 h2 hu
  have v12 : (¬ e 7 11) := fun hu => c626 e tri schur v9 h1 hu
  have v13 : (¬ e 11 13) := fun hu => c767 e tri schur h0 v9 hu
  have v14 : (e 2 11) := Classical.byContradiction (fun hu => c840 e tri schur hu h6 v13)
  have v15 : (e 4 7) := Classical.byContradiction (fun hu => c860 e tri schur hu v8 v12)
  have v16 : (e 6 11) := Classical.byContradiction (fun hu => c868 e tri schur h8 v11 hu)
  have v17 : (¬ e 2 15) := fun hu => c1177 e tri schur hu v14 h4
  have v18 : (¬ e 2 7) := fun hu => c1185 e tri schur v14 hu h4
  have v19 : (¬ e 2 6) := fun hu => c182 e tri schur v16 v14 hu
  have v20 : (¬ e 6 15) := fun hu => c571 e tri schur v9 hu v16
  have v21 : (e 2 5) := Classical.byContradiction (fun hu => c834 e tri schur hu v18 v3)
  have v22 : (e 7 9) := Classical.byContradiction (fun hu => c836 e tri schur v18 h5 hu)
  have v23 : (¬ e 6 7) := fun hu => c1037 e tri schur h1 v22 hu
  have v24 : (¬ e 2 16) := fun hu => c1065 e tri schur hu v14 v21 v11
  have v25 : (¬ e 5 17) := fun hu => c1129 e tri schur hu h2 v21 v17
  have v26 : (e 3 8) := Classical.byContradiction (fun hu => c1181 e tri schur v14 v19 v0 hu v10 v11)
  have v27 : (¬ e 9 13) := fun hu => c1221 e tri schur h0 hu v22 v20
  have v28 : (¬ e 4 5) := fun hu => c151 e tri schur hu v21 h4
  have v29 : (¬ e 4 9) := fun hu => c387 e tri schur v22 hu v15
  have v30 : (¬ e 9 15) := fun hu => c611 e tri schur hu h1 v22
  have v31 : (e 5 9) := Classical.byContradiction (fun hu => c858 e tri schur v28 v29 hu)
  exact c862 e tri schur v29 h7 v27

theorem c1226 : (e 11 15) → (e 6 15) → (e 5 15) → (¬ e 5 6) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 5 11) := fun hu => c505 e tri schur h0 h2 hu
  have v1 : (¬ e 6 11) := fun hu => c571 e tri schur h0 h1 hu
  exact c868 e tri schur h3 v0 v1

theorem c1227 : (e 13 17) → (e 9 13) → (e 8 13) → (¬ e 8 9) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 8 17) := fun hu => c684 e tri schur h0 hu h2
  have v1 : (¬ e 9 17) := fun hu => c720 e tri schur h0 hu h1
  exact c886 e tri schur h3 v0 v1

end Jsp746.Certificate
