/- Generated by scripts/generate_refutation.py from our own SAT trace.
Every statement below is proved with ordinary kernel-checked proof terms. -/
import Jsp746.Certificate.Steps04

namespace Jsp746.Certificate
variable (e : ℕ → ℕ → Prop)
variable (tri : TriangleCondition e) (schur : SchurCondition e)
include tri schur

theorem c1399 : (e 1 9) → (e 1 5) → (e 1 4) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 5) := fun hu => c31 e tri schur hu h1 h2
  have v1 : (¬ e 4 9) := fun hu => c35 e tri schur hu h0 h2
  have v2 : (¬ e 5 9) := fun hu => c48 e tri schur hu h0 h1
  exact c858 e tri schur v0 v1 v2

theorem c1400 : (e 11 12) → (e 4 15) → (e 2 10) → (e 1 9) → (e 1 4) → (¬ e 1 12) → (¬ e 2 3) → (¬ e 2 11) → (¬ e 2 12) → (¬ e 4 13) → (¬ e 12 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10
  have v0 : (¬ e 4 9) := fun hu => c35 e tri schur hu h3 h4
  have v1 : (¬ e 1 15) := fun hu => c41 e tri schur h1 hu h4
  have v2 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v0 h9 hu)
  have v3 : (¬ e 1 13) := fun hu => c1384 e tri schur hu h3 h4 h9
  have v4 : (¬ e 1 5) := fun hu => c1399 e tri schur h3 hu h4
  have v5 : (e 12 13) := Classical.byContradiction (fun hu => c826 e tri schur h5 v3 hu)
  have v6 : (e 1 14) := Classical.byContradiction (fun hu => c1359 e tri schur h0 h5 v3 hu h7)
  have v7 : (¬ e 3 13) := fun hu => c1392 e tri schur v5 v2 hu
  have v8 : (¬ e 4 14) := fun hu => c40 e tri schur hu v6 h4
  have v9 : (¬ e 9 14) := fun hu => c95 e tri schur hu v6 h3
  have v10 : (¬ e 9 12) := fun hu => c711 e tri schur v5 v2 hu
  have v11 : (¬ e 11 13) := fun hu => c760 e tri schur v5 hu h0
  have v12 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur h7 hu v11)
  have v13 : (¬ e 1 10) := fun hu => c1343 e tri schur v6 hu h4
  have v14 : (¬ e 2 9) := fun hu => c214 e tri schur v2 v12 hu
  have v15 : (¬ e 10 13) := fun hu => c222 e tri schur hu v12 h2
  have v16 : (e 9 11) := Classical.byContradiction (fun hu => c838 e tri schur v14 h7 hu)
  have v17 : (e 3 10) := Classical.byContradiction (fun hu => c852 e tri schur hu v7 v15)
  have v18 : (¬ e 3 11) := fun hu => c1361 e tri schur h0 v16 hu
  have v19 : (e 3 12) := Classical.byContradiction (fun hu => c1395 e tri schur h0 h1 v17 h2 v6 h3 h4 h6 h8 v18 hu v10 h10)
  have v20 : (¬ e 12 14) := fun hu => c1396 e tri schur hu h0 v19 v18
  have v21 : (¬ e 1 11) := fun hu => c92 e tri schur v16 hu h3
  have v22 : (¬ e 10 12) := fun hu => c326 e tri schur hu v19 v17
  have v23 : (e 10 11) := Classical.byContradiction (fun hu => c824 e tri schur v13 v21 hu)
  have v24 : (e 2 14) := Classical.byContradiction (fun hu => c841 e tri schur h8 hu v20)
  have v25 : (¬ e 1 2) := fun hu => c11 e tri schur v24 v6 hu
  have v26 : (¬ e 10 14) := fun hu => c223 e tri schur hu v24 h2
  have v27 : (¬ e 13 14) := fun hu => c241 e tri schur hu v24 v12
  have v28 : (¬ e 9 10) := fun hu => c696 e tri schur v23 v16 hu
  have v29 : (e 1 3) := Classical.byContradiction (fun hu => c816 e tri schur v25 hu h6)
  have v30 : (e 4 10) := Classical.byContradiction (fun hu => c863 e tri schur hu v8 v26)
  have v31 : (¬ e 3 4) := fun hu => c16 e tri schur hu h4 v29
  have v32 : (¬ e 3 9) := fun hu => c21 e tri schur hu h3 v29
  have v33 : (¬ e 3 14) := fun hu => c26 e tri schur hu v6 v29
  have v34 : (¬ e 2 4) := fun hu => c156 e tri schur v30 h2 hu
  have v35 : (¬ e 4 11) := fun hu => c416 e tri schur v23 hu v30
  have v36 : (¬ e 10 15) := fun hu => c420 e tri schur hu h1 v30
  have v37 : (e 11 14) := Classical.byContradiction (fun hu => c853 e tri schur v18 v33 hu)
  have v38 : (¬ e 5 6) := fun hu => c1398 e tri schur hu h1 v30 v17 v24 h2 h6 v32 v0 v9
  have v39 : (e 1 6) := Classical.byContradiction (fun hu => c819 e tri schur v4 hu v38)
  have v40 : (¬ e 3 6) := fun hu => c18 e tri schur hu v39 v29
  have v41 : (¬ e 4 6) := fun hu => c32 e tri schur hu v39 h4
  have v42 : (¬ e 6 9) := fun hu => c60 e tri schur hu h3 v39
  have v43 : (¬ e 6 14) := fun hu => c65 e tri schur hu v6 v39
  have v44 : (e 2 6) := Classical.byContradiction (fun hu => c833 e tri schur v34 hu v41)
  exact c848 e tri schur v40 v32 v42

theorem c1401 : (e 11 12) → (e 10 11) → (e 4 15) → (e 1 4) → (¬ e 1 10) → (¬ e 1 12) → (¬ e 2 11) → (¬ e 2 12) → (¬ e 4 13) → (¬ e 12 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9
  have v0 : (¬ e 1 15) := fun hu => c41 e tri schur h2 hu h3
  have v1 : (¬ e 10 12) := fun hu => c732 e tri schur h0 hu h1
  have v2 : (e 2 10) := Classical.byContradiction (fun hu => c839 e tri schur hu h7 v1)
  have v3 : (¬ e 2 3) := fun hu => c1391 e tri schur h0 h1 hu h3 h4 h5 h6 h8
  have v4 : (¬ e 1 9) := fun hu => c1400 e tri schur h0 h2 v2 hu h3 h5 v3 h6 h7 h8 h9
  have v5 : (e 9 10) := Classical.byContradiction (fun hu => c823 e tri schur v4 h4 hu)
  have v6 : (¬ e 2 9) := fun hu => c211 e tri schur v5 v2 hu
  have v7 : (¬ e 9 11) := fun hu => c696 e tri schur h1 hu v5
  exact c838 e tri schur v6 h6 v7

theorem c1402 : (e 9 10) → (e 2 9) → (e 1 13) → (e 1 6) → (e 1 4) → (¬ e 2 3) → (¬ e 2 4) → (¬ e 10 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 4 6) := fun hu => c32 e tri schur hu h3 h4
  have v1 : (¬ e 4 13) := fun hu => c39 e tri schur hu h2 h4
  have v2 : (¬ e 6 13) := fun hu => c64 e tri schur hu h2 h3
  have v3 : (¬ e 2 10) := fun hu => c211 e tri schur h0 hu h1
  have v4 : (e 2 6) := Classical.byContradiction (fun hu => c833 e tri schur h6 hu v0)
  have v5 : (¬ e 1 10) := fun hu => c1312 e tri schur hu h3 h4 v0
  have v6 : (¬ e 1 9) := fun hu => c1384 e tri schur h2 hu h4 v1
  have v7 : (¬ e 1 2) := fun hu => c1394 e tri schur h3 h4 hu
  have v8 : (¬ e 6 9) := fun hu => c180 e tri schur hu h1 v4
  have v9 : (e 1 3) := Classical.byContradiction (fun hu => c816 e tri schur v7 hu h5)
  have v10 : (¬ e 3 4) := fun hu => c16 e tri schur hu h4 v9
  have v11 : (¬ e 3 6) := fun hu => c18 e tri schur hu h3 v9
  have v12 : (¬ e 3 13) := fun hu => c25 e tri schur hu h2 v9
  have v13 : (e 3 9) := Classical.byContradiction (fun hu => c848 e tri schur v11 hu v8)
  have v14 : (e 3 10) := Classical.byContradiction (fun hu => c852 e tri schur hu v12 h7)
  exact c316 e tri schur h0 v14 v13

theorem c1403 : (e 11 13) → (e 9 10) → (e 1 2) → (¬ e 1 8) → (¬ e 1 9) → (¬ e 2 10) → (¬ e 2 11) → (¬ e 4 11) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8
  have v0 : (e 8 9) := Classical.byContradiction (fun hu => c822 e tri schur h3 h4 hu)
  have v1 : (¬ e 2 8) := fun hu => c1377 e tri schur h0 hu h2 h3 h6 h7 h8
  have v2 : (¬ e 8 10) := fun hu => c651 e tri schur h1 hu v0
  exact c837 e tri schur v1 h5 v2

theorem c1404 : (e 11 12) → (e 9 10) → (e 2 9) → (e 1 4) → (¬ e 1 9) → (¬ e 1 12) → (¬ e 2 3) → (¬ e 2 4) → (¬ e 2 11) → (¬ e 4 9) → (¬ e 4 11) → (¬ e 4 13) → (¬ e 5 6) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12
  have v0 : (¬ e 2 10) := fun hu => c211 e tri schur h1 hu h2
  have v1 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur h9 h11 hu)
  have v2 : (¬ e 2 13) := fun hu => c214 e tri schur v1 hu h2
  have v3 : (¬ e 10 13) := fun hu => c698 e tri schur hu v1 h1
  have v4 : (e 11 13) := Classical.byContradiction (fun hu => c840 e tri schur h8 v2 hu)
  have v5 : (¬ e 9 11) := fun hu => c705 e tri schur v4 v1 hu
  have v6 : (¬ e 12 13) := fun hu => c760 e tri schur hu v4 h0
  have v7 : (e 1 13) := Classical.byContradiction (fun hu => c826 e tri schur h5 hu v6)
  have v8 : (¬ e 1 6) := fun hu => c1402 e tri schur h1 h2 v7 hu h3 h6 h7 v3
  have v9 : (¬ e 1 11) := fun hu => c109 e tri schur v4 v7 hu
  have v10 : (e 1 5) := Classical.byContradiction (fun hu => c819 e tri schur hu v8 h12)
  have v11 : (¬ e 4 5) := fun hu => c31 e tri schur hu v10 h3
  have v12 : (¬ e 5 13) := fun hu => c52 e tri schur hu v7 v10
  have v13 : (e 5 9) := Classical.byContradiction (fun hu => c858 e tri schur v11 h9 hu)
  have v14 : (¬ e 7 9) := fun hu => c899 e tri schur hu v13 h2
  have v15 : (¬ e 2 5) := fun hu => c168 e tri schur v13 h2 hu
  have v16 : (¬ e 5 10) := fun hu => c485 e tri schur h1 hu v13
  have v17 : (e 3 5) := Classical.byContradiction (fun hu => c832 e tri schur h6 v15 hu)
  have v18 : (¬ e 1 3) := fun hu => c17 e tri schur v17 v10 hu
  have v19 : (¬ e 3 9) := fun hu => c273 e tri schur v13 hu v17
  have v20 : (e 1 2) := Classical.byContradiction (fun hu => c816 e tri schur hu v18 h6)
  have v21 : (e 1 8) := Classical.byContradiction (fun hu => c1403 e tri schur v4 h1 v20 hu h4 v0 h8 h10 h11)
  have v22 : (¬ e 2 8) := fun hu => c5 e tri schur hu v21 v20
  have v23 : (¬ e 4 8) := fun hu => c34 e tri schur hu v21 h3
  have v24 : (¬ e 5 8) := fun hu => c47 e tri schur hu v21 v10
  have v25 : (¬ e 8 13) := fun hu => c85 e tri schur hu v7 v21
  have v26 : (e 8 10) := Classical.byContradiction (fun hu => c837 e tri schur v22 v0 hu)
  exact c870 e tri schur v24 v12 v25

theorem c1405 : (e 11 13) → (e 11 12) → (e 9 10) → (e 5 11) → (e 1 5) → (e 1 2) → (¬ e 1 9) → (¬ e 1 12) → (¬ e 2 10) → (¬ e 2 11) → (¬ e 4 11) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11
  have v0 : (¬ e 2 5) := fun hu => c2 e tri schur hu h4 h5
  have v1 : (¬ e 1 11) := fun hu => c50 e tri schur h3 hu h4
  have v2 : (¬ e 5 12) := fun hu => c502 e tri schur h1 hu h3
  have v3 : (¬ e 5 13) := fun hu => c503 e tri schur h0 hu h3
  have v4 : (¬ e 12 13) := fun hu => c760 e tri schur hu h0 h1
  have v5 : (e 1 13) := Classical.byContradiction (fun hu => c826 e tri schur h7 hu v4)
  have v6 : (e 1 8) := Classical.byContradiction (fun hu => c1403 e tri schur h0 h2 h5 hu h6 h8 h9 h10 h11)
  have v7 : (¬ e 2 8) := fun hu => c5 e tri schur hu v6 h5
  have v8 : (¬ e 2 13) := fun hu => c10 e tri schur hu v5 h5
  have v9 : (¬ e 5 8) := fun hu => c47 e tri schur hu v6 h4
  have v10 : (¬ e 8 13) := fun hu => c85 e tri schur hu v5 v6
  have v11 : (e 8 10) := Classical.byContradiction (fun hu => c837 e tri schur v7 h8 hu)
  exact c870 e tri schur v9 v3 v10

theorem c1406 : (e 11 12) → (e 9 10) → (e 5 11) → (e 2 12) → (e 1 4) → (e 1 2) → (¬ e 1 9) → (¬ e 1 12) → (¬ e 2 10) → (¬ e 2 11) → (¬ e 4 11) → (¬ e 4 13) → (¬ e 5 6) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12
  have v0 : (¬ e 2 4) := fun hu => c1 e tri schur hu h4 h5
  have v1 : (¬ e 5 12) := fun hu => c502 e tri schur h0 hu h2
  have v2 : (¬ e 1 6) := fun hu => c1394 e tri schur hu h4 h5
  have v3 : (e 1 5) := Classical.byContradiction (fun hu => c819 e tri schur hu v2 h12)
  have v4 : (¬ e 11 13) := fun hu => c1405 e tri schur hu h0 h1 h2 v3 h5 h6 h7 h8 h9 h10 h11
  have v5 : (¬ e 2 5) := fun hu => c2 e tri schur hu v3 h5
  have v6 : (¬ e 4 5) := fun hu => c31 e tri schur hu v3 h4
  have v7 : (¬ e 1 11) := fun hu => c50 e tri schur h2 hu v3
  have v8 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur h9 hu v4)
  have v9 : (¬ e 1 13) := fun hu => c10 e tri schur v8 hu h5
  have v10 : (¬ e 12 13) := fun hu => c235 e tri schur hu v8 h3
  exact c826 e tri schur h7 v9 v10

theorem c1407 : (e 11 12) → (e 6 15) → (e 5 15) → (e 2 12) → (e 2 5) → (¬ e 2 15) → (¬ e 5 12) → (¬ e 6 11) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 2 11) := fun hu => c228 e tri schur h0 h3 hu
  have v1 : (¬ e 5 6) := fun hu => c460 e tri schur h1 h2 hu
  have v2 : (e 5 11) := Classical.byContradiction (fun hu => c868 e tri schur v1 hu h7)
  have v3 : (¬ e 5 17) := fun hu => c1129 e tri schur hu h2 h4 h5
  have v4 : (¬ e 11 15) := fun hu => c1226 e tri schur hu h1 h2 v1
  have v5 : (e 15 17) := Classical.byContradiction (fun hu => c1230 e tri schur h2 h3 h4 hu)
  have v6 : (¬ e 2 17) := fun hu => c1231 e tri schur hu h3 h4
  have v7 : (¬ e 5 9) := fun hu => c1322 e tri schur v2 hu h4
  have v8 : (¬ e 6 17) := fun hu => c591 e tri schur v5 hu h1
  have v9 : (e 12 17) := Classical.byContradiction (fun hu => c874 e tri schur h6 v3 hu)
  have v10 : (e 11 17) := Classical.byContradiction (fun hu => c880 e tri schur h7 v8 hu)
  have v11 : (¬ e 4 5) := fun hu => c1088 e tri schur h2 v2 hu v4
  exact c764 e tri schur v9 v10 h0

theorem c1408 : (e 11 12) → (e 10 11) → (e 9 10) → (e 4 15) → (e 2 12) → (e 1 4) → (¬ e 1 9) → (¬ e 1 12) → (¬ e 2 3) → (¬ e 2 4) → (¬ e 2 11) → (¬ e 4 11) → (¬ e 4 13) → (¬ e 5 6) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13
  have v0 : (¬ e 1 15) := fun hu => c41 e tri schur h3 hu h5
  have v1 : (¬ e 9 11) := fun hu => c696 e tri schur h1 hu h2
  have v2 : (¬ e 10 12) := fun hu => c732 e tri schur h0 hu h1
  have v3 : (e 2 9) := Classical.byContradiction (fun hu => c838 e tri schur hu h10 v1)
  have v4 : (e 4 9) := Classical.byContradiction (fun hu => c1404 e tri schur h0 h2 v3 h5 h6 h7 h8 h9 h10 hu h11 h12 h13)
  have v5 : (¬ e 2 10) := fun hu => c211 e tri schur h2 hu v3
  have v6 : (¬ e 9 12) := fun hu => c213 e tri schur hu h4 v3
  have v7 : (¬ e 4 10) := fun hu => c407 e tri schur h2 hu v4
  have v8 : (¬ e 9 15) := fun hu => c412 e tri schur hu h3 v4
  have v9 : (¬ e 6 9) := fun hu => c896 e tri schur hu v4 v3
  have v10 : (¬ e 4 6) := fun hu => c1194 e tri schur h3 v4 hu
  have v11 : (e 2 6) := Classical.byContradiction (fun hu => c833 e tri schur h9 hu v10)
  have v12 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur v10 v7 hu)
  have v13 : (e 6 15) := Classical.byContradiction (fun hu => c878 e tri schur v9 hu v8)
  have v14 : (¬ e 6 12) := fun hu => c183 e tri schur hu h4 v11
  have v15 : (¬ e 2 15) := fun hu => c186 e tri schur v13 hu v11
  have v16 : (¬ e 6 11) := fun hu => c560 e tri schur h1 hu v12
  have v17 : (¬ e 10 15) := fun hu => c564 e tri schur hu v13 v12
  have v18 : (e 5 11) := Classical.byContradiction (fun hu => c868 e tri schur h13 hu v16)
  have v19 : (¬ e 1 2) := fun hu => c1406 e tri schur h0 h2 v18 h4 h5 hu h6 h7 v5 h10 h11 h12 h13
  have v20 : (¬ e 5 10) := fun hu => c494 e tri schur h1 v18 hu
  have v21 : (¬ e 5 12) := fun hu => c502 e tri schur h0 hu v18
  have v22 : (e 1 3) := Classical.byContradiction (fun hu => c816 e tri schur v19 hu h8)
  have v23 : (e 5 15) := Classical.byContradiction (fun hu => c872 e tri schur v20 hu v17)
  have v24 : (¬ e 11 15) := fun hu => c1226 e tri schur hu v13 v23 h13
  have v25 : (¬ e 2 5) := fun hu => c1407 e tri schur h0 v13 v23 h4 hu v15 v21 v16
  have v26 : (¬ e 3 4) := fun hu => c16 e tri schur hu h5 v22
  have v27 : (¬ e 4 5) := fun hu => c370 e tri schur v23 h3 hu
  have v28 : (e 3 5) := Classical.byContradiction (fun hu => c832 e tri schur h8 v25 hu)
  have v29 : (¬ e 1 5) := fun hu => c17 e tri schur v28 hu v22
  have v30 : (¬ e 3 11) := fun hu => c275 e tri schur v18 hu v28
  have v31 : (¬ e 3 15) := fun hu => c279 e tri schur v23 hu v28
  have v32 : (e 1 6) := Classical.byContradiction (fun hu => c819 e tri schur v29 hu h13)
  have v33 : (¬ e 1 10) := fun hu => c1312 e tri schur hu v32 h5 v10
  have v34 : (¬ e 3 6) := fun hu => c18 e tri schur hu v32 v22
  have v35 : (e 3 9) := Classical.byContradiction (fun hu => c848 e tri schur v34 hu v9)
  have v36 : (¬ e 7 9) := fun hu => c894 e tri schur hu v4 v35
  have v37 : (¬ e 3 14) := fun hu => c992 e tri schur hu v35 v28
  have v38 : (¬ e 5 9) := fun hu => c273 e tri schur hu v35 v28
  have v39 : (¬ e 3 10) := fun hu => c316 e tri schur h2 hu v35
  have v40 : (e 11 14) := Classical.byContradiction (fun hu => c853 e tri schur v30 v37 hu)
  have v41 : (¬ e 5 14) := fun hu => c504 e tri schur v40 hu v18
  have v42 : (¬ e 10 14) := fun hu => c734 e tri schur v40 hu h1
  have v43 : (¬ e 12 14) := fun hu => c761 e tri schur hu v40 h0
  have v44 : (e 4 14) := Classical.byContradiction (fun hu => c863 e tri schur v7 hu v42)
  have v45 : (e 9 14) := Classical.byContradiction (fun hu => c871 e tri schur v38 v41 hu)
  have v46 : (¬ e 1 14) := fun hu => c40 e tri schur v44 hu h5
  have v47 : (¬ e 2 14) := fun hu => c215 e tri schur v45 hu v3
  exact c411 e tri schur v45 v44 v4

theorem c1409 : (e 5 15) → (e 5 6) → (e 4 15) → (¬ e 5 9) → (¬ e 6 9) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 4 5) := fun hu => c370 e tri schur h0 h2 hu
  have v1 : (¬ e 6 15) := fun hu => c460 e tri schur hu h0 h1
  have v2 : (e 4 9) := Classical.byContradiction (fun hu => c858 e tri schur v0 hu h3)
  have v3 : (e 9 15) := Classical.byContradiction (fun hu => c878 e tri schur h4 v1 hu)
  have v4 : (¬ e 4 6) := fun hu => c1194 e tri schur h2 v2 hu
  exact c412 e tri schur v3 h2 v2

theorem c1410 : (e 4 15) → (e 4 14) → (e 1 4) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 1 14) := fun hu => c40 e tri schur h1 hu h2
  have v1 : (¬ e 1 15) := fun hu => c41 e tri schur h0 hu h2
  have v2 : (¬ e 14 15) := fun hu => c442 e tri schur hu h0 h1
  exact c828 e tri schur v0 v1 v2

theorem c1411 : (e 10 14) → (e 10 11) → (e 9 10) → (e 5 6) → (e 3 5) → (¬ e 3 11) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 3 6) := fun hu => c270 e tri schur h3 hu h4
  have v1 : (¬ e 9 11) := fun hu => c696 e tri schur h1 hu h2
  have v2 : (¬ e 9 14) := fun hu => c699 e tri schur h0 hu h2
  have v3 : (¬ e 11 14) := fun hu => c734 e tri schur hu h0 h1
  have v4 : (e 3 14) := Classical.byContradiction (fun hu => c853 e tri schur h5 hu v3)
  have v5 : (¬ e 3 9) := fun hu => c992 e tri schur v4 hu h4
  have v6 : (¬ e 5 14) := fun hu => c278 e tri schur hu v4 h4
  have v7 : (¬ e 3 10) := fun hu => c328 e tri schur h0 v4 hu
  have v8 : (e 6 9) := Classical.byContradiction (fun hu => c848 e tri schur v0 v5 hu)
  have v9 : (e 5 9) := Classical.byContradiction (fun hu => c871 e tri schur hu v6 v2)
  exact c454 e tri schur v8 v9 h3

theorem c1412 : (e 9 10) → (e 5 6) → (e 4 15) → (e 4 10) → (¬ e 5 10) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 4 9) := fun hu => c407 e tri schur h0 h3 hu
  have v1 : (¬ e 10 15) := fun hu => c420 e tri schur hu h2 h3
  have v2 : (e 5 15) := Classical.byContradiction (fun hu => c872 e tri schur h4 hu v1)
  have v3 : (¬ e 4 5) := fun hu => c986 e tri schur h2 h3 hu h4
  have v4 : (¬ e 6 15) := fun hu => c460 e tri schur hu v2 h1
  have v5 : (e 5 9) := Classical.byContradiction (fun hu => c858 e tri schur v3 v0 hu)
  have v6 : (¬ e 6 9) := fun hu => c454 e tri schur hu v5 h1
  have v7 : (¬ e 9 15) := fun hu => c490 e tri schur hu v2 v5
  exact c878 e tri schur v6 v4 v7

theorem c1414 : (e 5 6) → (e 4 15) → (e 2 9) → (e 2 5) → (¬ e 2 4) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 2 6) := fun hu => c165 e tri schur h0 hu h3
  have v1 : (¬ e 5 9) := fun hu => c168 e tri schur hu h2 h3
  have v2 : (e 4 6) := Classical.byContradiction (fun hu => c833 e tri schur h4 v0 hu)
  have v3 : (¬ e 5 15) := fun hu => c1112 e tri schur hu h1 v2 h2 v1
  have v4 : (¬ e 5 8) := fun hu => c1182 e tri schur hu h0 h3
  have v5 : (¬ e 4 9) := fun hu => c1194 e tri schur h1 hu v2
  have v6 : (¬ e 4 5) := fun hu => c361 e tri schur h0 v2 hu
  have v7 : (¬ e 6 15) := fun hu => c382 e tri schur hu h1 v2
  exact c858 e tri schur v6 v5 v1

theorem c1415 : (e 9 10) → (e 5 6) → (e 2 9) → (¬ e 2 4) → (¬ e 3 6) → (¬ e 4 9) → (¬ e 4 13) → (¬ e 5 9) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 2 10) := fun hu => c211 e tri schur h0 hu h2
  have v1 : (e 4 5) := Classical.byContradiction (fun hu => c858 e tri schur hu h5 h7)
  have v2 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur h5 h6 hu)
  have v3 : (¬ e 2 13) := fun hu => c214 e tri schur v2 hu h2
  have v4 : (¬ e 4 6) := fun hu => c361 e tri schur h1 hu v1
  have v5 : (¬ e 10 13) := fun hu => c698 e tri schur hu v2 h0
  have v6 : (e 2 6) := Classical.byContradiction (fun hu => c833 e tri schur h3 hu v4)
  have v7 : (¬ e 2 3) := fun hu => c1010 e tri schur h2 v6 hu
  have v8 : (¬ e 2 5) := fun hu => c165 e tri schur h1 v6 hu
  have v9 : (¬ e 6 9) := fun hu => c180 e tri schur hu h2 v6
  have v10 : (e 3 5) := Classical.byContradiction (fun hu => c832 e tri schur v7 v8 hu)
  have v11 : (e 3 9) := Classical.byContradiction (fun hu => c848 e tri schur h4 hu v9)
  have v12 : (¬ e 3 14) := fun hu => c992 e tri schur hu v11 v10
  have v13 : (¬ e 3 4) := fun hu => c256 e tri schur v1 v10 hu
  have v14 : (¬ e 3 10) := fun hu => c316 e tri schur h0 hu v11
  have v15 : (¬ e 3 13) := fun hu => c319 e tri schur v2 hu v11
  exact c852 e tri schur v14 v15 v5

theorem c1416 : (e 9 10) → (e 5 6) → (e 4 15) → (e 2 9) → (¬ e 2 4) → (¬ e 3 6) → (¬ e 4 13) → (¬ e 5 9) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 2 10) := fun hu => c211 e tri schur h0 hu h3
  have v1 : (¬ e 2 5) := fun hu => c1414 e tri schur h1 h2 h3 hu h4
  have v2 : (e 4 9) := Classical.byContradiction (fun hu => c1415 e tri schur h0 h1 h3 h4 h5 hu h6 h7)
  have v3 : (¬ e 4 10) := fun hu => c407 e tri schur h0 hu v2
  have v4 : (¬ e 9 15) := fun hu => c412 e tri schur hu h2 v2
  have v5 : (¬ e 6 9) := fun hu => c896 e tri schur hu v2 h3
  have v6 : (¬ e 4 6) := fun hu => c1194 e tri schur h2 v2 hu
  have v7 : (¬ e 5 15) := fun hu => c1409 e tri schur hu h1 h2 h7 v5
  have v8 : (e 2 6) := Classical.byContradiction (fun hu => c833 e tri schur h4 hu v6)
  have v9 : (e 3 9) := Classical.byContradiction (fun hu => c848 e tri schur h5 hu v5)
  have v10 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur v6 v3 hu)
  have v11 : (e 6 15) := Classical.byContradiction (fun hu => c878 e tri schur v5 hu v4)
  have v12 : (¬ e 7 9) := fun hu => c894 e tri schur hu v2 v9
  have v13 : (¬ e 2 3) := fun hu => c1010 e tri schur h3 v8 hu
  have v14 : (¬ e 2 15) := fun hu => c186 e tri schur v11 hu v8
  have v15 : (¬ e 3 4) := fun hu => c260 e tri schur v2 v9 hu
  have v16 : (¬ e 3 10) := fun hu => c316 e tri schur h0 hu v9
  have v17 : (¬ e 5 10) := fun hu => c455 e tri schur v10 hu h1
  have v18 : (¬ e 10 15) := fun hu => c564 e tri schur hu v11 v10
  have v19 : (e 3 5) := Classical.byContradiction (fun hu => c832 e tri schur v13 v1 hu)
  exact c872 e tri schur v17 v7 v18

theorem c1417 : (e 11 12) → (e 10 11) → (e 4 15) → (e 2 12) → (e 1 4) → (¬ e 1 9) → (¬ e 1 10) → (¬ e 1 12) → (¬ e 2 4) → (¬ e 2 11) → (¬ e 4 11) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11
  have v0 : (¬ e 1 15) := fun hu => c41 e tri schur h2 hu h4
  have v1 : (¬ e 10 12) := fun hu => c732 e tri schur h0 hu h1
  have v2 : (e 9 10) := Classical.byContradiction (fun hu => c823 e tri schur h5 h6 hu)
  have v3 : (¬ e 2 3) := fun hu => c1390 e tri schur h1 v2 hu h9 v1
  have v4 : (e 5 6) := Classical.byContradiction (fun hu => c1408 e tri schur h0 h1 v2 h2 h3 h4 h5 h7 v3 h8 h9 h10 h11 hu)
  have v5 : (¬ e 4 14) := fun hu => c1410 e tri schur h2 hu h4
  have v6 : (¬ e 9 11) := fun hu => c696 e tri schur h1 hu v2
  have v7 : (e 2 9) := Classical.byContradiction (fun hu => c838 e tri schur hu h9 v6)
  have v8 : (¬ e 2 5) := fun hu => c1414 e tri schur v4 h2 v7 hu h8
  have v9 : (¬ e 2 10) := fun hu => c211 e tri schur v2 hu v7
  have v10 : (¬ e 9 12) := fun hu => c213 e tri schur hu h3 v7
  have v11 : (e 3 5) := Classical.byContradiction (fun hu => c832 e tri schur v3 v8 hu)
  have v12 : (¬ e 3 6) := fun hu => c270 e tri schur v4 hu v11
  have v13 : (e 5 9) := Classical.byContradiction (fun hu => c1416 e tri schur v2 v4 h2 v7 h8 v12 h11 hu)
  have v14 : (¬ e 3 9) := fun hu => c273 e tri schur v13 hu v11
  have v15 : (¬ e 6 9) := fun hu => c454 e tri schur hu v13 v4
  have v16 : (¬ e 5 10) := fun hu => c485 e tri schur v2 hu v13
  exact c848 e tri schur v12 v14 v15

theorem c1418 : (e 11 12) → (e 10 11) → (e 4 15) → (e 2 12) → (e 1 4) → (¬ e 1 10) → (¬ e 1 12) → (¬ e 2 4) → (¬ e 2 11) → (¬ e 4 11) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10
  have v0 : (¬ e 1 15) := fun hu => c41 e tri schur h2 hu h4
  have v1 : (¬ e 10 12) := fun hu => c732 e tri schur h0 hu h1
  have v2 : (¬ e 2 3) := fun hu => c1391 e tri schur h0 h1 hu h4 h5 h6 h8 h10
  have v3 : (¬ e 4 14) := fun hu => c1410 e tri schur h2 hu h4
  have v4 : (e 1 9) := Classical.byContradiction (fun hu => c1417 e tri schur h0 h1 h2 h3 h4 hu h5 h6 h7 h8 h9 h10)
  have v5 : (¬ e 4 9) := fun hu => c35 e tri schur hu v4 h4
  have v6 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v5 h10 hu)
  have v7 : (¬ e 1 13) := fun hu => c1384 e tri schur hu v4 h4 h10
  have v8 : (¬ e 1 5) := fun hu => c1399 e tri schur v4 hu h4
  have v9 : (e 12 13) := Classical.byContradiction (fun hu => c826 e tri schur h6 v7 hu)
  have v10 : (e 1 14) := Classical.byContradiction (fun hu => c1359 e tri schur h0 h6 v7 hu h8)
  have v11 : (¬ e 3 13) := fun hu => c1392 e tri schur v9 v6 hu
  have v12 : (¬ e 9 14) := fun hu => c95 e tri schur hu v10 v4
  have v13 : (¬ e 2 13) := fun hu => c235 e tri schur v9 hu h3
  have v14 : (¬ e 9 12) := fun hu => c711 e tri schur v9 v6 hu
  have v15 : (¬ e 11 13) := fun hu => c760 e tri schur v9 hu h0
  exact c840 e tri schur h8 v13 v15

theorem c1419 : (e 4 15) → (e 4 12) → (e 1 4) → (¬ e 1 11) → (¬ e 1 12) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 1 15) := fun hu => c41 e tri schur h0 hu h2
  have v1 : (¬ e 12 15) := fun hu => c433 e tri schur hu h0 h1
  have v2 : (e 11 12) := Classical.byContradiction (fun hu => c825 e tri schur h3 h4 hu)
  have v3 : (¬ e 3 4) := fun hu => c1188 e tri schur h0 h1 hu
  have v4 : (¬ e 4 13) := fun hu => c1260 e tri schur hu h1 h2
  have v5 : (¬ e 4 11) := fun hu => c1335 e tri schur h1 hu h2 h4
  have v6 : (¬ e 2 11) := fun hu => c1358 e tri schur h0 h1 hu h2 h3 h4
  have v7 : (¬ e 1 10) := fun hu => c1389 e tri schur h0 h1 hu h2 h3 h4
  have v8 : (¬ e 4 14) := fun hu => c1410 e tri schur h0 hu h2
  have v9 : (e 10 11) := Classical.byContradiction (fun hu => c824 e tri schur v7 h3 hu)
  have v10 : (¬ e 2 3) := fun hu => c1391 e tri schur v2 v9 hu h2 v7 h4 v6 v4
  have v11 : (e 2 12) := Classical.byContradiction (fun hu => c1401 e tri schur v2 v9 h0 h2 v7 h4 v6 hu v4 v1)
  have v12 : (e 2 4) := Classical.byContradiction (fun hu => c1418 e tri schur v2 v9 h0 v11 h2 v7 h4 hu v6 v5 v4)
  have v13 : (¬ e 1 2) := fun hu => c1 e tri schur v12 h2 hu
  exact c158 e tri schur h1 v11 v12

theorem c1420 : (e 11 12) → (e 10 11) → (e 4 15) → (e 2 12) → (e 1 11) → (e 1 4) → (¬ e 1 12) → (¬ e 2 4) → (¬ e 2 11) → (¬ e 4 11) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10
  have v0 : (¬ e 1 15) := fun hu => c41 e tri schur h2 hu h5
  have v1 : (¬ e 1 10) := fun hu => c100 e tri schur h1 h4 hu
  have v2 : (¬ e 10 12) := fun hu => c732 e tri schur h0 hu h1
  have v3 : (¬ e 2 3) := fun hu => c1391 e tri schur h0 h1 hu h5 v1 h6 h8 h10
  have v4 : (¬ e 4 14) := fun hu => c1410 e tri schur h2 hu h5
  exact c1418 e tri schur h0 h1 h2 h3 h5 v1 h6 h7 h8 h9 h10

theorem c1421 : (e 11 12) → (e 1 11) → (e 1 9) → (e 1 4) → (¬ e 1 12) → (¬ e 2 11) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 4 9) := fun hu => c35 e tri schur hu h2 h3
  have v1 : (¬ e 4 11) := fun hu => c37 e tri schur hu h1 h3
  have v2 : (¬ e 9 11) := fun hu => c92 e tri schur hu h1 h2
  have v3 : (e 2 9) := Classical.byContradiction (fun hu => c838 e tri schur hu h5 v2)
  have v4 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v0 h6 hu)
  have v5 : (¬ e 1 13) := fun hu => c1384 e tri schur hu h2 h3 h6
  have v6 : (¬ e 1 5) := fun hu => c1399 e tri schur h2 hu h3
  have v7 : (¬ e 1 2) := fun hu => c6 e tri schur v3 h2 hu
  have v8 : (¬ e 2 13) := fun hu => c214 e tri schur v4 hu v3
  have v9 : (e 12 13) := Classical.byContradiction (fun hu => c826 e tri schur h4 v5 hu)
  have v10 : (e 11 13) := Classical.byContradiction (fun hu => c840 e tri schur h5 v8 hu)
  have v11 : (e 1 14) := Classical.byContradiction (fun hu => c1359 e tri schur h0 h4 v5 hu h5)
  have v12 : (¬ e 3 13) := fun hu => c1392 e tri schur v9 v4 hu
  have v13 : (¬ e 4 14) := fun hu => c40 e tri schur hu v11 h3
  have v14 : (¬ e 9 14) := fun hu => c95 e tri schur hu v11 h2
  have v15 : (¬ e 11 14) := fun hu => c110 e tri schur hu v11 h1
  have v16 : (¬ e 9 12) := fun hu => c711 e tri schur v9 v4 hu
  exact c760 e tri schur v9 v10 h0

theorem c1422 : (e 11 13) → (e 11 12) → (e 1 11) → (¬ e 1 12) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 1 13) := fun hu => c109 e tri schur h0 hu h2
  have v1 : (¬ e 12 13) := fun hu => c760 e tri schur hu h0 h1
  exact c826 e tri schur h3 v0 v1

theorem c1423 : (e 9 10) → (e 4 15) → (e 2 13) → (e 2 9) → (e 1 11) → (¬ e 1 2) → (¬ e 1 9) → (¬ e 2 4) → (¬ e 4 13) → (¬ e 4 14) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9
  have v0 : (¬ e 2 10) := fun hu => c211 e tri schur h0 hu h3
  have v1 : (¬ e 9 13) := fun hu => c214 e tri schur hu h2 h3
  have v2 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu h8 v1)
  have v3 : (¬ e 6 9) := fun hu => c896 e tri schur hu v2 h3
  have v4 : (¬ e 4 6) := fun hu => c1194 e tri schur h1 v2 hu
  have v5 : (¬ e 4 10) := fun hu => c407 e tri schur h0 hu v2
  have v6 : (¬ e 9 15) := fun hu => c412 e tri schur hu h1 v2
  have v7 : (e 2 6) := Classical.byContradiction (fun hu => c833 e tri schur h7 hu v4)
  have v8 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur v4 v5 hu)
  have v9 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v5 h9 hu)
  have v10 : (e 6 15) := Classical.byContradiction (fun hu => c878 e tri schur v3 hu v6)
  have v11 : (¬ e 2 3) := fun hu => c1010 e tri schur h3 v7 hu
  have v12 : (¬ e 8 10) := fun hu => c1373 e tri schur v9 hu v8
  have v13 : (¬ e 6 13) := fun hu => c184 e tri schur hu h2 v7
  have v14 : (¬ e 2 15) := fun hu => c186 e tri schur v10 hu v7
  have v15 : (¬ e 6 14) := fun hu => c563 e tri schur v9 hu v8
  have v16 : (¬ e 10 15) := fun hu => c564 e tri schur hu v10 v8
  have v17 : (¬ e 9 14) := fun hu => c699 e tri schur v9 hu h0
  have v18 : (e 1 3) := Classical.byContradiction (fun hu => c816 e tri schur h5 hu v11)
  have v19 : (e 2 8) := Classical.byContradiction (fun hu => c837 e tri schur hu v0 v12)
  have v20 : (¬ e 2 14) := fun hu => c1215 e tri schur hu v19 v7
  have v21 : (¬ e 3 11) := fun hu => c23 e tri schur hu h4 v18
  have v22 : (¬ e 6 8) := fun hu => c179 e tri schur hu v19 v7
  have v23 : (¬ e 8 9) := fun hu => c201 e tri schur hu h3 v19
  have v24 : (¬ e 8 13) := fun hu => c205 e tri schur hu h2 v19
  have v25 : (e 1 8) := Classical.byContradiction (fun hu => c822 e tri schur hu h6 v23)
  have v26 : (e 8 14) := Classical.byContradiction (fun hu => c877 e tri schur v22 v15 hu)
  have v27 : (¬ e 8 12) := fun hu => c951 e tri schur v26 hu v19
  have v28 : (¬ e 3 8) := fun hu => c1297 e tri schur hu v19 v25
  have v29 : (¬ e 8 11) := fun hu => c83 e tri schur hu h4 v25
  have v30 : (¬ e 1 14) := fun hu => c86 e tri schur v26 hu v25
  exact c850 e tri schur v28 v21 v29

theorem c1424 : (e 1 11) → (e 1 8) → (e 1 3) → (¬ e 3 11) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 8) := fun hu => c20 e tri schur hu h1 h2
  have v1 : (¬ e 8 11) := fun hu => c83 e tri schur hu h0 h1
  exact c850 e tri schur v0 h3 v1

theorem c1425 : (e 5 6) → (e 3 6) → (e 2 6) → (¬ e 2 3) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 2 5) := fun hu => c165 e tri schur h0 h2 hu
  have v1 : (¬ e 3 5) := fun hu => c270 e tri schur h0 h1 hu
  exact c832 e tri schur h3 v0 v1

theorem c1427 : (e 9 11) → (e 8 11) → (e 1 11) → (¬ e 1 9) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 1 8) := fun hu => c83 e tri schur h1 h2 hu
  have v1 : (¬ e 8 9) := fun hu => c652 e tri schur h0 h1 hu
  exact c822 e tri schur v0 h3 v1

theorem c1428 : (e 9 11) → (e 8 9) → (e 3 8) → (e 3 6) → (e 2 6) → (e 1 11) → (e 1 3) → (¬ e 1 15) → (¬ e 2 9) → (¬ e 3 11) → (¬ e 4 11) → (¬ e 5 6) → (¬ e 11 13) → (¬ e 11 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13
  have v0 : (¬ e 1 6) := fun hu => c18 e tri schur h3 hu h6
  have v1 : (¬ e 1 8) := fun hu => c20 e tri schur h2 hu h6
  have v2 : (¬ e 1 9) := fun hu => c92 e tri schur h0 h5 hu
  have v3 : (¬ e 2 3) := fun hu => c138 e tri schur h3 h4 hu
  have v4 : (¬ e 6 8) := fun hu => c284 e tri schur hu h2 h3
  have v5 : (¬ e 3 9) := fun hu => c306 e tri schur h1 hu h2
  have v6 : (¬ e 8 11) := fun hu => c652 e tri schur h0 hu h1
  have v7 : (e 1 5) := Classical.byContradiction (fun hu => c819 e tri schur hu v0 h11)
  have v8 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur h10 hu h13)
  have v9 : (¬ e 3 14) := fun hu => c950 e tri schur hu h2 h3
  have v10 : (¬ e 3 5) := fun hu => c17 e tri schur hu v7 h6
  have v11 : (¬ e 5 11) := fun hu => c50 e tri schur hu h5 v7
  have v12 : (e 2 5) := Classical.byContradiction (fun hu => c832 e tri schur v3 hu v10)
  have v13 : (e 11 14) := Classical.byContradiction (fun hu => c853 e tri schur h9 v9 hu)
  have v14 : (e 6 11) := Classical.byContradiction (fun hu => c868 e tri schur h11 v11 hu)
  have v15 : (¬ e 2 11) := fun hu => c916 e tri schur hu h4 v12
  have v16 : (¬ e 2 7) := fun hu => c947 e tri schur v14 hu h4 h12
  have v17 : (¬ e 6 14) := fun hu => c954 e tri schur hu v14 h3
  have v18 : (¬ e 1 2) := fun hu => c2 e tri schur v12 v7 hu
  have v19 : (¬ e 1 14) := fun hu => c110 e tri schur v13 hu h5
  have v20 : (¬ e 6 9) := fun hu => c552 e tri schur h0 v14 hu
  have v21 : (¬ e 9 14) := fun hu => c706 e tri schur v13 hu h0
  have v22 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v19 h7 hu)
  have v23 : (e 7 9) := Classical.byContradiction (fun hu => c836 e tri schur v16 h8 hu)
  have v24 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur v15 hu h12)
  have v25 : (e 8 14) := Classical.byContradiction (fun hu => c877 e tri schur v4 v17 hu)
  have v26 : (¬ e 5 13) := fun hu => c172 e tri schur hu v24 v12
  have v27 : (¬ e 6 13) := fun hu => c184 e tri schur hu v24 h4
  have v28 : (¬ e 4 14) := fun hu => c442 e tri schur v22 v8 hu
  have v29 : (¬ e 7 8) := fun hu => c596 e tri schur h1 v23 hu
  have v30 : (¬ e 7 11) := fun hu => c607 e tri schur h0 hu v23
  have v31 : (¬ e 8 15) := fun hu => c686 e tri schur v22 hu v25
  have v32 : (e 1 7) := Classical.byContradiction (fun hu => c821 e tri schur hu v1 v29)
  have v33 : (e 4 7) := Classical.byContradiction (fun hu => c860 e tri schur hu h10 v30)
  have v34 : (e 7 15) := Classical.byContradiction (fun hu => c882 e tri schur v29 hu v31)
  exact c900 e tri schur v34 h10 v30 h13

theorem c1429 : (e 4 15) → (e 4 10) → (e 4 5) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 5 10) := fun hu => c365 e tri schur hu h1 h2
  have v1 : (¬ e 5 15) := fun hu => c370 e tri schur hu h0 h2
  have v2 : (¬ e 10 15) := fun hu => c420 e tri schur hu h0 h1
  exact c872 e tri schur v0 v1 v2

theorem c1430 : (e 9 11) → (e 9 10) → (e 8 9) → (e 3 8) → (e 2 6) → (e 1 11) → (e 1 3) → (¬ e 1 15) → (¬ e 2 9) → (¬ e 3 11) → (¬ e 4 6) → (¬ e 4 11) → (¬ e 5 6) → (¬ e 11 13) → (¬ e 11 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14
  have v0 : (¬ e 1 8) := fun hu => c20 e tri schur h3 hu h6
  have v1 : (¬ e 1 9) := fun hu => c92 e tri schur h0 h5 hu
  have v2 : (¬ e 3 9) := fun hu => c306 e tri schur h2 hu h3
  have v3 : (¬ e 8 10) := fun hu => c651 e tri schur h1 hu h2
  have v4 : (¬ e 8 11) := fun hu => c652 e tri schur h0 hu h2
  have v5 : (¬ e 10 11) := fun hu => c696 e tri schur hu h0 h1
  have v6 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur h11 hu h14)
  have v7 : (¬ e 3 6) := fun hu => c1428 e tri schur h0 h2 h3 hu h4 h5 h6 h7 h8 h9 h11 h12 h13 h14
  have v8 : (e 6 9) := Classical.byContradiction (fun hu => c848 e tri schur v7 v2 hu)
  have v9 : (¬ e 6 8) := fun hu => c541 e tri schur h2 v8 hu
  have v10 : (¬ e 6 10) := fun hu => c551 e tri schur h1 hu v8
  have v11 : (¬ e 6 11) := fun hu => c552 e tri schur h0 hu v8
  have v12 : (e 4 10) := Classical.byContradiction (fun hu => c859 e tri schur h10 hu v10)
  have v13 : (e 5 11) := Classical.byContradiction (fun hu => c868 e tri schur h12 hu v11)
  have v14 : (¬ e 4 5) := fun hu => c1429 e tri schur v6 v12 hu
  have v15 : (¬ e 1 5) := fun hu => c50 e tri schur v13 h5 hu
  have v16 : (¬ e 4 9) := fun hu => c407 e tri schur h1 v12 hu
  have v17 : (¬ e 10 15) := fun hu => c420 e tri schur hu v6 v12
  have v18 : (¬ e 5 9) := fun hu => c486 e tri schur h0 v13 hu
  have v19 : (e 1 4) := Classical.byContradiction (fun hu => c818 e tri schur hu v15 v14)
  have v20 : (e 1 6) := Classical.byContradiction (fun hu => c819 e tri schur v15 hu h12)
  exact c858 e tri schur v14 v16 v18

theorem c1431 : (e 9 11) → (e 9 10) → (e 8 9) → (e 3 8) → (e 1 11) → (e 1 3) → (¬ e 1 15) → (¬ e 2 3) → (¬ e 2 4) → (¬ e 2 9) → (¬ e 3 11) → (¬ e 4 6) → (¬ e 4 11) → (¬ e 11 13) → (¬ e 11 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14
  have v0 : (¬ e 1 8) := fun hu => c20 e tri schur h3 hu h5
  have v1 : (¬ e 1 9) := fun hu => c92 e tri schur h0 h4 hu
  have v2 : (¬ e 3 9) := fun hu => c306 e tri schur h2 hu h3
  have v3 : (¬ e 8 10) := fun hu => c651 e tri schur h1 hu h2
  have v4 : (¬ e 8 11) := fun hu => c652 e tri schur h0 hu h2
  have v5 : (¬ e 10 11) := fun hu => c696 e tri schur hu h0 h1
  have v6 : (e 2 6) := Classical.byContradiction (fun hu => c833 e tri schur h8 hu h11)
  have v7 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur h12 hu h14)
  have v8 : (e 5 6) := Classical.byContradiction (fun hu => c1430 e tri schur h0 h1 h2 h3 v6 h4 h5 h6 h9 h10 h11 h12 hu h13 h14)
  have v9 : (¬ e 2 5) := fun hu => c165 e tri schur v8 v6 hu
  have v10 : (e 3 5) := Classical.byContradiction (fun hu => c832 e tri schur h7 v9 hu)
  have v11 : (¬ e 3 6) := fun hu => c1425 e tri schur v8 hu v6 h7
  have v12 : (¬ e 1 5) := fun hu => c17 e tri schur v10 hu h5
  have v13 : (¬ e 5 8) := fun hu => c272 e tri schur hu h3 v10
  have v14 : (e 6 9) := Classical.byContradiction (fun hu => c848 e tri schur v11 v2 hu)
  have v15 : (¬ e 5 9) := fun hu => c454 e tri schur v14 hu v8
  have v16 : (¬ e 6 8) := fun hu => c541 e tri schur h2 v14 hu
  have v17 : (¬ e 6 10) := fun hu => c551 e tri schur h1 hu v14
  have v18 : (¬ e 6 11) := fun hu => c552 e tri schur h0 hu v14
  have v19 : (e 4 10) := Classical.byContradiction (fun hu => c859 e tri schur h11 hu v17)
  have v20 : (e 5 10) := Classical.byContradiction (fun hu => c1412 e tri schur h1 v8 v7 v19 hu)
  have v21 : (¬ e 4 5) := fun hu => c1429 e tri schur v7 v19 hu
  have v22 : (¬ e 3 10) := fun hu => c274 e tri schur v20 hu v10
  have v23 : (¬ e 4 9) := fun hu => c407 e tri schur h1 v19 hu
  have v24 : (¬ e 10 15) := fun hu => c420 e tri schur hu v7 v19
  have v25 : (e 1 4) := Classical.byContradiction (fun hu => c818 e tri schur hu v12 v21)
  exact c858 e tri schur v21 v23 v15

theorem c1432 : (e 8 9) → (¬ e 4 5) → (¬ e 4 9) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3
  have v0 : (e 5 9) := Classical.byContradiction (fun hu => c858 e tri schur h1 h2 hu)
  have v1 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur h2 h3 hu)
  have v2 : (¬ e 5 13) := fun hu => c1175 e tri schur hu h1 h2 h3
  have v3 : (¬ e 5 8) := fun hu => c475 e tri schur h0 v0 hu
  have v4 : (¬ e 8 13) := fun hu => c654 e tri schur v1 hu h0
  exact c870 e tri schur v3 v2 v4

theorem c1433 : (e 9 11) → (e 9 10) → (e 8 9) → (e 3 8) → (e 2 12) → (e 1 11) → (e 1 4) → (¬ e 1 2) → (¬ e 2 4) → (¬ e 2 9) → (¬ e 3 11) → (¬ e 4 11) → (¬ e 4 13) → (¬ e 9 12) → (¬ e 11 13) → (¬ e 11 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14 h15
  have v0 : (¬ e 1 9) := fun hu => c92 e tri schur h0 h5 hu
  have v1 : (¬ e 3 9) := fun hu => c306 e tri schur h2 hu h3
  have v2 : (¬ e 8 10) := fun hu => c651 e tri schur h1 hu h2
  have v3 : (¬ e 8 11) := fun hu => c652 e tri schur h0 hu h2
  have v4 : (¬ e 10 11) := fun hu => c696 e tri schur hu h0 h1
  have v5 : (e 3 12) := Classical.byContradiction (fun hu => c851 e tri schur v1 hu h13)
  have v6 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur h11 hu h15)
  have v7 : (¬ e 4 14) := fun hu => c1410 e tri schur v6 hu h6
  have v8 : (¬ e 1 15) := fun hu => c41 e tri schur v6 hu h6
  have v9 : (¬ e 2 3) := fun hu => c144 e tri schur v5 h4 hu
  have v10 : (¬ e 8 12) := fun hu => c309 e tri schur hu v5 h3
  have v11 : (e 1 3) := Classical.byContradiction (fun hu => c816 e tri schur h7 hu v9)
  have v12 : (¬ e 3 4) := fun hu => c915 e tri schur v5 h3 hu v10
  have v13 : (¬ e 1 8) := fun hu => c1424 e tri schur h5 hu v11 h10
  have v14 : (e 4 6) := Classical.byContradiction (fun hu => c1431 e tri schur h0 h1 h2 h3 h5 v11 v8 v9 h8 h9 h10 hu h11 h14 h15)
  have v15 : (¬ e 1 12) := fun hu => c24 e tri schur v5 hu v11
  have v16 : (¬ e 1 6) := fun hu => c32 e tri schur v14 hu h6
  have v17 : (¬ e 6 15) := fun hu => c382 e tri schur hu v6 v14
  have v18 : (¬ e 4 9) := fun hu => c1194 e tri schur v6 hu v14
  have v19 : (e 4 5) := Classical.byContradiction (fun hu => c1432 e tri schur h2 hu v18 h12)
  have v20 : (¬ e 1 5) := fun hu => c31 e tri schur v19 hu h6
  have v21 : (¬ e 5 6) := fun hu => c361 e tri schur hu v14 v19
  have v22 : (¬ e 5 15) := fun hu => c370 e tri schur hu v6 v19
  exact c819 e tri schur v20 v16 v21

theorem c1434 : (e 11 12) → (e 9 10) → (e 2 12) → (e 1 11) → (e 1 4) → (¬ e 1 2) → (¬ e 1 9) → (¬ e 2 4) → (¬ e 2 11) → (¬ e 4 11) → (¬ e 4 13) → (¬ e 11 13) → (¬ e 11 15) → (¬ e 12 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13
  have v0 : (¬ e 1 12) := fun hu => c108 e tri schur h0 hu h3
  have v1 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur h8 hu h11)
  have v2 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur h9 hu h12)
  have v3 : (¬ e 4 14) := fun hu => c1410 e tri schur v2 hu h4
  have v4 : (¬ e 10 11) := fun hu => c1420 e tri schur h0 hu v2 h2 h3 h4 v0 h7 h8 h9 h10
  have v5 : (¬ e 2 9) := fun hu => c1423 e tri schur h1 v2 v1 hu h3 h5 h6 h7 h10 v3
  have v6 : (¬ e 1 15) := fun hu => c41 e tri schur v2 hu h4
  have v7 : (¬ e 12 13) := fun hu => c235 e tri schur hu v1 h2
  have v8 : (e 1 13) := Classical.byContradiction (fun hu => c826 e tri schur v0 hu v7)
  have v9 : (e 9 11) := Classical.byContradiction (fun hu => c838 e tri schur v5 h8 hu)
  have v10 : (¬ e 3 11) := fun hu => c1361 e tri schur h0 v9 hu
  have v11 : (¬ e 8 11) := fun hu => c1427 e tri schur v9 hu h3 h6
  have v12 : (¬ e 9 12) := fun hu => c704 e tri schur h0 hu v9
  have v13 : (e 3 8) := Classical.byContradiction (fun hu => c850 e tri schur hu v10 v11)
  have v14 : (¬ e 8 9) := fun hu => c1433 e tri schur v9 h1 hu v13 h2 h3 h4 h5 h7 v5 v10 h9 h10 v12 h11 h12
  have v15 : (e 1 8) := Classical.byContradiction (fun hu => c822 e tri schur hu h6 v14)
  have v16 : (¬ e 2 8) := fun hu => c1297 e tri schur v13 hu v15
  have v17 : (¬ e 1 3) := fun hu => c1424 e tri schur h3 v15 hu v10
  have v18 : (¬ e 4 8) := fun hu => c34 e tri schur hu v15 h4
  have v19 : (¬ e 8 13) := fun hu => c85 e tri schur hu v8 v15
  have v20 : (e 2 3) := Classical.byContradiction (fun hu => c816 e tri schur h5 v17 hu)
  have v21 : (¬ e 2 15) := fun hu => c913 e tri schur hu h2 v20 h13
  have v22 : (¬ e 3 10) := fun hu => c1324 e tri schur hu v13 v20
  have v23 : (¬ e 3 12) := fun hu => c144 e tri schur hu h2 v20
  have v24 : (¬ e 3 13) := fun hu => c145 e tri schur hu v1 v20
  have v25 : (e 3 9) := Classical.byContradiction (fun hu => c851 e tri schur hu v23 v12)
  have v26 : (e 10 13) := Classical.byContradiction (fun hu => c852 e tri schur v22 v24 hu)
  have v27 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur v23 hu h13)
  have v28 : (¬ e 9 14) := fun hu => c948 e tri schur hu v9 v25
  have v29 : (¬ e 7 15) := fun hu => c1023 e tri schur hu v2 v27
  have v30 : (¬ e 1 10) := fun hu => c102 e tri schur v26 v8 hu
  have v31 : (¬ e 2 10) := fun hu => c222 e tri schur v26 v1 hu
  have v32 : (¬ e 3 4) := fun hu => c266 e tri schur v2 v27 hu
  have v33 : (¬ e 8 15) := fun hu => c312 e tri schur hu v27 v13
  have v34 : (¬ e 9 15) := fun hu => c321 e tri schur hu v27 v25
  have v35 : (¬ e 9 13) := fun hu => c698 e tri schur v26 hu h1
  have v36 : (e 8 10) := Classical.byContradiction (fun hu => c837 e tri schur v16 v31 hu)
  have v37 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu h10 v35)
  have v38 : (e 7 8) := Classical.byContradiction (fun hu => c882 e tri schur hu v29 v33)
  have v39 : (¬ e 7 9) := fun hu => c894 e tri schur hu v37 v25
  have v40 : (¬ e 2 7) := fun hu => c1076 e tri schur v38 hu v20 v22
  have v41 : (¬ e 4 6) := fun hu => c1194 e tri schur v2 v37 hu
  have v42 : (¬ e 1 7) := fun hu => c70 e tri schur v38 v15 hu
  have v43 : (¬ e 3 7) := fun hu => c295 e tri schur v38 v13 hu
  have v44 : (¬ e 4 10) := fun hu => c407 e tri schur h1 hu v37
  have v45 : (¬ e 7 10) := fun hu => c597 e tri schur v36 hu v38
  have v46 : (e 2 6) := Classical.byContradiction (fun hu => c833 e tri schur h7 hu v41)
  exact c836 e tri schur v40 v5 v39

theorem c1435 : (e 11 12) → (e 4 12) → (e 2 12) → (e 1 4) → (¬ e 1 12) → (¬ e 2 11) → (¬ e 11 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 2 4) := fun hu => c158 e tri schur h1 h2 hu
  have v1 : (¬ e 4 11) := fun hu => c424 e tri schur h0 h1 hu
  have v2 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur v1 hu h6)
  have v3 : (¬ e 3 4) := fun hu => c1188 e tri schur v2 h1 hu
  have v4 : (¬ e 4 13) := fun hu => c1260 e tri schur hu h1 h3
  have v5 : (¬ e 4 14) := fun hu => c1410 e tri schur v2 hu h3
  have v6 : (e 1 11) := Classical.byContradiction (fun hu => c1419 e tri schur v2 h1 h3 hu h4)
  have v7 : (¬ e 10 11) := fun hu => c1420 e tri schur h0 hu v2 h2 v6 h3 h4 v0 h5 v1 v4
  have v8 : (¬ e 1 9) := fun hu => c1421 e tri schur h0 v6 hu h3 h4 h5 v4
  have v9 : (¬ e 11 13) := fun hu => c1422 e tri schur hu h0 v6 h4
  have v10 : (¬ e 1 15) := fun hu => c41 e tri schur v2 hu h3
  have v11 : (¬ e 12 15) := fun hu => c433 e tri schur hu v2 h1
  have v12 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur h5 hu v9)
  have v13 : (¬ e 12 13) := fun hu => c235 e tri schur hu v12 h2
  have v14 : (e 1 13) := Classical.byContradiction (fun hu => c826 e tri schur h4 hu v13)
  have v15 : (¬ e 1 2) := fun hu => c10 e tri schur v12 v14 hu
  have v16 : (¬ e 9 10) := fun hu => c1434 e tri schur h0 hu h2 v6 h3 v15 v8 v0 h5 v1 v4 v9 h6 v11
  have v17 : (e 1 10) := Classical.byContradiction (fun hu => c823 e tri schur v8 hu v16)
  have v18 : (¬ e 1 14) := fun hu => c1343 e tri schur hu v17 h3
  have v19 : (¬ e 1 3) := fun hu => c1357 e tri schur v14 v17 hu
  have v20 : (¬ e 13 14) := fun hu => c1369 e tri schur hu h0 v2 h1 v14 v17 h3 h5
  have v21 : (¬ e 4 10) := fun hu => c36 e tri schur hu v17 h3
  have v22 : (¬ e 10 13) := fun hu => c102 e tri schur hu v14 v17
  have v23 : (e 2 3) := Classical.byContradiction (fun hu => c816 e tri schur v15 v19 hu)
  have v24 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v18 v10 hu)
  have v25 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v21 v5 hu)
  have v26 : (¬ e 2 15) := fun hu => c913 e tri schur hu h2 v23 v11
  have v27 : (¬ e 3 14) := fun hu => c1387 e tri schur v24 hu v23 v11
  have v28 : (¬ e 11 14) := fun hu => c1388 e tri schur v24 hu h0 v2 h1 v23 v17 v18 h5 v21 v4 v22
  have v29 : (¬ e 3 12) := fun hu => c144 e tri schur hu h2 v23
  have v30 : (¬ e 3 13) := fun hu => c145 e tri schur hu v12 v23
  have v31 : (¬ e 10 15) := fun hu => c750 e tri schur v24 hu v25
  have v32 : (e 3 10) := Classical.byContradiction (fun hu => c852 e tri schur hu v30 v22)
  have v33 : (e 3 11) := Classical.byContradiction (fun hu => c853 e tri schur hu v27 v28)
  have v34 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur v29 hu v11)
  have v35 : (¬ e 7 15) := fun hu => c1023 e tri schur hu v2 v34
  have v36 : (¬ e 3 8) := fun hu => c1324 e tri schur v32 hu v23
  have v37 : (¬ e 15 17) := fun hu => c1345 e tri schur hu v24 v34
  have v38 : (¬ e 9 11) := fun hu => c1361 e tri schur h0 hu v33
  have v39 : (e 13 15) := Classical.byContradiction (fun hu => c1362 e tri schur h0 v2 v33 h2 v14 v17 v0 h5 v11 hu)
  have v40 : (¬ e 2 9) := fun hu => c1363 e tri schur h2 hu v23 v29
  have v41 : (¬ e 2 10) := fun hu => c142 e tri schur v32 hu v23
  exact c838 e tri schur v40 h5 v38

theorem c1436 : (e 11 12) → (e 4 15) → (e 3 11) → (e 1 11) → (e 1 4) → (¬ e 1 12) → (¬ e 2 11) → (¬ e 2 12) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8
  have v0 : (¬ e 1 3) := fun hu => c23 e tri schur h2 h3 hu
  have v1 : (¬ e 4 11) := fun hu => c37 e tri schur hu h3 h4
  have v2 : (¬ e 1 15) := fun hu => c41 e tri schur h1 hu h4
  have v3 : (¬ e 3 12) := fun hu => c333 e tri schur h0 hu h2
  have v4 : (¬ e 9 11) := fun hu => c1361 e tri schur h0 hu h2
  have v5 : (¬ e 4 14) := fun hu => c1410 e tri schur h1 hu h4
  have v6 : (¬ e 1 9) := fun hu => c1421 e tri schur h0 h3 hu h4 h5 h6 h8
  have v7 : (¬ e 11 13) := fun hu => c1422 e tri schur hu h0 h3 h5
  have v8 : (e 2 9) := Classical.byContradiction (fun hu => c838 e tri schur hu h6 v4)
  have v9 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur h6 hu v7)
  have v10 : (¬ e 9 13) := fun hu => c214 e tri schur hu v9 v8
  have v11 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu h8 v10)
  have v12 : (¬ e 6 9) := fun hu => c896 e tri schur hu v11 v8
  have v13 : (¬ e 4 6) := fun hu => c1194 e tri schur h1 v11 hu
  have v14 : (¬ e 2 4) := fun hu => c155 e tri schur v11 v8 hu
  have v15 : (¬ e 9 15) := fun hu => c412 e tri schur hu h1 v11
  have v16 : (e 2 6) := Classical.byContradiction (fun hu => c833 e tri schur v14 hu v13)
  have v17 : (e 6 15) := Classical.byContradiction (fun hu => c878 e tri schur v12 hu v15)
  have v18 : (¬ e 2 3) := fun hu => c1010 e tri schur v8 v16 hu
  have v19 : (¬ e 6 13) := fun hu => c184 e tri schur hu v9 v16
  have v20 : (¬ e 2 15) := fun hu => c186 e tri schur v17 hu v16
  have v21 : (e 1 2) := Classical.byContradiction (fun hu => c816 e tri schur hu v0 v18)
  have v22 : (¬ e 1 6) := fun hu => c1394 e tri schur hu h4 v21
  have v23 : (¬ e 1 13) := fun hu => c10 e tri schur v9 hu v21
  have v24 : (e 12 13) := Classical.byContradiction (fun hu => c826 e tri schur h5 v23 hu)
  have v25 : (e 1 14) := Classical.byContradiction (fun hu => c1359 e tri schur h0 h5 v23 hu h6)
  have v26 : (¬ e 2 14) := fun hu => c11 e tri schur hu v25 v21
  have v27 : (¬ e 11 14) := fun hu => c110 e tri schur hu v25 h3
  have v28 : (e 12 14) := Classical.byContradiction (fun hu => c841 e tri schur h7 v26 hu)
  have v29 : (¬ e 1 10) := fun hu => c1343 e tri schur v25 hu h4
  have v30 : (¬ e 13 14) := fun hu => c781 e tri schur hu v28 v24
  have v31 : (e 9 10) := Classical.byContradiction (fun hu => c823 e tri schur v6 v29 hu)
  have v32 : (¬ e 2 10) := fun hu => c211 e tri schur v31 hu v8
  have v33 : (¬ e 4 10) := fun hu => c407 e tri schur v31 hu v11
  have v34 : (e 10 12) := Classical.byContradiction (fun hu => c839 e tri schur v32 h7 hu)
  have v35 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur v13 v33 hu)
  have v36 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v33 v5 hu)
  have v37 : (¬ e 8 10) := fun hu => c1373 e tri schur v36 hu v35
  have v38 : (¬ e 6 12) := fun hu => c561 e tri schur v34 hu v35
  have v39 : (¬ e 6 14) := fun hu => c563 e tri schur v36 hu v35
  have v40 : (¬ e 10 15) := fun hu => c564 e tri schur hu v17 v35
  have v41 : (¬ e 9 12) := fun hu => c697 e tri schur v34 hu v31
  have v42 : (¬ e 9 14) := fun hu => c699 e tri schur v36 hu v31
  have v43 : (¬ e 10 11) := fun hu => c732 e tri schur h0 v34 hu
  have v44 : (¬ e 10 13) := fun hu => c739 e tri schur v24 hu v34
  exact c740 e tri schur v28 v36 v34

theorem c1437 : (e 11 12) → (e 4 9) → (e 2 13) → (e 2 9) → (e 1 4) → (e 1 2) → (¬ e 1 9) → (¬ e 1 12) → (¬ e 2 11) → (¬ e 2 12) → (¬ e 4 14) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10
  have v0 : (¬ e 2 4) := fun hu => c1 e tri schur hu h4 h5
  have v1 : (¬ e 1 13) := fun hu => c10 e tri schur h2 hu h5
  have v2 : (¬ e 9 13) := fun hu => c214 e tri schur hu h2 h3
  have v3 : (e 12 13) := Classical.byContradiction (fun hu => c826 e tri schur h7 v1 hu)
  have v4 : (¬ e 6 9) := fun hu => c896 e tri schur hu h1 h3
  have v5 : (e 1 14) := Classical.byContradiction (fun hu => c1359 e tri schur h0 h7 v1 hu h8)
  have v6 : (¬ e 1 6) := fun hu => c1394 e tri schur hu h4 h5
  have v7 : (¬ e 2 14) := fun hu => c11 e tri schur hu v5 h5
  have v8 : (¬ e 11 13) := fun hu => c760 e tri schur v3 hu h0
  have v9 : (e 12 14) := Classical.byContradiction (fun hu => c841 e tri schur h9 v7 hu)
  have v10 : (¬ e 1 10) := fun hu => c1343 e tri schur v5 hu h4
  have v11 : (¬ e 11 14) := fun hu => c761 e tri schur v9 hu h0
  have v12 : (¬ e 13 14) := fun hu => c781 e tri schur hu v9 v3
  have v13 : (e 9 10) := Classical.byContradiction (fun hu => c823 e tri schur h6 v10 hu)
  have v14 : (¬ e 2 10) := fun hu => c211 e tri schur v13 hu h3
  have v15 : (¬ e 4 10) := fun hu => c407 e tri schur v13 hu h1
  have v16 : (e 10 12) := Classical.byContradiction (fun hu => c839 e tri schur v14 h9 hu)
  have v17 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v15 h10 hu)
  have v18 : (¬ e 9 12) := fun hu => c697 e tri schur v16 hu v13
  have v19 : (¬ e 9 14) := fun hu => c699 e tri schur v17 hu v13
  have v20 : (¬ e 10 11) := fun hu => c732 e tri schur h0 v16 hu
  have v21 : (¬ e 10 13) := fun hu => c739 e tri schur v3 hu v16
  exact c740 e tri schur v9 v17 v16

theorem c1438 : (e 11 12) → (e 4 15) → (e 2 9) → (e 1 11) → (e 1 4) → (¬ e 1 12) → (¬ e 2 11) → (¬ e 2 12) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8
  have v0 : (¬ e 4 11) := fun hu => c37 e tri schur hu h3 h4
  have v1 : (¬ e 1 15) := fun hu => c41 e tri schur h1 hu h4
  have v2 : (¬ e 4 14) := fun hu => c1410 e tri schur h1 hu h4
  have v3 : (¬ e 1 9) := fun hu => c1421 e tri schur h0 h3 hu h4 h5 h6 h8
  have v4 : (¬ e 11 13) := fun hu => c1422 e tri schur hu h0 h3 h5
  have v5 : (¬ e 3 11) := fun hu => c1436 e tri schur h0 h1 hu h3 h4 h5 h6 h7 h8
  have v6 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur h6 hu v4)
  have v7 : (¬ e 9 13) := fun hu => c214 e tri schur hu v6 h2
  have v8 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu h8 v7)
  have v9 : (¬ e 6 9) := fun hu => c896 e tri schur hu v8 h2
  have v10 : (¬ e 4 6) := fun hu => c1194 e tri schur h1 v8 hu
  have v11 : (¬ e 1 2) := fun hu => c1437 e tri schur h0 v8 v6 h2 h4 hu v3 h5 h6 h7 v2
  have v12 : (¬ e 2 4) := fun hu => c155 e tri schur v8 h2 hu
  have v13 : (¬ e 9 15) := fun hu => c412 e tri schur hu h1 v8
  have v14 : (e 2 6) := Classical.byContradiction (fun hu => c833 e tri schur v12 hu v10)
  have v15 : (e 6 15) := Classical.byContradiction (fun hu => c878 e tri schur v9 hu v13)
  have v16 : (¬ e 2 3) := fun hu => c1010 e tri schur h2 v14 hu
  have v17 : (¬ e 9 10) := fun hu => c1423 e tri schur hu h1 v6 h2 h3 v11 v3 v12 h8 v2
  have v18 : (¬ e 6 13) := fun hu => c184 e tri schur hu v6 v14
  have v19 : (¬ e 2 15) := fun hu => c186 e tri schur v15 hu v14
  have v20 : (e 1 3) := Classical.byContradiction (fun hu => c816 e tri schur v11 hu v16)
  have v21 : (e 1 10) := Classical.byContradiction (fun hu => c823 e tri schur v3 hu v17)
  have v22 : (¬ e 1 6) := fun hu => c1312 e tri schur v21 hu h4 v10
  have v23 : (¬ e 1 14) := fun hu => c1343 e tri schur hu v21 h4
  have v24 : (¬ e 1 13) := fun hu => c1357 e tri schur hu v21 v20
  exact c1359 e tri schur h0 h5 v24 v23 h6

theorem c1439 : (e 11 12) → (e 1 10) → (e 1 4) → (e 1 3) → (¬ e 1 12) → (¬ e 2 11) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 3 4) := fun hu => c16 e tri schur hu h2 h3
  have v1 : (¬ e 3 10) := fun hu => c22 e tri schur hu h1 h3
  have v2 : (¬ e 4 10) := fun hu => c36 e tri schur hu h1 h2
  have v3 : (¬ e 1 14) := fun hu => c1343 e tri schur hu h1 h2
  have v4 : (¬ e 1 13) := fun hu => c1357 e tri schur hu h1 h3
  exact c1359 e tri schur h0 h4 v4 v3 h5

theorem c1440 : (e 1 14) → (e 1 11) → (e 1 3) → (¬ e 3 11) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 14) := fun hu => c26 e tri schur hu h0 h2
  have v1 : (¬ e 11 14) := fun hu => c110 e tri schur hu h0 h1
  exact c853 e tri schur h3 v0 v1

theorem c1441 : (e 9 10) → (e 4 15) → (e 4 9) → (e 3 8) → (e 2 14) → (¬ e 3 9) → (¬ e 4 14) → (¬ e 8 10) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 4 10) := fun hu => c407 e tri schur h0 hu h2
  have v1 : (¬ e 9 15) := fun hu => c412 e tri schur hu h1 h2
  have v2 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v0 h6 hu)
  have v3 : (¬ e 4 6) := fun hu => c1194 e tri schur h1 h2 hu
  have v4 : (¬ e 2 10) := fun hu => c223 e tri schur v2 h4 hu
  have v5 : (¬ e 9 14) := fun hu => c699 e tri schur v2 hu h0
  have v6 : (e 2 8) := Classical.byContradiction (fun hu => c837 e tri schur hu v4 h7)
  have v7 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur v3 v0 hu)
  have v8 : (¬ e 2 6) := fun hu => c1215 e tri schur h4 v6 hu
  have v9 : (¬ e 1 8) := fun hu => c1297 e tri schur h3 v6 hu
  have v10 : (¬ e 2 3) := fun hu => c140 e tri schur h3 v6 hu
  have v11 : (¬ e 8 14) := fun hu => c206 e tri schur hu h4 v6
  have v12 : (¬ e 6 9) := fun hu => c551 e tri schur h0 v7 hu
  have v13 : (¬ e 6 14) := fun hu => c563 e tri schur v2 hu v7
  have v14 : (e 2 4) := Classical.byContradiction (fun hu => c833 e tri schur hu v8 v3)
  have v15 : (e 3 6) := Classical.byContradiction (fun hu => c848 e tri schur hu h5 v12)
  have v16 : (e 6 8) := Classical.byContradiction (fun hu => c877 e tri schur hu v13 v11)
  have v17 : (e 6 15) := Classical.byContradiction (fun hu => c878 e tri schur v12 hu v1)
  have v18 : (¬ e 3 14) := fun hu => c950 e tri schur hu h3 v15
  have v19 : (¬ e 6 11) := fun hu => c959 e tri schur hu v16 v15
  have v20 : (¬ e 2 12) := fun hu => c1233 e tri schur hu v6 v14
  have v21 : (¬ e 2 18) := fun hu => c1289 e tri schur hu h4 v14
  have v22 : (¬ e 4 8) := fun hu => c154 e tri schur hu v6 v14
  have v23 : (¬ e 2 9) := fun hu => c155 e tri schur h2 hu v14
  have v24 : (¬ e 2 15) := fun hu => c161 e tri schur h1 hu v14
  exact c284 e tri schur v16 h3 v15

theorem c1442 : (e 11 12) → (e 4 15) → (e 1 11) → (e 1 4) → (e 1 3) → (¬ e 1 12) → (¬ e 2 11) → (¬ e 2 12) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8
  have v0 : (¬ e 3 4) := fun hu => c16 e tri schur hu h3 h4
  have v1 : (¬ e 3 11) := fun hu => c23 e tri schur hu h2 h4
  have v2 : (¬ e 4 11) := fun hu => c37 e tri schur hu h2 h3
  have v3 : (¬ e 1 15) := fun hu => c41 e tri schur h1 hu h3
  have v4 : (¬ e 4 14) := fun hu => c1410 e tri schur h1 hu h3
  have v5 : (¬ e 1 9) := fun hu => c1421 e tri schur h0 h2 hu h3 h5 h6 h8
  have v6 : (¬ e 11 13) := fun hu => c1422 e tri schur hu h0 h2 h5
  have v7 : (¬ e 1 8) := fun hu => c1424 e tri schur h2 hu h4 v1
  have v8 : (¬ e 2 9) := fun hu => c1438 e tri schur h0 h1 hu h2 h3 h5 h6 h7 h8
  have v9 : (¬ e 1 10) := fun hu => c1439 e tri schur h0 hu h3 h4 h5 h6
  have v10 : (¬ e 1 14) := fun hu => c1440 e tri schur hu h2 h4 v1
  have v11 : (e 8 9) := Classical.byContradiction (fun hu => c822 e tri schur v7 v5 hu)
  have v12 : (e 9 10) := Classical.byContradiction (fun hu => c823 e tri schur v5 v9 hu)
  have v13 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v10 v3 hu)
  have v14 : (e 9 11) := Classical.byContradiction (fun hu => c838 e tri schur v8 h6 hu)
  have v15 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur h6 hu v6)
  have v16 : (e 1 13) := Classical.byContradiction (fun hu => c1359 e tri schur h0 h5 hu v10 h6)
  have v17 : (¬ e 8 11) := fun hu => c1427 e tri schur v14 hu h2 v5
  have v18 : (¬ e 1 2) := fun hu => c10 e tri schur v15 v16 hu
  have v19 : (¬ e 3 13) := fun hu => c25 e tri schur hu v16 h4
  have v20 : (¬ e 8 10) := fun hu => c651 e tri schur v12 hu v11
  have v21 : (¬ e 10 11) := fun hu => c696 e tri schur hu v14 v12
  have v22 : (¬ e 9 12) := fun hu => c704 e tri schur h0 hu v14
  have v23 : (e 3 8) := Classical.byContradiction (fun hu => c850 e tri schur hu v1 v17)
  have v24 : (¬ e 3 9) := fun hu => c306 e tri schur v11 hu v23
  have v25 : (e 3 12) := Classical.byContradiction (fun hu => c851 e tri schur v24 hu v22)
  have v26 : (¬ e 12 14) := fun hu => c1396 e tri schur hu h0 v25 v1
  have v27 : (¬ e 8 12) := fun hu => c309 e tri schur hu v25 v23
  have v28 : (e 2 14) := Classical.byContradiction (fun hu => c841 e tri schur h7 hu v26)
  have v29 : (¬ e 4 9) := fun hu => c1441 e tri schur v12 h1 hu v23 v28 v24 v4 v20
  have v30 : (¬ e 13 14) := fun hu => c241 e tri schur hu v28 v15
  have v31 : (¬ e 2 15) := fun hu => c246 e tri schur v13 hu v28
  have v32 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v29 h8 hu)
  have v33 : (e 4 5) := Classical.byContradiction (fun hu => c1432 e tri schur v11 hu v29 h8)
  have v34 : (¬ e 1 5) := fun hu => c31 e tri schur v33 hu h3
  have v35 : (¬ e 5 15) := fun hu => c370 e tri schur hu h1 v33
  have v36 : (¬ e 8 13) := fun hu => c654 e tri schur v32 hu v11
  have v37 : (¬ e 10 13) := fun hu => c698 e tri schur hu v32 v12
  have v38 : (e 3 10) := Classical.byContradiction (fun hu => c852 e tri schur hu v19 v37)
  have v39 : (¬ e 3 18) := fun hu => c963 e tri schur hu v38 v23
  have v40 : (¬ e 2 3) := fun hu => c1324 e tri schur v38 v23 hu
  have v41 : (¬ e 4 10) := fun hu => c1429 e tri schur h1 hu v33
  have v42 : (¬ e 10 12) := fun hu => c326 e tri schur hu v25 v38
  have v43 : (e 2 10) := Classical.byContradiction (fun hu => c839 e tri schur hu h7 v42)
  have v44 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v41 v4 hu)
  exact c223 e tri schur v44 v28 v43

theorem c1443 : (e 11 12) → (e 4 15) → (e 3 8) → (e 1 11) → (¬ e 1 3) → (¬ e 1 9) → (¬ e 1 12) → (¬ e 2 3) → (¬ e 2 11) → (¬ e 2 12) → (¬ e 3 11) → (¬ e 9 12) → (¬ e 12 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12
  have v0 : (e 1 2) := Classical.byContradiction (fun hu => c816 e tri schur hu h4 h7)
  have v1 : (¬ e 11 13) := fun hu => c1422 e tri schur hu h0 h3 h6
  have v2 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur h8 hu v1)
  have v3 : (¬ e 1 13) := fun hu => c10 e tri schur v2 hu v0
  have v4 : (e 12 13) := Classical.byContradiction (fun hu => c826 e tri schur h6 v3 hu)
  have v5 : (e 1 14) := Classical.byContradiction (fun hu => c1359 e tri schur h0 h6 v3 hu h8)
  have v6 : (¬ e 2 14) := fun hu => c11 e tri schur hu v5 v0
  have v7 : (¬ e 11 14) := fun hu => c110 e tri schur hu v5 h3
  have v8 : (e 12 14) := Classical.byContradiction (fun hu => c841 e tri schur h9 v6 hu)
  have v9 : (e 3 14) := Classical.byContradiction (fun hu => c853 e tri schur h10 hu v7)
  have v10 : (¬ e 3 6) := fun hu => c950 e tri schur v9 h2 hu
  have v11 : (¬ e 3 12) := fun hu => c1396 e tri schur v8 h0 hu h10
  have v12 : (¬ e 8 14) := fun hu => c311 e tri schur hu v9 h2
  have v13 : (¬ e 13 14) := fun hu => c781 e tri schur hu v8 v4
  have v14 : (e 3 9) := Classical.byContradiction (fun hu => c851 e tri schur hu v11 h11)
  have v15 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur v11 hu h12)
  have v16 : (¬ e 3 5) := fun hu => c992 e tri schur v9 v14 hu
  have v17 : (¬ e 7 15) := fun hu => c1023 e tri schur hu h1 v15
  have v18 : (¬ e 3 4) := fun hu => c266 e tri schur h1 v15 hu
  have v19 : (¬ e 8 9) := fun hu => c306 e tri schur hu v14 h2
  have v20 : (¬ e 8 15) := fun hu => c312 e tri schur hu v15 h2
  have v21 : (¬ e 9 14) := fun hu => c320 e tri schur hu v9 v14
  have v22 : (¬ e 9 15) := fun hu => c321 e tri schur hu v15 v14
  have v23 : (¬ e 14 15) := fun hu => c351 e tri schur hu v15 v9
  have v24 : (e 1 4) := Classical.byContradiction (fun hu => c817 e tri schur h4 hu v18)
  have v25 : (e 1 8) := Classical.byContradiction (fun hu => c822 e tri schur hu h5 v19)
  have v26 : (e 2 5) := Classical.byContradiction (fun hu => c832 e tri schur h7 hu v16)
  have v27 : (e 7 8) := Classical.byContradiction (fun hu => c882 e tri schur hu v17 v20)
  have v28 : (¬ e 2 8) := fun hu => c1297 e tri schur h2 hu v25
  have v29 : (¬ e 1 10) := fun hu => c1343 e tri schur v5 hu v24
  have v30 : (e 5 13) := Classical.byContradiction (fun hu => c1393 e tri schur v27 v26 v25 v0 hu)
  have v31 : (¬ e 1 6) := fun hu => c1394 e tri schur hu v24 v0
  have v32 : (¬ e 4 14) := fun hu => c1410 e tri schur h1 hu v24
  have v33 : (¬ e 2 4) := fun hu => c1 e tri schur hu v24 v0
  have v34 : (¬ e 1 5) := fun hu => c2 e tri schur v26 hu v0
  have v35 : (¬ e 4 8) := fun hu => c34 e tri schur hu v25 v24
  have v36 : (¬ e 4 11) := fun hu => c37 e tri schur hu h3 v24
  have v37 : (¬ e 1 15) := fun hu => c41 e tri schur h1 hu v24
  have v38 : (¬ e 1 7) := fun hu => c70 e tri schur v27 v25 hu
  have v39 : (¬ e 8 11) := fun hu => c83 e tri schur hu h3 v25
  exact c172 e tri schur v30 v2 v26

theorem c1444 : (e 11 12) → (e 4 12) → (e 1 4) → (¬ e 1 12) → (¬ e 2 11) → (¬ e 11 15) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 4 11) := fun hu => c424 e tri schur h0 h1 hu
  have v1 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur v0 hu h5)
  have v2 : (¬ e 3 4) := fun hu => c1188 e tri schur v1 h1 hu
  have v3 : (¬ e 4 13) := fun hu => c1260 e tri schur hu h1 h2
  have v4 : (¬ e 4 14) := fun hu => c1410 e tri schur v1 hu h2
  have v5 : (e 1 11) := Classical.byContradiction (fun hu => c1419 e tri schur v1 h1 h2 hu h3)
  have v6 : (¬ e 1 9) := fun hu => c1421 e tri schur h0 v5 hu h2 h3 h4 v3
  have v7 : (¬ e 11 13) := fun hu => c1422 e tri schur hu h0 v5 h3
  have v8 : (¬ e 2 12) := fun hu => c1435 e tri schur h0 h1 hu h2 h3 h4 h5
  have v9 : (¬ e 3 11) := fun hu => c1436 e tri schur h0 v1 hu v5 h2 h3 h4 v8 v3
  have v10 : (¬ e 2 9) := fun hu => c1438 e tri schur h0 v1 hu v5 h2 h3 h4 v8 v3
  have v11 : (¬ e 1 3) := fun hu => c1442 e tri schur h0 v1 v5 h2 hu h3 h4 v8 v3
  have v12 : (¬ e 1 15) := fun hu => c41 e tri schur v1 hu h2
  have v13 : (¬ e 12 15) := fun hu => c433 e tri schur hu v1 h1
  have v14 : (e 9 11) := Classical.byContradiction (fun hu => c838 e tri schur v10 h4 hu)
  have v15 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur h4 hu v7)
  have v16 : (¬ e 8 11) := fun hu => c1427 e tri schur v14 hu v5 v6
  have v17 : (¬ e 9 12) := fun hu => c704 e tri schur h0 hu v14
  have v18 : (e 3 8) := Classical.byContradiction (fun hu => c850 e tri schur hu v9 v16)
  have v19 : (e 2 3) := Classical.byContradiction (fun hu => c1443 e tri schur h0 v1 v18 v5 v11 v6 h3 hu h4 v8 v9 v17 v13)
  have v20 : (¬ e 2 8) := fun hu => c140 e tri schur v18 hu v19
  have v21 : (¬ e 3 13) := fun hu => c145 e tri schur hu v15 v19
  have v22 : (¬ e 3 10) := fun hu => c1324 e tri schur hu v18 v19
  have v23 : (e 10 13) := Classical.byContradiction (fun hu => c852 e tri schur v22 v21 hu)
  have v24 : (¬ e 2 10) := fun hu => c222 e tri schur v23 v15 hu
  have v25 : (e 8 10) := Classical.byContradiction (fun hu => c837 e tri schur v20 v24 hu)
  have v26 : (e 10 12) := Classical.byContradiction (fun hu => c839 e tri schur v24 v8 hu)
  have v27 : (¬ e 4 10) := fun hu => c417 e tri schur v26 h1 hu
  have v28 : (¬ e 8 12) := fun hu => c661 e tri schur v26 hu v25
  have v29 : (¬ e 8 13) := fun hu => c662 e tri schur v23 hu v25
  have v30 : (¬ e 10 11) := fun hu => c732 e tri schur h0 v26 hu
  have v31 : (¬ e 12 13) := fun hu => c739 e tri schur hu v23 v26
  have v32 : (e 1 13) := Classical.byContradiction (fun hu => c826 e tri schur h3 hu v31)
  have v33 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v27 v4 hu)
  have v34 : (¬ e 6 10) := fun hu => c1373 e tri schur v33 v25 hu
  have v35 : (¬ e 1 2) := fun hu => c10 e tri schur v15 v32 hu
  have v36 : (¬ e 1 10) := fun hu => c102 e tri schur v23 v32 hu
  have v37 : (¬ e 8 14) := fun hu => c663 e tri schur v33 hu v25
  have v38 : (¬ e 12 14) := fun hu => c740 e tri schur hu v33 v26
  have v39 : (¬ e 13 14) := fun hu => c745 e tri schur hu v33 v23
  have v40 : (e 9 10) := Classical.byContradiction (fun hu => c823 e tri schur v6 v36 hu)
  have v41 : (e 2 14) := Classical.byContradiction (fun hu => c841 e tri schur v8 hu v38)
  have v42 : (e 4 6) := Classical.byContradiction (fun hu => c859 e tri schur hu v27 v34)
  have v43 : (¬ e 6 12) := fun hu => c1017 e tri schur v26 hu h1 v34
  have v44 : (¬ e 4 9) := fun hu => c1194 e tri schur v1 hu v42
  have v45 : (¬ e 1 6) := fun hu => c32 e tri schur v42 hu h2
  have v46 : (¬ e 3 14) := fun hu => c146 e tri schur hu v41 v19
  have v47 : (¬ e 6 15) := fun hu => c382 e tri schur hu v1 v42
  have v48 : (¬ e 8 9) := fun hu => c651 e tri schur v40 v25 hu
  have v49 : (¬ e 9 13) := fun hu => c698 e tri schur v23 hu v40
  have v50 : (¬ e 9 14) := fun hu => c699 e tri schur v33 hu v40
  have v51 : (e 1 8) := Classical.byContradiction (fun hu => c822 e tri schur hu v6 v48)
  have v52 : (e 11 14) := Classical.byContradiction (fun hu => c853 e tri schur v9 v46 hu)
  exact c862 e tri schur v44 v3 v49

theorem c1445 : (e 4 15) → (e 4 12) → (e 3 8) → (e 1 13) → (e 1 11) → (¬ e 1 3) → (¬ e 1 9) → (¬ e 2 11) → (¬ e 2 12) → (¬ e 4 13) → (¬ e 4 14) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10
  have v0 : (¬ e 11 13) := fun hu => c109 e tri schur hu h3 h4
  have v1 : (¬ e 12 15) := fun hu => c433 e tri schur hu h0 h1
  have v2 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur h7 hu v0)
  have v3 : (¬ e 3 4) := fun hu => c1188 e tri schur h0 h1 hu
  have v4 : (¬ e 1 2) := fun hu => c10 e tri schur v2 h3 hu
  have v5 : (e 2 3) := Classical.byContradiction (fun hu => c816 e tri schur v4 h5 hu)
  have v6 : (e 1 4) := Classical.byContradiction (fun hu => c817 e tri schur h5 hu v3)
  have v7 : (¬ e 3 10) := fun hu => c1324 e tri schur hu h2 v5
  have v8 : (¬ e 4 11) := fun hu => c37 e tri schur hu h4 v6
  have v9 : (¬ e 1 12) := fun hu => c38 e tri schur h1 hu v6
  have v10 : (¬ e 1 15) := fun hu => c41 e tri schur h0 hu v6
  have v11 : (¬ e 2 8) := fun hu => c140 e tri schur h2 hu v5
  have v12 : (¬ e 3 13) := fun hu => c145 e tri schur hu v2 v5
  have v13 : (e 10 13) := Classical.byContradiction (fun hu => c852 e tri schur v7 v12 hu)
  have v14 : (¬ e 1 10) := fun hu => c102 e tri schur v13 h3 hu
  have v15 : (¬ e 2 10) := fun hu => c222 e tri schur v13 v2 hu
  have v16 : (e 9 10) := Classical.byContradiction (fun hu => c823 e tri schur h6 v14 hu)
  have v17 : (e 8 10) := Classical.byContradiction (fun hu => c837 e tri schur v11 v15 hu)
  have v18 : (e 10 12) := Classical.byContradiction (fun hu => c839 e tri schur v15 h8 hu)
  have v19 : (¬ e 4 10) := fun hu => c417 e tri schur v18 h1 hu
  have v20 : (¬ e 8 9) := fun hu => c651 e tri schur v16 v17 hu
  have v21 : (¬ e 8 12) := fun hu => c661 e tri schur v18 hu v17
  have v22 : (¬ e 8 13) := fun hu => c662 e tri schur v13 hu v17
  have v23 : (¬ e 9 12) := fun hu => c697 e tri schur v18 hu v16
  have v24 : (¬ e 9 13) := fun hu => c698 e tri schur v13 hu v16
  have v25 : (¬ e 12 13) := fun hu => c739 e tri schur hu v13 v18
  have v26 : (e 1 8) := Classical.byContradiction (fun hu => c822 e tri schur hu h6 v20)
  have v27 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu h9 v24)
  have v28 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v19 h10 hu)
  have v29 : (¬ e 4 6) := fun hu => c1194 e tri schur h0 v27 hu
  have v30 : (¬ e 6 10) := fun hu => c1373 e tri schur v28 v17 hu
  have v31 : (¬ e 4 8) := fun hu => c34 e tri schur hu v26 v6
  have v32 : (¬ e 8 11) := fun hu => c83 e tri schur hu h4 v26
  have v33 : (¬ e 9 15) := fun hu => c412 e tri schur hu h0 v27
  have v34 : (¬ e 8 14) := fun hu => c663 e tri schur v28 hu v17
  have v35 : (¬ e 9 14) := fun hu => c699 e tri schur v28 hu v16
  have v36 : (¬ e 12 14) := fun hu => c740 e tri schur hu v28 v18
  have v37 : (¬ e 13 14) := fun hu => c745 e tri schur hu v28 v13
  have v38 : (e 2 14) := Classical.byContradiction (fun hu => c841 e tri schur h8 hu v36)
  exact c859 e tri schur v29 v19 v30

theorem c1446 : (e 12 13) → (e 2 13) → (e 2 3) → (¬ e 2 12) → (¬ e 3 10) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 3 13) := fun hu => c145 e tri schur hu h1 h2
  have v1 : (e 10 13) := Classical.byContradiction (fun hu => c852 e tri schur h4 v0 hu)
  have v2 : (¬ e 2 10) := fun hu => c222 e tri schur v1 h1 hu
  have v3 : (¬ e 10 12) := fun hu => c739 e tri schur h0 v1 hu
  exact c839 e tri schur v2 h3 v3

theorem c1447 : (e 12 13) → (e 4 15) → (e 4 12) → (¬ e 2 8) → (¬ e 2 10) → (¬ e 2 12) → (¬ e 3 10) → (¬ e 4 13) → (¬ e 4 14) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8
  have v0 : (¬ e 12 15) := fun hu => c433 e tri schur hu h1 h2
  have v1 : (e 8 10) := Classical.byContradiction (fun hu => c837 e tri schur h3 h4 hu)
  have v2 : (e 10 12) := Classical.byContradiction (fun hu => c839 e tri schur h4 h5 hu)
  have v3 : (¬ e 3 4) := fun hu => c1188 e tri schur h1 h2 hu
  have v4 : (¬ e 4 10) := fun hu => c417 e tri schur v2 h2 hu
  have v5 : (¬ e 8 12) := fun hu => c661 e tri schur v2 hu v1
  have v6 : (¬ e 10 13) := fun hu => c739 e tri schur h0 hu v2
  have v7 : (e 3 13) := Classical.byContradiction (fun hu => c852 e tri schur h6 hu v6)
  have v8 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v4 h8 hu)
  have v9 : (¬ e 6 10) := fun hu => c1373 e tri schur v8 v1 hu
  have v10 : (¬ e 9 13) := fun hu => c1392 e tri schur h0 hu v7
  have v11 : (¬ e 3 12) := fun hu => c340 e tri schur h0 v7 hu
  have v12 : (¬ e 8 14) := fun hu => c663 e tri schur v8 hu v1
  have v13 : (¬ e 12 14) := fun hu => c740 e tri schur hu v8 v2
  have v14 : (e 2 14) := Classical.byContradiction (fun hu => c841 e tri schur h5 hu v13)
  have v15 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur v11 hu v0)
  have v16 : (e 4 6) := Classical.byContradiction (fun hu => c859 e tri schur hu v4 v9)
  have v17 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu h7 v10)
  have v18 : (¬ e 6 12) := fun hu => c1017 e tri schur v2 hu h2 v9
  have v19 : (¬ e 7 15) := fun hu => c1023 e tri schur hu h1 v15
  exact c1194 e tri schur h1 v17 v16

theorem c1448 : (e 10 12) → (e 4 12) → (e 2 10) → (¬ e 2 12) → (¬ e 4 14) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 4 10) := fun hu => c417 e tri schur h0 h1 hu
  have v1 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v0 h4 hu)
  have v2 : (¬ e 2 14) := fun hu => c223 e tri schur v1 hu h2
  have v3 : (¬ e 12 14) := fun hu => c740 e tri schur hu v1 h0
  exact c841 e tri schur h3 v2 v3

theorem c1449 : (e 11 13) → (e 4 15) → (e 3 8) → (e 2 10) → (e 2 3) → (e 1 14) → (e 1 11) → (e 1 4) → (¬ e 1 9) → (¬ e 2 11) → (¬ e 3 11) → (¬ e 4 11) → (¬ e 4 13) → (¬ e 12 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13
  have v0 : (¬ e 4 14) := fun hu => c40 e tri schur hu h5 h7
  have v1 : (¬ e 1 15) := fun hu => c41 e tri schur h1 hu h7
  have v2 : (¬ e 1 13) := fun hu => c109 e tri schur h0 hu h6
  have v3 : (¬ e 11 14) := fun hu => c110 e tri schur hu h5 h6
  have v4 : (¬ e 2 8) := fun hu => c140 e tri schur h2 hu h4
  have v5 : (¬ e 3 10) := fun hu => c142 e tri schur hu h3 h4
  have v6 : (e 3 14) := Classical.byContradiction (fun hu => c853 e tri schur h10 hu v3)
  have v7 : (¬ e 3 6) := fun hu => c950 e tri schur v6 h2 hu
  have v8 : (¬ e 3 12) := fun hu => c1323 e tri schur v6 hu h4
  have v9 : (¬ e 1 10) := fun hu => c1343 e tri schur h5 hu h7
  have v10 : (¬ e 14 15) := fun hu => c1387 e tri schur hu v6 h4 h13
  have v11 : (¬ e 1 3) := fun hu => c1440 e tri schur h5 h6 hu h10
  have v12 : (¬ e 2 14) := fun hu => c146 e tri schur v6 hu h4
  have v13 : (¬ e 8 14) := fun hu => c311 e tri schur hu v6 h2
  have v14 : (e 9 10) := Classical.byContradiction (fun hu => c823 e tri schur h8 v9 hu)
  have v15 : (e 3 15) := Classical.byContradiction (fun hu => c854 e tri schur v8 hu h13)
  have v16 : (¬ e 7 15) := fun hu => c1023 e tri schur hu h1 v15
  have v17 : (¬ e 2 15) := fun hu => c147 e tri schur v15 hu h4
  have v18 : (¬ e 2 9) := fun hu => c211 e tri schur v14 h3 hu
  have v19 : (¬ e 3 4) := fun hu => c266 e tri schur h1 v15 hu
  have v20 : (¬ e 8 15) := fun hu => c312 e tri schur hu v15 h2
  have v21 : (e 9 11) := Classical.byContradiction (fun hu => c838 e tri schur v18 h9 hu)
  have v22 : (e 7 8) := Classical.byContradiction (fun hu => c882 e tri schur hu v16 v20)
  have v23 : (¬ e 2 7) := fun hu => c1076 e tri schur v22 hu h4 v5
  exact c1376 e tri schur h0 v23 v18 h9 h11 h12

theorem c1450 : (e 12 13) → (e 4 15) → (e 4 12) → (e 3 8) → (e 2 3) → (e 1 11) → (e 1 4) → (¬ e 1 9) → (¬ e 1 13) → (¬ e 2 11) → (¬ e 2 12) → (¬ e 3 11) → (¬ e 4 11) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12
  have v0 : (¬ e 1 12) := fun hu => c38 e tri schur h2 hu h6
  have v1 : (¬ e 1 15) := fun hu => c41 e tri schur h1 hu h6
  have v2 : (¬ e 2 8) := fun hu => c140 e tri schur h3 hu h4
  have v3 : (¬ e 4 13) := fun hu => c431 e tri schur h0 hu h2
  have v4 : (¬ e 12 15) := fun hu => c433 e tri schur hu h1 h2
  have v5 : (¬ e 3 4) := fun hu => c1188 e tri schur h1 h2 hu
  have v6 : (¬ e 3 10) := fun hu => c1324 e tri schur hu h3 h4
  have v7 : (¬ e 4 14) := fun hu => c1410 e tri schur h1 hu h6
  have v8 : (¬ e 2 13) := fun hu => c1446 e tri schur h0 hu h4 h10 v6
  have v9 : (e 2 10) := Classical.byContradiction (fun hu => c1447 e tri schur h0 h1 h2 v2 hu h10 v6 v3 v7)
  have v10 : (¬ e 10 12) := fun hu => c1448 e tri schur hu h2 v9 h10 v7
  have v11 : (e 11 13) := Classical.byContradiction (fun hu => c840 e tri schur h9 v8 hu)
  have v12 : (¬ e 11 12) := fun hu => c1422 e tri schur v11 hu h5 v0
  have v13 : (¬ e 1 14) := fun hu => c1449 e tri schur v11 h1 h3 v9 h4 hu h5 h6 h7 h9 h11 h12 v3 v4
  have v14 : (e 13 14) := Classical.byContradiction (fun hu => c827 e tri schur h8 v13 hu)
  have v15 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v13 v1 hu)
  have v16 : (¬ e 3 14) := fun hu => c1387 e tri schur v15 hu h4 v4
  have v17 : (¬ e 11 14) := fun hu => c766 e tri schur v14 hu v11
  have v18 : (¬ e 12 14) := fun hu => c781 e tri schur v14 hu h0
  have v19 : (¬ e 13 15) := fun hu => c796 e tri schur v15 hu v14
  have v20 : (e 2 14) := Classical.byContradiction (fun hu => c841 e tri schur h10 hu v18)
  have v21 : (e 2 15) := Classical.byContradiction (fun hu => c842 e tri schur v8 hu v19)
  exact c853 e tri schur h11 v16 v17

theorem c1451 : (e 11 13) → (e 4 15) → (e 1 2) → (¬ e 1 6) → (¬ e 2 4) → (¬ e 2 9) → (¬ e 2 11) → (¬ e 4 11) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8
  have v0 : (e 9 11) := Classical.byContradiction (fun hu => c838 e tri schur h5 h6 hu)
  have v1 : (e 2 7) := Classical.byContradiction (fun hu => c1376 e tri schur h0 hu h5 h6 h7 h8)
  have v2 : (¬ e 1 7) := fun hu => c4 e tri schur v1 hu h2
  have v3 : (¬ e 9 13) := fun hu => c705 e tri schur h0 hu v0
  have v4 : (e 6 7) := Classical.byContradiction (fun hu => c820 e tri schur h3 v2 hu)
  have v5 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu h8 v3)
  have v6 : (¬ e 4 6) := fun hu => c1194 e tri schur h1 v5 hu
  have v7 : (¬ e 2 6) := fun hu => c178 e tri schur v4 v1 hu
  have v8 : (¬ e 9 15) := fun hu => c412 e tri schur hu h1 v5
  exact c833 e tri schur h4 v7 v6

theorem c1452 : (e 9 10) → (e 4 15) → (e 4 9) → (e 2 10) → (¬ e 2 4) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 2 9) := fun hu => c211 e tri schur h0 h3 hu
  have v1 : (¬ e 4 10) := fun hu => c407 e tri schur h0 hu h2
  have v2 : (¬ e 9 15) := fun hu => c412 e tri schur hu h1 h2
  have v3 : (¬ e 4 6) := fun hu => c1194 e tri schur h1 h2 hu
  have v4 : (e 2 6) := Classical.byContradiction (fun hu => c833 e tri schur h4 hu v3)
  have v5 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur v3 v1 hu)
  have v6 : (¬ e 2 16) := fun hu => c994 e tri schur hu h3 v4
  exact c181 e tri schur v5 h3 v4

theorem c1453 : (e 9 11) → (e 9 10) → (e 4 15) → (e 2 10) → (e 1 2) → (¬ e 1 6) → (¬ e 2 4) → (¬ e 4 6) → (¬ e 11 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8
  have v0 : (¬ e 1 10) := fun hu => c7 e tri schur h3 hu h4
  have v1 : (¬ e 2 9) := fun hu => c211 e tri schur h1 h3 hu
  have v2 : (¬ e 10 11) := fun hu => c696 e tri schur hu h0 h1
  have v3 : (e 1 11) := Classical.byContradiction (fun hu => c824 e tri schur v0 hu v2)
  have v4 : (e 2 6) := Classical.byContradiction (fun hu => c833 e tri schur h6 hu h7)
  have v5 : (¬ e 2 16) := fun hu => c994 e tri schur hu h3 v4
  have v6 : (¬ e 4 9) := fun hu => c1452 e tri schur h1 h2 hu h3 h6
  have v7 : (¬ e 2 11) := fun hu => c8 e tri schur hu v3 h4
  have v8 : (¬ e 1 9) := fun hu => c92 e tri schur h0 v3 hu
  have v9 : (¬ e 6 10) := fun hu => c181 e tri schur hu h3 v4
  have v10 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur v7 hu h8)
  have v11 : (e 4 10) := Classical.byContradiction (fun hu => c859 e tri schur h7 hu v9)
  have v12 : (¬ e 8 11) := fun hu => c1427 e tri schur h0 hu v3 v8
  have v13 : (¬ e 4 5) := fun hu => c1429 e tri schur h2 v11 hu
  have v14 : (¬ e 1 13) := fun hu => c10 e tri schur v10 hu h4
  have v15 : (¬ e 6 13) := fun hu => c184 e tri schur hu v10 v4
  have v16 : (¬ e 10 13) := fun hu => c222 e tri schur hu v10 h3
  have v17 : (¬ e 10 15) := fun hu => c420 e tri schur hu h2 v11
  have v18 : (e 5 9) := Classical.byContradiction (fun hu => c858 e tri schur v13 v6 hu)
  have v19 : (¬ e 5 10) := fun hu => c485 e tri schur h1 hu v18
  have v20 : (¬ e 5 11) := fun hu => c486 e tri schur h0 hu v18
  have v21 : (e 5 15) := Classical.byContradiction (fun hu => c872 e tri schur v19 hu v17)
  have v22 : (¬ e 5 6) := fun hu => c1412 e tri schur h1 hu h2 v11 v19
  have v23 : (¬ e 9 15) := fun hu => c490 e tri schur hu v21 v18
  have v24 : (e 1 5) := Classical.byContradiction (fun hu => c819 e tri schur hu h5 v22)
  have v25 : (e 6 11) := Classical.byContradiction (fun hu => c868 e tri schur v22 v20 hu)
  have v26 : (¬ e 2 7) := fun hu => c947 e tri schur v25 hu v4 h8
  have v27 : (¬ e 2 5) := fun hu => c2 e tri schur hu v24 h4
  have v28 : (¬ e 1 15) := fun hu => c54 e tri schur v21 hu v24
  have v29 : (¬ e 6 9) := fun hu => c552 e tri schur h0 v25 hu
  have v30 : (e 5 7) := Classical.byContradiction (fun hu => c834 e tri schur v27 v26 hu)
  have v31 : (e 7 9) := Classical.byContradiction (fun hu => c836 e tri schur v26 v1 hu)
  have v32 : (e 6 15) := Classical.byContradiction (fun hu => c878 e tri schur v29 hu v23)
  have v33 : (¬ e 4 7) := fun hu => c925 e tri schur hu v27 v26 v1
  have v34 : (¬ e 11 15) := fun hu => c953 e tri schur hu h0 v25 v29
  have v35 : (¬ e 1 7) := fun hu => c46 e tri schur v30 hu v24
  have v36 : (¬ e 2 15) := fun hu => c186 e tri schur v32 hu v4
  exact c465 e tri schur v31 v18 v30

theorem c1454 : (e 9 11) → (e 9 10) → (e 4 15) → (e 4 10) → (¬ e 4 9) → (¬ e 6 15) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 10 15) := fun hu => c420 e tri schur hu h2 h3
  have v1 : (¬ e 10 11) := fun hu => c696 e tri schur hu h0 h1
  have v2 : (¬ e 4 5) := fun hu => c1429 e tri schur h2 h3 hu
  have v3 : (e 5 9) := Classical.byContradiction (fun hu => c858 e tri schur v2 h4 hu)
  have v4 : (¬ e 5 10) := fun hu => c485 e tri schur h1 hu v3
  have v5 : (¬ e 5 11) := fun hu => c486 e tri schur h0 hu v3
  have v6 : (e 5 15) := Classical.byContradiction (fun hu => c872 e tri schur v4 hu v0)
  have v7 : (¬ e 5 6) := fun hu => c1412 e tri schur h1 hu h2 h3 v4
  have v8 : (¬ e 9 15) := fun hu => c490 e tri schur hu v6 v3
  have v9 : (e 6 11) := Classical.byContradiction (fun hu => c868 e tri schur v7 v5 hu)
  have v10 : (e 6 9) := Classical.byContradiction (fun hu => c878 e tri schur hu h5 v8)
  have v11 : (¬ e 6 10) := fun hu => c551 e tri schur h1 hu v10
  exact c552 e tri schur h0 v9 v10

theorem c1455 : (e 12 13) → (e 4 15) → (e 2 10) → (e 1 11) → (e 1 2) → (¬ e 1 6) → (¬ e 1 9) → (¬ e 1 13) → (¬ e 2 4) → (¬ e 2 11) → (¬ e 2 12) → (¬ e 3 11) → (¬ e 4 11) → (¬ e 4 13) → (¬ e 4 14) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14
  have v0 : (¬ e 1 10) := fun hu => c7 e tri schur h2 hu h4
  have v1 : (e 9 10) := Classical.byContradiction (fun hu => c823 e tri schur h6 v0 hu)
  have v2 : (¬ e 4 9) := fun hu => c1452 e tri schur v1 h1 hu h2 h8
  have v3 : (¬ e 2 9) := fun hu => c211 e tri schur v1 h2 hu
  have v4 : (e 9 11) := Classical.byContradiction (fun hu => c838 e tri schur v3 h9 hu)
  have v5 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v2 h13 hu)
  have v6 : (¬ e 3 13) := fun hu => c1392 e tri schur h0 v5 hu
  have v7 : (¬ e 8 11) := fun hu => c1427 e tri schur v4 hu h3 h6
  have v8 : (¬ e 11 13) := fun hu => c1451 e tri schur hu h1 h4 h5 h8 v3 h9 h12 h13
  have v9 : (e 4 6) := Classical.byContradiction (fun hu => c1453 e tri schur v4 v1 h1 h2 h4 h5 h8 hu v8)
  have v10 : (¬ e 6 15) := fun hu => c382 e tri schur hu h1 v9
  have v11 : (¬ e 10 11) := fun hu => c696 e tri schur hu v4 v1
  have v12 : (¬ e 10 13) := fun hu => c698 e tri schur hu v5 v1
  have v13 : (¬ e 9 12) := fun hu => c711 e tri schur h0 v5 hu
  have v14 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur h9 hu v8)
  have v15 : (e 3 8) := Classical.byContradiction (fun hu => c850 e tri schur hu h11 v7)
  have v16 : (e 3 10) := Classical.byContradiction (fun hu => c852 e tri schur hu v6 v12)
  have v17 : (¬ e 3 18) := fun hu => c963 e tri schur hu v16 v15
  have v18 : (¬ e 2 3) := fun hu => c1324 e tri schur v16 v15 hu
  have v19 : (¬ e 4 10) := fun hu => c1454 e tri schur v4 v1 h1 hu v2 v10
  have v20 : (¬ e 8 10) := fun hu => c307 e tri schur hu v16 v15
  have v21 : (¬ e 3 9) := fun hu => c316 e tri schur v1 v16 hu
  have v22 : (e 3 12) := Classical.byContradiction (fun hu => c851 e tri schur v21 hu v13)
  have v23 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v19 h14 hu)
  have v24 : (¬ e 2 14) := fun hu => c223 e tri schur v23 hu h2
  have v25 : (¬ e 8 12) := fun hu => c309 e tri schur hu v22 v15
  have v26 : (¬ e 10 12) := fun hu => c326 e tri schur hu v22 v16
  have v27 : (¬ e 3 14) := fun hu => c328 e tri schur v23 hu v16
  have v28 : (¬ e 9 14) := fun hu => c699 e tri schur v23 hu v1
  have v29 : (e 12 14) := Classical.byContradiction (fun hu => c841 e tri schur h10 v24 hu)
  have v30 : (e 11 14) := Classical.byContradiction (fun hu => c853 e tri schur h11 v27 hu)
  have v31 : (¬ e 3 4) := fun hu => c915 e tri schur v22 v15 hu v25
  have v32 : (¬ e 11 12) := fun hu => c1396 e tri schur v29 hu v22 h11
  have v33 : (¬ e 1 14) := fun hu => c110 e tri schur v30 hu h3
  have v34 : (¬ e 13 14) := fun hu => c781 e tri schur hu v29 h0
  exact c827 e tri schur h7 v33 v34

theorem c1456 : (e 4 15) → (e 4 12) → (e 3 8) → (e 1 4) → (¬ e 1 3) → (¬ e 1 9) → (¬ e 1 12) → (¬ e 2 11) → (¬ e 2 12) → (¬ e 3 11) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9
  have v0 : (¬ e 1 15) := fun hu => c41 e tri schur h0 hu h3
  have v1 : (¬ e 12 15) := fun hu => c433 e tri schur hu h0 h1
  have v2 : (¬ e 3 4) := fun hu => c1188 e tri schur h0 h1 hu
  have v3 : (¬ e 4 13) := fun hu => c1260 e tri schur hu h1 h3
  have v4 : (¬ e 4 11) := fun hu => c1335 e tri schur h1 hu h3 h6
  have v5 : (¬ e 4 14) := fun hu => c1410 e tri schur h0 hu h3
  have v6 : (e 1 11) := Classical.byContradiction (fun hu => c1419 e tri schur h0 h1 h3 hu h6)
  have v7 : (¬ e 1 13) := fun hu => c1445 e tri schur h0 h1 h2 hu v6 h4 h5 h7 h8 v3 v5
  have v8 : (e 12 13) := Classical.byContradiction (fun hu => c826 e tri schur h6 v7 hu)
  have v9 : (¬ e 2 3) := fun hu => c1450 e tri schur v8 h0 h1 h2 hu v6 h3 h5 v7 h7 h8 h9 v4
  have v10 : (e 1 2) := Classical.byContradiction (fun hu => c816 e tri schur hu h4 v9)
  have v11 : (¬ e 1 6) := fun hu => c1394 e tri schur hu h3 v10
  have v12 : (¬ e 2 4) := fun hu => c1 e tri schur hu h3 v10
  have v13 : (¬ e 2 10) := fun hu => c1455 e tri schur v8 h0 hu v6 v10 v11 h5 v7 v12 h7 h8 h9 v4 v3 v5
  have v14 : (e 10 12) := Classical.byContradiction (fun hu => c839 e tri schur v13 h8 hu)
  have v15 : (¬ e 4 10) := fun hu => c417 e tri schur v14 h1 hu
  have v16 : (¬ e 10 13) := fun hu => c739 e tri schur v8 hu v14
  have v17 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v15 v5 hu)
  have v18 : (¬ e 12 14) := fun hu => c740 e tri schur hu v17 v14
  have v19 : (e 2 14) := Classical.byContradiction (fun hu => c841 e tri schur h8 hu v18)
  have v20 : (¬ e 1 14) := fun hu => c11 e tri schur v19 hu v10
  have v21 : (e 13 14) := Classical.byContradiction (fun hu => c827 e tri schur v7 v20 hu)
  have v22 : (e 14 15) := Classical.byContradiction (fun hu => c828 e tri schur v20 v0 hu)
  have v23 : (¬ e 2 13) := fun hu => c1352 e tri schur v19 hu v10 v20
  have v24 : (¬ e 11 12) := fun hu => c1359 e tri schur hu h6 v7 v20 h7
  have v25 : (¬ e 3 14) := fun hu => c1366 e tri schur v21 v17 hu v16
  have v26 : (¬ e 2 15) := fun hu => c246 e tri schur v22 hu v19
  have v27 : (¬ e 10 15) := fun hu => c750 e tri schur v22 hu v17
  have v28 : (¬ e 13 15) := fun hu => c796 e tri schur v22 hu v21
  have v29 : (e 11 13) := Classical.byContradiction (fun hu => c840 e tri schur h7 v23 hu)
  exact c842 e tri schur v23 v26 v28

theorem c1458 : (e 14 15) → (e 1 11) → (¬ e 1 14) → (¬ e 2 11) → (¬ e 2 13) → (¬ e 2 15) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (e 11 13) := Classical.byContradiction (fun hu => c840 e tri schur h3 h4 hu)
  have v1 : (e 13 15) := Classical.byContradiction (fun hu => c842 e tri schur h4 h5 hu)
  have v2 : (¬ e 4 13) := fun hu => c1187 e tri schur v1 v0 hu
  have v3 : (¬ e 1 13) := fun hu => c109 e tri schur v0 hu h1
  have v4 : (¬ e 11 15) := fun hu => c767 e tri schur v1 hu v0
  have v5 : (¬ e 13 14) := fun hu => c796 e tri schur h0 v1 hu
  exact c827 e tri schur v3 h2 v5

theorem c1459 : (e 14 15) → (e 10 12) → (e 8 9) → (e 4 15) → (e 4 12) → (e 3 8) → (e 1 11) → (e 1 3) → (¬ e 1 9) → (¬ e 1 14) → (¬ e 2 11) → (¬ e 2 12) → (¬ e 4 13) → (¬ e 4 14) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13
  have v0 : (¬ e 1 8) := fun hu => c20 e tri schur h5 hu h7
  have v1 : (¬ e 3 11) := fun hu => c23 e tri schur hu h6 h7
  have v2 : (¬ e 3 9) := fun hu => c306 e tri schur h2 hu h5
  have v3 : (¬ e 4 10) := fun hu => c417 e tri schur h1 h4 hu
  have v4 : (¬ e 12 15) := fun hu => c433 e tri schur hu h3 h4
  have v5 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v3 h13 hu)
  have v6 : (¬ e 3 4) := fun hu => c1188 e tri schur h3 h4 hu
  have v7 : (¬ e 2 10) := fun hu => c1448 e tri schur h1 h4 hu h11 h13
  have v8 : (¬ e 12 14) := fun hu => c740 e tri schur hu v5 h1
  have v9 : (¬ e 10 15) := fun hu => c750 e tri schur h0 hu v5
  have v10 : (e 2 14) := Classical.byContradiction (fun hu => c841 e tri schur h11 hu v8)
  have v11 : (¬ e 2 15) := fun hu => c246 e tri schur h0 hu v10
  have v12 : (e 2 13) := Classical.byContradiction (fun hu => c1458 e tri schur h0 h6 h9 h10 hu v11)
  have v13 : (¬ e 13 14) := fun hu => c241 e tri schur hu v10 v12
  have v14 : (e 1 13) := Classical.byContradiction (fun hu => c827 e tri schur hu h9 v13)
  have v15 : (¬ e 1 2) := fun hu => c1352 e tri schur v10 v12 hu h9
  have v16 : (¬ e 1 10) := fun hu => c1357 e tri schur v14 hu h7
  have v17 : (¬ e 3 13) := fun hu => c25 e tri schur hu v14 h7
  have v18 : (¬ e 11 13) := fun hu => c109 e tri schur hu v14 h6
  have v19 : (e 9 10) := Classical.byContradiction (fun hu => c823 e tri schur h8 v16 hu)
  have v20 : (¬ e 8 10) := fun hu => c651 e tri schur v19 hu h2
  have v21 : (¬ e 9 12) := fun hu => c697 e tri schur h1 hu v19
  have v22 : (¬ e 9 14) := fun hu => c699 e tri schur v5 hu v19
  have v23 : (e 2 8) := Classical.byContradiction (fun hu => c837 e tri schur hu v7 v20)
  have v24 : (e 3 12) := Classical.byContradiction (fun hu => c851 e tri schur v2 hu v21)
  have v25 : (¬ e 2 6) := fun hu => c1215 e tri schur v10 v23 hu
  have v26 : (¬ e 4 9) := fun hu => c1441 e tri schur v19 h3 hu h5 v10 v2 h13 v20
  have v27 : (¬ e 1 12) := fun hu => c24 e tri schur v24 hu h7
  have v28 : (¬ e 2 3) := fun hu => c140 e tri schur h5 v23 hu
  have v29 : (¬ e 2 9) := fun hu => c201 e tri schur h2 hu v23
  have v30 : (¬ e 8 13) := fun hu => c205 e tri schur hu v12 v23
  have v31 : (¬ e 8 14) := fun hu => c206 e tri schur hu v10 v23
  have v32 : (¬ e 8 12) := fun hu => c309 e tri schur hu v24 h5
  have v33 : (¬ e 3 10) := fun hu => c326 e tri schur h1 v24 hu
  have v34 : (e 9 11) := Classical.byContradiction (fun hu => c838 e tri schur v29 h10 hu)
  have v35 : (e 10 13) := Classical.byContradiction (fun hu => c852 e tri schur v33 v17 hu)
  have v36 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v26 h12 hu)
  have v37 : (¬ e 8 11) := fun hu => c1427 e tri schur v34 hu h6 h8
  have v38 : (e 4 5) := Classical.byContradiction (fun hu => c1432 e tri schur h2 hu v26 h12)
  have v39 : (¬ e 5 12) := fun hu => c367 e tri schur hu h4 v38
  have v40 : (¬ e 5 15) := fun hu => c370 e tri schur hu h3 v38
  have v41 : (¬ e 10 11) := fun hu => c696 e tri schur hu v34 v19
  exact c698 e tri schur v35 v36 v19

theorem c1460 : (e 8 9) → (e 4 15) → (e 4 10) → (e 2 10) → (e 1 4) → (¬ e 1 9) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 1 10) := fun hu => c36 e tri schur h2 hu h4
  have v1 : (¬ e 1 15) := fun hu => c41 e tri schur h1 hu h4
  have v2 : (¬ e 2 4) := fun hu => c156 e tri schur h2 h3 hu
  have v3 : (¬ e 10 15) := fun hu => c420 e tri schur hu h1 h2
  have v4 : (e 9 10) := Classical.byContradiction (fun hu => c823 e tri schur h5 v0 hu)
  have v5 : (¬ e 4 14) := fun hu => c1410 e tri schur h1 hu h4
  have v6 : (¬ e 4 5) := fun hu => c1429 e tri schur h1 h2 hu
  have v7 : (e 4 9) := Classical.byContradiction (fun hu => c1432 e tri schur h0 v6 hu h6)
  exact c1452 e tri schur v4 h1 v7 h3 v2

theorem c1461 : (e 9 10) → (e 4 15) → (e 4 12) → (e 4 9) → (e 1 3) → (¬ e 1 12) → (¬ e 3 9) → (¬ e 4 10) → (¬ e 10 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8
  have v0 : (¬ e 9 12) := fun hu => c409 e tri schur hu h2 h3
  have v1 : (¬ e 9 15) := fun hu => c412 e tri schur hu h1 h3
  have v2 : (¬ e 12 15) := fun hu => c433 e tri schur hu h1 h2
  have v3 : (e 3 12) := Classical.byContradiction (fun hu => c851 e tri schur h6 hu v0)
  have v4 : (¬ e 3 4) := fun hu => c1188 e tri schur h1 h2 hu
  have v5 : (¬ e 4 6) := fun hu => c1194 e tri schur h1 h3 hu
  have v6 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur v5 h7 hu)
  have v7 : (¬ e 6 9) := fun hu => c551 e tri schur h0 v6 hu
  have v8 : (e 3 6) := Classical.byContradiction (fun hu => c848 e tri schur hu h6 v7)
  have v9 : (e 6 15) := Classical.byContradiction (fun hu => c878 e tri schur v7 hu v1)
  have v10 : (¬ e 6 12) := fun hu => c1248 e tri schur hu h6 v7 v0
  have v11 : (¬ e 1 6) := fun hu => c18 e tri schur v8 hu h4
  have v12 : (¬ e 3 10) := fun hu => c286 e tri schur v6 hu v8
  have v13 : (¬ e 3 15) := fun hu => c291 e tri schur v9 hu v8
  have v14 : (¬ e 10 15) := fun hu => c564 e tri schur hu v9 v6
  have v15 : (e 3 13) := Classical.byContradiction (fun hu => c852 e tri schur v12 hu h8)
  have v16 : (¬ e 1 13) := fun hu => c25 e tri schur v15 hu h4
  have v17 : (¬ e 6 13) := fun hu => c289 e tri schur hu v15 v8
  have v18 : (¬ e 12 13) := fun hu => c340 e tri schur hu v15 v3
  exact c826 e tri schur h5 v16 v18

end Jsp746.Certificate
