/- Generated by scripts/generate_refutation.py from our own SAT trace.
Every statement below is proved with ordinary kernel-checked proof terms. -/
import Jsp746.Certificate.Steps02

namespace Jsp746.Certificate
variable (e : ℕ → ℕ → Prop)
variable (tri : TriangleCondition e) (schur : SchurCondition e)
include tri schur

theorem c1228 : (e 13 18) → (e 12 14) → (e 10 18) → (e 8 13) → (e 6 10) → (e 4 12) → (e 2 8) → (e 2 4) → (¬ e 2 9) → (¬ e 2 15) → (¬ e 4 13) → (¬ e 5 6) → (¬ e 5 8) → (¬ e 5 10) → (¬ e 5 14) → (¬ e 15 18) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14 h15
  have v0 : (¬ e 4 8) := fun hu => c154 e tri schur hu h6 h7
  have v1 : (¬ e 2 12) := fun hu => c158 e tri schur h5 hu h7
  have v2 : (¬ e 2 13) := fun hu => c205 e tri schur h3 hu h6
  have v3 : (¬ e 4 14) := fun hu => c432 e tri schur h1 hu h5
  have v4 : (¬ e 6 18) := fun hu => c567 e tri schur h2 hu h4
  have v5 : (¬ e 8 18) := fun hu => c685 e tri schur h0 hu h3
  have v6 : (¬ e 10 13) := fun hu => c749 e tri schur h0 h2 hu
  have v7 : (e 13 15) := Classical.byContradiction (fun hu => c842 e tri schur v2 h9 hu)
  have v8 : (¬ e 4 11) := fun hu => c1218 e tri schur hu h7 h8 v2
  have v9 : (e 3 15) := Classical.byContradiction (fun hu => c1224 e tri schur h0 v7 h2 hu h15)
  have v10 : (¬ e 3 13) := fun hu => c347 e tri schur v7 v9 hu
  have v11 : (¬ e 8 15) := fun hu => c682 e tri schur v7 hu h3
  have v12 : (e 3 10) := Classical.byContradiction (fun hu => c852 e tri schur hu v10 v6)
  have v13 : (¬ e 10 15) := fun hu => c1222 e tri schur h0 v7 h1 h2 hu h4 h5 h6 h7 h8 v2 h10 h11 h12 h14 v11 h15
  have v14 : (¬ e 3 6) := fun hu => c286 e tri schur h4 v12 hu
  have v15 : (¬ e 3 18) := fun hu => c332 e tri schur h2 hu v12
  have v16 : (e 5 15) := Classical.byContradiction (fun hu => c872 e tri schur h13 hu v13)
  have v17 : (¬ e 7 15) := fun hu => c1225 e tri schur v7 hu v16 v9 h7 h8 v2 h10 h11
  have v18 : (¬ e 3 5) := fun hu => c279 e tri schur v16 v9 hu
  have v19 : (¬ e 5 13) := fun hu => c516 e tri schur v7 v16 hu
  have v20 : (e 3 8) := Classical.byContradiction (fun hu => c847 e tri schur v18 hu h12)
  have v21 : (e 7 8) := Classical.byContradiction (fun hu => c882 e tri schur hu v17 v11)
  have v22 : (e 2 5) := Classical.byContradiction (fun hu => c1075 e tri schur v21 h6 hu v18)
  have v23 : (¬ e 5 17) := fun hu => c1129 e tri schur hu v16 v22 h9
  have v24 : (¬ e 2 3) := fun hu => c140 e tri schur v20 h6 hu
  have v25 : (¬ e 4 5) := fun hu => c151 e tri schur hu v22 h7
  have v26 : (¬ e 2 7) := fun hu => c190 e tri schur v21 h6 hu
  have v27 : (¬ e 3 7) := fun hu => c295 e tri schur v21 v20 hu
  have v28 : (¬ e 8 10) := fun hu => c307 e tri schur hu v12 v20
  have v29 : (¬ e 7 13) := fun hu => c600 e tri schur h3 hu v21
  have v30 : (e 7 9) := Classical.byContradiction (fun hu => c836 e tri schur v26 h8 hu)
  have v31 : (¬ e 4 9) := fun hu => c1223 e tri schur h0 v7 h2 v30 h5 hu h6 h8 v8 v11 h15
  have v32 : (¬ e 8 9) := fun hu => c596 e tri schur hu v30 v21
  have v33 : (e 5 9) := Classical.byContradiction (fun hu => c858 e tri schur v25 v31 hu)
  have v34 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v31 h10 hu)
  have v35 : (e 6 15) := Classical.byContradiction (fun hu => c1221 e tri schur v7 v34 v30 hu)
  have v36 : (¬ e 11 15) := fun hu => c1226 e tri schur hu v35 v16 h11
  have v37 : (¬ e 13 17) := fun hu => c1227 e tri schur hu v34 h3 v32
  have v38 : (¬ e 5 7) := fun hu => c465 e tri schur v30 v33 hu
  have v39 : (¬ e 9 15) := fun hu => c490 e tri schur hu v16 v33
  have v40 : (¬ e 6 13) := fun hu => c582 e tri schur v7 v35 hu
  have v41 : (¬ e 9 18) := fun hu => c721 e tri schur h0 hu v34
  have v42 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur v8 hu v36)
  have v43 : (e 4 17) := Classical.byContradiction (fun hu => c866 e tri schur h10 hu v37)
  have v44 : (e 6 7) := Classical.byContradiction (fun hu => c876 e tri schur hu v40 v29)
  have v45 : (¬ e 3 4) := fun hu => c1188 e tri schur v42 h5 hu
  have v46 : (¬ e 2 17) := fun hu => c163 e tri schur v43 hu h7
  have v47 : (¬ e 4 6) := fun hu => c382 e tri schur v35 v42 hu
  have v48 : (¬ e 12 15) := fun hu => c433 e tri schur hu v42 h5
  have v49 : (¬ e 12 17) := fun hu => c435 e tri schur hu v43 h5
  have v50 : (¬ e 15 17) := fun hu => c447 e tri schur hu v43 v42
  have v51 : (¬ e 6 8) := fun hu => c530 e tri schur v21 hu v44
  have v52 : (¬ e 6 9) := fun hu => c531 e tri schur v30 hu v44
  have v53 : (¬ e 7 10) := fun hu => c532 e tri schur hu h4 v44
  exact c844 e tri schur h9 v46 v50

theorem c1229 : (e 6 12) → (e 5 16) → (e 2 8) → (e 2 5) → (¬ e 2 12) → (¬ e 5 13) → (¬ e 10 12) → (¬ e 12 16) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 5 8) := fun hu => c167 e tri schur hu h2 h3
  have v1 : (¬ e 2 16) := fun hu => c175 e tri schur h1 hu h3
  have v2 : (e 2 10) := Classical.byContradiction (fun hu => c839 e tri schur hu h4 h6)
  have v3 : (e 8 13) := Classical.byContradiction (fun hu => c870 e tri schur v0 h5 hu)
  have v4 : (¬ e 2 18) := fun hu => c1208 e tri schur hu v2 h2
  have v5 : (¬ e 2 15) := fun hu => c1217 e tri schur hu v2 h3
  have v6 : (¬ e 5 10) := fun hu => c169 e tri schur hu v2 h3
  have v7 : (¬ e 8 10) := fun hu => c202 e tri schur hu v2 h2
  have v8 : (¬ e 2 13) := fun hu => c205 e tri schur v3 hu h2
  have v9 : (e 13 15) := Classical.byContradiction (fun hu => c842 e tri schur v8 v5 hu)
  have v10 : (e 16 18) := Classical.byContradiction (fun hu => c845 e tri schur v1 v4 hu)
  have v11 : (¬ e 5 18) := fun hu => c528 e tri schur v10 hu h1
  have v12 : (¬ e 8 15) := fun hu => c682 e tri schur v9 hu v3
  have v13 : (e 13 18) := Classical.byContradiction (fun hu => c875 e tri schur h5 v11 hu)
  have v14 : (¬ e 8 18) := fun hu => c685 e tri schur v13 hu v3
  have v15 : (¬ e 15 18) := fun hu => c802 e tri schur hu v13 v9
  have v16 : (¬ e 13 16) := fun hu => c804 e tri schur v10 v13 hu
  have v17 : (e 10 18) := Classical.byContradiction (fun hu => c887 e tri schur v7 v14 hu)
  have v18 : (¬ e 10 16) := fun hu => c1081 e tri schur v17 hu v2 v4
  have v19 : (¬ e 4 6) := fun hu => c1210 e tri schur v10 v17 h0 hu h2 v1 h7
  have v20 : (¬ e 4 16) := fun hu => c1214 e tri schur v17 hu v2 h2 v1 v19
  have v21 : (¬ e 2 14) := fun hu => c1216 e tri schur hu v2 h2 v19
  have v22 : (e 3 15) := Classical.byContradiction (fun hu => c1224 e tri schur v13 v9 v17 hu v15)
  have v23 : (¬ e 3 13) := fun hu => c347 e tri schur v9 v22 hu
  have v24 : (¬ e 10 13) := fun hu => c749 e tri schur v13 v17 hu
  have v25 : (e 12 14) := Classical.byContradiction (fun hu => c841 e tri schur h4 v21 hu)
  have v26 : (e 14 16) := Classical.byContradiction (fun hu => c843 e tri schur v21 v1 hu)
  have v27 : (e 3 10) := Classical.byContradiction (fun hu => c852 e tri schur hu v23 v24)
  have v28 : (e 3 16) := Classical.byContradiction (fun hu => c855 e tri schur v23 hu v16)
  have v29 : (e 4 12) := Classical.byContradiction (fun hu => c865 e tri schur hu v20 h7)
  have v30 : (¬ e 2 3) := fun hu => c142 e tri schur v27 v2 hu
  have v31 : (¬ e 3 5) := fun hu => c280 e tri schur h1 v28 hu
  have v32 : (¬ e 10 15) := fun hu => c329 e tri schur hu v22 v27
  have v33 : (¬ e 3 18) := fun hu => c332 e tri schur v17 hu v27
  have v34 : (¬ e 3 14) := fun hu => c352 e tri schur v26 v28 hu
  have v35 : (¬ e 15 16) := fun hu => c355 e tri schur hu v28 v22
  have v36 : (¬ e 4 14) := fun hu => c432 e tri schur v25 hu v29
  have v37 : (¬ e 5 14) := fun hu => c521 e tri schur v26 h1 hu
  have v38 : (¬ e 6 14) := fun hu => c576 e tri schur v25 hu h0
  have v39 : (¬ e 14 18) := fun hu => c810 e tri schur v10 hu v26
  have v40 : (e 3 8) := Classical.byContradiction (fun hu => c847 e tri schur v31 hu v0)
  have v41 : (e 4 18) := Classical.byContradiction (fun hu => c867 e tri schur v36 hu v39)
  have v42 : (e 5 15) := Classical.byContradiction (fun hu => c872 e tri schur v6 hu v32)
  have v43 : (¬ e 9 18) := fun hu => c892 e tri schur v13 hu v41
  have v44 : (¬ e 5 17) := fun hu => c1129 e tri schur hu v42 h3 v5
  have v45 : (¬ e 8 16) := fun hu => c313 e tri schur hu v28 v40
  have v46 : (¬ e 4 10) := fun hu => c423 e tri schur v17 v41 hu
  have v47 : (¬ e 12 18) := fun hu => c436 e tri schur hu v41 v29
  have v48 : (¬ e 4 13) := fun hu => c441 e tri schur v13 v41 hu
  have v49 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur v19 v46 hu)
  have v50 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v46 v36 hu)
  have v51 : (¬ e 2 6) := fun hu => c181 e tri schur v49 v2 hu
  have v52 : (¬ e 3 6) := fun hu => c286 e tri schur v49 v27 hu
  have v53 : (¬ e 6 18) := fun hu => c567 e tri schur v17 hu v49
  have v54 : (e 2 4) := Classical.byContradiction (fun hu => c833 e tri schur hu v51 v19)
  have v55 : (¬ e 2 9) := fun hu => c1118 e tri schur hu h3 v54
  have v56 : (¬ e 4 11) := fun hu => c1218 e tri schur hu v54 v55 v8
  have v57 : (e 5 6) := Classical.byContradiction (fun hu => c1228 e tri schur v13 v25 v17 v3 v49 v29 h2 v54 v55 v5 v48 hu v0 v6 v37 v15)
  have v58 : (¬ e 4 5) := fun hu => c151 e tri schur hu h3 v54
  have v59 : (¬ e 4 8) := fun hu => c154 e tri schur hu h2 v54
  have v60 : (¬ e 5 12) := fun hu => c457 e tri schur h0 hu v57
  have v61 : (¬ e 6 15) := fun hu => c460 e tri schur hu v42 v57
  have v62 : (¬ e 6 16) := fun hu => c461 e tri schur hu h1 v57
  have v63 : (e 12 17) := Classical.byContradiction (fun hu => c874 e tri schur v60 v44 hu)
  have v64 : (e 6 9) := Classical.byContradiction (fun hu => c1042 e tri schur v22 v52 hu v61)
  have v65 : (¬ e 4 17) := fun hu => c435 e tri schur v63 hu v29
  have v66 : (¬ e 5 9) := fun hu => c454 e tri schur v64 hu v57
  have v67 : (¬ e 9 10) := fun hu => c551 e tri schur hu v49 v64
  have v68 : (¬ e 9 12) := fun hu => c553 e tri schur hu h0 v64
  have v69 : (¬ e 6 17) := fun hu => c579 e tri schur v63 hu h0
  have v70 : (¬ e 14 17) := fun hu => c788 e tri schur hu v63 v25
  have v71 : (e 3 17) := Classical.byContradiction (fun hu => c856 e tri schur v34 hu v70)
  have v72 : (e 4 9) := Classical.byContradiction (fun hu => c858 e tri schur v58 hu v66)
  have v73 : (e 13 17) := Classical.byContradiction (fun hu => c866 e tri schur v48 v65 hu)
  have v74 : (e 9 14) := Classical.byContradiction (fun hu => c871 e tri schur v66 v37 hu)
  have v75 : (¬ e 7 9) := fun hu => c1223 e tri schur v13 v9 v17 hu v29 v72 h2 v55 v56 v12 v15
  have v76 : (¬ e 8 17) := fun hu => c314 e tri schur hu v71 v40
  have v77 : (¬ e 10 17) := fun hu => c331 e tri schur hu v71 v27
  have v78 : (¬ e 3 12) := fun hu => c344 e tri schur v63 v71 hu
  have v79 : (¬ e 15 17) := fun hu => c356 e tri schur hu v71 v22
  have v80 : (¬ e 16 17) := fun hu => c358 e tri schur hu v71 v28
  have v81 : (¬ e 9 16) := fun hu => c723 e tri schur v26 hu v74
  have v82 : (¬ e 12 13) := fun hu => c784 e tri schur v73 v63 hu
  have v83 : (¬ e 17 18) := fun hu => c805 e tri schur hu v13 v73
  have v84 : (e 2 7) := Classical.byContradiction (fun hu => c836 e tri schur hu v55 v75)
  have v85 : (e 2 17) := Classical.byContradiction (fun hu => c844 e tri schur v5 hu v79)
  have v86 : (e 3 9) := Classical.byContradiction (fun hu => c851 e tri schur hu v78 v68)
  have v87 : (e 7 16) := Classical.byContradiction (fun hu => c883 e tri schur v75 hu v81)
  have v88 : (¬ e 9 11) := fun hu => c948 e tri schur v74 hu v86
  have v89 : (¬ e 2 11) := fun hu => c1185 e tri schur hu v84 v54
  have v90 : (¬ e 4 7) := fun hu => c153 e tri schur hu v84 v54
  have v91 : (¬ e 5 7) := fun hu => c166 e tri schur hu v84 h3
  have v92 : (¬ e 7 8) := fun hu => c190 e tri schur hu h2 v84
  have v93 : (¬ e 7 10) := fun hu => c192 e tri schur hu v2 v84
  have v94 : (¬ e 7 17) := fun hu => c199 e tri schur hu v85 v84
  have v95 : (¬ e 3 4) := fun hu => c260 e tri schur v72 v86 hu
  have v96 : (¬ e 3 7) := fun hu => c303 e tri schur v87 v28 hu
  have v97 : (¬ e 8 9) := fun hu => c306 e tri schur hu v86 v40
  have v98 : (¬ e 9 15) := fun hu => c321 e tri schur hu v22 v86
  have v99 : (¬ e 9 17) := fun hu => c323 e tri schur hu v71 v86
  have v100 : (¬ e 7 14) := fun hu => c642 e tri schur v26 v87 hu
  have v101 : (¬ e 7 18) := fun hu => c649 e tri schur v10 hu v87
  exact c838 e tri schur v55 v89 v88

theorem c1230 : (e 5 15) → (e 2 12) → (e 2 5) → (¬ e 15 17) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 5 12) := fun hu => c171 e tri schur hu h1 h2
  have v1 : (¬ e 2 15) := fun hu => c174 e tri schur h0 hu h2
  have v2 : (e 2 17) := Classical.byContradiction (fun hu => c844 e tri schur v1 hu h3)
  have v3 : (¬ e 5 17) := fun hu => c1129 e tri schur hu h0 h2 v1
  have v4 : (¬ e 12 17) := fun hu => c239 e tri schur hu v2 h1
  exact c874 e tri schur v0 v3 v4

theorem c1231 : (e 2 17) → (e 2 12) → (e 2 5) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 5 12) := fun hu => c171 e tri schur hu h1 h2
  have v1 : (¬ e 5 17) := fun hu => c176 e tri schur hu h0 h2
  have v2 : (¬ e 12 17) := fun hu => c239 e tri schur hu h0 h1
  exact c874 e tri schur v0 v1 v2

theorem c1232 : (e 13 15) → (e 10 15) → (e 3 15) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 10) := fun hu => c329 e tri schur h1 h2 hu
  have v1 : (¬ e 3 13) := fun hu => c347 e tri schur h0 h2 hu
  have v2 : (¬ e 10 13) := fun hu => c746 e tri schur h0 h1 hu
  exact c852 e tri schur v0 v1 v2

theorem c1233 : (e 2 12) → (e 2 8) → (e 2 4) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 8) := fun hu => c154 e tri schur hu h1 h2
  have v1 : (¬ e 4 12) := fun hu => c158 e tri schur hu h0 h2
  have v2 : (¬ e 8 12) := fun hu => c204 e tri schur hu h0 h1
  exact c861 e tri schur v0 v1 v2

theorem c1234 : (e 14 17) → (e 13 17) → (e 8 13) → (e 4 6) → (e 3 5) → (¬ e 3 6) → (¬ e 4 13) → (¬ e 5 14) → (¬ e 8 9) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8
  have v0 : (¬ e 8 17) := fun hu => c684 e tri schur h1 hu h2
  have v1 : (¬ e 13 14) := fun hu => c798 e tri schur h0 h1 hu
  have v2 : (e 9 17) := Classical.byContradiction (fun hu => c886 e tri schur h8 v0 hu)
  have v3 : (¬ e 9 13) := fun hu => c1227 e tri schur h1 hu h2 h8
  have v4 : (¬ e 9 14) := fun hu => c724 e tri schur h0 v2 hu
  have v5 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu h6 v3)
  have v6 : (e 5 9) := Classical.byContradiction (fun hu => c871 e tri schur hu h7 v4)
  have v7 : (¬ e 3 4) := fun hu => c1159 e tri schur v5 h3 hu
  have v8 : (¬ e 4 15) := fun hu => c1194 e tri schur hu v5 h3
  have v9 : (¬ e 3 9) := fun hu => c273 e tri schur v6 hu h4
  have v10 : (¬ e 4 5) := fun hu => c364 e tri schur v6 v5 hu
  have v11 : (¬ e 6 9) := fun hu => c376 e tri schur hu v5 h3
  have v12 : (¬ e 4 17) := fun hu => c414 e tri schur v2 hu v5
  have v13 : (¬ e 5 17) := fun hu => c492 e tri schur v2 hu v6
  exact c848 e tri schur h5 v9 v11

theorem c1235 : (e 8 13) → (e 8 9) → (e 4 8) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 9) := fun hu => c397 e tri schur h1 hu h2
  have v1 : (¬ e 4 13) := fun hu => c401 e tri schur h0 hu h2
  have v2 : (¬ e 9 13) := fun hu => c654 e tri schur hu h0 h1
  exact c862 e tri schur v0 v1 v2

theorem c1236 : (e 13 17) → (e 8 13) → (e 4 6) → (e 3 5) → (¬ e 3 6) → (¬ e 4 13) → (¬ e 5 14) → (¬ e 8 9) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 8 17) := fun hu => c684 e tri schur h0 hu h1
  have v1 : (e 9 17) := Classical.byContradiction (fun hu => c886 e tri schur h7 v0 hu)
  have v2 : (¬ e 9 13) := fun hu => c1227 e tri schur h0 hu h1 h7
  have v3 : (¬ e 14 17) := fun hu => c1234 e tri schur hu h0 h1 h2 h3 h4 h5 h6 h7
  have v4 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu h5 v2)
  have v5 : (¬ e 3 4) := fun hu => c1159 e tri schur v4 h2 hu
  have v6 : (¬ e 4 15) := fun hu => c1194 e tri schur hu v4 h2
  have v7 : (¬ e 6 9) := fun hu => c376 e tri schur hu v4 h2
  have v8 : (¬ e 4 17) := fun hu => c414 e tri schur v1 hu v4
  have v9 : (e 3 9) := Classical.byContradiction (fun hu => c848 e tri schur h4 hu v7)
  have v10 : (¬ e 7 9) := fun hu => c894 e tri schur hu v4 v9
  have v11 : (¬ e 3 14) := fun hu => c992 e tri schur hu v9 h3
  have v12 : (¬ e 5 9) := fun hu => c273 e tri schur hu v9 h3
  have v13 : (¬ e 3 17) := fun hu => c323 e tri schur v1 hu v9
  exact c856 e tri schur v11 v13 v3

theorem c1237 : (e 9 17) → (e 3 9) → (e 3 5) → (¬ e 14 17) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 5 9) := fun hu => c273 e tri schur hu h1 h2
  have v1 : (¬ e 3 17) := fun hu => c323 e tri schur h0 hu h1
  have v2 : (e 3 14) := Classical.byContradiction (fun hu => c856 e tri schur hu v1 h3)
  exact c992 e tri schur v2 h1 h2

theorem c1239 : (e 5 16) → (e 2 12) → (e 2 5) → (¬ e 2 9) → (¬ e 7 9) → (¬ e 9 16) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 5 12) := fun hu => c171 e tri schur hu h1 h2
  have v1 : (¬ e 2 16) := fun hu => c175 e tri schur h0 hu h2
  have v2 : (e 2 7) := Classical.byContradiction (fun hu => c836 e tri schur hu h3 h4)
  have v3 : (e 7 16) := Classical.byContradiction (fun hu => c883 e tri schur h4 hu h5)
  have v4 : (e 5 7) := Classical.byContradiction (fun hu => c1196 e tri schur h1 v2 h2 hu)
  have v5 : (¬ e 2 17) := fun hu => c1231 e tri schur hu h1 h2
  exact c166 e tri schur v4 v2 h2

theorem c1240 : (e 5 17) → (e 5 10) → (e 5 7) → (¬ e 7 17) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 7 10) := fun hu => c466 e tri schur hu h1 h2
  have v1 : (¬ e 10 17) := fun hu => c500 e tri schur hu h0 h1
  exact c884 e tri schur v0 h3 v1

theorem c1241 : (e 9 12) → (e 5 16) → (e 4 9) → (e 3 5) → (e 2 12) → (e 2 5) → (¬ e 3 4) → (¬ e 9 16) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 2 3) := fun hu => c137 e tri schur h3 h5 hu
  have v1 : (¬ e 5 12) := fun hu => c171 e tri schur hu h4 h5
  have v2 : (¬ e 2 16) := fun hu => c175 e tri schur h1 hu h5
  have v3 : (¬ e 2 9) := fun hu => c213 e tri schur h0 h4 hu
  have v4 : (¬ e 3 16) := fun hu => c280 e tri schur h1 hu h3
  have v5 : (¬ e 4 12) := fun hu => c409 e tri schur h0 hu h2
  have v6 : (¬ e 2 17) := fun hu => c1231 e tri schur hu h4 h5
  have v7 : (e 7 9) := Classical.byContradiction (fun hu => c1239 e tri schur h1 h4 h5 v3 hu h7)
  have v8 : (¬ e 4 7) := fun hu => c387 e tri schur v7 h2 hu
  have v9 : (¬ e 7 12) := fun hu => c608 e tri schur h0 hu v7
  have v10 : (e 3 7) := Classical.byContradiction (fun hu => c846 e tri schur h6 hu v8)
  have v11 : (e 5 7) := Classical.byContradiction (fun hu => c869 e tri schur hu v1 v9)
  have v12 : (¬ e 3 9) := fun hu => c894 e tri schur v7 h2 hu
  have v13 : (¬ e 2 7) := fun hu => c166 e tri schur v11 hu h5
  exact c271 e tri schur v11 v10 h3

theorem c1242 : (e 13 17) → (e 8 13) → (e 6 12) → (e 5 16) → (e 4 6) → (e 3 5) → (e 2 12) → (e 2 5) → (¬ e 4 13) → (¬ e 5 14) → (¬ e 8 9) → (¬ e 9 16) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11
  have v0 : (¬ e 2 3) := fun hu => c137 e tri schur h5 h7 hu
  have v1 : (¬ e 5 12) := fun hu => c171 e tri schur hu h6 h7
  have v2 : (¬ e 2 16) := fun hu => c175 e tri schur h3 hu h7
  have v3 : (¬ e 2 6) := fun hu => c183 e tri schur h2 h6 hu
  have v4 : (¬ e 3 16) := fun hu => c280 e tri schur h3 hu h5
  have v5 : (¬ e 4 12) := fun hu => c379 e tri schur h2 hu h4
  have v6 : (¬ e 8 17) := fun hu => c684 e tri schur h0 hu h1
  have v7 : (e 9 17) := Classical.byContradiction (fun hu => c886 e tri schur h10 v6 hu)
  have v8 : (¬ e 6 8) := fun hu => c1091 e tri schur h2 hu h4
  have v9 : (¬ e 9 13) := fun hu => c1227 e tri schur h0 hu h1 h10
  have v10 : (¬ e 2 17) := fun hu => c1231 e tri schur hu h6 h7
  have v11 : (e 3 6) := Classical.byContradiction (fun hu => c1236 e tri schur h0 h1 h4 h5 hu h8 h9 h10)
  have v12 : (¬ e 3 4) := fun hu => c257 e tri schur h4 v11 hu
  have v13 : (¬ e 5 6) := fun hu => c270 e tri schur hu v11 h5
  have v14 : (¬ e 3 12) := fun hu => c288 e tri schur h2 hu v11
  have v15 : (e 2 8) := Classical.byContradiction (fun hu => c835 e tri schur v3 hu v8)
  have v16 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu h8 v9)
  have v17 : (¬ e 4 15) := fun hu => c1194 e tri schur hu v16 h4
  have v18 : (¬ e 2 4) := fun hu => c1233 e tri schur h6 v15 hu
  have v19 : (¬ e 9 12) := fun hu => c1241 e tri schur hu h3 v16 h5 h6 h7 v12 h11
  have v20 : (¬ e 5 8) := fun hu => c167 e tri schur hu v15 h7
  have v21 : (¬ e 8 12) := fun hu => c204 e tri schur hu h6 v15
  have v22 : (¬ e 2 13) := fun hu => c205 e tri schur h1 hu v15
  have v23 : (¬ e 6 9) := fun hu => c376 e tri schur hu v16 h4
  have v24 : (¬ e 4 17) := fun hu => c414 e tri schur v7 hu v16
  have v25 : (e 3 9) := Classical.byContradiction (fun hu => c851 e tri schur hu v14 v19)
  have v26 : (e 4 8) := Classical.byContradiction (fun hu => c861 e tri schur hu v5 v21)
  have v27 : (¬ e 7 9) := fun hu => c894 e tri schur hu v16 v25
  have v28 : (¬ e 3 14) := fun hu => c992 e tri schur hu v25 h5
  have v29 : (e 14 17) := Classical.byContradiction (fun hu => c1237 e tri schur v7 v25 h5 hu)
  have v30 : (e 2 9) := Classical.byContradiction (fun hu => c1239 e tri schur h3 h6 h7 hu v27 h11)
  have v31 : (¬ e 5 9) := fun hu => c168 e tri schur hu v30 h7
  have v32 : (¬ e 3 17) := fun hu => c323 e tri schur v7 hu v25
  have v33 : (¬ e 9 14) := fun hu => c724 e tri schur v29 v7 hu
  have v34 : (¬ e 13 14) := fun hu => c798 e tri schur v29 h0 hu
  exact c871 e tri schur v31 h9 v33

theorem c1243 : (e 9 17) → (e 5 16) → (e 4 9) → (e 3 9) → (e 2 12) → (e 2 5) → (¬ e 5 14) → (¬ e 9 16) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 5 12) := fun hu => c171 e tri schur hu h4 h5
  have v1 : (¬ e 2 16) := fun hu => c175 e tri schur h1 hu h5
  have v2 : (¬ e 3 4) := fun hu => c260 e tri schur h2 h3 hu
  have v3 : (¬ e 3 17) := fun hu => c323 e tri schur h0 hu h3
  have v4 : (¬ e 4 17) := fun hu => c414 e tri schur h0 hu h2
  have v5 : (¬ e 7 9) := fun hu => c894 e tri schur hu h2 h3
  have v6 : (¬ e 2 17) := fun hu => c1231 e tri schur hu h4 h5
  have v7 : (e 2 9) := Classical.byContradiction (fun hu => c1239 e tri schur h1 h4 h5 hu v5 h7)
  have v8 : (¬ e 2 3) := fun hu => c141 e tri schur h3 v7 hu
  have v9 : (¬ e 2 4) := fun hu => c155 e tri schur h2 v7 hu
  have v10 : (¬ e 5 9) := fun hu => c168 e tri schur hu v7 h5
  have v11 : (¬ e 9 12) := fun hu => c213 e tri schur hu h4 v7
  have v12 : (e 9 14) := Classical.byContradiction (fun hu => c871 e tri schur v10 h6 hu)
  have v13 : (e 7 16) := Classical.byContradiction (fun hu => c883 e tri schur v5 hu h7)
  have v14 : (¬ e 6 9) := fun hu => c896 e tri schur hu h2 v7
  have v15 : (¬ e 9 11) := fun hu => c948 e tri schur v12 hu h3
  have v16 : (¬ e 2 14) := fun hu => c215 e tri schur v12 hu v7
  have v17 : (¬ e 3 14) := fun hu => c320 e tri schur v12 hu h3
  have v18 : (¬ e 4 14) := fun hu => c411 e tri schur v12 hu h2
  have v19 : (¬ e 5 7) := fun hu => c472 e tri schur v13 h1 hu
  have v20 : (¬ e 14 17) := fun hu => c724 e tri schur hu h0 v12
  have v21 : (e 14 16) := Classical.byContradiction (fun hu => c843 e tri schur v16 v1 hu)
  exact c856 e tri schur v17 v3 v20

theorem c1244 : (e 13 17) → (e 3 17) → (e 3 6) → (e 2 14) → (e 2 8) → (¬ e 2 13) → (¬ e 3 14) → (¬ e 6 8) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 8 14) := fun hu => c206 e tri schur hu h3 h4
  have v1 : (¬ e 6 17) := fun hu => c293 e tri schur hu h1 h2
  have v2 : (¬ e 3 13) := fun hu => c349 e tri schur h0 h1 hu
  have v3 : (e 6 14) := Classical.byContradiction (fun hu => c877 e tri schur h7 hu v0)
  have v4 : (¬ e 6 11) := fun hu => c954 e tri schur v3 hu h2
  have v5 : (¬ e 2 6) := fun hu => c1215 e tri schur h3 h4 hu
  have v6 : (e 11 17) := Classical.byContradiction (fun hu => c880 e tri schur v4 v1 hu)
  have v7 : (¬ e 3 11) := fun hu => c338 e tri schur v6 h1 hu
  have v8 : (¬ e 11 13) := fun hu => c769 e tri schur h0 v6 hu
  have v9 : (e 2 11) := Classical.byContradiction (fun hu => c840 e tri schur hu h5 v8)
  have v10 : (e 11 14) := Classical.byContradiction (fun hu => c853 e tri schur v7 h6 hu)
  have v11 : (¬ e 11 16) := fun hu => c1179 e tri schur hu v10 v9
  have v12 : (¬ e 8 11) := fun hu => c203 e tri schur hu v9 h4
  exact c230 e tri schur v10 h3 v9

theorem c1245 : (e 13 18) → (e 10 13) → (e 8 13) → (¬ e 8 18) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 8 10) := fun hu => c662 e tri schur h1 h2 hu
  have v1 : (¬ e 10 18) := fun hu => c749 e tri schur h0 hu h1
  exact c887 e tri schur v0 h3 v1

theorem c1246 : (e 13 17) → (e 6 12) → (e 5 16) → (e 4 16) → (e 2 12) → (e 2 8) → (e 2 5) → (¬ e 5 13) → (¬ e 5 14) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8
  have v0 : (¬ e 5 8) := fun hu => c167 e tri schur hu h5 h6
  have v1 : (¬ e 5 12) := fun hu => c171 e tri schur hu h4 h6
  have v2 : (¬ e 2 16) := fun hu => c175 e tri schur h2 hu h6
  have v3 : (¬ e 2 6) := fun hu => c183 e tri schur h1 h4 hu
  have v4 : (¬ e 8 12) := fun hu => c204 e tri schur hu h4 h5
  have v5 : (¬ e 4 5) := fun hu => c371 e tri schur h2 h3 hu
  have v6 : (e 8 13) := Classical.byContradiction (fun hu => c870 e tri schur v0 h7 hu)
  have v7 : (¬ e 2 17) := fun hu => c1231 e tri schur hu h4 h6
  have v8 : (¬ e 2 4) := fun hu => c1233 e tri schur h4 h5 hu
  have v9 : (¬ e 2 13) := fun hu => c205 e tri schur v6 hu h5
  have v10 : (¬ e 8 17) := fun hu => c684 e tri schur h0 hu v6
  have v11 : (e 4 6) := Classical.byContradiction (fun hu => c833 e tri schur v8 v3 hu)
  have v12 : (¬ e 6 8) := fun hu => c1091 e tri schur h1 hu v11
  have v13 : (¬ e 4 12) := fun hu => c379 e tri schur h1 hu v11
  have v14 : (¬ e 6 16) := fun hu => c383 e tri schur hu h3 v11
  have v15 : (e 4 8) := Classical.byContradiction (fun hu => c861 e tri schur hu v13 v4)
  have v16 : (¬ e 8 9) := fun hu => c1235 e tri schur v6 hu v15
  have v17 : (¬ e 4 13) := fun hu => c401 e tri schur v6 hu v15
  have v18 : (¬ e 8 16) := fun hu => c404 e tri schur hu h3 v15
  have v19 : (e 9 17) := Classical.byContradiction (fun hu => c886 e tri schur v16 v10 hu)
  have v20 : (¬ e 9 13) := fun hu => c1227 e tri schur h0 hu v6 v16
  have v21 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu v17 v20)
  have v22 : (¬ e 3 4) := fun hu => c1159 e tri schur v21 v11 hu
  have v23 : (¬ e 4 15) := fun hu => c1194 e tri schur hu v21 v11
  have v24 : (¬ e 6 9) := fun hu => c376 e tri schur hu v21 v11
  have v25 : (¬ e 9 16) := fun hu => c413 e tri schur hu h3 v21
  have v26 : (¬ e 4 17) := fun hu => c414 e tri schur v19 hu v21
  have v27 : (¬ e 3 5) := fun hu => c1242 e tri schur h0 v6 h1 h2 v11 hu h4 h6 v17 h8 v16 v25
  have v28 : (¬ e 3 9) := fun hu => c1243 e tri schur v19 h2 v21 hu h4 h6 h8 v25
  have v29 : (e 3 8) := Classical.byContradiction (fun hu => c847 e tri schur v27 hu v0)
  have v30 : (e 3 6) := Classical.byContradiction (fun hu => c848 e tri schur hu v28 v24)
  have v31 : (¬ e 3 14) := fun hu => c950 e tri schur hu v29 v30
  have v32 : (¬ e 2 3) := fun hu => c140 e tri schur v29 h5 hu
  have v33 : (¬ e 3 12) := fun hu => c288 e tri schur h1 hu v30
  have v34 : (¬ e 3 13) := fun hu => c310 e tri schur v6 hu v29
  have v35 : (e 9 12) := Classical.byContradiction (fun hu => c851 e tri schur v28 v33 hu)
  have v36 : (¬ e 2 9) := fun hu => c213 e tri schur v35 h4 hu
  have v37 : (¬ e 12 17) := fun hu => c715 e tri schur hu v19 v35
  have v38 : (e 5 17) := Classical.byContradiction (fun hu => c874 e tri schur v1 hu v37)
  have v39 : (e 7 9) := Classical.byContradiction (fun hu => c1239 e tri schur h2 h4 h6 v36 hu v25)
  have v40 : (¬ e 4 7) := fun hu => c387 e tri schur v39 v21 hu
  have v41 : (¬ e 5 9) := fun hu => c492 e tri schur v19 v38 hu
  have v42 : (¬ e 16 17) := fun hu => c527 e tri schur hu v38 h2
  have v43 : (¬ e 7 12) := fun hu => c608 e tri schur v35 hu v39
  have v44 : (¬ e 7 17) := fun hu => c613 e tri schur v19 hu v39
  have v45 : (e 3 7) := Classical.byContradiction (fun hu => c846 e tri schur v22 hu v40)
  have v46 : (e 5 7) := Classical.byContradiction (fun hu => c869 e tri schur hu v1 v43)
  have v47 : (e 9 14) := Classical.byContradiction (fun hu => c871 e tri schur v41 h8 hu)
  have v48 : (¬ e 5 10) := fun hu => c1240 e tri schur v38 hu v46 v44
  have v49 : (¬ e 2 7) := fun hu => c166 e tri schur v46 hu h6
  have v50 : (¬ e 6 7) := fun hu => c283 e tri schur hu v45 v30
  have v51 : (¬ e 7 8) := fun hu => c295 e tri schur hu v29 v45
  have v52 : (¬ e 4 14) := fun hu => c411 e tri schur v47 hu v21
  have v53 : (¬ e 7 16) := fun hu => c472 e tri schur hu h2 v46
  have v54 : (¬ e 7 14) := fun hu => c610 e tri schur v47 hu v39
  have v55 : (¬ e 12 14) := fun hu => c712 e tri schur hu v47 v35
  have v56 : (¬ e 14 17) := fun hu => c724 e tri schur hu v19 v47
  have v57 : (e 3 17) := Classical.byContradiction (fun hu => c856 e tri schur v31 hu v56)
  have v58 : (¬ e 2 14) := fun hu => c1244 e tri schur h0 v57 v30 hu h5 v9 v31 v12
  have v59 : (¬ e 6 17) := fun hu => c293 e tri schur hu v57 v30
  have v60 : (e 14 16) := Classical.byContradiction (fun hu => c843 e tri schur v58 v2 hu)
  have v61 : (¬ e 16 18) := fun hu => c1213 e tri schur hu v60 h3
  have v62 : (e 2 18) := Classical.byContradiction (fun hu => c845 e tri schur v2 hu v61)
  have v63 : (¬ e 2 10) := fun hu => c1208 e tri schur v62 hu h5
  have v64 : (¬ e 5 18) := fun hu => c177 e tri schur hu v62 h6
  have v65 : (¬ e 8 18) := fun hu => c210 e tri schur hu v62 h5
  have v66 : (¬ e 12 18) := fun hu => c240 e tri schur hu v62 h4
  have v67 : (e 13 18) := Classical.byContradiction (fun hu => c875 e tri schur h7 v64 hu)
  have v68 : (¬ e 10 13) := fun hu => c1245 e tri schur v67 hu v6 v65
  have v69 : (¬ e 17 18) := fun hu => c805 e tri schur hu v67 h0
  have v70 : (e 3 10) := Classical.byContradiction (fun hu => c852 e tri schur hu v34 v68)
  have v71 : (¬ e 3 18) := fun hu => c963 e tri schur hu v70 v29
  have v72 : (¬ e 6 10) := fun hu => c286 e tri schur hu v70 v30
  have v73 : (¬ e 7 10) := fun hu => c297 e tri schur hu v70 v45
  have v74 : (¬ e 8 10) := fun hu => c307 e tri schur hu v70 v29
  have v75 : (¬ e 10 17) := fun hu => c331 e tri schur hu v57 v70
  have v76 : (e 10 16) := Classical.byContradiction (fun hu => c879 e tri schur v72 v14 hu)
  exact c884 e tri schur v73 v44 v75

theorem c1247 : (e 5 16) → (e 5 14) → (e 2 5) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 14) := fun hu => c173 e tri schur h1 hu h2
  have v1 : (¬ e 2 16) := fun hu => c175 e tri schur h0 hu h2
  have v2 : (¬ e 14 16) := fun hu => c521 e tri schur hu h0 h1
  exact c843 e tri schur v0 v1 v2

theorem c1248 : (e 6 12) → (¬ e 3 9) → (¬ e 6 9) → (¬ e 9 12) → False := by
  intro h0 h1 h2 h3
  have v0 : (e 3 6) := Classical.byContradiction (fun hu => c848 e tri schur hu h1 h2)
  have v1 : (e 3 12) := Classical.byContradiction (fun hu => c851 e tri schur h1 hu h3)
  exact c288 e tri schur h0 v1 v0

theorem c1249 : (e 14 16) → (e 10 16) → (e 4 16) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 10) := fun hu => c421 e tri schur h1 h2 hu
  have v1 : (¬ e 4 14) := fun hu => c443 e tri schur h0 h2 hu
  have v2 : (¬ e 10 14) := fun hu => c751 e tri schur h0 h1 hu
  exact c863 e tri schur v0 v1 v2

theorem c1250 : (e 11 17) → (e 9 17) → (e 4 17) → (¬ e 2 9) → (¬ e 2 17) → (¬ e 4 15) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 4 9) := fun hu => c414 e tri schur h1 h2 hu
  have v1 : (¬ e 4 11) := fun hu => c429 e tri schur h0 h2 hu
  have v2 : (¬ e 9 11) := fun hu => c709 e tri schur h0 h1 hu
  have v3 : (e 2 11) := Classical.byContradiction (fun hu => c838 e tri schur h3 hu v2)
  have v4 : (e 11 15) := Classical.byContradiction (fun hu => c864 e tri schur v1 h5 hu)
  have v5 : (¬ e 2 15) := fun hu => c231 e tri schur v4 hu v3
  have v6 : (¬ e 15 17) := fun hu => c776 e tri schur hu h0 v4
  exact c844 e tri schur v5 h4 v6

theorem c1251 : (e 6 12) → (e 5 16) → (e 2 8) → (e 2 5) → (¬ e 5 13) → (¬ e 10 12) → (¬ e 12 16) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 5 8) := fun hu => c167 e tri schur hu h2 h3
  have v1 : (¬ e 2 16) := fun hu => c175 e tri schur h1 hu h3
  have v2 : (e 8 13) := Classical.byContradiction (fun hu => c870 e tri schur v0 h4 hu)
  have v3 : (e 2 12) := Classical.byContradiction (fun hu => c1229 e tri schur h0 h1 h2 h3 hu h4 h5 h6)
  have v4 : (¬ e 2 17) := fun hu => c1231 e tri schur hu v3 h3
  have v5 : (¬ e 2 4) := fun hu => c1233 e tri schur v3 h2 hu
  have v6 : (¬ e 5 14) := fun hu => c1247 e tri schur h1 hu h3
  have v7 : (¬ e 5 12) := fun hu => c171 e tri schur hu v3 h3
  have v8 : (¬ e 2 6) := fun hu => c183 e tri schur h0 v3 hu
  have v9 : (¬ e 8 12) := fun hu => c204 e tri schur hu v3 h2
  have v10 : (¬ e 2 13) := fun hu => c205 e tri schur v2 hu h2
  have v11 : (e 4 6) := Classical.byContradiction (fun hu => c833 e tri schur v5 v8 hu)
  have v12 : (¬ e 6 8) := fun hu => c1091 e tri schur h0 hu v11
  have v13 : (¬ e 4 12) := fun hu => c379 e tri schur h0 hu v11
  have v14 : (e 4 8) := Classical.byContradiction (fun hu => c861 e tri schur hu v13 v9)
  have v15 : (e 4 16) := Classical.byContradiction (fun hu => c865 e tri schur v13 hu h6)
  have v16 : (¬ e 8 9) := fun hu => c1235 e tri schur v2 hu v14
  have v17 : (¬ e 13 17) := fun hu => c1246 e tri schur hu h0 h1 v15 v3 h2 h3 h4 v6
  have v18 : (¬ e 4 5) := fun hu => c371 e tri schur h1 v15 hu
  have v19 : (¬ e 6 16) := fun hu => c383 e tri schur hu v15 v11
  have v20 : (¬ e 4 13) := fun hu => c401 e tri schur v2 hu v14
  have v21 : (¬ e 8 16) := fun hu => c404 e tri schur hu v15 v14
  have v22 : (e 4 17) := Classical.byContradiction (fun hu => c866 e tri schur v20 hu v17)
  have v23 : (¬ e 6 17) := fun hu => c384 e tri schur hu v22 v11
  have v24 : (¬ e 8 17) := fun hu => c405 e tri schur hu v22 v14
  have v25 : (¬ e 16 17) := fun hu => c449 e tri schur hu v22 v15
  have v26 : (e 9 17) := Classical.byContradiction (fun hu => c886 e tri schur v16 v24 hu)
  have v27 : (¬ e 4 9) := fun hu => c414 e tri schur v26 v22 hu
  have v28 : (e 5 9) := Classical.byContradiction (fun hu => c858 e tri schur v18 v27 hu)
  have v29 : (e 9 13) := Classical.byContradiction (fun hu => c862 e tri schur v27 v20 hu)
  have v30 : (¬ e 2 9) := fun hu => c168 e tri schur v28 hu h3
  have v31 : (¬ e 9 16) := fun hu => c491 e tri schur hu h1 v28
  have v32 : (¬ e 5 17) := fun hu => c492 e tri schur v26 hu v28
  have v33 : (e 12 17) := Classical.byContradiction (fun hu => c874 e tri schur v7 v32 hu)
  have v34 : (e 7 9) := Classical.byContradiction (fun hu => c1239 e tri schur h1 v3 h3 v30 hu v31)
  have v35 : (¬ e 5 7) := fun hu => c465 e tri schur v34 v28 hu
  have v36 : (¬ e 7 13) := fun hu => c609 e tri schur v29 hu v34
  have v37 : (¬ e 7 17) := fun hu => c613 e tri schur v26 hu v34
  have v38 : (¬ e 9 12) := fun hu => c715 e tri schur v33 v26 hu
  have v39 : (e 7 12) := Classical.byContradiction (fun hu => c869 e tri schur v35 v7 hu)
  have v40 : (¬ e 2 7) := fun hu => c1196 e tri schur v3 hu h3 v35
  have v41 : (¬ e 6 7) := fun hu => c534 e tri schur v39 h0 hu
  have v42 : (e 6 13) := Classical.byContradiction (fun hu => c876 e tri schur v41 hu v36)
  have v43 : (¬ e 3 13) := fun hu => c940 e tri schur v29 v42 hu
  have v44 : (¬ e 6 9) := fun hu => c554 e tri schur v29 v42 hu
  have v45 : (¬ e 12 13) := fun hu => c575 e tri schur hu v42 h0
  have v46 : (e 3 9) := Classical.byContradiction (fun hu => c1248 e tri schur h0 hu v44 v38)
  have v47 : (¬ e 3 5) := fun hu => c273 e tri schur v28 v46 hu
  have v48 : (¬ e 3 7) := fun hu => c296 e tri schur v34 v46 hu
  have v49 : (¬ e 3 17) := fun hu => c323 e tri schur v26 hu v46
  have v50 : (e 3 8) := Classical.byContradiction (fun hu => c847 e tri schur v47 hu v0)
  have v51 : (¬ e 2 3) := fun hu => c140 e tri schur v50 h2 hu
  have v52 : (¬ e 3 4) := fun hu => c259 e tri schur v14 v50 hu
  have v53 : (e 4 7) := Classical.byContradiction (fun hu => c846 e tri schur v52 v48 hu)
  have v54 : (¬ e 4 15) := fun hu => c929 e tri schur hu v14 v53
  have v55 : (¬ e 11 17) := fun hu => c1250 e tri schur hu v26 v22 v30 v4 v54
  have v56 : (¬ e 7 8) := fun hu => c386 e tri schur hu v14 v53
  have v57 : (¬ e 7 16) := fun hu => c394 e tri schur hu v15 v53
  have v58 : (e 6 11) := Classical.byContradiction (fun hu => c880 e tri schur hu v23 v55)
  have v59 : (¬ e 6 15) := fun hu => c961 e tri schur hu v58 v11
  have v60 : (¬ e 13 15) := fun hu => c1221 e tri schur hu v29 v34 v59
  have v61 : (¬ e 4 11) := fun hu => c378 e tri schur v58 hu v11
  have v62 : (¬ e 11 12) := fun hu => c568 e tri schur hu h0 v58
  have v63 : (¬ e 11 13) := fun hu => c569 e tri schur hu v42 v58
  have v64 : (e 2 11) := Classical.byContradiction (fun hu => c840 e tri schur hu v10 v63)
  have v65 : (e 2 15) := Classical.byContradiction (fun hu => c842 e tri schur v10 hu v60)
  have v66 : (e 11 15) := Classical.byContradiction (fun hu => c864 e tri schur v61 v54 hu)
  have v67 : (e 9 15) := Classical.byContradiction (fun hu => c878 e tri schur v44 v59 hu)
  have v68 : (¬ e 9 11) := fun hu => c953 e tri schur v66 hu v58 v44
  have v69 : (¬ e 2 10) := fun hu => c1217 e tri schur v65 hu h3
  have v70 : (¬ e 5 11) := fun hu => c170 e tri schur hu v64 h3
  have v71 : (¬ e 5 15) := fun hu => c174 e tri schur hu v65 h3
  have v72 : (¬ e 8 11) := fun hu => c203 e tri schur hu v64 h2
  have v73 : (¬ e 8 15) := fun hu => c207 e tri schur hu v65 h2
  exact c231 e tri schur v66 v65 v64

theorem c1252 : (e 9 17) → (e 5 13) → (¬ e 4 5) → (¬ e 4 13) → (¬ e 13 17) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (e 4 17) := Classical.byContradiction (fun hu => c866 e tri schur h3 hu h4)
  have v1 : (e 4 9) := Classical.byContradiction (fun hu => c1175 e tri schur h1 h2 hu h3)
  exact c414 e tri schur h0 v0 v1

theorem c1256 : (e 4 18) → (e 3 18) → (e 1 18) → (¬ e 3 4) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 1 3) := fun hu => c30 e tri schur h1 h2 hu
  have v1 : (¬ e 1 4) := fun hu => c44 e tri schur h0 h2 hu
  exact c817 e tri schur v0 v1 h3

theorem c1260 : (e 4 13) → (e 4 12) → (e 1 4) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 1 12) := fun hu => c38 e tri schur h1 hu h2
  have v1 : (¬ e 1 13) := fun hu => c39 e tri schur h0 hu h2
  have v2 : (¬ e 12 13) := fun hu => c431 e tri schur hu h0 h1
  exact c826 e tri schur v0 v1 v2

theorem c1265 : (e 5 13) → (e 2 10) → (e 2 6) → (e 2 5) → (¬ e 2 9) → (¬ e 4 6) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 5 6) := fun hu => c165 e tri schur hu h2 h3
  have v1 : (¬ e 5 10) := fun hu => c169 e tri schur hu h1 h3
  have v2 : (¬ e 2 13) := fun hu => c172 e tri schur h0 hu h3
  have v3 : (¬ e 6 10) := fun hu => c181 e tri schur hu h1 h2
  have v4 : (e 4 10) := Classical.byContradiction (fun hu => c859 e tri schur h5 hu v3)
  have v5 : (¬ e 2 11) := fun hu => c916 e tri schur hu h2 h3
  have v6 : (¬ e 2 16) := fun hu => c994 e tri schur hu h1 h2
  have v7 : (¬ e 2 15) := fun hu => c1217 e tri schur hu h1 h3
  have v8 : (¬ e 2 4) := fun hu => c156 e tri schur v4 h1 hu
  have v9 : (e 9 11) := Classical.byContradiction (fun hu => c838 e tri schur h4 v5 hu)
  have v10 : (e 11 13) := Classical.byContradiction (fun hu => c840 e tri schur v5 v2 hu)
  have v11 : (e 13 15) := Classical.byContradiction (fun hu => c842 e tri schur v2 v7 hu)
  have v12 : (¬ e 4 11) := fun hu => c1028 e tri schur v10 v9 hu
  exact c1176 e tri schur v11 v10 h0 v4 v12 v1

theorem c1289 : (e 2 18) → (e 2 14) → (e 2 4) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 14) := fun hu => c160 e tri schur hu h1 h2
  have v1 : (¬ e 4 18) := fun hu => c164 e tri schur hu h0 h2
  have v2 : (¬ e 14 18) := fun hu => c249 e tri schur hu h0 h1
  exact c867 e tri schur v0 v1 v2

theorem c1292 : (e 10 12) → (e 6 9) → (e 4 12) → (e 1 12) → (¬ e 1 9) → (¬ e 4 6) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 1 4) := fun hu => c38 e tri schur h2 h3 hu
  have v1 : (¬ e 1 10) := fun hu => c101 e tri schur h0 h3 hu
  have v2 : (¬ e 4 10) := fun hu => c417 e tri schur h0 h2 hu
  have v3 : (e 9 10) := Classical.byContradiction (fun hu => c823 e tri schur h4 v1 hu)
  have v4 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur h5 v2 hu)
  exact c551 e tri schur v3 v4 h1

theorem c1293 : (e 14 16) → (e 11 14) → (e 5 14) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 5 11) := fun hu => c504 e tri schur h1 h2 hu
  have v1 : (¬ e 5 16) := fun hu => c521 e tri schur h0 hu h2
  have v2 : (¬ e 11 16) := fun hu => c772 e tri schur h0 hu h1
  exact c873 e tri schur v0 v1 v2

theorem c1294 : (e 12 14) → (e 6 8) → (¬ e 4 10) → (¬ e 4 14) → (¬ e 4 18) → (¬ e 6 12) → (¬ e 8 10) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur h2 h3 hu)
  have v1 : (e 14 18) := Classical.byContradiction (fun hu => c867 e tri schur h3 h4 hu)
  have v2 : (¬ e 10 18) := fun hu => c1095 e tri schur hu h2 h3 h4
  have v3 : (¬ e 10 12) := fun hu => c740 e tri schur h0 v0 hu
  have v4 : (¬ e 12 18) := fun hu => c789 e tri schur v1 hu h0
  have v5 : (e 6 18) := Classical.byContradiction (fun hu => c881 e tri schur h5 hu v4)
  have v6 : (e 8 18) := Classical.byContradiction (fun hu => c887 e tri schur h6 hu v2)
  exact c550 e tri schur v6 v5 h1

theorem c1296 : (e 8 12) → (e 8 11) → (e 1 8) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 1 11) := fun hu => c83 e tri schur h1 hu h2
  have v1 : (¬ e 1 12) := fun hu => c84 e tri schur h0 hu h2
  have v2 : (¬ e 11 12) := fun hu => c668 e tri schur hu h0 h1
  exact c825 e tri schur v0 v1 v2

theorem c1297 : (e 3 8) → (e 2 8) → (e 1 8) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 1 2) := fun hu => c5 e tri schur h1 h2 hu
  have v1 : (¬ e 1 3) := fun hu => c20 e tri schur h0 h2 hu
  have v2 : (¬ e 2 3) := fun hu => c140 e tri schur h0 h1 hu
  exact c816 e tri schur v0 v1 v2

theorem c1298 : (e 4 5) → (e 3 4) → (e 2 4) → (¬ e 2 3) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 2 5) := fun hu => c151 e tri schur h0 hu h2
  have v1 : (¬ e 3 5) := fun hu => c256 e tri schur h0 hu h1
  exact c832 e tri schur h3 v0 v1

theorem c1299 : (e 7 15) → (e 3 15) → (e 3 5) → (¬ e 5 10) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 5 15) := fun hu => c279 e tri schur hu h1 h2
  have v1 : (¬ e 3 7) := fun hu => c302 e tri schur h0 h1 hu
  have v2 : (e 10 15) := Classical.byContradiction (fun hu => c872 e tri schur h3 v0 hu)
  have v3 : (¬ e 4 15) := fun hu => c1023 e tri schur h0 hu h1
  have v4 : (¬ e 13 15) := fun hu => c1232 e tri schur hu v2 h1
  have v5 : (¬ e 3 10) := fun hu => c329 e tri schur v2 h1 hu
  have v6 : (¬ e 7 10) := fun hu => c619 e tri schur v2 h0 hu
  exact c849 e tri schur v1 v5 v6

theorem c1300 : (e 12 15) → (e 10 15) → (e 6 8) → (e 4 18) → (e 3 4) → (¬ e 3 15) → (¬ e 4 10) → (¬ e 6 12) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 3 18) := fun hu => c269 e tri schur h3 hu h4
  have v1 : (¬ e 10 12) := fun hu => c741 e tri schur h0 h1 hu
  have v2 : (e 15 18) := Classical.byContradiction (fun hu => c857 e tri schur h5 v0 hu)
  have v3 : (¬ e 8 15) := fun hu => c944 e tri schur v2 h1 hu
  have v4 : (¬ e 4 15) := fun hu => c448 e tri schur v2 h3 hu
  have v5 : (¬ e 10 18) := fun hu => c756 e tri schur v2 hu h1
  have v6 : (¬ e 12 18) := fun hu => c792 e tri schur v2 hu h0
  have v7 : (e 6 18) := Classical.byContradiction (fun hu => c881 e tri schur h7 hu v6)
  have v8 : (¬ e 9 18) := fun hu => c890 e tri schur v2 hu v7
  have v9 : (¬ e 4 6) := fun hu => c385 e tri schur v7 h3 hu
  have v10 : (¬ e 8 18) := fun hu => c550 e tri schur hu v7 h2
  have v11 : (¬ e 6 15) := fun hu => c592 e tri schur v2 v7 hu
  have v12 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur v9 h6 hu)
  have v13 : (e 8 10) := Classical.byContradiction (fun hu => c887 e tri schur hu v10 v5)
  exact c542 e tri schur v13 v12 h2

theorem c1302 : (e 15 18) → (e 12 15) → (e 10 15) → (e 6 8) → (¬ e 6 12) → (¬ e 8 10) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 10 12) := fun hu => c741 e tri schur h1 h2 hu
  have v1 : (¬ e 10 18) := fun hu => c756 e tri schur h0 hu h2
  have v2 : (¬ e 12 18) := fun hu => c792 e tri schur h0 hu h1
  have v3 : (e 6 18) := Classical.byContradiction (fun hu => c881 e tri schur h4 hu v2)
  have v4 : (e 8 18) := Classical.byContradiction (fun hu => c887 e tri schur h5 hu v1)
  have v5 : (¬ e 9 18) := fun hu => c890 e tri schur h0 hu v3
  have v6 : (¬ e 8 15) := fun hu => c944 e tri schur h0 h2 hu
  exact c550 e tri schur v4 v3 h3

theorem c1303 : (e 8 18) → (e 8 12) → (e 6 8) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 6 12) := fun hu => c544 e tri schur h1 hu h2
  have v1 : (¬ e 6 18) := fun hu => c550 e tri schur h0 hu h2
  have v2 : (¬ e 12 18) := fun hu => c680 e tri schur hu h0 h1
  exact c881 e tri schur v0 v1 v2

theorem c1304 : (e 5 12) → (e 5 9) → (e 3 5) → (¬ e 3 12) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 9) := fun hu => c273 e tri schur h1 hu h2
  have v1 : (¬ e 9 12) := fun hu => c487 e tri schur hu h0 h1
  exact c851 e tri schur v0 h3 v1

theorem c1307 : (e 5 9) → (e 4 6) → (e 3 4) → (e 1 11) → (¬ e 1 7) → (¬ e 3 9) → (¬ e 4 11) → (¬ e 5 11) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 3 6) := fun hu => c257 e tri schur h1 hu h2
  have v1 : (e 6 9) := Classical.byContradiction (fun hu => c848 e tri schur v0 h5 hu)
  have v2 : (¬ e 4 9) := fun hu => c1159 e tri schur hu h1 h2
  have v3 : (¬ e 5 6) := fun hu => c454 e tri schur v1 h0 hu
  have v4 : (e 6 11) := Classical.byContradiction (fun hu => c868 e tri schur v3 h7 hu)
  have v5 : (¬ e 6 15) := fun hu => c961 e tri schur hu v4 h1
  have v6 : (¬ e 1 6) := fun hu => c62 e tri schur v4 h3 hu
  have v7 : (¬ e 9 11) := fun hu => c552 e tri schur hu v4 v1
  have v8 : (e 1 5) := Classical.byContradiction (fun hu => c819 e tri schur hu v6 v3)
  have v9 : (e 6 7) := Classical.byContradiction (fun hu => c820 e tri schur v6 h4 hu)
  have v10 : (¬ e 1 9) := fun hu => c48 e tri schur h0 hu v8
  have v11 : (¬ e 4 7) := fun hu => c374 e tri schur v9 hu h1
  have v12 : (¬ e 7 9) := fun hu => c531 e tri schur hu v1 v9
  have v13 : (¬ e 7 11) := fun hu => c533 e tri schur hu v4 v9
  exact c860 e tri schur v11 h6 v13

theorem c1308 : (e 10 15) → (e 8 12) → (e 8 10) → (e 5 9) → (e 5 7) → (e 3 10) → (e 3 5) → (¬ e 1 3) → (¬ e 1 4) → (¬ e 4 5) → (¬ e 8 9) → (¬ e 9 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11
  have v0 : (¬ e 3 7) := fun hu => c271 e tri schur h4 hu h6
  have v1 : (¬ e 3 9) := fun hu => c273 e tri schur h3 hu h6
  have v2 : (¬ e 5 10) := fun hu => c274 e tri schur hu h5 h6
  have v3 : (¬ e 3 8) := fun hu => c307 e tri schur h2 h5 hu
  have v4 : (¬ e 3 15) := fun hu => c329 e tri schur h0 hu h5
  have v5 : (¬ e 7 9) := fun hu => c465 e tri schur hu h3 h4
  have v6 : (¬ e 10 12) := fun hu => c661 e tri schur hu h1 h2
  have v7 : (¬ e 8 15) := fun hu => c664 e tri schur h0 hu h2
  have v8 : (e 3 4) := Classical.byContradiction (fun hu => c817 e tri schur h7 h8 hu)
  have v9 : (e 1 5) := Classical.byContradiction (fun hu => c818 e tri schur h8 hu h9)
  have v10 : (¬ e 1 7) := fun hu => c46 e tri schur h4 hu v9
  have v11 : (¬ e 1 9) := fun hu => c48 e tri schur h3 hu v9
  have v12 : (¬ e 4 10) := fun hu => c261 e tri schur hu h5 v8
  have v13 : (e 1 8) := Classical.byContradiction (fun hu => c822 e tri schur hu v11 h10)
  have v14 : (¬ e 8 11) := fun hu => c1296 e tri schur h1 hu v13
  have v15 : (¬ e 5 8) := fun hu => c47 e tri schur hu v13 v9
  have v16 : (¬ e 1 10) := fun hu => c82 e tri schur h2 hu v13
  have v17 : (¬ e 1 12) := fun hu => c84 e tri schur h1 hu v13
  have v18 : (e 9 10) := Classical.byContradiction (fun hu => c823 e tri schur v11 v16 hu)
  have v19 : (e 3 11) := Classical.byContradiction (fun hu => c850 e tri schur v3 hu v14)
  have v20 : (¬ e 4 11) := fun hu => c262 e tri schur hu v19 v8
  have v21 : (¬ e 5 11) := fun hu => c275 e tri schur hu v19 h6
  have v22 : (¬ e 10 11) := fun hu => c325 e tri schur hu v19 h5
  have v23 : (e 1 11) := Classical.byContradiction (fun hu => c824 e tri schur v16 hu v22)
  have v24 : (¬ e 4 6) := fun hu => c1307 e tri schur h3 hu v8 v23 v10 v1 v20 v21
  have v25 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur v24 v12 hu)
  have v26 : (¬ e 3 6) := fun hu => c286 e tri schur v25 h5 hu
  have v27 : (¬ e 6 8) := fun hu => c542 e tri schur h2 v25 hu
  have v28 : (¬ e 6 9) := fun hu => c551 e tri schur v18 v25 hu
  have v29 : (¬ e 6 15) := fun hu => c564 e tri schur h0 hu v25
  exact c848 e tri schur v26 v1 v28

theorem c1309 : (e 10 15) → (e 8 12) → (e 8 10) → (e 5 9) → (e 5 7) → (e 3 10) → (e 3 5) → (e 3 4) → (e 1 5) → (¬ e 8 9) → (¬ e 9 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10
  have v0 : (¬ e 1 3) := fun hu => c17 e tri schur h6 h8 hu
  have v1 : (¬ e 1 7) := fun hu => c46 e tri schur h4 hu h8
  have v2 : (¬ e 1 9) := fun hu => c48 e tri schur h3 hu h8
  have v3 : (¬ e 4 5) := fun hu => c256 e tri schur hu h6 h7
  have v4 : (¬ e 4 10) := fun hu => c261 e tri schur hu h5 h7
  have v5 : (¬ e 3 7) := fun hu => c271 e tri schur h4 hu h6
  have v6 : (¬ e 3 9) := fun hu => c273 e tri schur h3 hu h6
  have v7 : (¬ e 5 10) := fun hu => c274 e tri schur hu h5 h6
  have v8 : (¬ e 3 8) := fun hu => c307 e tri schur h2 h5 hu
  have v9 : (¬ e 3 15) := fun hu => c329 e tri schur h0 hu h5
  have v10 : (¬ e 7 9) := fun hu => c465 e tri schur hu h3 h4
  have v11 : (¬ e 10 12) := fun hu => c661 e tri schur hu h1 h2
  have v12 : (¬ e 8 15) := fun hu => c664 e tri schur h0 hu h2
  have v13 : (e 1 8) := Classical.byContradiction (fun hu => c822 e tri schur hu v2 h9)
  have v14 : (¬ e 8 11) := fun hu => c1296 e tri schur h1 hu v13
  have v15 : (e 1 4) := Classical.byContradiction (fun hu => c1308 e tri schur h0 h1 h2 h3 h4 h5 h6 v0 hu v3 h9 h10)
  have v16 : (¬ e 4 8) := fun hu => c34 e tri schur hu v13 v15
  have v17 : (¬ e 5 8) := fun hu => c47 e tri schur hu v13 h8
  have v18 : (¬ e 1 10) := fun hu => c82 e tri schur h2 hu v13
  have v19 : (¬ e 1 12) := fun hu => c84 e tri schur h1 hu v13
  have v20 : (e 9 10) := Classical.byContradiction (fun hu => c823 e tri schur v2 v18 hu)
  have v21 : (e 3 11) := Classical.byContradiction (fun hu => c850 e tri schur v8 hu v14)
  have v22 : (¬ e 4 11) := fun hu => c262 e tri schur hu v21 h7
  have v23 : (¬ e 5 11) := fun hu => c275 e tri schur hu v21 h6
  have v24 : (¬ e 10 11) := fun hu => c325 e tri schur hu v21 h5
  have v25 : (e 1 11) := Classical.byContradiction (fun hu => c824 e tri schur v18 hu v24)
  have v26 : (¬ e 4 6) := fun hu => c1307 e tri schur h3 hu h7 v25 v1 v6 v22 v23
  have v27 : (e 6 10) := Classical.byContradiction (fun hu => c859 e tri schur v26 v4 hu)
  have v28 : (¬ e 3 6) := fun hu => c286 e tri schur v27 h5 hu
  have v29 : (¬ e 6 8) := fun hu => c542 e tri schur h2 v27 hu
  have v30 : (¬ e 6 9) := fun hu => c551 e tri schur v20 v27 hu
  have v31 : (¬ e 6 15) := fun hu => c564 e tri schur h0 hu v27
  exact c848 e tri schur v28 v6 v30

theorem c1310 : (e 3 11) → (e 3 6) → (e 3 5) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 5 6) := fun hu => c270 e tri schur hu h1 h2
  have v1 : (¬ e 5 11) := fun hu => c275 e tri schur hu h0 h2
  have v2 : (¬ e 6 11) := fun hu => c287 e tri schur hu h0 h1
  exact c868 e tri schur v0 v1 v2

theorem c1311 : (e 10 11) → (e 6 11) → (e 3 4) → (¬ e 3 7) → (¬ e 4 6) → (¬ e 4 11) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 6 10) := fun hu => c560 e tri schur h0 h1 hu
  have v1 : (e 4 10) := Classical.byContradiction (fun hu => c859 e tri schur h4 hu v0)
  have v2 : (¬ e 3 10) := fun hu => c261 e tri schur v1 hu h2
  have v3 : (e 7 10) := Classical.byContradiction (fun hu => c849 e tri schur h3 v2 hu)
  have v4 : (¬ e 4 7) := fun hu => c388 e tri schur v3 v1 hu
  have v5 : (¬ e 7 11) := fun hu => c615 e tri schur h0 hu v3
  exact c860 e tri schur v4 h5 v5

theorem c1312 : (e 1 10) → (e 1 6) → (e 1 4) → (¬ e 4 6) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 4 10) := fun hu => c36 e tri schur hu h0 h2
  have v1 : (¬ e 6 10) := fun hu => c61 e tri schur hu h0 h1
  exact c859 e tri schur h3 v0 v1

theorem c1313 : (e 7 15) → (e 7 10) → (e 5 7) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 5 10) := fun hu => c466 e tri schur h1 hu h2
  have v1 : (¬ e 5 15) := fun hu => c471 e tri schur h0 hu h2
  have v2 : (¬ e 10 15) := fun hu => c619 e tri schur hu h0 h1
  exact c872 e tri schur v0 v1 v2

theorem c1314 : (e 8 12) → (¬ e 1 7) → (¬ e 3 11) → (¬ e 7 8) → (¬ e 7 15) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (e 1 8) := Classical.byContradiction (fun hu => c821 e tri schur h1 hu h3)
  have v1 : (e 8 15) := Classical.byContradiction (fun hu => c882 e tri schur h3 h4 hu)
  have v2 : (¬ e 3 8) := fun hu => c987 e tri schur v1 h0 hu
  have v3 : (¬ e 8 11) := fun hu => c1296 e tri schur h0 hu v0
  have v4 : (¬ e 1 12) := fun hu => c84 e tri schur h0 hu v0
  have v5 : (¬ e 1 15) := fun hu => c87 e tri schur v1 hu v0
  have v6 : (¬ e 12 15) := fun hu => c677 e tri schur hu v1 h0
  exact c850 e tri schur v2 h2 v3

theorem c1315 : (e 9 12) → (e 8 12) → (e 8 11) → (¬ e 1 11) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 8 9) := fun hu => c653 e tri schur h0 h1 hu
  have v1 : (¬ e 11 12) := fun hu => c668 e tri schur hu h1 h2
  have v2 : (e 1 12) := Classical.byContradiction (fun hu => c825 e tri schur h3 hu v1)
  have v3 : (¬ e 1 8) := fun hu => c1296 e tri schur h1 h2 hu
  have v4 : (¬ e 1 9) := fun hu => c93 e tri schur h0 v2 hu
  exact c822 e tri schur v3 v4 v0

theorem c1318 : (e 9 15) → (e 9 12) → (e 3 9) → (¬ e 3 15) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 12) := fun hu => c318 e tri schur h1 hu h2
  have v1 : (¬ e 12 15) := fun hu => c713 e tri schur hu h0 h1
  exact c854 e tri schur v0 h3 v1

theorem c1322 : (e 5 11) → (e 5 9) → (e 2 5) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 9) := fun hu => c168 e tri schur h1 hu h2
  have v1 : (¬ e 2 11) := fun hu => c170 e tri schur h0 hu h2
  have v2 : (¬ e 9 11) := fun hu => c486 e tri schur hu h0 h1
  exact c838 e tri schur v0 v1 v2

theorem c1323 : (e 3 14) → (e 3 12) → (e 2 3) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 12) := fun hu => c144 e tri schur h1 hu h2
  have v1 : (¬ e 2 14) := fun hu => c146 e tri schur h0 hu h2
  have v2 : (¬ e 12 14) := fun hu => c341 e tri schur hu h0 h1
  exact c841 e tri schur v0 v1 v2

theorem c1324 : (e 3 10) → (e 3 8) → (e 2 3) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 8) := fun hu => c140 e tri schur h1 hu h2
  have v1 : (¬ e 2 10) := fun hu => c142 e tri schur h0 hu h2
  have v2 : (¬ e 8 10) := fun hu => c307 e tri schur hu h0 h1
  exact c837 e tri schur v0 v1 v2

theorem c1325 : (e 10 15) → (e 8 10) → (e 7 10) → (¬ e 7 8) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 7 15) := fun hu => c619 e tri schur h0 hu h2
  have v1 : (¬ e 8 15) := fun hu => c664 e tri schur h0 hu h1
  exact c882 e tri schur h3 v0 v1

theorem c1328 : (e 8 10) → (e 7 10) → (e 1 10) → (¬ e 7 8) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 1 7) := fun hu => c72 e tri schur h1 h2 hu
  have v1 : (¬ e 1 8) := fun hu => c82 e tri schur h0 h2 hu
  exact c821 e tri schur v0 v1 h3

theorem c1330 : (e 7 10) → (e 6 10) → (e 5 12) → (e 3 8) → (e 1 6) → (¬ e 1 12) → (¬ e 3 10) → (¬ e 5 8) → (¬ e 6 7) → (¬ e 7 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9
  have v0 : (¬ e 1 10) := fun hu => c61 e tri schur h1 hu h4
  have v1 : (e 6 13) := Classical.byContradiction (fun hu => c876 e tri schur h8 hu h9)
  have v2 : (¬ e 10 13) := fun hu => c1106 e tri schur hu h0 h1 h9
  have v3 : (¬ e 1 13) := fun hu => c64 e tri schur v1 hu h4
  have v4 : (e 12 13) := Classical.byContradiction (fun hu => c826 e tri schur h5 v3 hu)
  have v5 : (e 3 13) := Classical.byContradiction (fun hu => c852 e tri schur h6 hu v2)
  have v6 : (¬ e 9 13) := fun hu => c940 e tri schur hu v1 v5
  have v7 : (¬ e 3 6) := fun hu => c289 e tri schur v1 v5 hu
  have v8 : (¬ e 8 13) := fun hu => c310 e tri schur hu v5 h3
  have v9 : (¬ e 3 12) := fun hu => c340 e tri schur v4 v5 hu
  have v10 : (¬ e 5 13) := fun hu => c509 e tri schur v4 hu h2
  have v11 : (¬ e 6 12) := fun hu => c575 e tri schur v4 v1 hu
  exact c870 e tri schur h7 v10 v8

theorem c1331 : (e 8 18) → (e 8 15) → (e 3 8) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 15) := fun hu => c312 e tri schur h1 hu h2
  have v1 : (¬ e 3 18) := fun hu => c315 e tri schur h0 hu h2
  have v2 : (¬ e 15 18) := fun hu => c692 e tri schur hu h0 h1
  exact c857 e tri schur v0 v1 v2

theorem c1333 : (e 2 17) → (e 2 11) → (e 2 6) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 6 11) := fun hu => c182 e tri schur hu h1 h2
  have v1 : (¬ e 6 17) := fun hu => c188 e tri schur hu h0 h2
  have v2 : (¬ e 11 17) := fun hu => c233 e tri schur hu h0 h1
  exact c880 e tri schur v0 v1 v2

theorem c1334 : (e 8 15) → (e 5 13) → (¬ e 2 13) → (¬ e 2 15) → (¬ e 2 17) → (¬ e 4 5) → (¬ e 4 13) → (¬ e 8 9) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (e 13 15) := Classical.byContradiction (fun hu => c842 e tri schur h2 h3 hu)
  have v1 : (e 15 17) := Classical.byContradiction (fun hu => c844 e tri schur h3 h4 hu)
  have v2 : (e 4 9) := Classical.byContradiction (fun hu => c1175 e tri schur h1 h5 hu h6)
  have v3 : (¬ e 5 15) := fun hu => c516 e tri schur v0 hu h1
  have v4 : (¬ e 8 13) := fun hu => c682 e tri schur v0 h0 hu
  have v5 : (¬ e 8 17) := fun hu => c691 e tri schur v1 hu h0
  have v6 : (¬ e 13 17) := fun hu => c801 e tri schur v1 hu v0
  have v7 : (e 4 17) := Classical.byContradiction (fun hu => c866 e tri schur h6 hu v6)
  have v8 : (e 9 17) := Classical.byContradiction (fun hu => c886 e tri schur h7 v5 hu)
  exact c1252 e tri schur v8 h1 h5 h6 v6

theorem c1335 : (e 4 12) → (e 4 11) → (e 1 4) → (¬ e 1 12) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 1 11) := fun hu => c37 e tri schur h1 hu h2
  have v1 : (¬ e 11 12) := fun hu => c424 e tri schur hu h0 h1
  exact c825 e tri schur v0 h3 v1

theorem c1336 : (e 11 12) → (e 10 11) → (e 2 11) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 10) := fun hu => c220 e tri schur h1 h2 hu
  have v1 : (¬ e 2 12) := fun hu => c228 e tri schur h0 hu h2
  have v2 : (¬ e 10 12) := fun hu => c732 e tri schur h0 hu h1
  exact c839 e tri schur v0 v1 v2

end Jsp746.Certificate
