/- Generated by scripts/generate_refutation.py from our own SAT trace.
Every statement below is proved with ordinary kernel-checked proof terms. -/
import Jsp746.Certificate.Steps00

namespace Jsp746.Certificate
variable (e : ℕ → ℕ → Prop)
variable (tri : TriangleCondition e) (schur : SchurCondition e)
include tri schur

theorem c992 : (e 3 14) → (e 3 9) → (e 3 5) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 5 9) := fun hu => c273 e tri schur hu h1 h2
  have v1 : (¬ e 5 14) := fun hu => c278 e tri schur hu h0 h2
  have v2 : (¬ e 9 14) := fun hu => c320 e tri schur hu h0 h1
  exact c871 e tri schur v0 v1 v2

theorem c994 : (e 2 16) → (e 2 10) → (e 2 6) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 6 10) := fun hu => c181 e tri schur hu h1 h2
  have v1 : (¬ e 6 16) := fun hu => c187 e tri schur hu h0 h2
  have v2 : (¬ e 10 16) := fun hu => c225 e tri schur hu h0 h1
  exact c879 e tri schur v0 v1 v2

theorem c996 : (e 7 15) → (e 7 13) → (e 2 7) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 13) := fun hu => c195 e tri schur h1 hu h2
  have v1 : (¬ e 2 15) := fun hu => c197 e tri schur h0 hu h2
  have v2 : (¬ e 13 15) := fun hu => c637 e tri schur hu h0 h1
  exact c842 e tri schur v0 v1 v2

theorem c998 : (e 15 18) → (e 13 15) → (e 10 18) → (¬ e 5 10) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 10 15) := fun hu => c756 e tri schur h0 h2 hu
  have v1 : (¬ e 13 18) := fun hu => c802 e tri schur h0 hu h1
  have v2 : (e 5 15) := Classical.byContradiction (fun hu => c872 e tri schur h3 hu v0)
  have v3 : (¬ e 5 13) := fun hu => c516 e tri schur h1 v2 hu
  have v4 : (¬ e 5 18) := fun hu => c526 e tri schur h0 hu v2
  exact c875 e tri schur v3 v4 v1

theorem c1000 : (e 10 18) → (e 10 13) → (e 5 10) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 5 13) := fun hu => c496 e tri schur h1 hu h2
  have v1 : (¬ e 5 18) := fun hu => c501 e tri schur h0 hu h2
  have v2 : (¬ e 13 18) := fun hu => c749 e tri schur hu h0 h1
  exact c875 e tri schur v0 v1 v2

theorem c1001 : (e 10 13) → (e 7 13) → (e 7 8) → (e 2 3) → (¬ e 2 5) → (¬ e 3 10) → (¬ e 5 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 8 13) := fun hu => c600 e tri schur hu h1 h2
  have v1 : (¬ e 7 10) := fun hu => c617 e tri schur h0 h1 hu
  have v2 : (e 3 7) := Classical.byContradiction (fun hu => c849 e tri schur hu h5 v1)
  have v3 : (e 5 8) := Classical.byContradiction (fun hu => c870 e tri schur hu h6 v0)
  have v4 : (¬ e 2 7) := fun hu => c139 e tri schur v2 hu h3
  have v5 : (¬ e 3 8) := fun hu => c295 e tri schur h2 hu v2
  have v6 : (¬ e 3 13) := fun hu => c300 e tri schur h1 hu v2
  have v7 : (¬ e 5 7) := fun hu => c464 e tri schur h2 v3 hu
  exact c834 e tri schur h4 v4 v7

theorem c1002 : (e 16 18) → (e 12 16) → (e 6 16) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 6 12) := fun hu => c578 e tri schur h1 h2 hu
  have v1 : (¬ e 6 18) := fun hu => c594 e tri schur h0 hu h2
  have v2 : (¬ e 12 18) := fun hu => c794 e tri schur h0 hu h1
  exact c881 e tri schur v0 v1 v2

theorem c1003 : (e 7 10) → (e 6 16) → (e 4 16) → (e 3 16) → (¬ e 3 7) → (¬ e 6 10) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 3 4) := fun hu => c267 e tri schur h2 h3 hu
  have v1 : (¬ e 3 6) := fun hu => c292 e tri schur h1 h3 hu
  have v2 : (¬ e 4 6) := fun hu => c383 e tri schur h1 h2 hu
  have v3 : (e 4 7) := Classical.byContradiction (fun hu => c846 e tri schur v0 h4 hu)
  have v4 : (e 4 10) := Classical.byContradiction (fun hu => c859 e tri schur v2 hu h5)
  exact c388 e tri schur h0 v4 v3

theorem c1004 : (e 10 17) → (e 10 13) → (e 4 10) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 13) := fun hu => c418 e tri schur h1 hu h2
  have v1 : (¬ e 4 17) := fun hu => c422 e tri schur h0 hu h2
  have v2 : (¬ e 13 17) := fun hu => c748 e tri schur hu h0 h1
  exact c866 e tri schur v0 v1 v2

theorem c1005 : (e 4 17) → (e 4 12) → (e 4 11) → (¬ e 5 11) → (¬ e 5 12) → (¬ e 6 11) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 11 12) := fun hu => c424 e tri schur hu h1 h2
  have v1 : (¬ e 11 17) := fun hu => c429 e tri schur hu h0 h2
  have v2 : (¬ e 12 17) := fun hu => c435 e tri schur hu h0 h1
  have v3 : (e 5 6) := Classical.byContradiction (fun hu => c868 e tri schur hu h3 h5)
  have v4 : (e 5 17) := Classical.byContradiction (fun hu => c874 e tri schur h4 hu v2)
  have v5 : (e 6 17) := Classical.byContradiction (fun hu => c880 e tri schur h5 hu v1)
  exact c917 e tri schur v4 h3 h5 v1

theorem c1006 : (e 13 17) → (e 6 13) → (¬ e 2 13) → (¬ e 2 15) → (¬ e 6 11) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 6 17) := fun hu => c584 e tri schur h0 hu h1
  have v1 : (e 13 15) := Classical.byContradiction (fun hu => c842 e tri schur h2 h3 hu)
  have v2 : (e 11 17) := Classical.byContradiction (fun hu => c880 e tri schur h4 v0 hu)
  have v3 : (¬ e 6 15) := fun hu => c582 e tri schur v1 hu h1
  have v4 : (¬ e 11 13) := fun hu => c769 e tri schur h0 v2 hu
  have v5 : (¬ e 15 17) := fun hu => c801 e tri schur hu h0 v1
  have v6 : (e 2 11) := Classical.byContradiction (fun hu => c840 e tri schur hu h2 v4)
  have v7 : (e 2 17) := Classical.byContradiction (fun hu => c844 e tri schur h3 hu v5)
  exact c233 e tri schur v2 v7 v6

theorem c1008 : (e 5 18) → (e 5 11) → (e 5 7) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 7 11) := fun hu => c467 e tri schur hu h1 h2
  have v1 : (¬ e 7 18) := fun hu => c474 e tri schur hu h0 h2
  have v2 : (¬ e 11 18) := fun hu => c508 e tri schur hu h0 h1
  exact c885 e tri schur v0 v1 v2

theorem c1010 : (e 2 9) → (e 2 6) → (e 2 3) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 6) := fun hu => c138 e tri schur hu h1 h2
  have v1 : (¬ e 3 9) := fun hu => c141 e tri schur hu h0 h2
  have v2 : (¬ e 6 9) := fun hu => c180 e tri schur hu h0 h1
  exact c848 e tri schur v0 v1 v2

theorem c1013 : (e 8 15) → (e 5 15) → (e 3 15) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 5) := fun hu => c279 e tri schur h1 h2 hu
  have v1 : (¬ e 3 8) := fun hu => c312 e tri schur h0 h2 hu
  have v2 : (¬ e 5 8) := fun hu => c481 e tri schur h0 h1 hu
  exact c847 e tri schur v0 v1 v2

theorem c1014 : (e 5 18) → (e 5 12) → (e 5 6) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 6 12) := fun hu => c457 e tri schur hu h1 h2
  have v1 : (¬ e 6 18) := fun hu => c463 e tri schur hu h0 h2
  have v2 : (¬ e 12 18) := fun hu => c514 e tri schur hu h0 h1
  exact c881 e tri schur v0 v1 v2

theorem c1017 : (e 10 12) → (e 6 12) → (e 4 12) → (¬ e 6 10) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 4 6) := fun hu => c379 e tri schur h1 h2 hu
  have v1 : (¬ e 4 10) := fun hu => c417 e tri schur h0 h2 hu
  exact c859 e tri schur v0 v1 h3

theorem c1018 : (e 6 13) → (e 6 11) → (e 2 7) → (e 2 6) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 6 7) := fun hu => c178 e tri schur hu h2 h3
  have v1 : (¬ e 2 11) := fun hu => c182 e tri schur h1 hu h3
  have v2 : (¬ e 2 13) := fun hu => c184 e tri schur h0 hu h3
  have v3 : (¬ e 11 13) := fun hu => c569 e tri schur hu h0 h1
  exact c840 e tri schur v1 v2 v3

theorem c1021 : (e 6 12) → (e 4 12) → (¬ e 2 6) → (¬ e 2 10) → (¬ e 6 10) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 4 6) := fun hu => c379 e tri schur h0 h1 hu
  have v1 : (e 2 4) := Classical.byContradiction (fun hu => c833 e tri schur hu h2 v0)
  have v2 : (e 4 10) := Classical.byContradiction (fun hu => c859 e tri schur v0 hu h4)
  have v3 : (¬ e 10 12) := fun hu => c1017 e tri schur hu h0 h1 h4
  have v4 : (¬ e 2 12) := fun hu => c158 e tri schur h1 hu v1
  exact c839 e tri schur h3 v4 v3

theorem c1023 : (e 7 15) → (e 4 15) → (e 3 15) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 4) := fun hu => c266 e tri schur h1 h2 hu
  have v1 : (¬ e 3 7) := fun hu => c302 e tri schur h0 h2 hu
  have v2 : (¬ e 4 7) := fun hu => c393 e tri schur h0 h1 hu
  exact c846 e tri schur v0 v1 v2

theorem c1025 : (e 2 11) → (e 2 8) → (e 2 3) → (¬ e 3 8) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 11) := fun hu => c143 e tri schur hu h0 h2
  have v1 : (¬ e 8 11) := fun hu => c203 e tri schur hu h0 h1
  exact c850 e tri schur h3 v0 v1

theorem c1027 : (e 8 11) → (e 6 8) → (e 5 8) → (¬ e 5 11) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 5 6) := fun hu => c453 e tri schur h1 h2 hu
  have v1 : (¬ e 6 11) := fun hu => c543 e tri schur h0 hu h1
  exact c868 e tri schur v0 h3 v1

theorem c1028 : (e 11 13) → (e 9 11) → (e 4 11) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 9) := fun hu => c408 e tri schur h1 h2 hu
  have v1 : (¬ e 4 13) := fun hu => c425 e tri schur h0 hu h2
  have v2 : (¬ e 9 13) := fun hu => c705 e tri schur h0 hu h1
  exact c862 e tri schur v0 v1 v2

theorem c1032 : (e 6 11) → (e 4 11) → (e 2 11) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 4) := fun hu => c157 e tri schur h1 h2 hu
  have v1 : (¬ e 2 6) := fun hu => c182 e tri schur h0 h2 hu
  have v2 : (¬ e 4 6) := fun hu => c378 e tri schur h0 h1 hu
  exact c833 e tri schur v0 v1 v2

theorem c1035 : (e 16 18) → (e 11 18) → (e 5 18) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 5 11) := fun hu => c508 e tri schur h1 h2 hu
  have v1 : (¬ e 5 16) := fun hu => c528 e tri schur h0 h2 hu
  have v2 : (¬ e 11 16) := fun hu => c779 e tri schur h0 h1 hu
  exact c873 e tri schur v0 v1 v2

theorem c1037 : (e 7 15) → (e 7 9) → (e 6 7) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 6 9) := fun hu => c531 e tri schur h1 hu h2
  have v1 : (¬ e 6 15) := fun hu => c537 e tri schur h0 hu h2
  have v2 : (¬ e 9 15) := fun hu => c611 e tri schur hu h0 h1
  exact c878 e tri schur v0 v1 v2

theorem c1039 : (e 7 16) → (e 7 10) → (e 6 7) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 6 10) := fun hu => c532 e tri schur h1 hu h2
  have v1 : (¬ e 6 16) := fun hu => c538 e tri schur h0 hu h2
  have v2 : (¬ e 10 16) := fun hu => c620 e tri schur hu h0 h1
  exact c879 e tri schur v0 v1 v2

theorem c1042 : (e 3 15) → (¬ e 3 6) → (¬ e 6 9) → (¬ e 6 15) → False := by
  intro h0 h1 h2 h3
  have v0 : (e 3 9) := Classical.byContradiction (fun hu => c848 e tri schur h1 hu h2)
  have v1 : (e 9 15) := Classical.byContradiction (fun hu => c878 e tri schur h2 h3 hu)
  exact c321 e tri schur v1 h0 v0

theorem c1043 : (e 6 13) → (e 6 9) → (e 2 9) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 2 6) := fun hu => c180 e tri schur h1 h2 hu
  have v1 : (¬ e 9 13) := fun hu => c554 e tri schur hu h0 h1
  have v2 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu h3 v1)
  exact c896 e tri schur h1 v2 h2

theorem c1045 : (e 6 16) → (e 6 13) → (e 3 6) → (¬ e 3 13) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 16) := fun hu => c292 e tri schur h0 hu h2
  have v1 : (¬ e 13 16) := fun hu => c583 e tri schur hu h0 h1
  exact c855 e tri schur h3 v0 v1

theorem c1046 : (e 10 18) → (e 10 16) → (e 10 13) → (e 2 11) → (¬ e 2 18) → (¬ e 3 5) → (¬ e 3 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 13 16) := fun hu => c747 e tri schur hu h1 h2
  have v1 : (¬ e 13 18) := fun hu => c749 e tri schur hu h0 h2
  have v2 : (¬ e 16 18) := fun hu => c758 e tri schur hu h0 h1
  have v3 : (e 2 16) := Classical.byContradiction (fun hu => c845 e tri schur hu h4 v2)
  have v4 : (e 3 16) := Classical.byContradiction (fun hu => c855 e tri schur h6 hu v0)
  have v5 : (¬ e 5 10) := fun hu => c1000 e tri schur h0 h2 hu
  have v6 : (¬ e 2 3) := fun hu => c148 e tri schur v4 v3 hu
  have v7 : (¬ e 2 10) := fun hu => c225 e tri schur h1 v3 hu
  have v8 : (¬ e 11 16) := fun hu => c232 e tri schur hu v3 h3
  have v9 : (¬ e 3 10) := fun hu => c330 e tri schur h1 v4 hu
  have v10 : (e 2 5) := Classical.byContradiction (fun hu => c832 e tri schur v6 hu h5)
  have v11 : (¬ e 2 6) := fun hu => c916 e tri schur h3 hu v10
  have v12 : (¬ e 5 11) := fun hu => c170 e tri schur hu h3 v10
  have v13 : (¬ e 5 16) := fun hu => c175 e tri schur hu v3 v10
  exact c873 e tri schur v12 v13 v8

theorem c1047 : (e 3 16) → (e 2 16) → (e 2 11) → (¬ e 3 5) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 2 3) := fun hu => c148 e tri schur h0 h1 hu
  have v1 : (¬ e 11 16) := fun hu => c232 e tri schur hu h1 h2
  have v2 : (e 2 5) := Classical.byContradiction (fun hu => c832 e tri schur v0 hu h3)
  have v3 : (¬ e 2 6) := fun hu => c916 e tri schur h2 hu v2
  have v4 : (¬ e 5 11) := fun hu => c170 e tri schur hu h2 v2
  have v5 : (¬ e 5 16) := fun hu => c175 e tri schur hu h1 v2
  exact c873 e tri schur v4 v5 v1

theorem c1048 : (e 13 15) → (e 10 13) → (e 7 10) → (e 6 13) → (e 3 15) → (e 2 11) → (¬ e 2 18) → (¬ e 3 5) → (¬ e 3 7) → (¬ e 10 16) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9
  have v0 : (¬ e 3 13) := fun hu => c347 e tri schur h0 h4 hu
  have v1 : (¬ e 6 10) := fun hu => c562 e tri schur h1 h3 hu
  have v2 : (¬ e 6 15) := fun hu => c582 e tri schur h0 hu h3
  have v3 : (¬ e 7 13) := fun hu => c617 e tri schur h1 hu h2
  have v4 : (¬ e 10 15) := fun hu => c746 e tri schur h0 hu h1
  have v5 : (e 6 16) := Classical.byContradiction (fun hu => c879 e tri schur v1 hu h9)
  have v6 : (¬ e 3 6) := fun hu => c1045 e tri schur v5 h3 hu v0
  have v7 : (¬ e 13 16) := fun hu => c583 e tri schur hu v5 h3
  have v8 : (e 3 16) := Classical.byContradiction (fun hu => c855 e tri schur v0 hu v7)
  have v9 : (¬ e 4 16) := fun hu => c1003 e tri schur h2 v5 hu v8 h8 v1
  have v10 : (e 6 9) := Classical.byContradiction (fun hu => c1042 e tri schur h4 v6 hu v2)
  have v11 : (¬ e 2 16) := fun hu => c1047 e tri schur v8 hu h5 h7
  have v12 : (¬ e 15 16) := fun hu => c355 e tri schur hu v8 h4
  have v13 : (¬ e 9 13) := fun hu => c554 e tri schur hu h3 v10
  have v14 : (¬ e 9 16) := fun hu => c557 e tri schur hu v5 v10
  have v15 : (e 16 18) := Classical.byContradiction (fun hu => c845 e tri schur v11 h6 hu)
  have v16 : (¬ e 4 6) := fun hu => c904 e tri schur h3 v10 hu v13
  have v17 : (¬ e 12 16) := fun hu => c1002 e tri schur v15 hu v5
  have v18 : (¬ e 3 18) := fun hu => c359 e tri schur v15 hu v8
  have v19 : (¬ e 6 18) := fun hu => c594 e tri schur v15 hu v5
  have v20 : (e 4 10) := Classical.byContradiction (fun hu => c859 e tri schur v16 hu v1)
  have v21 : (e 4 12) := Classical.byContradiction (fun hu => c865 e tri schur hu v9 v17)
  have v22 : (¬ e 10 17) := fun hu => c1004 e tri schur hu h1 v20
  have v23 : (¬ e 4 7) := fun hu => c388 e tri schur h2 v20 hu
  have v24 : (¬ e 10 12) := fun hu => c417 e tri schur hu v21 v20
  have v25 : (¬ e 4 13) := fun hu => c418 e tri schur h1 hu v20
  have v26 : (e 3 4) := Classical.byContradiction (fun hu => c846 e tri schur hu h8 v23)
  have v27 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu v25 v13)
  have v28 : (¬ e 2 9) := fun hu => c896 e tri schur v10 v27 hu
  have v29 : (¬ e 3 9) := fun hu => c260 e tri schur v27 hu v26
  have v30 : (¬ e 3 10) := fun hu => c261 e tri schur v20 hu v26
  have v31 : (¬ e 3 12) := fun hu => c263 e tri schur v21 hu v26
  have v32 : (¬ e 4 15) := fun hu => c266 e tri schur hu h4 v26
  have v33 : (¬ e 9 10) := fun hu => c407 e tri schur hu v20 v27
  have v34 : (¬ e 9 12) := fun hu => c409 e tri schur hu v21 v27
  exact c851 e tri schur v29 v31 v34

theorem c1051 : (e 7 8) → (e 3 6) → (¬ e 2 5) → (¬ e 2 7) → (¬ e 3 5) → (¬ e 6 8) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (e 2 3) := Classical.byContradiction (fun hu => c832 e tri schur hu h2 h4)
  have v1 : (e 5 7) := Classical.byContradiction (fun hu => c834 e tri schur h2 h3 hu)
  have v2 : (¬ e 2 6) := fun hu => c138 e tri schur h1 hu v0
  have v3 : (¬ e 5 8) := fun hu => c464 e tri schur h0 hu v1
  have v4 : (e 2 8) := Classical.byContradiction (fun hu => c835 e tri schur v2 hu h5)
  have v5 : (e 3 8) := Classical.byContradiction (fun hu => c847 e tri schur h4 hu v3)
  have v6 : (¬ e 3 14) := fun hu => c950 e tri schur hu v5 h1
  exact c140 e tri schur v5 v4 v0

theorem c1052 : (e 7 10) → (e 6 7) → (e 4 7) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 6) := fun hu => c374 e tri schur h1 h2 hu
  have v1 : (¬ e 4 10) := fun hu => c388 e tri schur h0 hu h2
  have v2 : (¬ e 6 10) := fun hu => c532 e tri schur h0 hu h1
  exact c859 e tri schur v0 v1 v2

theorem c1053 : (e 13 15) → (e 10 13) → (e 7 10) → (e 7 8) → (e 3 15) → (e 3 6) → (e 2 11) → (¬ e 2 18) → (¬ e 3 5) → (¬ e 3 7) → (¬ e 10 16) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10
  have v0 : (¬ e 6 15) := fun hu => c291 e tri schur hu h4 h5
  have v1 : (¬ e 3 13) := fun hu => c347 e tri schur h0 h4 hu
  have v2 : (¬ e 8 10) := fun hu => c597 e tri schur hu h2 h3
  have v3 : (¬ e 7 13) := fun hu => c617 e tri schur h1 hu h2
  have v4 : (¬ e 10 15) := fun hu => c746 e tri schur h0 hu h1
  have v5 : (¬ e 2 7) := fun hu => c931 e tri schur h2 h3 hu
  have v6 : (¬ e 6 13) := fun hu => c1048 e tri schur h0 h1 h2 hu h4 h6 h7 h8 h9 h10
  have v7 : (e 6 7) := Classical.byContradiction (fun hu => c876 e tri schur hu v6 v3)
  have v8 : (¬ e 7 16) := fun hu => c1039 e tri schur hu h2 v7
  have v9 : (¬ e 4 7) := fun hu => c1052 e tri schur h2 v7 hu
  have v10 : (¬ e 6 8) := fun hu => c530 e tri schur h3 hu v7
  have v11 : (¬ e 6 10) := fun hu => c532 e tri schur h2 hu v7
  have v12 : (e 3 4) := Classical.byContradiction (fun hu => c846 e tri schur hu h9 v9)
  have v13 : (e 6 16) := Classical.byContradiction (fun hu => c879 e tri schur v11 hu h10)
  have v14 : (e 2 5) := Classical.byContradiction (fun hu => c1051 e tri schur h3 h5 hu v5 h8 v10)
  have v15 : (¬ e 5 11) := fun hu => c170 e tri schur hu h6 v14
  have v16 : (¬ e 4 6) := fun hu => c257 e tri schur hu h5 v12
  have v17 : (¬ e 4 15) := fun hu => c266 e tri schur hu h4 v12
  have v18 : (¬ e 3 16) := fun hu => c292 e tri schur v13 hu h5
  have v19 : (e 13 16) := Classical.byContradiction (fun hu => c855 e tri schur v1 v18 hu)
  have v20 : (e 4 10) := Classical.byContradiction (fun hu => c859 e tri schur v16 hu v11)
  have v21 : (¬ e 2 6) := fun hu => c916 e tri schur h6 hu v14
  have v22 : (¬ e 10 17) := fun hu => c1004 e tri schur hu h1 v20
  have v23 : (¬ e 3 10) := fun hu => c261 e tri schur v20 hu v12
  have v24 : (¬ e 4 13) := fun hu => c418 e tri schur h1 hu v20
  have v25 : (¬ e 15 16) := fun hu => c800 e tri schur hu v19 h0
  have v26 : (e 2 4) := Classical.byContradiction (fun hu => c833 e tri schur hu v21 v16)
  have v27 : (e 2 8) := Classical.byContradiction (fun hu => c835 e tri schur v21 hu v10)
  have v28 : (¬ e 2 3) := fun hu => c136 e tri schur v12 v26 hu
  have v29 : (¬ e 4 5) := fun hu => c151 e tri schur hu v14 v26
  have v30 : (¬ e 4 8) := fun hu => c154 e tri schur hu v27 v26
  have v31 : (¬ e 2 10) := fun hu => c156 e tri schur v20 hu v26
  have v32 : (¬ e 4 11) := fun hu => c157 e tri schur hu h6 v26
  have v33 : (¬ e 5 8) := fun hu => c167 e tri schur hu v27 v14
  have v34 : (¬ e 8 11) := fun hu => c203 e tri schur hu h6 v27
  have v35 : (e 3 8) := Classical.byContradiction (fun hu => c847 e tri schur h8 hu v33)
  have v36 : (e 7 11) := Classical.byContradiction (fun hu => c860 e tri schur v9 v32 hu)
  have v37 : (e 11 15) := Classical.byContradiction (fun hu => c864 e tri schur v32 v17 hu)
  have v38 : (¬ e 3 14) := fun hu => c950 e tri schur hu v35 h5
  have v39 : (¬ e 2 15) := fun hu => c231 e tri schur v37 hu h6
  have v40 : (¬ e 8 15) := fun hu => c312 e tri schur hu h4 v35
  have v41 : (¬ e 3 11) := fun hu => c336 e tri schur v37 h4 hu
  have v42 : (¬ e 6 11) := fun hu => c533 e tri schur v36 hu v7
  have v43 : (¬ e 10 11) := fun hu => c615 e tri schur hu v36 h2
  have v44 : (¬ e 7 15) := fun hu => c626 e tri schur v37 hu v36
  have v45 : (¬ e 11 13) := fun hu => c767 e tri schur h0 v37 hu
  have v46 : (e 11 14) := Classical.byContradiction (fun hu => c853 e tri schur v41 v38 hu)
  have v47 : (e 5 6) := Classical.byContradiction (fun hu => c868 e tri schur hu v15 v42)
  have v48 : (¬ e 2 14) := fun hu => c230 e tri schur v46 hu h6
  have v49 : (¬ e 5 7) := fun hu => c452 e tri schur v7 hu v47
  have v50 : (¬ e 5 16) := fun hu => c461 e tri schur v13 hu v47
  have v51 : (¬ e 7 14) := fun hu => c625 e tri schur v46 hu v36
  have v52 : (¬ e 14 15) := fun hu => c771 e tri schur hu v37 v46
  have v53 : (e 11 16) := Classical.byContradiction (fun hu => c873 e tri schur v15 v50 hu)
  have v54 : (¬ e 2 16) := fun hu => c232 e tri schur v53 hu h6
  have v55 : (¬ e 14 16) := fun hu => c772 e tri schur hu v53 v46
  exact c843 e tri schur v48 v54 v55

theorem c1054 : (e 13 15) → (e 10 13) → (e 7 10) → (e 7 8) → (e 3 15) → (e 3 6) → (e 2 11) → (¬ e 2 18) → (¬ e 3 5) → (¬ e 10 16) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8 h9
  have v0 : (¬ e 6 15) := fun hu => c291 e tri schur hu h4 h5
  have v1 : (¬ e 3 13) := fun hu => c347 e tri schur h0 h4 hu
  have v2 : (¬ e 8 10) := fun hu => c597 e tri schur hu h2 h3
  have v3 : (¬ e 7 13) := fun hu => c617 e tri schur h1 hu h2
  have v4 : (¬ e 10 15) := fun hu => c746 e tri schur h0 hu h1
  have v5 : (¬ e 2 7) := fun hu => c931 e tri schur h2 h3 hu
  have v6 : (e 3 7) := Classical.byContradiction (fun hu => c1053 e tri schur h0 h1 h2 h3 h4 h5 h6 h7 h8 hu h9)
  have v7 : (¬ e 6 7) := fun hu => c283 e tri schur hu v6 h5
  have v8 : (¬ e 3 8) := fun hu => c295 e tri schur h3 hu v6
  have v9 : (¬ e 3 10) := fun hu => c297 e tri schur h2 hu v6
  have v10 : (¬ e 7 15) := fun hu => c302 e tri schur hu h4 v6
  have v11 : (e 5 8) := Classical.byContradiction (fun hu => c847 e tri schur h8 v8 hu)
  have v12 : (e 6 13) := Classical.byContradiction (fun hu => c876 e tri schur v7 hu v3)
  have v13 : (¬ e 6 16) := fun hu => c1045 e tri schur hu v12 h5 v1
  have v14 : (¬ e 5 7) := fun hu => c464 e tri schur h3 v11 hu
  have v15 : (¬ e 6 10) := fun hu => c562 e tri schur h1 v12 hu
  have v16 : (e 2 5) := Classical.byContradiction (fun hu => c834 e tri schur hu v5 v14)
  exact c879 e tri schur v15 v13 h9

theorem c1055 : (e 7 8) → (e 5 8) → (e 2 11) → (¬ e 2 7) → (¬ e 6 8) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 5 7) := fun hu => c464 e tri schur h0 h1 hu
  have v1 : (e 2 5) := Classical.byContradiction (fun hu => c834 e tri schur hu h3 v0)
  have v2 : (¬ e 2 6) := fun hu => c916 e tri schur h2 hu v1
  have v3 : (¬ e 2 8) := fun hu => c167 e tri schur h1 hu v1
  have v4 : (¬ e 5 11) := fun hu => c170 e tri schur hu h2 v1
  exact c835 e tri schur v2 v3 h4

theorem c1056 : (e 6 11) → (e 6 7) → (e 2 11) → (¬ e 4 7) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 2 6) := fun hu => c182 e tri schur h0 h2 hu
  have v1 : (¬ e 7 11) := fun hu => c533 e tri schur hu h0 h1
  have v2 : (e 4 11) := Classical.byContradiction (fun hu => c860 e tri schur h3 hu v1)
  exact c1032 e tri schur h0 v2 h2

theorem c1057 : (e 5 18) → (e 5 11) → (e 2 11) → (¬ e 2 7) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 2 5) := fun hu => c170 e tri schur h1 h2 hu
  have v1 : (¬ e 11 18) := fun hu => c508 e tri schur hu h0 h1
  have v2 : (e 5 7) := Classical.byContradiction (fun hu => c834 e tri schur v0 h3 hu)
  exact c1008 e tri schur h0 h1 v2

theorem c1059 : (e 7 8) → (e 5 8) → (e 5 6) → (e 2 11) → (¬ e 2 7) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 6 8) := fun hu => c453 e tri schur hu h1 h2
  have v1 : (¬ e 5 7) := fun hu => c464 e tri schur h0 h1 hu
  have v2 : (e 2 5) := Classical.byContradiction (fun hu => c834 e tri schur hu h4 v1)
  have v3 : (¬ e 2 6) := fun hu => c916 e tri schur h3 hu v2
  exact c1055 e tri schur h0 h1 h3 h4 v0

theorem c1065 : (e 2 16) → (e 2 11) → (e 2 5) → (¬ e 5 11) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 5 16) := fun hu => c175 e tri schur hu h0 h2
  have v1 : (¬ e 11 16) := fun hu => c232 e tri schur hu h0 h1
  exact c873 e tri schur h3 v0 v1

theorem c1066 : (e 13 16) → (e 9 13) → (e 7 13) → (¬ e 7 16) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 7 9) := fun hu => c609 e tri schur h1 h2 hu
  have v1 : (¬ e 9 16) := fun hu => c719 e tri schur h0 hu h1
  exact c883 e tri schur v0 h3 v1

theorem c1069 : (e 7 8) → (e 5 6) → (e 3 7) → (e 2 11) → (¬ e 3 5) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 3 8) := fun hu => c295 e tri schur h0 hu h2
  have v1 : (e 5 8) := Classical.byContradiction (fun hu => c847 e tri schur h4 v0 hu)
  have v2 : (e 2 7) := Classical.byContradiction (fun hu => c1059 e tri schur h0 v1 h1 h3 hu)
  have v3 : (¬ e 2 3) := fun hu => c139 e tri schur h2 v2 hu
  have v4 : (¬ e 2 8) := fun hu => c190 e tri schur h0 hu v2
  have v5 : (¬ e 7 11) := fun hu => c193 e tri schur hu h3 v2
  have v6 : (¬ e 6 8) := fun hu => c453 e tri schur hu v1 h1
  have v7 : (¬ e 5 7) := fun hu => c464 e tri schur h0 v1 hu
  have v8 : (e 2 5) := Classical.byContradiction (fun hu => c832 e tri schur v3 hu h4)
  have v9 : (e 2 6) := Classical.byContradiction (fun hu => c835 e tri schur hu v4 v6)
  exact c916 e tri schur h3 v9 v8

theorem c1075 : (e 7 8) → (e 2 8) → (¬ e 2 5) → (¬ e 3 5) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 2 7) := fun hu => c190 e tri schur h0 h1 hu
  have v1 : (e 2 3) := Classical.byContradiction (fun hu => c832 e tri schur hu h2 h3)
  have v2 : (e 5 7) := Classical.byContradiction (fun hu => c834 e tri schur h2 v0 hu)
  have v3 : (¬ e 3 8) := fun hu => c140 e tri schur hu h1 v1
  have v4 : (¬ e 5 8) := fun hu => c464 e tri schur h0 hu v2
  exact c847 e tri schur h3 v3 v4

theorem c1076 : (e 7 8) → (e 2 7) → (e 2 3) → (¬ e 3 10) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 7) := fun hu => c139 e tri schur hu h1 h2
  have v1 : (¬ e 2 8) := fun hu => c190 e tri schur h0 hu h1
  have v2 : (e 7 10) := Classical.byContradiction (fun hu => c849 e tri schur v0 h3 hu)
  exact c931 e tri schur v2 h0 h1

theorem c1080 : (e 7 8) → (e 5 6) → (e 2 5) → (¬ e 2 8) → (¬ e 5 13) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 2 6) := fun hu => c165 e tri schur h1 hu h2
  have v1 : (e 6 8) := Classical.byContradiction (fun hu => c835 e tri schur v0 h3 hu)
  have v2 : (¬ e 5 8) := fun hu => c453 e tri schur v1 hu h1
  have v3 : (¬ e 6 7) := fun hu => c530 e tri schur h0 v1 hu
  have v4 : (e 8 13) := Classical.byContradiction (fun hu => c870 e tri schur v2 h4 hu)
  have v5 : (¬ e 6 13) := fun hu => c988 e tri schur hu v1 h1 v2
  have v6 : (¬ e 7 13) := fun hu => c600 e tri schur v4 hu h0
  exact c876 e tri schur v3 v5 v6

theorem c1081 : (e 10 18) → (e 10 16) → (e 2 10) → (¬ e 2 18) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 2 16) := fun hu => c225 e tri schur h1 hu h2
  have v1 : (¬ e 16 18) := fun hu => c758 e tri schur hu h0 h1
  exact c845 e tri schur v0 h3 v1

theorem c1088 : (e 5 15) → (e 5 11) → (e 4 5) → (¬ e 11 15) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 4 11) := fun hu => c366 e tri schur h1 hu h2
  have v1 : (¬ e 4 15) := fun hu => c370 e tri schur h0 hu h2
  exact c864 e tri schur v0 v1 h3

theorem c1091 : (e 6 12) → (e 6 8) → (e 4 6) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 8) := fun hu => c375 e tri schur h1 hu h2
  have v1 : (¬ e 4 12) := fun hu => c379 e tri schur h0 hu h2
  have v2 : (¬ e 8 12) := fun hu => c544 e tri schur hu h0 h1
  exact c861 e tri schur v0 v1 v2

theorem c1094 : (e 7 12) → (e 7 9) → (e 3 7) → (¬ e 3 9) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 12) := fun hu => c299 e tri schur h0 hu h2
  have v1 : (¬ e 9 12) := fun hu => c608 e tri schur hu h0 h1
  exact c851 e tri schur h3 v0 v1

theorem c1095 : (e 10 18) → (¬ e 4 10) → (¬ e 4 14) → (¬ e 4 18) → False := by
  intro h0 h1 h2 h3
  have v0 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur h1 h2 hu)
  have v1 : (e 14 18) := Classical.byContradiction (fun hu => c867 e tri schur h2 h3 hu)
  exact c753 e tri schur v1 h0 v0

theorem c1096 : (e 4 14) → (e 4 12) → (e 4 9) → (e 2 5) → (¬ e 2 12) → (¬ e 5 9) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 9 12) := fun hu => c409 e tri schur hu h1 h2
  have v1 : (¬ e 9 14) := fun hu => c411 e tri schur hu h0 h2
  have v2 : (¬ e 12 14) := fun hu => c432 e tri schur hu h0 h1
  have v3 : (e 2 14) := Classical.byContradiction (fun hu => c841 e tri schur h4 hu v2)
  have v4 : (e 5 14) := Classical.byContradiction (fun hu => c871 e tri schur h5 hu v1)
  have v5 : (¬ e 2 4) := fun hu => c160 e tri schur h0 v3 hu
  exact c173 e tri schur v4 v3 h3

theorem c1105 : (e 4 14) → (e 4 11) → (e 3 4) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 11) := fun hu => c262 e tri schur h1 hu h2
  have v1 : (¬ e 3 14) := fun hu => c265 e tri schur h0 hu h2
  have v2 : (¬ e 11 14) := fun hu => c426 e tri schur hu h0 h1
  exact c853 e tri schur v0 v1 v2

theorem c1106 : (e 10 13) → (e 7 10) → (e 6 10) → (¬ e 7 13) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 6 7) := fun hu => c532 e tri schur h1 h2 hu
  have v1 : (¬ e 6 13) := fun hu => c562 e tri schur h0 hu h2
  exact c876 e tri schur v0 v1 h3

theorem c1111 : (e 13 15) → (e 11 13) → (e 9 11) → (e 4 6) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 9 13) := fun hu => c705 e tri schur h1 hu h2
  have v1 : (¬ e 11 15) := fun hu => c767 e tri schur h0 hu h1
  have v2 : (¬ e 4 11) := fun hu => c1028 e tri schur h1 h2 hu
  have v3 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur v2 hu v1)
  have v4 : (¬ e 6 15) := fun hu => c382 e tri schur hu v3 h3
  have v5 : (¬ e 4 13) := fun hu => c438 e tri schur h0 v3 hu
  have v6 : (e 4 9) := Classical.byContradiction (fun hu => c862 e tri schur hu v5 v0)
  have v7 : (¬ e 6 9) := fun hu => c376 e tri schur hu v6 h3
  have v8 : (¬ e 9 15) := fun hu => c412 e tri schur hu v3 v6
  exact c878 e tri schur v7 v4 v8

theorem c1112 : (e 5 15) → (e 4 15) → (e 4 6) → (e 2 9) → (¬ e 5 9) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 4 5) := fun hu => c370 e tri schur h0 h1 hu
  have v1 : (¬ e 6 15) := fun hu => c382 e tri schur hu h1 h2
  have v2 : (e 4 9) := Classical.byContradiction (fun hu => c858 e tri schur v0 hu h4)
  have v3 : (¬ e 6 9) := fun hu => c896 e tri schur hu v2 h3
  have v4 : (¬ e 2 4) := fun hu => c155 e tri schur v2 h3 hu
  have v5 : (¬ e 9 15) := fun hu => c412 e tri schur hu h1 v2
  exact c878 e tri schur v3 v1 v5

theorem c1114 : (e 16 18) → (e 6 16) → (e 4 6) → (¬ e 12 18) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 4 16) := fun hu => c383 e tri schur h1 hu h2
  have v1 : (¬ e 6 18) := fun hu => c594 e tri schur h0 hu h1
  have v2 : (e 6 12) := Classical.byContradiction (fun hu => c881 e tri schur hu v1 h3)
  have v3 : (¬ e 12 16) := fun hu => c1002 e tri schur h0 hu h1
  have v4 : (¬ e 6 8) := fun hu => c1091 e tri schur v2 hu h2
  have v5 : (¬ e 4 12) := fun hu => c379 e tri schur v2 hu h2
  exact c865 e tri schur v5 v0 v3

theorem c1115 : (e 5 12) → (e 5 8) → (e 4 14) → (e 4 9) → (e 2 5) → (¬ e 4 8) → (¬ e 5 9) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 2 8) := fun hu => c167 e tri schur h1 hu h4
  have v1 : (¬ e 2 12) := fun hu => c171 e tri schur h0 hu h4
  have v2 : (¬ e 9 14) := fun hu => c411 e tri schur hu h2 h3
  have v3 : (¬ e 8 12) := fun hu => c478 e tri schur hu h0 h1
  have v4 : (e 4 12) := Classical.byContradiction (fun hu => c861 e tri schur h5 hu v3)
  have v5 : (e 5 14) := Classical.byContradiction (fun hu => c871 e tri schur h6 hu v2)
  exact c1096 e tri schur h2 v4 h3 h4 v1 h6

theorem c1118 : (e 2 9) → (e 2 5) → (e 2 4) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 5) := fun hu => c151 e tri schur hu h1 h2
  have v1 : (¬ e 4 9) := fun hu => c155 e tri schur hu h0 h2
  have v2 : (¬ e 5 9) := fun hu => c168 e tri schur hu h0 h1
  exact c858 e tri schur v0 v1 v2

theorem c1121 : (e 7 11) → (e 7 8) → (e 3 7) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 8) := fun hu => c295 e tri schur h1 hu h2
  have v1 : (¬ e 3 11) := fun hu => c298 e tri schur h0 hu h2
  have v2 : (¬ e 8 11) := fun hu => c598 e tri schur hu h0 h1
  exact c850 e tri schur v0 v1 v2

end Jsp746.Certificate
