/- Generated by scripts/generate_refutation.py from our own SAT trace.
Every statement below is proved with ordinary kernel-checked proof terms. -/
import Jsp746.Certificate.Steps29

namespace Jsp746.Certificate
variable (e : ℕ → ℕ → Prop)
variable (tri : TriangleCondition e) (schur : SchurCondition e)
include tri schur

theorem c2990 : (¬ e 4 11) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (¬ e 1 3) := fun hu => c16 e tri schur v32 v14 hu
  have v34 : (¬ e 1 10) := fun hu => c82 e tri schur v30 hu v3
  have v35 : (¬ e 3 6) := fun hu => c257 e tri schur v25 hu v32
  exact c860 e tri schur v28 h0 v21

theorem c2991 : (e 1 10) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2870 e tri schur h0 hu)
  have v4 : (¬ e 2 6) := fun hu => c2887 e tri schur hu h0
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2928 e tri schur h0 hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2971 e tri schur hu h0
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 3) := fun hu => c16 e tri schur v32 v14 hu
  have v35 : (¬ e 4 10) := fun hu => c36 e tri schur hu h0 v14
  have v36 : (¬ e 1 11) := fun hu => c37 e tri schur v33 hu v14
  have v37 : (¬ e 1 7) := fun hu => c72 e tri schur v24 h0 hu
  exact c82 e tri schur v30 h0 v3

theorem c2992 : (e 10 15) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 1 3) := fun hu => c16 e tri schur v32 v14 hu
  have v36 : (¬ e 1 11) := fun hu => c37 e tri schur v33 hu v14
  have v37 : (¬ e 3 6) := fun hu => c257 e tri schur v25 hu v32
  have v38 : (¬ e 6 11) := fun hu => c378 e tri schur hu v33 v25
  have v39 : (¬ e 7 15) := fun hu => c619 e tri schur h0 hu v24
  have v40 : (¬ e 8 15) := fun hu => c664 e tri schur h0 hu v30
  have v41 : (e 10 11) := Classical.byContradiction (fun hu => c824 e tri schur v34 v36 hu)
  have v42 : (e 11 12) := Classical.byContradiction (fun hu => c825 e tri schur v36 v16 hu)
  exact c882 e tri schur v20 v39 v40

theorem c2993 : (e 1 3) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2843 e tri schur h0 hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2933 e tri schur h0 hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  exact c16 e tri schur v32 v14 h0

theorem c2994 : (e 3 6) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  have v36 : (¬ e 1 3) := fun hu => c2993 e tri schur hu
  have v37 : (¬ e 1 11) := fun hu => c37 e tri schur v33 hu v14
  exact c257 e tri schur v25 h0 v32

theorem c2995 : (e 4 9) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  have v36 : (¬ e 1 3) := fun hu => c2993 e tri schur hu
  have v37 : (¬ e 3 6) := fun hu => c2994 e tri schur hu
  have v38 : (¬ e 1 9) := fun hu => c35 e tri schur h0 hu v14
  have v39 : (¬ e 1 11) := fun hu => c37 e tri schur v33 hu v14
  have v40 : (¬ e 3 9) := fun hu => c260 e tri schur h0 hu v32
  have v41 : (¬ e 6 9) := fun hu => c376 e tri schur hu h0 v25
  have v42 : (¬ e 6 11) := fun hu => c378 e tri schur hu v33 v25
  have v43 : (¬ e 9 11) := fun hu => c408 e tri schur hu v33 h0
  have v44 : (e 9 10) := Classical.byContradiction (fun hu => c823 e tri schur v38 v34 hu)
  have v45 : (e 10 11) := Classical.byContradiction (fun hu => c824 e tri schur v34 v39 hu)
  have v46 : (e 11 12) := Classical.byContradiction (fun hu => c825 e tri schur v39 v16 hu)
  exact c848 e tri schur v37 v40 v41

theorem c2996 : (e 4 14) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  have v36 : (¬ e 1 3) := fun hu => c2993 e tri schur hu
  have v37 : (¬ e 3 6) := fun hu => c2994 e tri schur hu
  have v38 : (¬ e 4 9) := fun hu => c2995 e tri schur hu
  have v39 : (¬ e 1 11) := fun hu => c37 e tri schur v33 hu v14
  have v40 : (¬ e 1 14) := fun hu => c40 e tri schur h0 hu v14
  have v41 : (¬ e 3 14) := fun hu => c265 e tri schur h0 hu v32
  have v42 : (¬ e 6 11) := fun hu => c378 e tri schur hu v33 v25
  have v43 : (¬ e 6 14) := fun hu => c381 e tri schur hu h0 v25
  have v44 : (¬ e 11 14) := fun hu => c426 e tri schur hu h0 v33
  have v45 : (e 10 11) := Classical.byContradiction (fun hu => c824 e tri schur v34 v39 hu)
  have v46 : (e 11 12) := Classical.byContradiction (fun hu => c825 e tri schur v39 v16 hu)
  exact c853 e tri schur v9 v41 v44

theorem c2997 : (e 4 12) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  have v36 : (¬ e 1 3) := fun hu => c2993 e tri schur hu
  have v37 : (¬ e 3 6) := fun hu => c2994 e tri schur hu
  have v38 : (¬ e 4 9) := fun hu => c2995 e tri schur hu
  have v39 : (¬ e 4 14) := fun hu => c2996 e tri schur hu
  have v40 : (¬ e 1 11) := fun hu => c37 e tri schur v33 hu v14
  have v41 : (¬ e 3 12) := fun hu => c263 e tri schur h0 hu v32
  have v42 : (¬ e 6 11) := fun hu => c378 e tri schur hu v33 v25
  have v43 : (¬ e 11 12) := fun hu => c424 e tri schur hu h0 v33
  have v44 : (e 10 11) := Classical.byContradiction (fun hu => c824 e tri schur v34 v40 hu)
  exact c825 e tri schur v40 v16 v43

theorem c2998 : (e 1 11) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  have v36 : (¬ e 1 3) := fun hu => c2993 e tri schur hu
  have v37 : (¬ e 3 6) := fun hu => c2994 e tri schur hu
  have v38 : (¬ e 4 9) := fun hu => c2995 e tri schur hu
  have v39 : (¬ e 4 14) := fun hu => c2996 e tri schur hu
  have v40 : (¬ e 4 12) := fun hu => c2997 e tri schur hu
  exact c37 e tri schur v33 h0 v14

theorem c2999 : (e 6 11) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  have v36 : (¬ e 1 3) := fun hu => c2993 e tri schur hu
  have v37 : (¬ e 3 6) := fun hu => c2994 e tri schur hu
  have v38 : (¬ e 4 9) := fun hu => c2995 e tri schur hu
  have v39 : (¬ e 4 14) := fun hu => c2996 e tri schur hu
  have v40 : (¬ e 4 12) := fun hu => c2997 e tri schur hu
  have v41 : (¬ e 1 11) := fun hu => c2998 e tri schur hu
  exact c378 e tri schur h0 v33 v25

theorem c3000 : (¬ e 5 9) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 4 9) := Classical.byContradiction (fun hu => c2678 e tri schur hu h0)
  have v4 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v5 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v6 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v7 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v8 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v9 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v10 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v11 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v12 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v13 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v14 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v15 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v16 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v17 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v18 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v19 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v20 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v21 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v22 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v23 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v24 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v25 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v26 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v27 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v28 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v29 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v30 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v31 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v32 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v33 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v34 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v35 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v36 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  have v37 : (¬ e 1 3) := fun hu => c2993 e tri schur hu
  have v38 : (¬ e 3 6) := fun hu => c2994 e tri schur hu
  exact c2995 e tri schur v3

theorem c3001 : (¬ e 8 12) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  have v36 : (¬ e 1 3) := fun hu => c2993 e tri schur hu
  have v37 : (¬ e 3 6) := fun hu => c2994 e tri schur hu
  have v38 : (¬ e 4 9) := fun hu => c2995 e tri schur hu
  have v39 : (¬ e 4 14) := fun hu => c2996 e tri schur hu
  have v40 : (¬ e 4 12) := fun hu => c2997 e tri schur hu
  have v41 : (¬ e 1 11) := fun hu => c2998 e tri schur hu
  have v42 : (¬ e 6 11) := fun hu => c2999 e tri schur hu
  have v43 : (e 5 9) := Classical.byContradiction (fun hu => c3000 e tri schur hu)
  have v44 : (e 10 11) := Classical.byContradiction (fun hu => c824 e tri schur v34 v41 hu)
  have v45 : (e 11 12) := Classical.byContradiction (fun hu => c825 e tri schur v41 v16 hu)
  exact c861 e tri schur v15 v40 h0

theorem c3002 : (¬ e 10 11) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  have v36 : (¬ e 1 3) := fun hu => c2993 e tri schur hu
  have v37 : (¬ e 3 6) := fun hu => c2994 e tri schur hu
  have v38 : (¬ e 4 9) := fun hu => c2995 e tri schur hu
  have v39 : (¬ e 4 14) := fun hu => c2996 e tri schur hu
  have v40 : (¬ e 4 12) := fun hu => c2997 e tri schur hu
  have v41 : (¬ e 1 11) := fun hu => c2998 e tri schur hu
  have v42 : (¬ e 6 11) := fun hu => c2999 e tri schur hu
  have v43 : (e 5 9) := Classical.byContradiction (fun hu => c3000 e tri schur hu)
  have v44 : (e 8 12) := Classical.byContradiction (fun hu => c3001 e tri schur hu)
  have v45 : (¬ e 10 12) := fun hu => c661 e tri schur hu v44 v30
  exact c824 e tri schur v34 v41 h0

theorem c3003 : (¬ e 1 9) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  have v36 : (¬ e 1 3) := fun hu => c2993 e tri schur hu
  have v37 : (¬ e 3 6) := fun hu => c2994 e tri schur hu
  have v38 : (¬ e 4 9) := fun hu => c2995 e tri schur hu
  have v39 : (¬ e 4 14) := fun hu => c2996 e tri schur hu
  have v40 : (¬ e 4 12) := fun hu => c2997 e tri schur hu
  have v41 : (¬ e 1 11) := fun hu => c2998 e tri schur hu
  have v42 : (¬ e 6 11) := fun hu => c2999 e tri schur hu
  have v43 : (e 5 9) := Classical.byContradiction (fun hu => c3000 e tri schur hu)
  have v44 : (e 8 12) := Classical.byContradiction (fun hu => c3001 e tri schur hu)
  have v45 : (e 10 11) := Classical.byContradiction (fun hu => c3002 e tri schur hu)
  have v46 : (¬ e 4 10) := fun hu => c416 e tri schur v45 v33 hu
  have v47 : (¬ e 8 11) := fun hu => c660 e tri schur v45 hu v30
  have v48 : (¬ e 10 12) := fun hu => c661 e tri schur hu v44 v30
  have v49 : (e 9 10) := Classical.byContradiction (fun hu => c823 e tri schur h0 v34 hu)
  have v50 : (e 11 12) := Classical.byContradiction (fun hu => c825 e tri schur v41 v16 hu)
  have v51 : (e 2 12) := Classical.byContradiction (fun hu => c839 e tri schur v26 hu v48)
  have v52 : (e 3 8) := Classical.byContradiction (fun hu => c850 e tri schur hu v9 v47)
  have v53 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v46 v39 hu)
  have v54 : (¬ e 8 15) := fun hu => c987 e tri schur hu v44 v52
  have v55 : (¬ e 8 18) := fun hu => c1303 e tri schur hu v44 v10
  exact c1336 e tri schur v50 v45 v5

theorem c3004 : (e 9 12) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  have v36 : (¬ e 1 3) := fun hu => c2993 e tri schur hu
  have v37 : (¬ e 3 6) := fun hu => c2994 e tri schur hu
  have v38 : (¬ e 4 9) := fun hu => c2995 e tri schur hu
  have v39 : (¬ e 4 14) := fun hu => c2996 e tri schur hu
  have v40 : (¬ e 4 12) := fun hu => c2997 e tri schur hu
  have v41 : (¬ e 1 11) := fun hu => c2998 e tri schur hu
  have v42 : (¬ e 6 11) := fun hu => c2999 e tri schur hu
  have v43 : (e 5 9) := Classical.byContradiction (fun hu => c3000 e tri schur hu)
  have v44 : (e 8 12) := Classical.byContradiction (fun hu => c3001 e tri schur hu)
  have v45 : (e 10 11) := Classical.byContradiction (fun hu => c3002 e tri schur hu)
  have v46 : (e 1 9) := Classical.byContradiction (fun hu => c3003 e tri schur hu)
  have v47 : (¬ e 1 5) := fun hu => c48 e tri schur v43 v46 hu
  have v48 : (¬ e 8 9) := fun hu => c81 e tri schur hu v46 v3
  have v49 : (¬ e 4 10) := fun hu => c416 e tri schur v45 v33 hu
  have v50 : (¬ e 5 12) := fun hu => c487 e tri schur h0 hu v43
  have v51 : (¬ e 8 11) := fun hu => c660 e tri schur v45 hu v30
  have v52 : (¬ e 10 12) := fun hu => c661 e tri schur hu v44 v30
  have v53 : (e 5 6) := Classical.byContradiction (fun hu => c819 e tri schur v47 v11 hu)
  have v54 : (e 11 12) := Classical.byContradiction (fun hu => c825 e tri schur v41 v16 hu)
  have v55 : (e 2 12) := Classical.byContradiction (fun hu => c839 e tri schur v26 hu v52)
  have v56 : (e 3 8) := Classical.byContradiction (fun hu => c850 e tri schur hu v9 v51)
  have v57 : (e 10 14) := Classical.byContradiction (fun hu => c863 e tri schur v49 v39 hu)
  have v58 : (e 5 7) := Classical.byContradiction (fun hu => c869 e tri schur hu v50 v27)
  have v59 : (¬ e 7 15) := fun hu => c907 e tri schur hu v24 v58 v35
  have v60 : (¬ e 8 15) := fun hu => c987 e tri schur hu v44 v56
  have v61 : (¬ e 6 13) := fun hu => c988 e tri schur hu v10 v53 v12
  have v62 : (¬ e 5 13) := fun hu => c1170 e tri schur hu v58 v53
  have v63 : (¬ e 8 18) := fun hu => c1303 e tri schur hu v44 v10
  have v64 : (e 1 7) := Classical.byContradiction (fun hu => c1314 e tri schur v44 hu v9 v20 v59)
  exact c1336 e tri schur v54 v45 v5

theorem c3005 : (¬ e 11 12) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  have v36 : (¬ e 1 3) := fun hu => c2993 e tri schur hu
  have v37 : (¬ e 3 6) := fun hu => c2994 e tri schur hu
  have v38 : (¬ e 4 9) := fun hu => c2995 e tri schur hu
  have v39 : (¬ e 4 14) := fun hu => c2996 e tri schur hu
  have v40 : (¬ e 4 12) := fun hu => c2997 e tri schur hu
  have v41 : (¬ e 1 11) := fun hu => c2998 e tri schur hu
  have v42 : (¬ e 6 11) := fun hu => c2999 e tri schur hu
  have v43 : (e 5 9) := Classical.byContradiction (fun hu => c3000 e tri schur hu)
  have v44 : (e 8 12) := Classical.byContradiction (fun hu => c3001 e tri schur hu)
  have v45 : (e 10 11) := Classical.byContradiction (fun hu => c3002 e tri schur hu)
  have v46 : (e 1 9) := Classical.byContradiction (fun hu => c3003 e tri schur hu)
  have v47 : (¬ e 9 12) := fun hu => c3004 e tri schur hu
  have v48 : (¬ e 1 5) := fun hu => c48 e tri schur v43 v46 hu
  have v49 : (¬ e 8 9) := fun hu => c81 e tri schur hu v46 v3
  have v50 : (¬ e 4 10) := fun hu => c416 e tri schur v45 v33 hu
  have v51 : (¬ e 8 11) := fun hu => c660 e tri schur v45 hu v30
  have v52 : (¬ e 10 12) := fun hu => c661 e tri schur hu v44 v30
  have v53 : (e 5 6) := Classical.byContradiction (fun hu => c819 e tri schur v48 v11 hu)
  exact c825 e tri schur v41 v16 h0

theorem c3006 : (e 10 12) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  have v36 : (¬ e 1 3) := fun hu => c2993 e tri schur hu
  have v37 : (¬ e 3 6) := fun hu => c2994 e tri schur hu
  have v38 : (¬ e 4 9) := fun hu => c2995 e tri schur hu
  have v39 : (¬ e 4 14) := fun hu => c2996 e tri schur hu
  have v40 : (¬ e 4 12) := fun hu => c2997 e tri schur hu
  have v41 : (¬ e 1 11) := fun hu => c2998 e tri schur hu
  have v42 : (¬ e 6 11) := fun hu => c2999 e tri schur hu
  have v43 : (e 5 9) := Classical.byContradiction (fun hu => c3000 e tri schur hu)
  have v44 : (e 8 12) := Classical.byContradiction (fun hu => c3001 e tri schur hu)
  have v45 : (e 10 11) := Classical.byContradiction (fun hu => c3002 e tri schur hu)
  have v46 : (e 1 9) := Classical.byContradiction (fun hu => c3003 e tri schur hu)
  have v47 : (¬ e 9 12) := fun hu => c3004 e tri schur hu
  have v48 : (e 11 12) := Classical.byContradiction (fun hu => c3005 e tri schur hu)
  have v49 : (¬ e 1 5) := fun hu => c48 e tri schur v43 v46 hu
  have v50 : (¬ e 8 9) := fun hu => c81 e tri schur hu v46 v3
  have v51 : (¬ e 2 12) := fun hu => c228 e tri schur v48 hu v5
  have v52 : (¬ e 4 10) := fun hu => c416 e tri schur v45 v33 hu
  have v53 : (¬ e 8 11) := fun hu => c660 e tri schur v45 hu v30
  exact c661 e tri schur h0 v44 v30

theorem c3007 : (¬ e 3 9) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  have v36 : (¬ e 1 3) := fun hu => c2993 e tri schur hu
  have v37 : (¬ e 3 6) := fun hu => c2994 e tri schur hu
  have v38 : (¬ e 4 9) := fun hu => c2995 e tri schur hu
  have v39 : (¬ e 4 14) := fun hu => c2996 e tri schur hu
  have v40 : (¬ e 4 12) := fun hu => c2997 e tri schur hu
  have v41 : (¬ e 1 11) := fun hu => c2998 e tri schur hu
  have v42 : (¬ e 6 11) := fun hu => c2999 e tri schur hu
  have v43 : (e 5 9) := Classical.byContradiction (fun hu => c3000 e tri schur hu)
  have v44 : (e 8 12) := Classical.byContradiction (fun hu => c3001 e tri schur hu)
  have v45 : (e 10 11) := Classical.byContradiction (fun hu => c3002 e tri schur hu)
  have v46 : (e 1 9) := Classical.byContradiction (fun hu => c3003 e tri schur hu)
  have v47 : (¬ e 9 12) := fun hu => c3004 e tri schur hu
  have v48 : (e 11 12) := Classical.byContradiction (fun hu => c3005 e tri schur hu)
  have v49 : (¬ e 10 12) := fun hu => c3006 e tri schur hu
  have v50 : (¬ e 1 5) := fun hu => c48 e tri schur v43 v46 hu
  have v51 : (¬ e 8 9) := fun hu => c81 e tri schur hu v46 v3
  have v52 : (¬ e 2 12) := fun hu => c228 e tri schur v48 hu v5
  have v53 : (¬ e 4 10) := fun hu => c416 e tri schur v45 v33 hu
  have v54 : (¬ e 8 11) := fun hu => c660 e tri schur v45 hu v30
  have v55 : (e 5 6) := Classical.byContradiction (fun hu => c819 e tri schur v50 v11 hu)
  exact c839 e tri schur v26 v52 v49

theorem c3008 : (e 8 11) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  have v36 : (¬ e 1 3) := fun hu => c2993 e tri schur hu
  have v37 : (¬ e 3 6) := fun hu => c2994 e tri schur hu
  have v38 : (¬ e 4 9) := fun hu => c2995 e tri schur hu
  have v39 : (¬ e 4 14) := fun hu => c2996 e tri schur hu
  have v40 : (¬ e 4 12) := fun hu => c2997 e tri schur hu
  have v41 : (¬ e 1 11) := fun hu => c2998 e tri schur hu
  have v42 : (¬ e 6 11) := fun hu => c2999 e tri schur hu
  have v43 : (e 5 9) := Classical.byContradiction (fun hu => c3000 e tri schur hu)
  have v44 : (e 8 12) := Classical.byContradiction (fun hu => c3001 e tri schur hu)
  have v45 : (e 10 11) := Classical.byContradiction (fun hu => c3002 e tri schur hu)
  have v46 : (e 1 9) := Classical.byContradiction (fun hu => c3003 e tri schur hu)
  have v47 : (¬ e 9 12) := fun hu => c3004 e tri schur hu
  have v48 : (e 11 12) := Classical.byContradiction (fun hu => c3005 e tri schur hu)
  have v49 : (¬ e 10 12) := fun hu => c3006 e tri schur hu
  have v50 : (e 3 9) := Classical.byContradiction (fun hu => c3007 e tri schur hu)
  have v51 : (¬ e 1 5) := fun hu => c48 e tri schur v43 v46 hu
  have v52 : (¬ e 8 9) := fun hu => c81 e tri schur hu v46 v3
  have v53 : (¬ e 2 12) := fun hu => c228 e tri schur v48 hu v5
  have v54 : (¬ e 3 5) := fun hu => c273 e tri schur v43 v50 hu
  have v55 : (¬ e 4 10) := fun hu => c416 e tri schur v45 v33 hu
  exact c660 e tri schur v45 h0 v30

theorem c3009 : (e 8 18) → False := by
  intro h0
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  have v36 : (¬ e 1 3) := fun hu => c2993 e tri schur hu
  have v37 : (¬ e 3 6) := fun hu => c2994 e tri schur hu
  have v38 : (¬ e 4 9) := fun hu => c2995 e tri schur hu
  have v39 : (¬ e 4 14) := fun hu => c2996 e tri schur hu
  have v40 : (¬ e 4 12) := fun hu => c2997 e tri schur hu
  have v41 : (¬ e 1 11) := fun hu => c2998 e tri schur hu
  have v42 : (¬ e 6 11) := fun hu => c2999 e tri schur hu
  have v43 : (e 5 9) := Classical.byContradiction (fun hu => c3000 e tri schur hu)
  have v44 : (e 8 12) := Classical.byContradiction (fun hu => c3001 e tri schur hu)
  have v45 : (e 10 11) := Classical.byContradiction (fun hu => c3002 e tri schur hu)
  have v46 : (e 1 9) := Classical.byContradiction (fun hu => c3003 e tri schur hu)
  have v47 : (¬ e 9 12) := fun hu => c3004 e tri schur hu
  have v48 : (e 11 12) := Classical.byContradiction (fun hu => c3005 e tri schur hu)
  have v49 : (¬ e 10 12) := fun hu => c3006 e tri schur hu
  have v50 : (e 3 9) := Classical.byContradiction (fun hu => c3007 e tri schur hu)
  have v51 : (¬ e 8 11) := fun hu => c3008 e tri schur hu
  have v52 : (¬ e 1 5) := fun hu => c48 e tri schur v43 v46 hu
  have v53 : (¬ e 8 9) := fun hu => c81 e tri schur hu v46 v3
  have v54 : (¬ e 1 18) := fun hu => c90 e tri schur h0 hu v3
  have v55 : (¬ e 2 12) := fun hu => c228 e tri schur v48 hu v5
  have v56 : (¬ e 3 5) := fun hu => c273 e tri schur v43 v50 hu
  have v57 : (¬ e 4 10) := fun hu => c416 e tri schur v45 v33 hu
  have v58 : (¬ e 6 18) := fun hu => c550 e tri schur h0 hu v10
  have v59 : (¬ e 10 18) := fun hu => c667 e tri schur hu h0 v30
  have v60 : (¬ e 12 18) := fun hu => c680 e tri schur hu h0 v44
  have v61 : (e 5 6) := Classical.byContradiction (fun hu => c819 e tri schur v52 v11 hu)
  exact c839 e tri schur v26 v55 v49

theorem c3010 : False := by
  have v0 : (¬ e 1 2) := fun hu => c2019 e tri schur hu
  have v1 : (¬ e 7 9) := fun hu => c2229 e tri schur hu
  have v2 : (¬ e 4 5) := fun hu => c2653 e tri schur hu
  have v3 : (e 1 8) := Classical.byContradiction (fun hu => c2873 e tri schur hu)
  have v4 : (¬ e 2 6) := fun hu => c2895 e tri schur hu
  have v5 : (e 2 11) := Classical.byContradiction (fun hu => c2951 e tri schur hu)
  have v6 : (e 2 3) := Classical.byContradiction (fun hu => c2955 e tri schur hu)
  have v7 : (¬ e 3 10) := fun hu => c2956 e tri schur hu
  have v8 : (¬ e 2 8) := fun hu => c2957 e tri schur hu
  have v9 : (¬ e 3 11) := fun hu => c2958 e tri schur hu
  have v10 : (e 6 8) := Classical.byContradiction (fun hu => c2959 e tri schur hu)
  have v11 : (¬ e 1 6) := fun hu => c2960 e tri schur hu
  have v12 : (¬ e 5 8) := fun hu => c2961 e tri schur hu
  have v13 : (¬ e 2 14) := fun hu => c2963 e tri schur hu
  have v14 : (e 1 4) := Classical.byContradiction (fun hu => c2968 e tri schur hu)
  have v15 : (¬ e 4 8) := fun hu => c2969 e tri schur hu
  have v16 : (¬ e 1 12) := fun hu => c2970 e tri schur hu
  have v17 : (¬ e 2 9) := fun hu => c2974 e tri schur hu
  have v18 : (e 2 7) := Classical.byContradiction (fun hu => c2975 e tri schur hu)
  have v19 : (¬ e 3 7) := fun hu => c2976 e tri schur hu
  have v20 : (¬ e 7 8) := fun hu => c2977 e tri schur hu
  have v21 : (¬ e 7 11) := fun hu => c2978 e tri schur hu
  have v22 : (¬ e 2 4) := fun hu => c2979 e tri schur hu
  have v23 : (¬ e 2 18) := fun hu => c2980 e tri schur hu
  have v24 : (e 7 10) := Classical.byContradiction (fun hu => c2981 e tri schur hu)
  have v25 : (e 4 6) := Classical.byContradiction (fun hu => c2982 e tri schur hu)
  have v26 : (¬ e 2 10) := fun hu => c2983 e tri schur hu
  have v27 : (¬ e 7 12) := fun hu => c2984 e tri schur hu
  have v28 : (¬ e 4 7) := fun hu => c2985 e tri schur hu
  have v29 : (¬ e 6 12) := fun hu => c2986 e tri schur hu
  have v30 : (e 8 10) := Classical.byContradiction (fun hu => c2987 e tri schur hu)
  have v31 : (¬ e 6 10) := fun hu => c2988 e tri schur hu
  have v32 : (e 3 4) := Classical.byContradiction (fun hu => c2989 e tri schur hu)
  have v33 : (e 4 11) := Classical.byContradiction (fun hu => c2990 e tri schur hu)
  have v34 : (¬ e 1 10) := fun hu => c2991 e tri schur hu
  have v35 : (¬ e 10 15) := fun hu => c2992 e tri schur hu
  have v36 : (¬ e 1 3) := fun hu => c2993 e tri schur hu
  have v37 : (¬ e 3 6) := fun hu => c2994 e tri schur hu
  have v38 : (¬ e 4 9) := fun hu => c2995 e tri schur hu
  have v39 : (¬ e 4 14) := fun hu => c2996 e tri schur hu
  have v40 : (¬ e 4 12) := fun hu => c2997 e tri schur hu
  have v41 : (¬ e 1 11) := fun hu => c2998 e tri schur hu
  have v42 : (¬ e 6 11) := fun hu => c2999 e tri schur hu
  have v43 : (e 5 9) := Classical.byContradiction (fun hu => c3000 e tri schur hu)
  have v44 : (e 8 12) := Classical.byContradiction (fun hu => c3001 e tri schur hu)
  have v45 : (e 10 11) := Classical.byContradiction (fun hu => c3002 e tri schur hu)
  have v46 : (e 1 9) := Classical.byContradiction (fun hu => c3003 e tri schur hu)
  have v47 : (¬ e 9 12) := fun hu => c3004 e tri schur hu
  have v48 : (e 11 12) := Classical.byContradiction (fun hu => c3005 e tri schur hu)
  have v49 : (¬ e 10 12) := fun hu => c3006 e tri schur hu
  have v50 : (e 3 9) := Classical.byContradiction (fun hu => c3007 e tri schur hu)
  have v51 : (¬ e 8 11) := fun hu => c3008 e tri schur hu
  have v52 : (¬ e 8 18) := fun hu => c3009 e tri schur hu
  have v53 : (¬ e 1 5) := fun hu => c48 e tri schur v43 v46 hu
  have v54 : (¬ e 8 9) := fun hu => c81 e tri schur hu v46 v3
  have v55 : (¬ e 2 12) := fun hu => c228 e tri schur v48 hu v5
  have v56 : (¬ e 3 5) := fun hu => c273 e tri schur v43 v50 hu
  have v57 : (¬ e 4 10) := fun hu => c416 e tri schur v45 v33 hu
  have v58 : (e 5 6) := Classical.byContradiction (fun hu => c819 e tri schur v53 v11 hu)
  exact c839 e tri schur v26 v55 v49

end Jsp746.Certificate
