/- Generated by scripts/generate_refutation.py from our own SAT trace.
Every statement below is proved with ordinary kernel-checked proof terms. -/
import Jsp746.Certificate.Initial

namespace Jsp746.Certificate
variable (e : ℕ → ℕ → Prop)
variable (tri : TriangleCondition e) (schur : SchurCondition e)
include tri schur

theorem c888 : (e 17 18) → (e 9 18) → (e 8 18) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 8 9) := fun hu => c659 e tri schur h1 h2 hu
  have v1 : (¬ e 8 17) := fun hu => c695 e tri schur h0 h2 hu
  have v2 : (¬ e 9 17) := fun hu => c731 e tri schur h0 h1 hu
  exact c886 e tri schur v0 v1 v2

theorem c889 : (e 16 18) → (e 9 18) → (e 7 18) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 7 9) := fun hu => c614 e tri schur h1 h2 hu
  have v1 : (¬ e 7 16) := fun hu => c649 e tri schur h0 h2 hu
  have v2 : (¬ e 9 16) := fun hu => c730 e tri schur h0 h1 hu
  exact c883 e tri schur v0 v1 v2

theorem c890 : (e 15 18) → (e 9 18) → (e 6 18) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 6 9) := fun hu => c559 e tri schur h1 h2 hu
  have v1 : (¬ e 6 15) := fun hu => c592 e tri schur h0 h2 hu
  have v2 : (¬ e 9 15) := fun hu => c728 e tri schur h0 h1 hu
  exact c878 e tri schur v0 v1 v2

theorem c891 : (e 14 18) → (e 9 18) → (e 5 18) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 5 9) := fun hu => c493 e tri schur h1 h2 hu
  have v1 : (¬ e 5 14) := fun hu => c523 e tri schur h0 h2 hu
  have v2 : (¬ e 9 14) := fun hu => c725 e tri schur h0 h1 hu
  exact c871 e tri schur v0 v1 v2

theorem c892 : (e 13 18) → (e 9 18) → (e 4 18) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 9) := fun hu => c415 e tri schur h1 h2 hu
  have v1 : (¬ e 4 13) := fun hu => c441 e tri schur h0 h2 hu
  have v2 : (¬ e 9 13) := fun hu => c721 e tri schur h0 h1 hu
  exact c862 e tri schur v0 v1 v2

theorem c893 : (e 12 18) → (e 9 18) → (e 3 18) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 9) := fun hu => c324 e tri schur h1 h2 hu
  have v1 : (¬ e 3 12) := fun hu => c345 e tri schur h0 h2 hu
  have v2 : (¬ e 9 12) := fun hu => c716 e tri schur h0 h1 hu
  exact c851 e tri schur v0 v1 v2

theorem c894 : (e 7 9) → (e 4 9) → (e 3 9) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 4) := fun hu => c260 e tri schur h1 h2 hu
  have v1 : (¬ e 3 7) := fun hu => c296 e tri schur h0 h2 hu
  have v2 : (¬ e 4 7) := fun hu => c387 e tri schur h0 h1 hu
  exact c846 e tri schur v0 v1 v2

theorem c895 : (e 11 18) → (e 9 18) → (e 2 18) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 9) := fun hu => c219 e tri schur h1 h2 hu
  have v1 : (¬ e 2 11) := fun hu => c234 e tri schur h0 h2 hu
  have v2 : (¬ e 9 11) := fun hu => c710 e tri schur h0 h1 hu
  exact c838 e tri schur v0 v1 v2

theorem c896 : (e 6 9) → (e 4 9) → (e 2 9) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 4) := fun hu => c155 e tri schur h1 h2 hu
  have v1 : (¬ e 2 6) := fun hu => c180 e tri schur h0 h2 hu
  have v2 : (¬ e 4 6) := fun hu => c376 e tri schur h0 h1 hu
  exact c833 e tri schur v0 v1 v2

theorem c899 : (e 7 9) → (e 5 9) → (e 2 9) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 5) := fun hu => c168 e tri schur h1 h2 hu
  have v1 : (¬ e 2 7) := fun hu => c191 e tri schur h0 h2 hu
  have v2 : (¬ e 5 7) := fun hu => c465 e tri schur h0 h1 hu
  exact c834 e tri schur v0 v1 v2

theorem c900 : (e 7 15) → (¬ e 4 11) → (¬ e 7 11) → (¬ e 11 15) → False := by
  intro h0 h1 h2 h3
  have v0 : (e 4 7) := Classical.byContradiction (fun hu => c860 e tri schur hu h1 h2)
  have v1 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur h1 hu h3)
  exact c393 e tri schur h0 v1 v0

theorem c903 : (e 8 9) → (e 6 9) → (e 2 9) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 6) := fun hu => c180 e tri schur h1 h2 hu
  have v1 : (¬ e 2 8) := fun hu => c201 e tri schur h0 h2 hu
  have v2 : (¬ e 6 8) := fun hu => c541 e tri schur h0 h1 hu
  exact c835 e tri schur v0 v1 v2

theorem c904 : (e 6 13) → (e 6 9) → (e 4 6) → (¬ e 9 13) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 4 9) := fun hu => c376 e tri schur h1 hu h2
  have v1 : (¬ e 4 13) := fun hu => c380 e tri schur h0 hu h2
  exact c862 e tri schur v0 v1 h3

theorem c905 : (e 3 7) → (¬ e 2 3) → (¬ e 2 5) → (¬ e 2 7) → False := by
  intro h0 h1 h2 h3
  have v0 : (e 3 5) := Classical.byContradiction (fun hu => c832 e tri schur h1 h2 hu)
  have v1 : (e 5 7) := Classical.byContradiction (fun hu => c834 e tri schur h2 h3 hu)
  exact c271 e tri schur v1 h0 v0

theorem c907 : (e 7 15) → (e 7 10) → (e 5 7) → (¬ e 10 15) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 5 10) := fun hu => c466 e tri schur h1 hu h2
  have v1 : (¬ e 5 15) := fun hu => c471 e tri schur h0 hu h2
  exact c872 e tri schur v0 v1 h3

theorem c912 : (e 7 12) → (e 7 10) → (e 2 7) → (¬ e 10 12) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 2 10) := fun hu => c192 e tri schur h1 hu h2
  have v1 : (¬ e 2 12) := fun hu => c194 e tri schur h0 hu h2
  exact c839 e tri schur v0 v1 h3

theorem c913 : (e 2 15) → (e 2 12) → (e 2 3) → (¬ e 12 15) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 12) := fun hu => c144 e tri schur hu h1 h2
  have v1 : (¬ e 3 15) := fun hu => c147 e tri schur hu h0 h2
  exact c854 e tri schur v0 v1 h3

theorem c914 : (e 8 9) → (e 5 9) → (e 3 9) → (¬ e 5 8) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 5) := fun hu => c273 e tri schur h1 h2 hu
  have v1 : (¬ e 3 8) := fun hu => c306 e tri schur h0 h2 hu
  exact c847 e tri schur v0 v1 h3

theorem c915 : (e 3 12) → (e 3 8) → (e 3 4) → (¬ e 8 12) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 4 8) := fun hu => c259 e tri schur hu h1 h2
  have v1 : (¬ e 4 12) := fun hu => c263 e tri schur hu h0 h2
  exact c861 e tri schur v0 v1 h3

theorem c916 : (e 2 11) → (e 2 6) → (e 2 5) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 5 6) := fun hu => c165 e tri schur hu h1 h2
  have v1 : (¬ e 5 11) := fun hu => c170 e tri schur hu h0 h2
  have v2 : (¬ e 6 11) := fun hu => c182 e tri schur hu h0 h1
  exact c868 e tri schur v0 v1 v2

theorem c917 : (e 5 17) → (¬ e 5 11) → (¬ e 6 11) → (¬ e 11 17) → False := by
  intro h0 h1 h2 h3
  have v0 : (e 5 6) := Classical.byContradiction (fun hu => c868 e tri schur hu h1 h2)
  have v1 : (e 6 17) := Classical.byContradiction (fun hu => c880 e tri schur h2 hu h3)
  exact c462 e tri schur v1 h0 v0

theorem c923 : (e 6 11) → (e 4 7) → (e 4 6) → (¬ e 9 13) → (¬ e 9 15) → (¬ e 11 15) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 6 7) := fun hu => c374 e tri schur hu h1 h2
  have v1 : (¬ e 4 11) := fun hu => c378 e tri schur h0 hu h2
  have v2 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur v1 hu h5)
  have v3 : (¬ e 6 15) := fun hu => c382 e tri schur hu v2 h2
  have v4 : (¬ e 7 15) := fun hu => c393 e tri schur hu v2 h1
  have v5 : (e 6 9) := Classical.byContradiction (fun hu => c878 e tri schur hu v3 h4)
  have v6 : (¬ e 6 13) := fun hu => c904 e tri schur hu v5 h2 h3
  have v7 : (¬ e 4 9) := fun hu => c376 e tri schur v5 hu h2
  have v8 : (¬ e 9 11) := fun hu => c552 e tri schur hu h0 v5
  have v9 : (e 4 13) := Classical.byContradiction (fun hu => c862 e tri schur v7 hu h3)
  have v10 : (e 7 13) := Classical.byContradiction (fun hu => c876 e tri schur v0 v6 hu)
  exact c391 e tri schur v10 v9 h1

theorem c925 : (e 4 7) → (¬ e 2 5) → (¬ e 2 7) → (¬ e 2 9) → False := by
  intro h0 h1 h2 h3
  have v0 : (e 5 7) := Classical.byContradiction (fun hu => c834 e tri schur h1 h2 hu)
  have v1 : (e 7 9) := Classical.byContradiction (fun hu => c836 e tri schur h2 h3 hu)
  have v2 : (¬ e 4 5) := fun hu => c362 e tri schur v0 h0 hu
  have v3 : (¬ e 4 9) := fun hu => c387 e tri schur v1 hu h0
  have v4 : (¬ e 5 9) := fun hu => c465 e tri schur v1 hu v0
  exact c858 e tri schur v2 v3 v4

theorem c926 : (e 7 9) → (e 5 7) → (e 4 7) → (¬ e 4 9) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 4 5) := fun hu => c362 e tri schur h1 h2 hu
  have v1 : (¬ e 5 9) := fun hu => c465 e tri schur h0 hu h1
  exact c858 e tri schur v0 h3 v1

theorem c927 : (e 4 13) → (e 4 7) → (e 4 6) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 6 7) := fun hu => c374 e tri schur hu h1 h2
  have v1 : (¬ e 6 13) := fun hu => c380 e tri schur hu h0 h2
  have v2 : (¬ e 7 13) := fun hu => c391 e tri schur hu h0 h1
  exact c876 e tri schur v0 v1 v2

theorem c928 : (e 4 12) → (e 4 7) → (e 4 5) → (¬ e 5 7) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 5 12) := fun hu => c367 e tri schur hu h0 h2
  have v1 : (¬ e 7 12) := fun hu => c390 e tri schur hu h0 h1
  exact c869 e tri schur h3 v0 v1

theorem c929 : (e 4 15) → (e 4 8) → (e 4 7) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 7 8) := fun hu => c386 e tri schur hu h1 h2
  have v1 : (¬ e 7 15) := fun hu => c393 e tri schur hu h0 h2
  have v2 : (¬ e 8 15) := fun hu => c403 e tri schur hu h0 h1
  exact c882 e tri schur v0 v1 v2

theorem c930 : (e 5 17) → (e 5 13) → (e 4 5) → (¬ e 4 13) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 4 17) := fun hu => c372 e tri schur h0 hu h2
  have v1 : (¬ e 13 17) := fun hu => c518 e tri schur hu h0 h1
  exact c866 e tri schur h3 v0 v1

theorem c931 : (e 7 10) → (e 7 8) → (e 2 7) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 8) := fun hu => c190 e tri schur h1 hu h2
  have v1 : (¬ e 2 10) := fun hu => c192 e tri schur h0 hu h2
  have v2 : (¬ e 8 10) := fun hu => c597 e tri schur hu h0 h1
  exact c837 e tri schur v0 v1 v2

theorem c932 : (e 5 14) → (e 5 10) → (e 4 5) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 10) := fun hu => c365 e tri schur h1 hu h2
  have v1 : (¬ e 4 14) := fun hu => c369 e tri schur h0 hu h2
  have v2 : (¬ e 10 14) := fun hu => c497 e tri schur hu h0 h1
  exact c863 e tri schur v0 v1 v2

theorem c939 : (e 5 10) → (e 2 10) → (e 2 7) → (¬ e 2 5) → (¬ e 3 7) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 7 10) := fun hu => c192 e tri schur hu h1 h2
  have v1 : (e 3 10) := Classical.byContradiction (fun hu => c849 e tri schur h4 hu v0)
  have v2 : (¬ e 2 3) := fun hu => c142 e tri schur v1 h1 hu
  have v3 : (¬ e 3 5) := fun hu => c274 e tri schur h0 v1 hu
  exact c832 e tri schur v2 h3 v3

theorem c940 : (e 9 13) → (e 6 13) → (e 3 13) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 6) := fun hu => c289 e tri schur h1 h2 hu
  have v1 : (¬ e 3 9) := fun hu => c319 e tri schur h0 h2 hu
  have v2 : (¬ e 6 9) := fun hu => c554 e tri schur h0 h1 hu
  exact c848 e tri schur v0 v1 v2

theorem c941 : (e 13 18) → (e 10 13) → (e 5 10) → (¬ e 8 18) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 5 13) := fun hu => c496 e tri schur h1 hu h2
  have v1 : (¬ e 10 18) := fun hu => c749 e tri schur h0 hu h1
  have v2 : (e 8 10) := Classical.byContradiction (fun hu => c887 e tri schur hu h3 v1)
  have v3 : (¬ e 5 8) := fun hu => c476 e tri schur v2 h2 hu
  have v4 : (¬ e 8 13) := fun hu => c662 e tri schur h1 hu v2
  exact c870 e tri schur v3 v0 v4

theorem c942 : (e 8 10) → (e 5 10) → (e 3 10) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 5) := fun hu => c274 e tri schur h1 h2 hu
  have v1 : (¬ e 3 8) := fun hu => c307 e tri schur h0 h2 hu
  have v2 : (¬ e 5 8) := fun hu => c476 e tri schur h0 h1 hu
  exact c847 e tri schur v0 v1 v2

theorem c944 : (e 15 18) → (e 10 15) → (e 8 15) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 8 10) := fun hu => c664 e tri schur h1 h2 hu
  have v1 : (¬ e 8 18) := fun hu => c692 e tri schur h0 hu h2
  have v2 : (¬ e 10 18) := fun hu => c756 e tri schur h0 hu h1
  exact c887 e tri schur v0 v1 v2

theorem c947 : (e 6 11) → (e 2 7) → (e 2 6) → (¬ e 11 13) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 6 7) := fun hu => c178 e tri schur hu h1 h2
  have v1 : (¬ e 2 11) := fun hu => c182 e tri schur h0 hu h2
  have v2 : (e 2 13) := Classical.byContradiction (fun hu => c840 e tri schur v1 hu h3)
  have v3 : (¬ e 6 13) := fun hu => c184 e tri schur hu v2 h2
  have v4 : (¬ e 7 13) := fun hu => c195 e tri schur hu v2 h1
  exact c876 e tri schur v0 v3 v4

theorem c948 : (e 9 14) → (e 9 11) → (e 3 9) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 11) := fun hu => c317 e tri schur h1 hu h2
  have v1 : (¬ e 3 14) := fun hu => c320 e tri schur h0 hu h2
  have v2 : (¬ e 11 14) := fun hu => c706 e tri schur hu h0 h1
  exact c853 e tri schur v0 v1 v2

theorem c949 : (e 5 10) → (e 4 5) → (e 3 10) → (¬ e 2 5) → (¬ e 4 12) → (¬ e 10 12) → False := by
  intro h0 h1 h2 h3 h4 h5
  have v0 : (¬ e 3 5) := fun hu => c274 e tri schur h0 h2 hu
  have v1 : (¬ e 4 10) := fun hu => c365 e tri schur h0 hu h1
  have v2 : (e 2 3) := Classical.byContradiction (fun hu => c832 e tri schur hu h3 v0)
  have v3 : (¬ e 5 14) := fun hu => c932 e tri schur hu h0 h1
  have v4 : (¬ e 8 10) := fun hu => c942 e tri schur hu h0 h2
  have v5 : (¬ e 2 10) := fun hu => c142 e tri schur h2 hu v2
  have v6 : (e 2 8) := Classical.byContradiction (fun hu => c837 e tri schur hu v5 v4)
  have v7 : (e 2 12) := Classical.byContradiction (fun hu => c839 e tri schur v5 hu h5)
  have v8 : (¬ e 3 8) := fun hu => c140 e tri schur hu v6 v2
  have v9 : (¬ e 3 12) := fun hu => c144 e tri schur hu v7 v2
  have v10 : (¬ e 8 12) := fun hu => c204 e tri schur hu v7 v6
  have v11 : (e 5 8) := Classical.byContradiction (fun hu => c847 e tri schur v0 v8 hu)
  have v12 : (e 4 8) := Classical.byContradiction (fun hu => c861 e tri schur hu h4 v10)
  have v13 : (¬ e 2 4) := fun hu => c154 e tri schur v12 v6 hu
  exact c363 e tri schur v11 v12 h1

theorem c950 : (e 3 14) → (e 3 8) → (e 3 6) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 6 8) := fun hu => c284 e tri schur hu h1 h2
  have v1 : (¬ e 6 14) := fun hu => c290 e tri schur hu h0 h2
  have v2 : (¬ e 8 14) := fun hu => c311 e tri schur hu h0 h1
  exact c877 e tri schur v0 v1 v2

theorem c951 : (e 8 14) → (e 8 12) → (e 2 8) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 12) := fun hu => c204 e tri schur h1 hu h2
  have v1 : (¬ e 2 14) := fun hu => c206 e tri schur h0 hu h2
  have v2 : (¬ e 12 14) := fun hu => c676 e tri schur hu h0 h1
  exact c841 e tri schur v0 v1 v2

theorem c953 : (e 11 15) → (e 9 11) → (e 6 11) → (¬ e 6 9) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 6 15) := fun hu => c571 e tri schur h0 hu h2
  have v1 : (¬ e 9 15) := fun hu => c707 e tri schur h0 hu h1
  exact c878 e tri schur h3 v0 v1

theorem c954 : (e 6 14) → (e 6 11) → (e 3 6) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 11) := fun hu => c287 e tri schur h1 hu h2
  have v1 : (¬ e 3 14) := fun hu => c290 e tri schur h0 hu h2
  have v2 : (¬ e 11 14) := fun hu => c570 e tri schur hu h0 h1
  exact c853 e tri schur v0 v1 v2

theorem c959 : (e 6 11) → (e 6 8) → (e 3 6) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 8) := fun hu => c284 e tri schur h1 hu h2
  have v1 : (¬ e 3 11) := fun hu => c287 e tri schur h0 hu h2
  have v2 : (¬ e 8 11) := fun hu => c543 e tri schur hu h0 h1
  exact c850 e tri schur v0 v1 v2

theorem c961 : (e 6 15) → (e 6 11) → (e 4 6) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 4 11) := fun hu => c378 e tri schur h1 hu h2
  have v1 : (¬ e 4 15) := fun hu => c382 e tri schur h0 hu h2
  have v2 : (¬ e 11 15) := fun hu => c571 e tri schur hu h0 h1
  exact c864 e tri schur v0 v1 v2

theorem c963 : (e 3 18) → (e 3 10) → (e 3 8) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 8 10) := fun hu => c307 e tri schur hu h1 h2
  have v1 : (¬ e 8 18) := fun hu => c315 e tri schur hu h0 h2
  have v2 : (¬ e 10 18) := fun hu => c332 e tri schur hu h0 h1
  exact c887 e tri schur v0 v1 v2

theorem c964 : (e 7 12) → (e 7 10) → (e 2 7) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 10) := fun hu => c192 e tri schur h1 hu h2
  have v1 : (¬ e 2 12) := fun hu => c194 e tri schur h0 hu h2
  have v2 : (¬ e 10 12) := fun hu => c616 e tri schur hu h0 h1
  exact c839 e tri schur v0 v1 v2

theorem c970 : (e 9 15) → (e 3 15) → (e 3 8) → (e 2 7) → (¬ e 2 6) → (¬ e 6 9) → (¬ e 7 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 8 15) := fun hu => c312 e tri schur hu h1 h2
  have v1 : (¬ e 3 9) := fun hu => c321 e tri schur h0 h1 hu
  have v2 : (e 3 6) := Classical.byContradiction (fun hu => c848 e tri schur hu v1 h5)
  have v3 : (e 7 8) := Classical.byContradiction (fun hu => c882 e tri schur hu h6 v0)
  have v4 : (¬ e 7 10) := fun hu => c931 e tri schur hu v3 h3
  have v5 : (¬ e 3 14) := fun hu => c950 e tri schur hu h2 v2
  have v6 : (¬ e 2 8) := fun hu => c190 e tri schur v3 hu h3
  have v7 : (¬ e 6 8) := fun hu => c284 e tri schur hu h2 v2
  have v8 : (¬ e 6 15) := fun hu => c291 e tri schur hu h1 v2
  have v9 : (¬ e 3 7) := fun hu => c295 e tri schur v3 h2 hu
  exact c835 e tri schur h4 v6 v7

theorem c971 : (e 8 14) → (e 8 10) → (e 2 8) → (¬ e 4 12) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 2 10) := fun hu => c202 e tri schur h1 hu h2
  have v1 : (¬ e 2 14) := fun hu => c206 e tri schur h0 hu h2
  have v2 : (¬ e 10 14) := fun hu => c663 e tri schur hu h0 h1
  have v3 : (¬ e 8 12) := fun hu => c951 e tri schur h0 hu h2
  have v4 : (e 4 8) := Classical.byContradiction (fun hu => c861 e tri schur hu h3 v3)
  have v5 : (¬ e 2 4) := fun hu => c154 e tri schur v4 h2 hu
  have v6 : (¬ e 4 10) := fun hu => c398 e tri schur h1 hu v4
  have v7 : (¬ e 4 14) := fun hu => c402 e tri schur h0 hu v4
  exact c863 e tri schur v6 v7 v2

theorem c973 : (e 15 18) → (e 6 8) → (e 4 6) → (e 3 8) → (¬ e 3 15) → (¬ e 4 12) → (¬ e 6 18) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (¬ e 3 6) := fun hu => c284 e tri schur h1 h3 hu
  have v1 : (¬ e 4 8) := fun hu => c375 e tri schur h1 hu h2
  have v2 : (e 8 12) := Classical.byContradiction (fun hu => c861 e tri schur v1 h5 hu)
  have v3 : (¬ e 3 12) := fun hu => c309 e tri schur v2 hu h3
  have v4 : (¬ e 6 12) := fun hu => c544 e tri schur v2 hu h1
  have v5 : (e 12 15) := Classical.byContradiction (fun hu => c854 e tri schur v3 h4 hu)
  have v6 : (e 12 18) := Classical.byContradiction (fun hu => c881 e tri schur v4 h6 hu)
  have v7 : (¬ e 8 15) := fun hu => c677 e tri schur v5 hu v2
  have v8 : (¬ e 8 18) := fun hu => c680 e tri schur v6 hu v2
  exact c792 e tri schur h0 v6 v5

theorem c976 : (e 8 10) → (e 7 10) → (e 2 7) → (¬ e 3 8) → (¬ e 3 15) → (¬ e 5 7) → (¬ e 5 10) → (¬ e 7 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 2 10) := fun hu => c192 e tri schur h1 hu h2
  have v1 : (¬ e 7 8) := fun hu => c597 e tri schur h0 h1 hu
  have v2 : (e 8 15) := Classical.byContradiction (fun hu => c882 e tri schur v1 h7 hu)
  have v3 : (¬ e 7 12) := fun hu => c964 e tri schur hu h1 h2
  have v4 : (¬ e 10 15) := fun hu => c664 e tri schur hu v2 h0
  have v5 : (e 5 12) := Classical.byContradiction (fun hu => c869 e tri schur h5 hu v3)
  have v6 : (e 5 15) := Classical.byContradiction (fun hu => c872 e tri schur h6 hu v4)
  have v7 : (¬ e 5 8) := fun hu => c481 e tri schur v2 v6 hu
  have v8 : (¬ e 12 15) := fun hu => c511 e tri schur hu v6 v5
  have v9 : (e 3 5) := Classical.byContradiction (fun hu => c847 e tri schur hu h3 v7)
  have v10 : (e 3 12) := Classical.byContradiction (fun hu => c854 e tri schur hu h4 v8)
  exact c276 e tri schur v5 v10 v9

theorem c977 : (e 7 11) → (e 7 9) → (e 2 7) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 2 9) := fun hu => c191 e tri schur h1 hu h2
  have v1 : (¬ e 2 11) := fun hu => c193 e tri schur h0 hu h2
  have v2 : (¬ e 9 11) := fun hu => c607 e tri schur hu h0 h1
  exact c838 e tri schur v0 v1 v2

theorem c978 : (e 8 10) → (e 6 11) → (e 3 6) → (¬ e 2 6) → (¬ e 4 12) → False := by
  intro h0 h1 h2 h3 h4
  have v0 : (¬ e 3 11) := fun hu => c287 e tri schur h1 hu h2
  have v1 : (¬ e 6 14) := fun hu => c954 e tri schur hu h1 h2
  have v2 : (¬ e 6 8) := fun hu => c959 e tri schur h1 hu h2
  have v3 : (e 2 8) := Classical.byContradiction (fun hu => c835 e tri schur h3 hu v2)
  have v4 : (e 8 14) := Classical.byContradiction (fun hu => c877 e tri schur v2 v1 hu)
  have v5 : (¬ e 8 12) := fun hu => c951 e tri schur v4 hu v3
  exact c971 e tri schur v4 h0 v3 h4

theorem c980 : (e 5 12) → (¬ e 3 5) → (¬ e 3 8) → (¬ e 3 11) → (¬ e 4 12) → (¬ e 7 11) → (¬ e 11 15) → False := by
  intro h0 h1 h2 h3 h4 h5 h6
  have v0 : (e 5 8) := Classical.byContradiction (fun hu => c847 e tri schur h1 h2 hu)
  have v1 : (e 8 11) := Classical.byContradiction (fun hu => c850 e tri schur h2 h3 hu)
  have v2 : (¬ e 5 11) := fun hu => c477 e tri schur v1 hu v0
  have v3 : (¬ e 8 12) := fun hu => c478 e tri schur hu h0 v0
  have v4 : (e 4 8) := Classical.byContradiction (fun hu => c861 e tri schur hu h4 v3)
  have v5 : (¬ e 4 5) := fun hu => c363 e tri schur v0 v4 hu
  have v6 : (¬ e 4 11) := fun hu => c399 e tri schur v1 hu v4
  have v7 : (e 4 7) := Classical.byContradiction (fun hu => c860 e tri schur hu v6 h5)
  have v8 : (e 4 15) := Classical.byContradiction (fun hu => c864 e tri schur v6 hu h6)
  have v9 : (¬ e 7 15) := fun hu => c900 e tri schur hu v6 h5 h6
  exact c929 e tri schur v8 v4 v7

theorem c984 : (e 4 11) → (e 4 6) → (e 4 5) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 5 6) := fun hu => c361 e tri schur hu h1 h2
  have v1 : (¬ e 5 11) := fun hu => c366 e tri schur hu h0 h2
  have v2 : (¬ e 6 11) := fun hu => c378 e tri schur hu h0 h1
  exact c868 e tri schur v0 v1 v2

theorem c985 : (e 8 14) → (e 5 14) → (e 3 14) → (¬ e 3 5) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 3 8) := fun hu => c311 e tri schur h0 h2 hu
  have v1 : (¬ e 5 8) := fun hu => c480 e tri schur h0 h1 hu
  exact c847 e tri schur h3 v0 v1

theorem c986 : (e 4 15) → (e 4 10) → (e 4 5) → (¬ e 5 10) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 5 15) := fun hu => c370 e tri schur hu h0 h2
  have v1 : (¬ e 10 15) := fun hu => c420 e tri schur hu h0 h1
  exact c872 e tri schur h3 v0 v1

theorem c987 : (e 8 15) → (e 8 12) → (e 3 8) → False := by
  intro h0 h1 h2
  have v0 : (¬ e 3 12) := fun hu => c309 e tri schur h1 hu h2
  have v1 : (¬ e 3 15) := fun hu => c312 e tri schur h0 hu h2
  have v2 : (¬ e 12 15) := fun hu => c677 e tri schur hu h0 h1
  exact c854 e tri schur v0 v1 v2

theorem c988 : (e 6 13) → (e 6 8) → (e 5 6) → (¬ e 5 8) → False := by
  intro h0 h1 h2 h3
  have v0 : (¬ e 5 13) := fun hu => c458 e tri schur h0 hu h2
  have v1 : (¬ e 8 13) := fun hu => c545 e tri schur hu h0 h1
  exact c870 e tri schur h3 v0 v1

theorem c989 : (e 4 10) → (e 3 8) → (e 2 7) → (e 2 6) → (e 2 3) → (¬ e 4 7) → (¬ e 4 12) → (¬ e 6 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7
  have v0 : (¬ e 3 6) := fun hu => c138 e tri schur hu h3 h4
  have v1 : (¬ e 3 7) := fun hu => c139 e tri schur hu h2 h4
  have v2 : (¬ e 2 8) := fun hu => c140 e tri schur h1 hu h4
  have v3 : (¬ e 6 7) := fun hu => c178 e tri schur hu h2 h3
  have v4 : (e 3 4) := Classical.byContradiction (fun hu => c846 e tri schur hu v1 h5)
  have v5 : (e 7 13) := Classical.byContradiction (fun hu => c876 e tri schur v3 h7 hu)
  have v6 : (¬ e 2 4) := fun hu => c136 e tri schur v4 hu h4
  have v7 : (¬ e 2 13) := fun hu => c195 e tri schur v5 hu h2
  have v8 : (¬ e 4 8) := fun hu => c259 e tri schur hu h1 v4
  have v9 : (¬ e 3 10) := fun hu => c261 e tri schur h0 hu v4
  have v10 : (e 7 10) := Classical.byContradiction (fun hu => c849 e tri schur v1 v9 hu)
  have v11 : (e 8 12) := Classical.byContradiction (fun hu => c861 e tri schur v8 h6 hu)
  have v12 : (¬ e 7 8) := fun hu => c931 e tri schur v10 hu h2
  have v13 : (¬ e 7 12) := fun hu => c964 e tri schur hu v10 h2
  have v14 : (¬ e 8 15) := fun hu => c987 e tri schur hu v11 h1
  have v15 : (¬ e 2 10) := fun hu => c192 e tri schur v10 hu h2
  have v16 : (¬ e 3 12) := fun hu => c309 e tri schur v11 hu h1
  have v17 : (¬ e 10 13) := fun hu => c617 e tri schur hu v5 v10
  have v18 : (e 8 10) := Classical.byContradiction (fun hu => c837 e tri schur v2 v15 hu)
  have v19 : (e 3 13) := Classical.byContradiction (fun hu => c852 e tri schur v9 hu v17)
  have v20 : (e 7 15) := Classical.byContradiction (fun hu => c882 e tri schur v12 hu v14)
  have v21 : (¬ e 2 15) := fun hu => c197 e tri schur v20 hu h2
  have v22 : (¬ e 4 13) := fun hu => c264 e tri schur hu v19 v4
  have v23 : (¬ e 8 13) := fun hu => c310 e tri schur hu v19 h1
  have v24 : (¬ e 10 15) := fun hu => c619 e tri schur hu v20 v10
  have v25 : (¬ e 13 15) := fun hu => c637 e tri schur hu v20 v5
  have v26 : (¬ e 10 12) := fun hu => c661 e tri schur hu v11 v18
  have v27 : (e 2 12) := Classical.byContradiction (fun hu => c839 e tri schur v15 hu v26)
  exact c842 e tri schur v7 v21 v25

theorem c990 : (e 5 6) → (e 4 10) → (e 3 9) → (¬ e 2 5) → (¬ e 2 7) → (¬ e 2 9) → (¬ e 4 7) → (¬ e 4 9) → (¬ e 6 13) → False := by
  intro h0 h1 h2 h3 h4 h5 h6 h7 h8
  have v0 : (e 5 7) := Classical.byContradiction (fun hu => c834 e tri schur h3 h4 hu)
  have v1 : (e 7 9) := Classical.byContradiction (fun hu => c836 e tri schur h4 h5 hu)
  have v2 : (¬ e 3 7) := fun hu => c296 e tri schur v1 h2 hu
  have v3 : (¬ e 6 7) := fun hu => c452 e tri schur hu v0 h0
  have v4 : (¬ e 5 9) := fun hu => c465 e tri schur v1 hu v0
  have v5 : (e 3 4) := Classical.byContradiction (fun hu => c846 e tri schur hu v2 h6)
  have v6 : (e 4 5) := Classical.byContradiction (fun hu => c858 e tri schur hu h7 v4)
  have v7 : (e 7 13) := Classical.byContradiction (fun hu => c876 e tri schur v3 h8 hu)
  have v8 : (¬ e 3 5) := fun hu => c256 e tri schur v6 hu v5
  have v9 : (¬ e 3 10) := fun hu => c261 e tri schur h1 hu v5
  have v10 : (¬ e 4 6) := fun hu => c361 e tri schur h0 hu v6
  have v11 : (¬ e 5 10) := fun hu => c365 e tri schur hu h1 v6
  have v12 : (¬ e 5 13) := fun hu => c469 e tri schur v7 hu v0
  have v13 : (¬ e 9 13) := fun hu => c609 e tri schur hu v7 v1
  have v14 : (e 2 3) := Classical.byContradiction (fun hu => c832 e tri schur hu h3 v8)
  have v15 : (e 7 10) := Classical.byContradiction (fun hu => c849 e tri schur v2 v9 hu)
  have v16 : (e 4 13) := Classical.byContradiction (fun hu => c862 e tri schur h7 hu v13)
  have v17 : (¬ e 4 15) := fun hu => c986 e tri schur hu h1 v6 v11
  have v18 : (¬ e 2 4) := fun hu => c136 e tri schur v5 hu v14
  have v19 : (¬ e 3 13) := fun hu => c264 e tri schur v16 hu v5
  have v20 : (¬ e 10 13) := fun hu => c418 e tri schur hu v16 h1
  have v21 : (¬ e 9 10) := fun hu => c606 e tri schur hu v15 v1
  have v22 : (e 2 6) := Classical.byContradiction (fun hu => c833 e tri schur v18 hu v10)
  exact c852 e tri schur v9 v19 v20

end Jsp746.Certificate
