/- Generated by scripts/generate_refutation.py from our own SAT trace.
Every statement below is proved with ordinary kernel-checked proof terms. -/
import Jsp746.Certificate.Steps30

namespace Jsp746

/-- No triangle-free graph on the first 18 positive integers can avoid an
independent Schur triple. The proof replays an explicit propositional certificate
from our independently generated SAT instance. -/
theorem sat_refutation
    (e : ℕ → ℕ → Prop)
    (tri : ∀ i j k, 1 ≤ i → i < j → j < k → k ≤ 18 →
      ¬ (e i j ∧ e i k ∧ e j k))
    (schur : ∀ a b, 1 ≤ a → a < b → a + b ≤ 18 →
      e a b ∨ e a (a + b) ∨ e b (a + b)) : False :=
  Certificate.c3010 e tri schur

end Jsp746
