#!/usr/bin/env python3
"""Compile our independently generated DRUP trace into explicit Lean proof terms.

Untrusted generator: Lean checks each resulting propositional theorem. No SAT
solver invocation, Python execution or native evaluation is needed by the Lean
build. Learned clauses are represented by curried implications to False.
"""
from pathlib import Path
from itertools import combinations
from collections import defaultdict
import json,hashlib

ROOT=Path(__file__).resolve().parents[1]
PROBE=ROOT/'data'
OUT=ROOT/'Jsp746/Certificate'
OUT.mkdir(parents=True,exist_ok=True)
PAIR={i+1:p for i,p in enumerate(combinations(range(1,19),2))}

def parse(s):return tuple(sorted(map(int,s.split()[:-1])))
base=[parse(s) for s in (PROBE/'n18.cnf').read_text().splitlines() if s and s[0] not in 'cp']
clauses=list(base)
proofs={}
live=defaultdict(list)
for i,c in enumerate(base):live[c].append(i)

def replay(target):
    assignment={}
    steps=[]
    for k,lit in enumerate(target):
        assert abs(lit) not in assignment
        assignment[abs(lit)]=(lit<0,f'h{k}')
    while True:
        progress=False
        for c,ids in live.items():
            names=[]; remaining=[]
            for lit in c:
                v=abs(lit)
                if v in assignment:
                    val,name=assignment[v]
                    if val==(lit>0):break
                    names.append(name)
                else:
                    names.append(None);remaining.append(lit)
            else:
                if not remaining:return steps,(ids[-1],names)
                if len(remaining)==1:
                    lit=remaining[0]
                    name=f'v{len(steps)}'
                    steps.append((lit,name,ids[-1],names))
                    assignment[abs(lit)]=(lit>0,name)
                    progress=True
                continue
        assert progress,('not RUP',target)

for line in (PROBE/'n18.drat').read_text().splitlines():
    if line.startswith('d '):
        c=parse(line[2:]);assert live[c]
        live[c].pop()
        if not live[c]:del live[c]
    else:
        c=parse(line)
        i=len(clauses)
        proofs[i]=replay(c)
        clauses.append(c)
        live[c].append(i)
assert clauses[-1]==()
needed=set()
def visit(i):
    if i in needed:return
    needed.add(i)
    if i in proofs:
        steps,final=proofs[i]
        for _,_,source,_ in steps:visit(source)
        visit(final[0])
visit(len(clauses)-1)

def atom(v):
    a,b=PAIR[v]
    return f'e {a} {b}'
def literal(lit):return f'({atom(lit)})' if lit>0 else f'(¬ {atom(-lit)})'
def clause_type(c):return ' → '.join([literal(-lit) for lit in c]+['False'])
def application(source,names):return f'c{source} e tri schur '+ ' '.join('(fun z => z)' if x is None else x for x in names)

header='''/- Generated by scripts/generate_refutation.py from our own SAT trace.
Every statement below is proved with ordinary kernel-checked proof terms. -/
'''
section='''namespace Jsp746.Certificate
variable (e : ℕ → ℕ → Prop)
variable (tri : TriangleCondition e) (schur : SchurCondition e)
include tri schur

'''
initial=header+'''import Mathlib.Data.Nat.Basic

-- The generated initial-clause interface uniformly carries both hypotheses.
set_option linter.unusedSectionVars false

namespace Jsp746.Certificate

def TriangleCondition (e : ℕ → ℕ → Prop) : Prop :=
  ∀ i j k, 1 ≤ i → i < j → j < k → k ≤ 18 →
    ¬ (e i j ∧ e i k ∧ e j k)

def SchurCondition (e : ℕ → ℕ → Prop) : Prop :=
  ∀ a b, 1 ≤ a → a < b → a + b ≤ 18 →
    e a b ∨ e a (a + b) ∨ e b (a + b)

end Jsp746.Certificate

'''+section
tris=list(combinations(range(1,19),3))
sums=[(a,b,a+b) for a,b in combinations(range(1,19),2) if a+b<=18]
for i,c in enumerate(base):
    if i not in needed:continue
    initial+=f'theorem c{i} : {clause_type(c)} := by\n  intro h0 h1 h2\n'
    if i<len(tris):
        a,b,d=tris[i]
        lookup={PAIR[-lit]:f'h{k}' for k,lit in enumerate(c)}
        initial+=f'  exact tri {a} {b} {d} (by decide) (by decide) (by decide) (by decide) ⟨{lookup[a,b]}, {lookup[a,d]}, {lookup[b,d]}⟩\n\n'
    else:
        a,b,d=sums[i-len(tris)]
        lookup={PAIR[lit]:f'h{k}' for k,lit in enumerate(c)}
        initial+=f'  exact (schur {a} {b} (by decide) (by decide) (by decide)).elim {lookup[a,b]} (fun h => h.elim {lookup[a,d]} {lookup[b,d]})\n\n'
initial+='end Jsp746.Certificate\n'
(OUT/'Initial.lean').write_text(initial)
learned=[i for i in range(len(base),len(clauses)) if i in needed]
chunks=[learned[i:i+60] for i in range(0,len(learned),60)]
previous='Initial'
proof_steps=0
for k,chunk in enumerate(chunks):
    chunk_name=f'Steps{k:02d}'
    content=header+f'import Jsp746.Certificate.{previous}\n\n'+section
    for i in chunk:
        c=clauses[i]
        content+=f'theorem c{i} : {clause_type(c)} := by\n'
        if c:content+='  intro '+' '.join(f'h{k}' for k in range(len(c)))+'\n'
        steps,final=proofs[i]
        for lit,name,source,names in steps:
            args=['hu' if x is None else x for x in names]
            call=f'c{source} e tri schur '+' '.join(args)
            rhs=f'Classical.byContradiction (fun hu => {call})' if lit>0 else f'fun hu => {call}'
            content+=f'  have {name} : {literal(lit)} := {rhs}\n'
        source,names=final
        content+=f'  exact c{source} e tri schur '+ ' '.join(names)+'\n\n'
        proof_steps+=len(steps)
    content+='end Jsp746.Certificate\n'
    (OUT/f'{chunk_name}.lean').write_text(content)
    previous=chunk_name
(ROOT/'Jsp746/Refutation.lean').write_text(header+f'''import Jsp746.Certificate.{previous}

namespace Jsp746

/-- No triangle-free graph on the first 18 positive integers can avoid an
independent Schur triple. The proof replays an explicit propositional certificate
from our independently generated SAT instance. -/
theorem sat_refutation
    (e : ℕ → ℕ → Prop)
    (tri : ∀ i j k, 1 ≤ i → i < j → j < k → k ≤ 18 →
      ¬ (e i j ∧ e i k ∧ e j k))
    (schur : ∀ a b, 1 ≤ a → a < b → a + b ≤ 18 →
      e a b ∨ e a (a + b) ∨ e b (a + b)) : False :=
  Certificate.c{len(clauses)-1} e tri schur

end Jsp746
''')
report={'cnf_sha256':hashlib.sha256((PROBE/'n18.cnf').read_bytes()).hexdigest(),'trace_sha256':hashlib.sha256((PROBE/'n18.drat').read_bytes()).hexdigest(),'input_clauses':len(base),'trace_additions':len(proofs),'used_initial_clauses':len(needed)-len(learned),'used_learned_clauses':len(learned),'propagation_steps':proof_steps,'chunk_files':len(chunks),'last_clause':len(clauses)-1}
(ROOT/'scripts/refutation-generation.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps(report))
